### ISSUE TITLE
MissingMethodException thrown on Django solution load

### ISSUE THREAD

**Issue by chausner** [Microsoft/PTVS#1003]
Since some time now, when I open my Django solution in VS, an error message pops up pointing to the ActivityLog.xml file which contains several instances of the following exception being thrown:
> System.MissingMethodException: Methode nicht gefunden: "Microsoft.VisualStudio.Text.Editor.ITextView Microsoft.Html.Editor.Document.HtmlEditorDocument.get_PrimaryView()". 
> bei Microsoft.PythonTools.Django.TemplateParsing.TemplateClassifier.GetClassificationSpans(SnapshotSpan span) 
> bei Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext() 
> bei Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()

Any idea what is causing this and how to fix it? PTVS seems to run fine but I keep getting this error when loading a solution. I am using VS Community 2015 with PTVS 2.2.30718.00. Edit: I have recently installed ASP.NET and Web Tools 2015 (Beta8). Could it be caused by this?

**Comment by zooba** [comment]
It's possible that the Web Tools update has removed that property, which would be a fairly significant issue. I'll check next week and see what they've done.

**Comment by zooba** [comment]
We need to rewrite our template handling for Django to deal with the changed API of Web Tools. I'm working on it, but it's a fairly painful thing to have to do and it isn't clear when we'll get it out as an update or what form it will take.

**Comment by chausner** [comment]
I see, that's bad news. In the meantime, until a proper fix is put in place, it would be nice to at least get rid of the error message that pops up during each solution load and let it just fail silently.

**Comment by zooba** [comment]
So the error message will pop up once per Visual Studio session, when you open a document with the Django editor. It's only popping up on solution load because the document is being opened.

If you right-click the file and choose "Open with", you can select the normal HTML editor. I'm not currently sure what it will do with templated sections without our overrides (it used to do nothing, but they've added much more support for non-ASP.NET templates), but it can't be much worse than having the error. Once you've opened the document once it should reopen with the same editor next time you open the solution.

**Comment by zooba** [comment]
I've just uploaded a dev build that fixes this issue. Please give it a try and let me know if it is fixed: https://github.com/Microsoft/PTVS/releases/tag/dev-2016-01-19

**Comment by chausner** [comment]
Did a quick test and syntax highlighting for templates seems to work again and no error message pops up anymore. Great. Will let you know if I come across any issues with this build.

**Comment by zooba** [comment]
Awesome, thanks.
