### ISSUE TITLE
PTVS provides wrong completion in interactive window

### ISSUE THREAD

**Issue by willyd** [Microsoft/PTVS#1012]
Sometimes the keyword completion provides wrong completion in the interactive window. For example if I type:

``` python
import numpy as np
x = np.array(range(10), dtype=
```

`dtype` erroneously becomes `module_type` as shown in this [screenshot](http://snag.gy/oN52L.jpg). I would have uploaded the screenshot in this issue but for some reason github did not like my image (maybe some network restrictions at my workplace).

**Comment by zooba** [comment]
This is a general issue with our analysis, especially for modules like `numpy` that expose their information in docstrings rather than more easily parseable forms.

(Yes, `numpy` style doc comments are fairly easy to parse, but when you account for the three major styles and thousands of inconsistent styles out there it's very hard to declare docstrings generally parseable.)

**Comment by willyd** [comment]
@zooba Thanks for the explanation. But is the code completion different in the Interactive Consoleand in the Editor? I only see this in the Interactive Console.

**Comment by zooba** [comment]
See #3046
