### ISSUE TITLE
Interpreter crashes only when debugging without native code debugging

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#1013]
Using VS 2015

I have a situation that unfortunately I cannot find a way to provide useful diagnostics _or_ an easy repro for.  I'm working on porting the LLDB project to work with Python 3, which involves porting its test suite to Python 3 as well.  So I have two separate PTVS solutions.  One that uses a Python 3 solution and one that uses a Python 2 solution (only difference is the search paths and the default environment)

Each of these imports and uses the corresponding lldb extension module -- either the 2.7 version or the 3.5 version depending on which solution.

I've seen a couple of instances of tests attempting to call one of the extension module methods and `python_d.exe` crashes when doing so.  But here's the wrinkle:
1. It only crashes when native code debugging is not enabled, so I can't see where the crash even happens.
2. Since PTVS is already attached, I can't attach another debugger.
3. Detach does not seem to be implemented for PTVS solutions, so I can't detach and then re-attach with native code debugging enabled.

I can't think of any solution to this.

Interestingly, it only happens in Python 3.5 and not in 2.7.  It also doesn't crash when I run the exact same command line from a command prompt as opposed to through PTVS.

Any thoughts?  I'm open to the possibility that there's a bug in my code and not in PTVS, but it's mighty suspicious that it only crashes when a particular setting is enabled in PTVS, so I suspect a problem in PTVS.

I could probably help you get a build set up, but I don't know if you want to go to that much trouble for something that you might not even be able to reproduce after all the effort.

**Comment by int19h** [comment]
There is a way to attach WinDbg to a process that is already being debugged, albeit in a limited mode (but usually enough to diagnose a crash) - you need to check the "non-invasive" checkbox:

https://msdn.microsoft.com/en-us/library/windows/hardware/ff552274(v=vs.85).aspx

If you can build PTVS youself, one other option is to run PTVS itself under the debugger (basically just open the solution and do F5), andset a breakpoint [here](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/Debugger/PythonProcess.cs#L78), then use Debug -> Attach to attach to your test. When that breakpoint is hit, VS has already made the check for "no debugger attached", but it hasn't set the process bit indicating that it has finished attaching, and so you can actually spin up another VS instance and do native attach to the same process.

The resulting arrangement is not particularly stable, because debuggers can get in each other way, but if you set the native one to only break on Win32 exceptions, and don't touch it otherwise, it shouldn't interfere with Python debugger. So then when it crashes, the native debugger should break and let you inspect the context.
