### ISSUE TITLE
System.MissingMethodException in Django

### ISSUE THREAD

**Issue by aewhatley** [Microsoft/PTVS#1014]
I got the following error message after opening up a Django project after upgrading to Visual Studio 2015 Upgrade 1:

System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.Text.Editor.ITextView Microsoft.Html.Editor.Document.HtmlEditorDocument.get_PrimaryView()'. at Microsoft.PythonTools.Django.TemplateParsing.TemplateClassifier.GetClassificationSpans(SnapshotSpan span) at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()

**Comment by zooba** [comment]
Thanks for this. It appears someone made a breaking change they shouldn't have in an update. I'm investigating now, but I'm not aware of any workaround just yet.

**Comment by zooba** [comment]
The change is in the HTML editor - they removed that property late during Update 1 and we didn't notice in time.

Currently discussing with that team whether they'll fix their public API or maybe we'll do another PTVS release to fix this.

**Comment by GaelGirodon** [comment]
Same problem here, I can't use Django Template Editing on Visual Studio 2015 Update 1 with PTVS 2.2. When I try to open some html file in a Django Project, multiple exceptions are thrown (same as @aewhatley 's one) and I can't get syntax highlighting and Intellisense in templates. The issue seems to be only linked to templates. Please, let us know when you'll have a workaround! Thanks.

**Comment by mhogg** [comment]
Any progress on this? I am getting the same error message

**Comment by zooba** [comment]
It's fixed in our latest [dev builds](https://github.com/Microsoft/PTVS/releases), and will be in our next release.
