### ISSUE TITLE
PythonTools project build fails

### ISSUE THREAD

**Issue by mstechies** [Microsoft/PTVS#1024]
I tried to build the latest (clone) and received this error that 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	
The type or namespace name 'Web' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)	PythonTools	 "Microsoft.VisualStudio.Web.WindowsAzure.Contracts" 

I have checked that I have all the required components installed - like Azure SDK for .NET, Visual Studio SDK and VS Test Host release.

I also tried in multiple machines.

**Comment by int19h** [comment]
The requisite assembly should be in:

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Azure\WindowsAzure`

(adjusted for Visual Studio version that you're building for)

Can you please check whether it is physically there?

**Comment by mstechies** [comment]
I checked in the above location and its not present there.

**Comment by int19h** [comment]
Which version of Azure SDK for .NET are you using?

**Comment by mstechies** [comment]
Azure SDK for .NET 2.8.1

**Comment by mstechies** [comment]
Any update on this?

**Comment by int19h** [comment]
Now that I look at the assembly name closely, I think this is a part of Web Tools rather than Azure. If you go to Tools -> Extensions and Updates, do you have the item titled "Microsoft ASP.NET and Web Tools" in the list under the "Installed" tab there?

If not, then it might have become an optional VS component that can be deselected during VS setup. Try doing repair/change on VS itself, and see if you can locate it in the component list.
