### ISSUE TITLE
The type 'Window' does not support direct content

### ISSUE THREAD

**Issue by lennoncork** [Microsoft/PTVS#1048]
I'm using visual studio 2015 to develop a basic IronPython WPF project. The XAML window shows the error "the type 'Window' does not support direct content", similar to the unrelated issue reported here http://stackoverflow.com/questions/33805234/the-type-window-does-not-support-direct-content.

Previously the issue didn't exist, and I believe it only occurred after updating to VS2015 Update 1 and Python Tools 2.2. 

I can repeat this by creating a new IronPython WPF project with no additional content (image attached). 

I can also fix the issue, temporarily, by adding a reference to "System.Xml". The reference can then be removed, but the warning will return when the project is loaded again. 

![capture](https://cloud.githubusercontent.com/assets/7624296/12156158/0a048970-b515-11e5-8063-f7a5f29f24fb.PNG)

**Comment by NetworkActiv** [comment]
For me, adding `System.Xaml` (note the 'a') solves the problem *properly*. Adding any other reference seems to solve it only *temporarily*.

**Comment by lennoncork** [comment]
Perfect, that works for me as well! I had to reload the application, but all is well! Thank you!

**Comment by NetworkActiv** [comment]
Since this approach seems to work, someone should probably make it to where new PTVS WPF projects include the `System.Xaml` reference by default. It appears that C# WPF projects include this reference by default. I am not sufficiently familiar with this repository to know where in the code this would be done.

**Comment by mistopportunity** [comment]
This is still happening. Even with the error the project can still be built/run, though.

**Comment by zooba** [comment]
We haven't released anything in the last 22 days, that's why it's still happening :)

Our next update will have a fixed template. The fix for existing projects is to add the `System.Xaml` reference.

**Comment by JohnnyDeeee** [comment]
Somehow i cant fix this problem with adding the "System.Xaml" reference..

![8680954c78d54b581ba3711d20f72f31](https://cloud.githubusercontent.com/assets/9005496/20238422/9d5ef5b4-a8eb-11e6-91b1-1afcd6cff53e.png)

I'm not sure if it is because im using the "MahApps.Metro" plugin
or
because i'm using 2 projects within one solution...

![330c85df442b2a175ab8ea92c1d92e06](https://cloud.githubusercontent.com/assets/9005496/20238424/a06da1f6-a8eb-11e6-9d4f-93f982b7f875.png)
