### ISSUE TITLE
Unable to run simple python code in Visual Studio

### ISSUE THREAD

**Issue by udayguntupalli** [Microsoft/PTVS#1049]
Hello, 

I followed the instructions provided  and installed Python Tools in Visual Studio 2013. I also installed Anaconda. I tried to run a simple line of code and I keep getting errors. I don't understand if the problem is with the setup because the same lines of code work perfectly well in IDLE IDE . Please guide : 
Here are the lines of code : 

import sys 
User = input(" What is your FS ID ? :") 
print(User) 
Site = input("Enter the name of the site : ") 
print(Site) 

Best 

Uday

**Comment by codywd** [comment]
What is the error message it gives you?

**Comment by udayguntupalli** [comment]
What is your FS ID ? : 12345 
and I hit enter 
name '12345' is not defined 

@ Codywd : '12345' is just an example . I have tried different names and different alphanumerics to  get the same error

**Comment by codywd** [comment]
Alright, so I typed that exact code in my Visual Studio, and it worked perfectly fine (although, mine is Visual Studio 2015). So, I want to see a few more pieces of information.

1. What Python interpreter are you running? In your case, I guess I should ask what version of Anaconda? 3.5 or 2.7?
2. What version of PTVS are you running?
3. Is that all of the code within your application, or is there some other code?

**Comment by crwilcox** [comment]
@codywd Thanks so much for helping out!

The issue here is Python 2.x and input. If you want to do this in Python 2.x use raw_input instead of input. What input does is try to evaluate the input.  Hence, `12345` is not declared. It is attempting to assign the variable `12345` to the `User` var, not the string `'12345'`

Docs for this: https://docs.python.org/2/library/functions.html#input

This code will work as written on Python 3.x

**Comment by udayguntupalli** [comment]
@crwilcox  : Thanks that worked :+1:

**Comment by codywd** [comment]
That makes perfect sense @crwilcox!

I was running 3.5, which is why I did not have the issue haha. Using my IronPython 2.7 distribution, I get the same error. Didn't even cross my mind.

And your welcome @crwilcox, I hope to contribute to this project some, as I love Python and PTVS is wonderful. Haha

**Comment by crwilcox** [comment]
@udayguntupalli, That is a fine course to use, though I would advise using Python 3 as it seems that is what they are using.

As for guides on using Visual Studio, we have a number of videos on [YouTube](https://www.youtube.com/watch?v=_okUV47eM5c&list=PLReL099Y5nRdLgGAdrb_YeTdEnd23s6Ff). Though, these are more targeted to people that have some Python familiarity and want to use our tooling and not the pure beginner.

**Comment by shanmugapriyathangavel** [comment]
Hi,
I have installed python 2.7. but while trying to run a simple application its showing an popup window telling that install python 2.7. I am using visual studio 2015. Please help me to solve

**Comment by zooba** [comment]
@shanmugapriyathangavel Please create a new issue and attach the information from Tools, Python Tools, Diagnostic Info.
