### ISSUE TITLE
Running unit tests is slow

### ISSUE THREAD

**Issue by JumbleJumble** [Microsoft/PTVS#1067]
A small project with 30-something unit tests across 5 test files can take 30 seconds to run, with the time for each individual test ranging from 300 to 800ms. Running the tests from the command line takes place in about 10-15ms.

Obviously speed of running unit tests has an enormous effect on how often you run them. At present my workflow is to save my work, Alt+Tab to PowerShell, and then run my little script that finds all the .py files in the "tests" folder and runs them through the command line. This is great for checking I haven't broken anything. But if any fail, it's awkward again, and I end up running them from with VS, and then waiting until it shows me which one(s) failed.

I am aware that this is mainly due to creating a new process to run each test and get the result. It seems that there would be many strategies to improve this. One would be to quickly do a full run right at the start. If all the tests pass, you can mark them all green and stop. If some don't then you can go back to the slow method. But actually it seems to me that you could parse the output that I see in my PowerShell window quite easily and have a system that ran all the tests and marked them as pass/fail with information, in a very small amount of time indeed.

Any improvement at all would be most gratefully received!

**Comment by zooba** [comment]
Yep, we'd certainly like to speed it up.

The idea about running all tests together and then retrying if any fail is interesting, we hadn't thought about that.

But the "best" solution is to implement an output handler (that generates the display on screen) that can producing something guaranteed to be machine readable. Ideally, an XML format following MSTest, XUnit or similar. Unfortunately, the normal output that shows is not trustworthy enough for us to use it - when tests fail it would be impossible to parse it. (Also, we'd need the output on stdout so we can read it as the tests run, otherwise we can't provide any feedback until they've all finished.)

To make things complicated, we work hard to maintain support for as many versions of Python as possible (2.5-2.7, 3.0-3.5, IronPython/PyPy/Jython, etc.), so many of the existing tools for this aren't really suitable. It shouldn't be too complicated to have something that works for all of these versions, but it does mean that we probably have to write it ourselves.

**Comment by JumbleJumble** [comment]
Well in the meantime it'd be great if you could try the "run all first" thing. Perhaps then narrow it down by running each file as a whole. It'd be interesting to see how that affects overall performance on average test runs. If I fail one test in a project with 10 test files, will it be quicker to {run the entire batch, see a fail, then run 10 files, see one fail, then run that file to see which one failed} than it would to {run every test indvidually}?
