### ISSUE TITLE
Respect VS debugger hex-formatting selection

### ISSUE THREAD

**Issue by shuffle2** [Microsoft/PTVS#1077]
If you have "hexadecimal display" selected in VS, only single "int" objects will be displayed in hex. int objects in arrays for example, are still shown in decimal.

**Comment by int19h** [comment]
For the most part, we try to use Python's own `repr()` for the values, and it doesn't know anything about hexadecimal, unfortunately. This is currently special-cased for `int`, and it could to some extent be special-cased in standard collections, since we already handle those ourselves to limit their output. But all such fixes will be limited - we can never fix it in the most generic case (an arbitrary type defining its own `__repr__` that prints out ints as part of its representation).

**Comment by huguesv** [comment]
Works with both int and int arrays now.
