### ISSUE TITLE
Setting up python with visual studio 2015 is missing batteries

### ISSUE THREAD

**Issue by obeleh** [Microsoft/PTVS#1081]
My steps so far:
- install win10
- install visual studio professional 2015
- I select python as a language
- Also selecting C# and C++ the latter because I know I have some pip modules that need compiling
  install python because after installing vs with python there is no python?
  I tried inporting my python project:
- Cannot select python: 
  ![image](https://cloud.githubusercontent.com/assets/174411/12744125/b769d732-c992-11e5-9a81-4d4bfaf9f8eb.png)
- Online I read I should install PTVS. So that I can select it. So I download it and get the message that my version is newer. Ok my bad. I go to visual studio and I try to update or install PVTS there because that might fix things I guess. But apparently visual studio thinks I dont have it installed?
  ![image](https://cloud.githubusercontent.com/assets/174411/12744783/68aafa0a-c996-11e5-977b-c883a83aa793.png)
  Next to other things visual studio draws a green arrow to indicate it is installed. So I click on download hoping this will fix things. 
- Then I land here: 
  ![image](https://cloud.githubusercontent.com/assets/174411/12744814/9a1419e6-c996-11e5-8986-93084aed906d.png) 
  No I dont want to download visual studio I just clicked on a button in visual studio :S All the way down on the page there is a link to Install PVTS And I get on this repository. And I read "or find it in the Visual Studio 2015 installer under Custom, Programming Languages" So I go to VS and try to find the "Custom" menu. And now I start to feel real stupid because I see this: 
  ![image](https://cloud.githubusercontent.com/assets/174411/12744966/59af8f74-c997-11e5-9240-b6ed9931beab.png)
- I figure I should check what happens if simply create a project but then I find that it is possible after all:
  ![image](https://cloud.githubusercontent.com/assets/174411/12744182/17178a8a-c993-11e5-8314-2a8851d17b24.png)
- So ok this works now I start installing my pip libraries And I get and error that it cannot find vc compiler. Hadn't I just installed VC + Pyhon? A bit googling brought me to a Stack Overflow article that sais you should install the python compiler for visual studio. My first thought was "Aaaah nice this will ensure that pip installing just works". I was wrong.
- pip install lxml

```
pip install lxml
Collecting lxml
  Using cached lxml-3.5.0.tar.gz
Installing collected packages: lxml
  Running setup.py install for lxml ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\sjuul~1.ins\\appdata\\local\\temp\\pip-build-jcmncw\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sjuul~1.ins\appdata\local\temp\pip-m2rdkk-record\install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: 'xslt-config' is not recognized as an internal or external command,
    operable program or batch file.

    ** make sure the development packages of libxml2 and libxslt are installed **

........

src\lxml\includes\etree_defs.h(14) : fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Users\\sjuul.INSIGNIT\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
    creating users
    creating users\sjuul~1.ins
    creating users\sjuul~1.ins\appdata
    creating users\sjuul~1.ins\appdata\local
    creating users\sjuul~1.ins\appdata\local\temp
    C:\Users\sjuul.INSIGNIT\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/libxml2 /Tcc:\users\sjuul~1.ins\appdata\local\temp\xmlXPathInitim9eet.c /Fousers\sjuul~1.ins\appdata\local\temp\xmlXPathInitim9eet.obj
    xmlXPathInitim9eet.c
    c:\users\sjuul~1.ins\appdata\local\temp\xmlXPathInitim9eet.c(1) : fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'C:\\Users\\sjuul.INSIGNIT\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```
- So on [StackOverflow I read](http://stackoverflow.com/questions/20460890/lxml-install-on-windows-7-using-pip-and-python-2-7):  `set STATICBUILD=true && pip install lxml` it sais:

```
As pointed out on documentation, setting STATICBUILD will tell to lxml's installer to automatically download all its binary dependencies before build.
```
- So I need libxml to work in some different way. Then I read [online I can just do this](https://www.nuget.org/packages/libxml2/):  Open nuget:  `Install-Package libxml2` but that gives our next errror

```
Get-Package : Project 'Default' is not found.
```
- On the libxml pages everything is 32 bit http://users.skynet.be/sbi/libxml-python/
- I remember golhke find out there are whl files which I can pip install. `http://users.skynet.be/sbi/libxml-python/`

```
Installing collected packages: libxml2-python
Successfully installed libxml2-python-2.9.3
```

Hmmm will the pip install work now? Nope.
- I find that there is a simple installer on this page though https://pypi.python.org/pypi/lxml/3.5.0 this appears to work
- Ok to the next step:

```
import xml.etree.cElementTree as etree
```

which raises an exception in this file (cElementTree.py):
![image](https://cloud.githubusercontent.com/assets/174411/12745904/1dff7912-c99c-11e5-8893-cbef47a05319.png)
- Apparently running in the python interpreter this is just fine:
  ![image](https://cloud.githubusercontent.com/assets/174411/12745922/46b804a0-c99c-11e5-9be7-5574844d53bf.png)
- Then I notice I can just step over this? The debugger goes on and enters the `if __name__ == '__main__':` even though **name** is definately not `__main__`

**Comment by obeleh** [comment]
I found more differences between python and PTVS:

![image](https://cloud.githubusercontent.com/assets/174411/12746596/c3904c6e-c99f-11e5-8824-19c0800b8d6b.png)

**Comment by obeleh** [comment]
I noticed that my `ect` folder isn't showing in the solution explorer but my var folder is. No clue why this behaves differently. In eclipse I could just refresh my solution and it would updat the folder explorer. With Visual Studio even a restart doesn't help

**Comment by obeleh** [comment]
I just tried debugging 2 py files at the same time :/  my "start with debugging" button is gone.

**Comment by zooba** [comment]
Thanks for all this really good feedback! Can't promise it is all fixable, but here's some of the reasons why it is how it is:

* We don't automatically install Python because we don't know which Python you want. Some will want 3.5, others 3.4, others 2.7, others Anaconda, others Canopy, etc. There are links to pages here to help people decide.
* We used to be in the standard New Project from Existing wizard, but it was very restrictive and most people didn't look there, so we moved to the place where most people looked.
* Apologies for the confusing web site. We don't control that ourselves, and the team that does obsesses about removing extra links. I'll use your feedback to try and get the extra link back (again).
* Many Python packages need to be built on Windows, which is why we normally recommend using Anaconda (since it already has them built). Not a perfect solution, but also not something we can solve unilaterally - the community is very aware and actively working on improving issues like these.
* The extra exception messages you are seeing are a known limitation of our code for detecting whether there is an exception handler available - sometimes PTVS thinks an exception will not be handled and so we break in the dialog. You can easily disable breaking from this point (with the checkbox) or just keep continuing. We hope to improve this in a future update so that we can tell when an exception will be handled better.
* If you start a Python file directly, `__name__` is always `"__main__"`, regardless of the filename. It is different when you `import` it from another module.
* Visual Studio projects are static and do not dynamically add/remove new files and folders. There is a "Show All Files" option in the toolbar that will make them visible, and you can easily "Include/Exclude" files and folders from their context menus.
* Currently we only support starting debugging for one process at a time. It is possible (though confusing) to debug multiple processes simultaneously, but we need to do some work to enable the menu items here and make sure it doesn't break. If you could file a separate issue for this, we'll triage it appropriately.

**Comment by obeleh** [comment]
Would it be possible to ship the python compiler with common libs like libssl-dev, xml libs, libffi-dev ?
Or would it be possible to add a command line like `PythonCompiler Install-Package libxml2` ?

**Comment by zooba** [comment]
It is technically possible, but we operate under other constraints that make it difficult. This is why we currently recommend getting [Anaconda](http://continuum.io) instead of python.org Python if you can't get by with the standard libraries - Anaconda comes with many of those libraries already.

**Comment by obeleh** [comment]
Would it be possible to release these as msi's and put them on the same page as the compiler? I'm sorry simply using anaconda is not going to help me. I want to be able to pyfreeze my programs and somewhat controll what I ship.

**Comment by zooba** [comment]
In theory yes, but there are different groups of people behind each of these projects. The arrangement we have now handles the different parties best, though it does rely on package maintainers producing builds for Windows, which is still a tricky proposition.

You can find many pre-built packages at [Christoph Gohlke's](http://www.lfd.uci.edu/~gohlke/pythonlibs/) site, which can be downloaded and then installed with `pip install [filename]`. These are all unofficial builds for Windows, but in our experience they work well.

I'd also suggest considering [pynsist](http://pynsist.readthedocs.org/en/latest/) as an alternative to freezing. You get an installer, rather than a single executable, but it will be considerably more reliable for your users.
