### ISSUE TITLE
"Add Reference" to pyd; set via env variable?

### ISSUE THREAD

**Issue by technomagos** [Microsoft/PTVS#1084]
Hi

We develop a couple of C extensions (pyd files) and we need PTVS to offer intellisense for them in the main editor. We use the "Add Reference" method but there is an issue with it.

We have a different pyd files for debug and release builds of each extension, so would like to tell PTVS on its startup (e.g. via an environment variable) which pyd files to use as references. The "Add reference" menu seems to **hard code the pyd full path** so we need to change manually each time we start PTVS, if we need to run in different env (debug vs release).

Maybe there is already a mechanism to do this, but a search in the docs and here did not reveal something

Many thanks

**Comment by zooba** [comment]
We should be storing them as relative paths from the project, but that may not be the case.

We'll take a look.

**Comment by zooba** [comment]
The mechanism now uses search paths rather than references, and lazily scans pyd files when they are imported in code.

It needs to be tested, but I believe the process works like this:
* we see `import spam` when analyzing some code
* we iterate through search paths finding `spam<tag>.pyd` where `<tag>` may include the `_d` suffix or a full `cp35-win32` ABI tag
* we run our scraper script which will do its own `import spam` and scrape whichever is loaded

What this means is that finding _any_ matching name will stop our search and then we'll scrape one that matches the active environment. We probably ought to do the scrape with all search paths active and let it find the file that way (after doing our source code search), as that will also work for non-CPython modules.

But we won't be making any more changes at this stage, so that may come in an update. Until then, I'm removing the milestone from the issue and we'll review it again in the future.
