### ISSUE TITLE
Installing mysql through PTVS

### ISSUE THREAD

**Issue by tbrenci** [Microsoft/PTVS#1132]
Installing mysqlclient through PTVS (2.2.3 RC) results in the error:

    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

Searching reveals no solution other than installing mysqlclient directly into the virtualenv, however this also doesn't work.. attempting to do so results in the same error it was also suggested to install the wheel from (http://www.lfd.uci.edu/~gohlke/pythonlibs/#mysqlclient), in my case "mysqlclient-1.3.7-cp35-cp35m-win32.whl" which claims that is is not a supported wheel, but the virtual env claims it's 3.5 and the wheel is 3.5 so there should be no problem... 

EDIT: Additionally, if I install mysqlclient globally and include the global env in my project I then receive this new error when I attempt to migrate: 

django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'

**Comment by tbrenci** [comment]
Additionally, if I install mysqlclient globally and include the global env in my project I then receive this new error when I attempt to migrate: 

django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'

**Comment by zooba** [comment]
The "not supported" part of Gohlke's site is the fact that the person who built the wheel is not the person/team who wrote the code. He's simply absolving himself of responsibility for the contents, while providing a very useful service. We usually recommend his wheels to people, and you can install them via PTVS by pasting the full path to the downloaded wheel (with "quotes" if there are spaces) into the install field.

The second error may be due to a misconfiguration. I haven't configured this myself recently so I don't know off the top of my head what the issue may be specifically, but when I get a chance I'll look into it for you and see what I can find. Possibly the name is not `MySQLdb` (or maybe the case is different?) for this library.

**Comment by tbrenci** [comment]
Thanks for the reply I was able to solve the issue.  It appears that if I was using an older version of python I may not have had an issue but if anyone else has this issue the steps I took to install the wheel successfully were:

- created a new django project & and 
- attempted to update pip through cmd (this results in an error)
- used "easy_install pip" which identified pip as the lastest version (8.0.3 compared to the 7.x.x that was installed by default with the django package) and installed it correctly
- then through cmd I activated the env and was able to successfully install the wheel

Sorry if these terms aren't "technically correct" but I'm a new python user, but hopefully this helps someone else.

**Comment by ghjconan** [comment]
I am using MySQL-python, you can down it for http://www.lfd.uci.edu/~gohlke/pythonlibs/.
Then you can use pip install <path>\MySQL_python-1.2.5-cp27-none-win_amd64.whl to install it.

For virtualenv scenario, just run env\Script\activate before running pip command.
