### ISSUE TITLE
multiprocessing.Process fails when passing dictionary as single argument

### ISSUE THREAD

**Issue by pyuser00** [Microsoft/PTVS#1133]
I have a function 'module.func(myDict)' that is called with a dictionary as the only parameter. When I call this function as  p1 = Process(target=module.func, args=(myDict)), Python 2.7 throws an exception saying the function requires (1) argument but (#) arguments have been passed, where # is the number of items in the dictionary. It appears multiprocessing.Process() is expanding the dictionary into a list of arguments when a dictionary is the only argument. If I modify the function to 'module.func(myDict, null)' and call p1 = Process(target=module.func, args=(myDict, 0)) the code executes as expected. 

Is this the intended behavior?

**Comment by zooba** [comment]
These general Python questions are better asked on [python-list](https://mail.python.org/mailman/listinfo/python-list), unless there's a PTVS-specific issue. But since you're here and I can see the problem, I'll just answer.

In this case, you're hitting a slight oddity where `()` is an empty tuple, `(a, b)` is a tuple with two elements, but `(a)` is just `a` with parentheses around it (exactly the same as `(a + b)`, which should not be a tuple).

To create a tuple with one item in it, you need to include a comma: `(a,)`.

In your code above, you are passing `(myDict)` when you need to pass `(myDict,)` to make sure it's a tuple.
