### ISSUE TITLE
No cross-package analysis for site-packages

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1136]
Azure-common package contains conditional aliases:
```python
try:
    from msrestazure.azure_exceptions import CloudError
except ImportError:
    raise ImportError("You need to install 'msrestazure' to use this feature")
```

It seems to be a problem for PTVS
![intellisenseproblem](https://cloud.githubusercontent.com/assets/1050156/13623009/2b18c310-e558-11e5-875f-307719d0dced.png)

There is no problem if I import directly the class

**Comment by zooba** [comment]
This is actually because we don't do sophisticated enough cross-module analysis when analyzing installed packages. We do `msrestazure` and `azure` separately, and they don't know anything about each other, which is why the imports don't resolve.

We could probably scan the install metadata and selectively load other packages to handle this. If we try and load everything all the time then analysis will never complete.

**Comment by lmazuel** [comment]
Even if it's not solving the whole problem, if I add a `__all__` statement this can help? Because in that case, you will have the explicit set of stuff I want to export.

**Comment by zooba** [comment]
No, the only way to help is to copy the entire type definition over (or put a stub definition under `if False`).
