### ISSUE TITLE
Intellisense Completion DB stops with error 'This interpreter is already being analyzed'

### ISSUE THREAD

**Issue by alexandertmaher** [Microsoft/PTVS#1168]
Hi - not sure if this is the right place to post, but any help is appreciated.  

When I click 'Refresh DB' it says collecting files for about 5 seconds, then stops.  There are 13  packages that have been analyzed, but the vast majority have a red !

Using VS2015, PTVS 2.2.2, Anaconda 3.5... see diagnostic info for all the details...

[Diagnostic Info 2016-03-18T151648.txt](https://github.com/Microsoft/PTVS/files/180246/Diagnostic.Info.2016-03-18T151648.txt)

**Comment by zooba** [comment]
It sounds like the analyzer is either getting stuck or just crashing. Unfortunately, it was still running when you grabbed that diagnostic info, so we don't have its detailed log.

Could you make sure you don't have any `Microsoft.PythonTools.Analyzer.exe` processes running and then get the diagnostic info again?

(Oh, and you're in exactly the right place to post.)

**Comment by alexandertmaher** [comment]
ok - this should be the complete log now.  Let me know if it still isn't -- it ends abruptly after 'start analysis'.  There were no Microsoft.PythonTools.Analyzer.exe instances running when I generated it.

Thanks for your help Steve

[Diagnostic Info 2016-03-18T204426.txt](https://github.com/Microsoft/PTVS/files/180577/Diagnostic.Info.2016-03-18T204426.txt)

**Comment by zooba** [comment]
It looks a bit like your Anaconda install has become corrupted - did you update `scipy` and not `numpy` or other packages recently? (I see a lot of errors where `scipy` is expecting `numpy` to have certain names, and `skimage` is expecting `scipy` to have certain names that it doesn't.)

Also, since you're using Anaconda, you really ought to use `conda` from a command line to manage packages, rather than the `pip` support we provide in VS. `conda` knows how to prevent these situations (provided you use it all the time - mixing the two tools is not easy).

Our logic for whether the DB needs updating is based on timestamps, so it's possible that those have become confused. It will take time to regenerate everything, but you should close VS, delete `%LocalAppData%\Python Tools\CompletionDB\14.0\9a7a9026-48c1-4688-9d5d-e5699d47d074\3.5`, then reload VS and regenerate the DB. I suspect it will be fine after that.

**Comment by tdaliviu** [comment]
Same here.
[Diagnostic Info 2016-04-21T120203.txt](https://github.com/Microsoft/PTVS/files/229552/Diagnostic.Info.2016-04-21T120203.txt)

**Comment by zooba** [comment]
@tdaliviu Does my suggestion above (last paragraph) help?

**Comment by tdaliviu** [comment]
@zooba, sorry, missed that last sentence. Yes, that did help, thanks.
