### ISSUE TITLE
Cyrillic bug

### ISSUE THREAD

**Issue by VladIT4** [Microsoft/PTVS#1170]
Hello! Sorry for my bad english. After running the debugging symbols Cyrillic are displayed as follows:
![https://i.gyazo.com/2d6f710ae14583be401d6b4d6cad050d.png](https://i.gyazo.com/2d6f710ae14583be401d6b4d6cad050d.png)
If run without debugging, then everything is fine. As if saving options to specify the encoding UTF-8, characters are derived using the print be good, but the output of the input(text) function has a problem
![https://i.gyazo.com/047a633b22910d045957c7b374147fc8.png](https://i.gyazo.com/047a633b22910d045957c7b374147fc8.png)
If you remove the check mark next, everything works fine:
![https://i.gyazo.com/97498c47db004f33f49f4d58099ffbef.png](https://i.gyazo.com/97498c47db004f33f49f4d58099ffbef.png)
Make please default encoding UTF-8, it was not necessary to specify it each time. And please solve the problem with the encoding functions input(). 
Thanks!

**Comment by zooba** [comment]
Thanks for this! I don't remember exactly what encoding we're using in this situation, but we'll take a look.

**Comment by zooba** [comment]
@huguesv Your current project will either fix this automatically, or will prevent anyone else from fixing it in the meantime. Can you check this when you get to it? (I think `write_string` and `read_string` in `visualstudio_py_util.py` are the culprits, or the `_DebuggerOutput` class.)

**Comment by zooba** [comment]
So here's the flow of how this happens:
* `input()` grabs `sys.stdin`, `sys.stdout` and `sys.stderr` (which are our wrapper classes)
* `input()` calls `.fileno()` on these
* our wrapper class forwards to the original object and returns the fileno
* `input()` compares filenos with the original streams and sees that they are the same
* `input()` encodes the prompt using `sys.stdout.encoding` (which is our wrapper class's `utf8`)
* `input()` calls through the readline hook passing the encoded prompt
* the readline hook writes the prompt to stderr directly, which expects ACP rather than UTF8 bytes

It would be possible to work around this by providing our own `.fileno()`, similar to what we do for the REPL, but I don't want to take that change at this stage (too close to release). This can be done as part of #749 and future REPL work (as an aside - it may be interesting to use `sys.displayhook` and the readline override for REPL integration, rather than what we currently have...)

**Comment by zooba** [comment]
Probably the best way to deal with this immediately is to provide an option to switch between `utf-8` and `locale.getpreferredencoding()` as the encoding used for the output hooks. We can continue to default to UTF-8, as that has been reliable for long enough.

Note that the first screenshot above is expected behavior - it's coming from Python's parser and not us (Python 3 assumes UTF-8 unless told otherwise via a coding comment).

**Comment by zooba** [comment]
And to address the two different bugs in the original post:
* default file encoding is now UTF-8 (but it was ACP in an earlier version when this was reported)
* workaround for `input()` displaying incorrect prompt is to disable tee to output, as in the first post

This issue is now tracking an enhancement to detect cases where users override the default encoding from UTF-8 without also adding a coding comment. This is why Python failed in the first screenshot - it assumes UTF-8 (for Python 3) or ASCII (Python 2) unless you specify. The best we can do in VS is warn you if you need to specify the encoding but haven't.
