### ISSUE TITLE
Startup file not always highlighted in the solution explorer

### ISSUE THREAD

**Issue by erl987** [Microsoft/PTVS#1173]
Hi all,

in VS 2015 not always the current startup file as well as the active python environment is shown highlighted (i.e. in bold). This happens while the startup file is still active. When you change the startup file, then highlighting works again.

I could not figure out, under which conditions this happens. I am using Python tools version 2.2.2.

Best regards,
Ralf

**Comment by zooba** [comment]
Yeah, we haven't been able to figure this one out either. It's been happening for many releases.

I think it's a race-condition within Visual Studio startup, where _we_ have requested that some items be bolded, but _Visual Studio_ ignores the request because something runs out of order. There's no way for us to detect and fix this, as far as I can tell.

Issue #162 is the same as this, so I'll close this as a duplicate.
