### ISSUE TITLE
Problem debugging with enable standard library

### ISSUE THREAD

**Issue by jrowen** [Microsoft/PTVS#1214]
I'm trying to debug a script with the 'Enable debugging of the Python standard library' option checked and receive errors related to uninstalled packages.  For example, both lines below generate errors when debugging with the option checked but work fine when it is not checked.

```
import pandas as pd
from cassandra.cluster import Cluster
```

For the first, there is an error related to the `matplotlib` library missing, but it is not being used and therefore not installed.  For the second, there is an error related to `libev` (`cassandra.io.libevwrapper`) and a missing C extension, but again, this is not being used.  It seems that that debugger is trying to load all referenced libraries, regardless of whether they are installed.

I'm using Python 3.4, Visual Studio 2015 and PTVS 2.2.3.

**Comment by zooba** [comment]
What's actually happening is that Python is trying to load all referenced libraries (`import` is a statement - it actually runs code whenever you reach it) and when they aren't found there is an exception being raised.

Normally, we'd ignore the exception until it reached your code, but you've changed that option.

What should _really_ happen is that we should scan all the code in the current call stack, determine that there is an `except ImportError` somewhere, and ignore the exception automatically. But it seems that we can't prove that it is handled, so we break to tell you (the alternative would be to always ignore them in this case, but since you're running in a debugger we assume that you want *more* information, not less :) ).

You can safely press F5 here to continue, and there is also a checkbox in the popup window to disable ever breaking on this kind of error. Just remember that when you hit another `ImportError` that is not handled, you won't see the debugger - just the normal Python stack trace.

**Comment by jrowen** [comment]
Thanks for the suggestion.  I unchecked the box and continued to run, but now run into an IndexError that appears to be originating with `from cassandra.cluster import Cluster`.
```
>	SubPattern.__getitem__ in sre_parse line 147	Python
 	_compile in sre_compile line 84	Python
 	_compile in sre_compile line 150	Python
 	_compile in sre_compile line 191	Python
 	_compile in sre_compile line 150	Python
 	_code in sre_compile line 557	Python
 	compile in sre_compile line 572	Python
 	_compile in re line 294	Python
 	compile in re line 223	Python
 	_TemplateMetaclass.__init__ in string line 70	Python
 	string module line 73	Python
```

**Comment by zooba** [comment]
Exactly the same issue, with the same solution.

Though this particular one (`sre_compile`) occurs enough that I'm just about ready to put in a special check for it and always ignore it...
