### ISSUE TITLE
Python Interactive Environment Won't Start 

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/PTVS#1217]
Hello. When I try to open the Python Interactive Environment the window says:

"Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio."

Restarting Visual Studio does NOT help. Also, clicking the refresh button on the Python Interactive window does not help, but it does bring up the >>> prompt, which doesn't respond to inputs, but instead just responds as shown below

"Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio.
Interactive window is not yet started.
>>> !help
... Help
... 1+1
... "

However, VS will run Python programs, or at least "Hello, World". The Python Environment tab shows that the Anaconda environment has been found and is working. Please help me to resolve this issue. 

I think I have all the latest versions of the software:

Microsoft VS Enterprise 2015: Version 14.0.24720.00 Update 1
Python Tools for Visual Studio 2.2.30718.00
Anaconda 4.0.0 with Python 3.5.1

**Comment by zooba** [comment]
You may have ended up in a corrupt state where some DLLs are from VS 2015 and most of it's from VS 2015 Update 1 - that's the only way I can think of that would put you in this state.

Update 2 has been released now, so you may want to install that. Otherwise, I'd suggest running a VS repair through Programs and Features, which should ensure you have the right files installed. If neither of those work, we'll have to do some more thorough investigation, but try them first.

**Comment by LowerySJ** [comment]
I installed Update 2 and it works now. Thanks!

**Comment by dongzhixihe** [comment]
I installed update 3, however, it still doesn't work.
