### ISSUE TITLE
IntelliSense does not show parameters in case of single line function definition

### ISSUE THREAD

**Issue by RussBaz** [Microsoft/PTVS#1220]
As it turns out, this is a valid statement in Python (this style is even used in the standard library, e.g. in collections.UserList):
```python
def foo(param): return param
```
However, IntelliSense does not show 'param' as available after I finish typing return.

Is this an intentional behaviour?

**Comment by zooba** [comment]
It's not intentional.

I'm guessing it's related to our handling for when you're at the end of a function but up one level of indentation (i.e. _after_ and _outside_ the function, but there's no text there to prove it yet - only whitespace). Being at the end of a single line function probably looks the same to the logic we have there.

**Comment by DinoV** [comment]
This is actually fixed w/ the fix for #1000, we were always finding the start of a statement to figure out intellisense instead of the start of the current expression.  The fix for that is in my active pull request.
