### ISSUE TITLE
PTVS "March 2016" version depending on VS2015 Update 2 ? 

### ISSUE THREAD

**Issue by traits** [Microsoft/PTVS#1228]
When I make an attempt to update PTVS to v2.2.3 in VS2015, VS seems to require an update to the current VS service pack (update 2). This update is broken and I would prefer to avoid it. Is this a prerequisite?

Regarding version numbering:
The "Extension an Updates" Menu in VS2015 states "Current Version: 2.2.2" and "New Version: 2.2.3" but  Help->About Microsoft Visual Studio is showing a slightly puzzling "Python Tools for Visual Studio 2.2.31124.00". Is this correct?

**Comment by zooba** [comment]
Yeah, version numbering is a little bit weird. Help/About shows our build number, which is automatically generated after the first two numbers - Tools/Extensions should show the release version "2.2.2". However, since these values are meaningless for the majority of people downloading us through the VS installer (who just want to know roughly how much newer it is, since they've already been told that it _is_ newer), we switched to displaying an approximate date.

We don't actually require Update 2 for PTVS 2.2.3, so if you download the installer directly from our [releases page](https://github.com/Microsoft/PTVS/releases) you can update without getting the VS update. (Since we _do_ require Update 1, there was the potential for some weirdness in the installer - VS updates are represented as separate items, not as a single item with different versions, so it would look like a dependency conflict.)

**Comment by traits** [comment]
> However, since these values are meaningless for the majority of people

Not always (but I agree, in many cases). For example, in my particular case, because VS interfered in his annoying attempts to install Update 2, I wasn't sure what eventually happened and what not. It was actually the reason, to check the "About" information. It is simply reassuring to know, that at least some part of an installation (in this case PTVS) did the expected thing (in this case, not to install anything).
