### ISSUE TITLE
ptvs 2.2.3

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#1233]
Upgraded to ptvs 2.2.3 from 2.2.2.  Now Vs isn't recognizing anything I add to the search path, I've confirmed it by printing the path in a test program.

How do I debug / fix this?

**Comment by zooba** [comment]
Can you share your test program? And while you've got your project open, collect the info from Tools, Python Tools, Diagnostic Info and either post it as a [gist](https://gist.github.com) or email to ptvshelp@microsoft.com.

**Comment by sma202** [comment]
It looks like putting "PYTHONPATH" in the python environments solves the issue.  Does this get reset somehow?  I don't remember setting this explicitly before.  If we add a search folder through visual studio, it should automatically take it and add it to the PYTHONPATH.  Isn't that the point of adding to search path?

It's pretty counter-intuitive right now and can waste a lot of time for someone.  Please fix this please.

**Comment by zooba** [comment]
It was probably never set. When you add a custom environment we don't automatically know what environment variable to use to provide search paths, so that needs to be entered as part of configuration.

The bug in #211 means we don't assume you meant `PYTHONPATH` when you didn't specify anything. Arguably, assuming that is bad behavior, as now there could be something you can't see causing problems (as opposed to your problem, where the cause _could_ be seen), but it seems to be worth the change so it will surely happen sooner rather than later.
