### ISSUE TITLE
cannot import ptvsd

### ISSUE THREAD

**Issue by ejc1** [Microsoft/PTVS#1235]
I have installed ptvs 2.2.1under VS2015 pro (update 2).  I am able to use main features such as templates, editor, and debugger.  But now I want to do remote debugging on Linux.  The instructions for that
(https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging)
say to put the line 
import ptvsd
in the file of python code.  I try that and get an error because it is not recognized as a module.  What additional step or steps do I need to take so that I can use that module?  Thank you.

**Comment by ejc1** [comment]
I found out that I also had to download and install ptvsd in addition to ptvs.  In the run menu, I used 
pip install ptvsd
It seemed to succeed, but I still cannot import ptvsd.  I can find no .pyd nor .dll to reference from the project.

**Comment by ejc1** [comment]
According to the Microsoft Canadian Developer Association
(https://blogs.msdn.microsoft.com/cdndevs/2014/10/16/part-5-get-started-with-python-debugging-in-ptvs/)
I had to copy the ptvsd folder from C:\Python27\Lib\site-packages to the folder that contains my solution, and then add the folder to the project.  Now it works.  Thanks, eh?

**Comment by int19h** [comment]
There are two ways to obtain the `ptvsd` package.

One is, indeed, to copy it to your project folder. You don't even need to get it from pip for that - you can just copy it from `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2`.

Alternatively (and easier), you can use pip. But then you need to do that _on the remote machine_ (because that's where the `import ptvsd` statement is actually running!). So in your ssh session to that Linux box, do `sudo pip install ptvsd`, and you should be good.

**Comment by ejc1** [comment]
Thank you.  I thought pip was supposed to make the package available for import, without copying it locally, but for some reason, that didn't work.  If I understand correctly, you are also saying that the remote machine also needs access to ptvsd files.  And that on the remote machine, I need to either have the ptvsd folder in the same directory as my code, or ptvsd needs to be installed on the remote machine in general.  Correct?

**Comment by int19h** [comment]
Yes. In fact, you don't need it on the local machine at all (unless you're also running that code locally, and want to debug it locally using remote attach by attaching to `localhost`). It's only needed on remote - it's the server side of the connection, and PTVS itself is the client side.

One other trick that you can do is this:
```python
try:
   import ptvsd
except ImportError: pass
else:
  ptvsd.enable_attach(...)
```

This way, `ptvsd` is only imported and set up if it's installed, and otherwise it runs normally. If you do this, and remove your local `ptvsd` package on your development machine (so that only remote one has it), then you can debug locally with plain F5, and remotely with `ptvsd`.

**Comment by ejc1** [comment]
I don't want to get errors while I edit, so that's one reason to install ptvsd locally.  The Try block is a good idea too.

**Comment by int19h** [comment]
Ah, I see. If you're in control of how you launch your program remotely, then you might want to avoid `import ptvsd` entirely. Instead, you can use `ptvsd` as a launcher for your app (without making any changes to your source code, so it wouldn't even have to reference the module). It's not documented in the wiki, but if you run it with `python -m ptvsd --help`, you will see the various command line options that let you do that (they all map to various `enable_attach` arguments).

**Comment by ejc1** [comment]
Great tip!  I will try that.  The main things I want to do are to edit using the VS editor, and be able to set breakpoints and examine variables within VS while the code runs on Linux.  That's why I'm working on getting ptvsd running.

**Comment by ejc1** [comment]
Your suggestions worked very nicely.  I have another question.  I can attach to the remote debugger, and I can set breakpoints and examine the value of variables (yay).  It seems like a lot of steps every time I run, though.  If I make a change to the python code, I have to manually upload it to Linux and run it there.  Then while it waits for debugger attachment, I have to select Debug -> Attach to process, then select Python remote (ptvsd) and type my account and Linux machine name, and then select the remote process.  Is there any way to get the local source file to automatically get uploaded every time it is saved, and any way to automatically start the remote code running and attach to the remote process with just a click to the Start arrow?  Thank you.

**Comment by int19h** [comment]
Unfortunately, no. You could probably script it by using [DTE](https://msdn.microsoft.com/en-us/library/envdte._dte.debugger.aspx) to drive VS, and presumably Putty to drive the remote system over SSH.

Enabling this as a single-click scenario directly from PTVS has been on the TODO list for a while. Basically, it should be possible for us to use an ssh connection to do all this for you - publish your source to the other end, set up `ptvsd` there, and then attach to it.

I can't find an issue in the tracker that would be specifically about this, though, so feel free to create one. #763 and #185 are possibly related.

**Comment by ejc1** [comment]
Thank you.  I have created a separate issue to request this.
