### ISSUE TITLE
native debugger fails when attaching both python and native debuggers

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#1242]
![image](https://cloud.githubusercontent.com/assets/7870949/14869517/901659d6-0c99-11e6-9387-01a3e7c5f0dd.png)

**Comment by denfromufa** [comment]
very similar issue, but now python debugger complains:

![image](https://cloud.githubusercontent.com/assets/7870949/14869985/a36de94c-0c9c-11e6-957d-aaf0138f343f.png)


the modules shows a lot of python symbols loaded:


![image](https://cloud.githubusercontent.com/assets/7870949/14870007/e451c06e-0c9c-11e6-9e8f-87404205bf68.png)

**Comment by zooba** [comment]
Ping @int19h 

I think we've seen this before, but I don't recall what the issue was.

**Comment by int19h** [comment]
I think I never got the repro working last time. This really needs to be debugged to figure out what's going wrong. Since .py files are already showing up in the Modules window, this is happening very late in the attach process, when our runtime is already registered etc. 

In fact, I wonder what exactly is working incorrectly aside from the error message. i.e. are breakpoints hit in Python? Does stepping work?

**Comment by denfromufa** [comment]
If I have c# assembly's symbols then only c# can be debugged, otherwise
only Python can be debugged! Of course I'm using pythonnet, one of the
latest builds.

**Comment by denfromufa** [comment]
can I provide you with minimal reproducible example for debugging: c# -> pythonnet -> cpython?

**Comment by int19h** [comment]
Yes, a self-contained repro would be extremely helpful.

**Comment by Artfunkel** [comment]
@zooba: You're thinking of Issue #481, which is about the same error message.

**Comment by denfromufa** [comment]
Ok, no more issues with this:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython
