### ISSUE TITLE
mpi debugging

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#1243]
I'm using mpi4py, how do I debug code within ptvs?  So for example, in the cmd line I would use:

mpiexec -n 2 python mpi_test.py

How do I do using visual studio?

**Comment by denfromufa** [comment]
@sma202 you can use ptvsd which you can inject in your code and connect to it from PTVS remote python debugger.

**Comment by sma202** [comment]
What about just trying to run the mpi code locally on the debugger?  How do I pass in mpiexec to the ide?

**Comment by zooba** [comment]
If you have a project set up, you _could_ go to Project Properties, Debug and change the interpreter path to "mpiexec" and interpreter arguments to "-n 2 python" (using full paths where required). However, while this will work fine for Ctrl+F5, it is unlikely to work well for running under the debugger (since there will be 2 processes trying to attach, which is not currently supported).

For local testing, you can still use `ptvsd` and attach to each process individually. You'll just specify `localhost` (or `127.0.0.1`) as the "remote" machine.
