### ISSUE TITLE
Is there a way to set editor Intellisense to show possible methods like in REPL window?

### ISSUE THREAD

**Issue by luisTJ** [Microsoft/PTVS#1276]
Pictures below show the differences between editor completion list vs REPL completion list.
Note that the editor completion list shows only base object methods but not the pandas dataframe's methods. I was wondering if there is something to set to make this happen? 

![image](https://cloud.githubusercontent.com/assets/1425306/15133993/8102836e-162d-11e6-9b23-88d911d2b130.png)

![image](https://cloud.githubusercontent.com/assets/1425306/15134005/a041d130-162d-11e6-9487-17ff8c5e2242.png)

**Comment by tommai78101** [comment]
I'm also looking into this. I'm on Python 3.5.1.

As far as I can tell, there are no methods of doing this.

**Comment by zooba** [comment]
Afraid there isn't.

The big difference here is that your code in the REPL is actually being executed, whereas in the editor we don't ever execute your code for real. But because we don't have access to a real object (to do `dir(...)` on), we can only provide information we've been able to get by inspecting either the source code or the class object.

(To understand why we do it this way, type `import shutil; shutil.rmtree("C:\\Windows")` in the editor, but then _don't_ write it in the REPL ;) )

We're constantly investigating ways to make this better, so each new release should have improvements. Our current latest release is part of [Visual Studio "15" Preview 2](https://www.visualstudio.com/en-us/news/releasenotes/vs15/vs15-relnotes) (if you try it with the [new installer](https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs) it shouldn't mess up your machine as much as VS previews normally do).

That said, `pandas` (and related package `numpy`) are incredibly difficult to extract information from without actually running all of your code. When we (and they) support type hints (new in Python 3.5), things should get better, but until then there's going to be differences here.

**Comment by luisTJ** [comment]
Thank you for your clarification :+1:  :-)
