### ISSUE TITLE
Project script arguments are url-decoded

### ISSUE THREAD

**Issue by annatisch** [microsoft/PTVS#1282]
Hello,
When I include url encoded script arguments in the project debug properties they get decoded when the script is run.

E.g., if I include the argument "2016-05-11T21%3A31%3A23Z", it will be decoded to "2016-05-11T21:31:23Z" when executing the script.

This seems to happen regardless of whether the arguments are in quotes or not.
Is this expected behavior? And if so, is there a workaround so that arguments will be passed to the script "as is"?

Cheers,
Anna

**Comment by zooba** [comment]
This happens because we store the argument in the .pyproj file, which is XML.

You could try encoding the percent signs - "2016-05-11T21**%25**3A31**%25**3A23Z" - I don't believe it will double-decode. I think you could also write it as `$([msbuild]::Escape('2015-05-11T21%3A31%3A23Z')` to do the escaping for you.

Maybe we should automatically do this encoding, but it seems like that may be too magic. We'll think about it.
