### ISSUE TITLE
No intellisense for exceptions?

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/PTVS#1293]
I have a simple Python program:

```
import re

# Pattern to match for objects with no __repr__ method
pattern = re.compile('^<.*>$')

def get_properties(obj):
    for member in filter(lambda x: not x.startswith('__'), dir(obj)):
        try:
            attr = getattr(obj, member)
            if not callable(attr):
                if not pattern.match(str(attr)):
                    yield member, attr
        except Exception as ex:
            print ex   #===>> no intellisense here
            # Catch members not implemented
            continue

def print_properties(obj):
    for prop, value in get_properties(obj):
        print '{:50}: {}'.format(prop, value)
```

On the line 'print ex'  when I start typing 'print ex.'  no dropdown appears showing the members (arg and message, in this case) available to me.

**Comment by zooba** [comment]
Good catch. (I don't know if this has ever worked...)

**Comment by zooba** [comment]
Actually, I take that back - the code to do this has been there forever and it seems to work fine.

Can you capture the output from Tools, Python Tools, Diagnostic Info and post it as a [gist](https://gist.github.com) (or email to ptvshelp@microsoft.com)? There may be something about your setup that's causing issues here.

**Comment by gbritton1** [comment]
gist: [Dianostic Info](https://gist.github.com/gbritton1/92eff26daf9e683bb96d29d8ac921520)

**Comment by gbritton1** [comment]
BTW, according to this page: [Microsoft Support Lifecycle](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Visual%20Studio), VS 2012 will not exit mainstream support until 1 Sep 2018.  Is it possible to continue to support PTVS for VS 2012 until that date as well?

**Comment by zooba** [comment]
Thanks. I'd first suggest updating to [PTVS 2.1.1](https://github.com/Microsoft/PTVS/releases/v2.1.1), which was the last version we released for VS 2012. It had a number of fixes for IronPython that may be affecting this. If that does not help, then we'll get someone here to set up an equivalent system and try and reproduce the error.

PTVS is not covered by the support lifecycle for VS 2012 as it is not considered part of that product (it's provided "as-is" as a separate extension). If you/your business is willing to enter into a dedicated support contract, email python@microsoft.com and we'll see what we can arrange. Otherwise, the last version of the source code that worked with VS 2012 is linked from [here](https://github.com/Microsoft/PTVS/releases/v2.1.1) and updating/building it yourself is your best bet for continued VS 2012 support.

**Comment by gbritton1** [comment]
OK.  And thanks for that link!!!!

**Comment by gbritton1** [comment]
BTW that update fixed my intellisense problem!!!
