### ISSUE TITLE
Moving python project into Centos Environment

### ISSUE THREAD

**Issue by adityosnrost** [Microsoft/PTVS#1303]
Hi, 

I would like to ask about how to move Python flask project that created by visual studio python into Centos environment for testing and production purpose. I have created a sample flask project from visual studio template and tried to move it directly into Centos environment. These are my step:

1. Create flask project from visual studio
2. Zip or 7zip it and move it into Centos VM, then unzip it
3. Giving chmod a+x mode into runserver.py file.
4. tried to run it with ./runserver.py

It did not run and came with these error:
![image](https://cloud.githubusercontent.com/assets/8223156/15351153/fe94135c-1d07-11e6-921c-97d60543d1bf.png)

I have created python flask project before directly into Centos and edit it directly, it was felt inconvenience with IDE from FTP program.

I would like to move into Visual IDE and Microsoft platform for python development but still deploy it on Centos that prepared by my company.

Any suggestion on how do this ?

Thanks

**Comment by zooba** [comment]
I think you may just need to add a shebang line to the start of the `runserver.py` file. Something like:

```
#! /usr/bin/env python3
```

as the very first line. (Use `python2` if you are expecting that version.)

Windows associates the `.py` extension with Python, but most Linux variations need the shebang line. Since it starts with a `#`, Python will see it as a comment, so you can also use it on Windows.

You'll also need to make sure that you've installed flask and its dependencies. `pip install -r requirements.txt` should do that, though you probably want to create a virtual environment first. [This](https://www.digitalocean.com/community/tutorials/common-python-tools-using-virtualenv-installing-with-pip-and-managing-packages) looks like a helpful list of some of the commands you'll need.

If you want to be able to debug your code in VS while it's running on CentOS, see our [remote debugger](https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging) information and video.

**Comment by adityosnrost** [comment]
Hi, thanks for your reply. So I need to create new virtualenv inside my project. Can't I use windows created virtualenv ?

Thanks

**Comment by zooba** [comment]
Afraid not. virtualenvs are not transferable between machines, so you need to recreate them whenever you move. They also include files copied from the base Python install (e.g. `python.exe`, which is certainly not going to work if you copy from Windows to Linux).

An easy way to make sure you have exactly the same libraries is to do this on your dev machine:
```
pip freeze > requirements.txt
```

Then copy `requirements.txt` and do this on the target machine (commands may vary based on OS/Python version/names):
```
python -m venv env
env\Scripts\pip install -r requirements.txt
```

Many Python-specific deployment systems will detect a `requirements.txt` file and do this automatically for you. Note however that you need to be able to install all packages on both systems for this to work - some packages won't work well on Windows or vice versa.

**Comment by adityosnrost** [comment]
Hi, sorry for my late reply. Thanks for your explanation, it helped me a lot with configuring environment for my flask development.

Thanks

Best Regards,

Adityo
