### ISSUE TITLE
PTVS crashes with pypy and  Net framework 4.6.2

### ISSUE THREAD

**Issue by Kurdakov** [Microsoft/PTVS#1313]
PTVS crashes with pypy being added as environment and Net framework 4.6.2 preview being installed on Windows 10,

the log is

Faulting application name: devenv.exe, version: 14.0.25123.0, time stamp: 0x56f22f32
Faulting module name: clr.dll, version: 4.6.1532.0, time stamp: 0x56e76357
Exception code: 0xc00000fd
Fault offset: 0x0001e99e
Faulting process id: 0x18b0
Faulting application start time: 0x01d1b3bef7241071
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll

while the crash is well known ( though no current fix is down loadable ) https://support.microsoft.com/en-us/kb/2640103 the reason it appears might be a bug in PTVS

**Comment by zooba** [comment]
I suspect it's not actually that crash, or the fault offset would be the same, but it's almost certainly a bug.

Can you copy the output of Tools, Python Tools, Diagnostic Info into a [gist](https://gist.github.com)? Or look for a nearby event in Event Viewer with a detailed stack trace (we automatically collect those into the diagnostic log, so that may be easier).

**Comment by Kurdakov** [comment]
I  uninstalled Net framework 4.6.2 so had to re install to see the problem again, but currently no error appears ( so I think additional info now will not be useful ) 

as soon as I have that problem again,  I will provide requested information

**Comment by Kurdakov** [comment]
btw in fact Visual Studio would have the same problems just less frequent than with with pypy with which it stops working always, I started notice that  since version of PTVS which started support Django 1.9, for example VS regularly  closes during adding virtual environment.

**Comment by zooba** [comment]
Unfortunately, without any information from the logs we can't do anything to fix those issues. But since there are no errors coming from the event log, it may not actually be something we can fix anyway.

Hopefully the crashes will show up in the reports people send back to Microsoft and the right team will get them.

**Comment by Kurdakov** [comment]
found a problem - this was a combination of new asp web tools with node tools extensions which VS somehow loaded when having PTVS project.

**Comment by zooba** [comment]
Glad to hear it!
