### ISSUE TITLE
No module named "abc"

### ISSUE THREAD

**Issue by cutecode** [Microsoft/PTVS#1330]
I created my own module (abc) in a sub folder with the **init**.py created, then from abc import function. It's not able to resolve the abc module. Is this support on automatically build the module, and publish to my virtulenv?

**Comment by zooba** [comment]
That's an interesting error, since `abc` is part of the standard library and should always be available (incidentally, you shouldn't name your own modules the same as standard library modules or you could break libraries).

Could you show the full layout of your project? Maybe a screenshot of Solution Explorer?
