### ISSUE TITLE
Build and package with dependencies

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/PTVS#1332]
This is actually the key reason I chose VS for python dev over another environment.  I am working with a standard python application that needs to be built with the environment it is using turned into a .exe with everything it needs to be dropped on a server and run as a cron job.  My target is Azure Cloud Services, Azure Web Jobs and eventually Azure GPU when that comes around.

I tried the Cloud Services project type, however there were dependency issues in which the application had issues bringing in various packages.

**Comment by zooba** [comment]
We don't have anything for this right now (since Python doesn't really have anything official to do it), but you may find some information in [this blog post](https://blogs.msdn.microsoft.com/pythonengineering/2016/04/26/cpython-embeddable-zip-file/).

As one suggestion, I'd strongly recommend thinking about extracting a ZIP file onto the server, rather than dropping a single EXE. There are a number of features of CPython that simply don't work well when you merge everything into a single image, but are completely fine if you can drop files into a directory and run an EXE out of that. The blog post I linked above should help.
