### ISSUE TITLE
Autocomplete when typing 

### ISSUE THREAD

**Issue by gglanzani** [Microsoft/PTVS#1409]
When typing a dot after an object, the intellisense menu pops up, as it should. 

I was wondering if it is possible to have it pop up to complete the variables names as well, without explicitly invoking it with space + bar. I.e. I would love to have in the autocomplete pop up on the pipe in the following snippet

long_variable = 42
short variable = lon|(g_variable * 2)

(Sorry for the lack of the back ticks, I'm on my phone).

**Comment by zooba** [comment]
That should already work (unless you're not on the latest version - we added it for 2.2 IIRC).

It currently does not automatically pop up on the left-hand side of an assignment, since that turned out to be really annoying. But we're looking at ways to enable it without regularly getting in the way.

It's possible that syntax errors could prevent it from appearing - are there any errors being reported in your code?

**Comment by gglanzani** [comment]
New file: all works.

Existing file without syntax error but with modules missing from path (PySpark in this case): intellisense on known modules works, autocompletion for variables in scope doesn't. Is that intended?

**Comment by zooba** [comment]
Can you be more precise about what you mean by "autocompletion for variables in scope" doesn't?

```python
def f():
    my_var = 123
    my|   # didn't automatically pop up after typing?
```

or

```python
def f():
    my_var = 123
    my|   # didn't know what my_var is after pressing Ctrl+Space?
```

Currently the first one is intentional (and we intend to change it), but the second one would be a bug.

**Comment by gglanzani** [comment]
First one. If this is intentional, then we can close.
