### ISSUE TITLE
Visual Studio 2015 with PTVS 2.2.4.  Intellisense not working

### ISSUE THREAD

**Issue by DavidChilvers** [Microsoft/PTVS#1416]
I have Visual Studio 2015 enterprise and installed PTVS 2.2.4 a few days ago.  I have a python project open in VS2015 copied from an Eclipse/PyDev project. The good news is that it runs in VS2015 with CPython 3.4 and I can debug it. The bad new is that Intellisense not working in the text editor. If I type os. then it comes up with no "no completions". Doing the same thing in the Interactive widow does work.

I have tried various fixes, refreshing the database, Restarting VS2015, using IronPython rather than CPython and creating a new environment. In the latter case it spent 15minutes building a new database.

**Comment by zooba** [comment]
Can you get the output from Tools-Python Tools-Diagnostic Info and put it in a [gist](https://gist.github.com) or email it to ptvshelp@microsoft.com?

It sounds like your CPython install is failing to run correctly, and that log should have the error messages in it. (Feel free to read through and diagnose it yourself, but if you do I'd also like to hear the details so we can try and prevent it happening in the future.)

**Comment by mikebourbeauart** [comment]
I'm having the same problem.  I'm using virtualenvs, but I don't see why it wouldn't autocomplete basic python modules.

Here's my gist: https://gist.github.com/mikebourbeauart/1fb517f74decce8d0264b6c62efeff15

**Comment by zooba** [comment]
It sounds a lot like we're hitting an exception while reloading the database, but are handling it without reporting any problem.

Since I can't reproduce this locally, what I really need is someone with this problem to start two copies of VS, attach the debugger of one of them to the other, enable breaking on all exceptions, and then open the Python project having the problem. At least knowing what kind of exception (or that there is one at all) will be helpful - any more detailed information would be handy too.

**Comment by mikebourbeauart** [comment]
Fixed it! Running 2 versions of VS didn't pick anything up, but when I turned on all python exceptions in my opened project it found a key error in a JSON dictionary- the key didn't exist.  After adding the key to the JSON file Intellisense started to work again for some reason.  I can't seem to reproduce the error though, Intellisense is just working now no matter what.  I'm trying to attach a basic setup to this post (zip file) but it's telling me it doesn't accept that file type... even though it give zip as an example file type.

**Comment by mikebourbeauart** [comment]
Spoke too soon. It's broken again.  Happened when I was playing with virtual envs

**Comment by zooba** [comment]
Inside your virtual environment there'll be a hidden `.ptvs` folder. Inside there is an `AnalysisLog.txt` file - typically these are included in Diagnostic Info, but if the virtual environment is not active at the time then we won't find it.

You could scan through there to see if there are any major errors (typically they look like a .NET stack trace, rather than a Python stack trace), or send it to us to take a look at.

**Comment by mikebourbeauart** [comment]
Not sure what to look for myself haha, so here it is:
[AnalysisLog.txt](https://github.com/Microsoft/PTVS/files/516965/AnalysisLog.txt)

**Comment by zooba** [comment]
There's nothing to see in the log, unfortunately.

I guess we had some setting in the `.pyproj` file that was incorrect, so recreating the project will have fixed that. We don't keep any information in the `.vs` folder or `.sln` file. Let us know if you run into more trouble and we'll have a better idea where to start looking.

**Comment by Jaggy99** [comment]
Did anyone find a fix as I'm experiencing the same issue.

**Comment by Nirvan-S** [comment]
Using PTVS. In the editor, Auto-complete variable names is functioning. Auto-complete member names (i.e pandas.Series) is also functioning. There doesn't seem to be an auto-complete member names for objects defined in the script (i.e mydata.Educa doesn't offer any suggestions for autocompleting to mydata.Education)
