### ISSUE TITLE
VS 15 encoding issues(console output isn't utf8)

### ISSUE THREAD

**Issue by robinhad** [Microsoft/PTVS#1419]
Python 3.5.2
I can't output some characters. 
Firstly, I save file to utf8
![1](https://cloud.githubusercontent.com/assets/5759207/16769334/f7ca7646-4850-11e6-95b8-3ba3297793f3.PNG)
Then write a program, which consists of single statement print("і")  
(it's not the same symbol as English "i")
![2](https://cloud.githubusercontent.com/assets/5759207/16769336/f7d1d80a-4850-11e6-8737-d0f5af8a52c5.PNG)
 When i try to output character "і"(it's like english "i", but not the same symbol), I get this error.
![3](https://cloud.githubusercontent.com/assets/5759207/16769335/f7cb314e-4850-11e6-830f-2c366d56a2d4.PNG)

**Comment by zooba** [comment]
Python needs support for outputting Unicode characters, which is actually the problem here (you'll get the same error if you run from the command line).

We _could_ set a default `PYTHONIOENCODING=utf-8` environment variable, which helps prevent the exception, but the output will not appear correct unless the code page of the console is changed to 65001 (`CP_UTF8`). But this is outside the scope of what PTVS can or should do. (I'd say go report it at https://bugs.python.org, but I know that it's already a well-known problem with a very difficult solution.)
