### ISSUE TITLE
Installing PTVS breaks debugging of Maya Plugin

### ISSUE THREAD

**Issue by ChipBurwell** [Microsoft/PTVS#1564]
Using VisualStudio 2015 community with update 1 and Maya 2017 I have written a Maya plugin. (a dynamic linked library) I have been able to debug my plugin with no problems setting breakpoints and receiving OutputDebugString messages when VS is attached to Maya and my plugin is loaded.  Today I downloaded and installed PTVS and found shortly after installing that I could no longer debug my plugin. I tried rebooting, rebuilding files, etc. but didn't fix the problem.  Finally, I uninstalled PTVS and that fixed the problem.  I have no idea why installing PTVS would break the ability of VS to debug a dll module but thought you might want to know. Possibly related to bug 844 but can't tell if their situation is similar enough to be the same.

**Comment by int19h** [comment]
What is likely happening is that PTVS detects that Maya is running Python code, and so when you're trying to attach to the Maya process, Python debugger kicks in (normally you'd get Native debugger). This is the expected behavior - in a similar way, if a process is running managed code, the Managed debugger is used by default.

However, it is possible to override this in the Attach dialog by using the "Select" button to select the code types that you want (probably will be just Native in this case).

**Comment by ChipBurwell** [comment]
@int19h - Yup you're correct it works if I select native code in the Attach dialog.  Thanks
