### ISSUE TITLE
Tests with decorators do not appear in the test explorer view

### ISSUE THREAD

**Issue by richgb** [Microsoft/PTVS#16]
This is the same as issue # 1969 on the CodePlex issue tracker. https://pytools.codeplex.com/workitem/1969

It has been marked as resolved there, but I still see the problem with the latest stable release 2.1 and the latest dev build April 13th.

If a Python unittest has a decorator, it does not appear in the test explorer. If the decorator is removed, it then appears.

``` python
    @patch.object(os.path, 'isfile')
    def test_A(self):
        ''' Doesn't appear in the test explorer '''
        self.fail("Not implemented")

    def test_B(self):
        ''' This does appear in the test explorer '''
        self.fail("Not implemented")
```

I'm using the mock library, so have hundreds of tests with patch decorators.

**Comment by richgb** [comment]
After some further investigation, I have discovered the following:
1. Some decorators do work. I tried the example on the original ticket on codeplex and that works fine.
2. It doesn't appear to like decorators that accept arguments. I added arguments to the previous and it no longer appeared in the test explorer.

**Comment by zooba** [comment]
Currently we reduce test discovery time by avoiding deep analysis of the code, which is what leads to us not fully understanding decorators. That said, since these are in the standard library, I doubt we're ever going to get them correct without manually specializing them inside our analyser.

That said, for `patch`, it should be a fairly easy specialization as we don't necessarily need to implement the full patching semantics - just the fact that the resulting function is the same as the original function.

**Comment by zooba** [comment]
This is back in the latest release, since we now use the live analysis (which attempts to handle decorators properly) instead of the separate analysis that ignored decorators entirely.

Not sure how to resolve it now - possibly we should assume that a decorator that doesn't return a function is not analyzed correctly and we should just keep the original function in the result.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/58736/python-decorated-test-methods-are-not-discovered.html
