### ISSUE TITLE
Running Python in Visual Studio Error : "Press any key to continue..."

### ISSUE THREAD

**Issue by vmeade** [Microsoft/PTVS#1670]
When I run (press F5) a Python Program from Visual Studio, I get the Python window that pops up stating

"Press any key to continue..."

When any key is indeed pressed it exits. 
I'm trying to print Hello, World.

What is wrong?

**Comment by huguesv** [comment]
If you're looking for the option that disables the "press any key to continue...", it's called "Wait for input when process exists normally" under Tools/Options/Python Tools/Debugging.  The console will still come up, but will go away as soon as it finishes executing your startup file.

If you'd like to execute the code in the interactive window, rather than an external console, there's Debug/Execute Project in Python Interactive.  That won't run it under the debugger though.
