### ISSUE TITLE
Debugger Stepping (IronPython2.7.5) does not work correctly with PVTS 2.2.5 and PVTS 2.2.4 in VS2015.

### ISSUE THREAD

**Issue by tsweeney2016** [Microsoft/PTVS#1691]
Debugger Stepping does not work correctly with PVTS 2.2.5 and PVTS 2.2.4 in VS2015. 
Stops at breakpoints correctly but step buttons don't step , just continue to next breakpoint or end of program. 
This issue does not occur with  PVTS 2.2  with VS2013 and also does not occur with Cpython in VS2015, nor with non PVTS language such as C#

Several IronPython users in my department has noticed the same once they transitioned to VS2015.
We tried clearing 'Just my code' in The Debugger settings , and while this restored stepping, led to other problems.

We feel that PVTS did not transition well to 2015.
Has anybody else seen the same issue. ?

**Comment by huguesv** [comment]
Thanks for the report. I will try this out tomorrow.

**Comment by huguesv** [comment]
I tried PTVS 2.2.4 and IronPython 2.7.5 and then IronPython 2.7.6.3.

I can confirm that I'm seeing this too.  Stepping sometimes jumps over sections of code.  Like you said, clearing "Just my code" makes it work better.

If you don't need to debug into C# code, you could also use the Standard Python launcher instead of IronPython (.NET) launcher.

**Comment by tsweeney2016** [comment]
Hi Hugo, 
thanks for looking at this and your comments.
Unfortunately clearing Just mu code leads to the debugger looking for .cs file even when stepping into your own code.
Also using the Python launcher does work but increases the Run Time of our iron python scripts which will make it unusable for the team. (we use scripts to drive complex R&D lab setups)
For the moment we can switch launchers when we need to step through the program, but this issue if not fixed might lead us to reverting back to VS2013 which is a step backward.
Can you please look into if this issue can be fixed.
Thank you for your help.

**Comment by tsweeney2016** [comment]
Hi Hugo,
 just realised that changing the Python launcher can be specific to (F5) debug mode, so won't affect our normal run time while not debugging ( CTRL+F5).
Please forgive my lack of understanding about launchers or what  what changing launcher actually does (ipy window still pops up, so what does it change). As a  result I am cautious that I might come across limitations of not using the Iron Python launcher.

Is this issue debugging while using the IronPython launcher something that can be addressed in future PVTS updates ?.

**Comment by huguesv** [comment]
IronPython will be used if you've set your project to use IronPython.  The choice of launcher (Python or IronPython) will only affect which debugger is attached.

With IronPython launcher, PTVS attaches the standard .NET debugger instead of our own Python debugger which is written in Python and works with any Python interpreter, including IronPython.

The Python debugger will give you a better Python debugging experience in general, even with IronPython, but the downside is that it won't let you debug non Python code (also it can be a bit slow, as you've noted).

This issue is likely due to a change in .NET debugger for VS 2015.  That doesn't mean the fix needs to come from them though, it may be a change that they intended and IronPython and/or PTVS needs to work around it.
