### ISSUE TITLE
Tests are not being discovered *solved*

### ISSUE THREAD

**Issue by maadborn** [Microsoft/PTVS#1693]
I was having problems with tests disappearing, some showing and some not showing, until I realized the test method name must start with the word "test", followed by an arbitrary string. Valid names of discovered tests are for example `test1`, `test_a` or `test_or_fail`, while `my_test` or `hidden_test` are not shown. I was expecting methods in classes inheriting from `unittest.TestCase` to be discovered as tests, whether or not their name began with "test".

I cannot find any reference in the wiki or anywhere else where this specific behavior is documented.

Is it a bug or intended feature?

**Comment by huguesv** [comment]
Hi!

Our test discovery matches the naming convention dictated by the unittest module (the only test module we support at this time).
https://docs.python.org/3.5/library/unittest.html

"A testcase is created by subclassing unittest.TestCase. The three individual tests are defined with methods whose names start with the letters test. This naming convention informs the test runner about which methods represent tests."

It's so that you get equivalent results whether you run inside Test Explorer or from command line.

Good point about it not being mentioned in the wiki, I'll update it right away.
