### ISSUE TITLE
Doc section start expands collapsed outlines

### ISSUE THREAD

**Issue by polakovicp** [microsoft/PTVS#1730]
Hello.
When I type start of document section ("""/''' after method/class) all collapsed outlines from current line to bottom expands.
Thanks for resolving this issue.
 I am using PTVS version 2.2.4, VS 2015

**Comment by zooba** [comment]
Thanks for reporting this!

At a guess, I think it's because starting the quotes flips the rest of the file (from code to string or string to code), and we get in quickly enough to change all the outlining as a result. I wonder if we can do something clever with parsing triple-quoted strings while they are still being typed?

As a sort of workaround, if you type all six quotes quickly enough then this probably won't happen. But it depends on how big your code is and how fast your computer is.

**Comment by polakovicp** [comment]
I just tried and the delay after typing """ can be like 2 seconds.
Maybe detect start of docstring - if it's on the first line or there is a method/class definition on preceding line then do nothing. Or would it be possible to remember collapsed outlines and apply them again when the docstring section get closed?

**Comment by zooba** [comment]
The problem with trying to remember things across edits is that we will inevitably get them wrong, and then you just end up with a different set of problems.

What I hope we could do is recognize that someone is partway through typing a triple-quoted literal and treat it like a single line one or force it to end at the end of the current function. The problem is, eventually someone will genuinely want to turn their entire file into a string (it's an easy way to comment out lots of code), and then *they'll* report a bug that triple-quoted strings don't work properly. Getting the balance right is the difficult part.

**Comment by polakovicp** [comment]
Satisfactory enough for me would be for example offering closing quotes through IntelliSense. But I understand there is no easy way out.

**Comment by zooba** [comment]
This is likely also a problem with any opening of a multiline grouping. We should look into some way to set a "temporary" (or "provisional") flag on a line of text that gains an unclosed grouping and assume that it is closed at the end of the line.
