### ISSUE TITLE
intellisense not working when starting new line

### ISSUE THREAD

**Issue by EdStone** [Microsoft/PTVS#1755]
Hi All:

When I begin a new line with something like "pri", a new intellisense box should open and show the entries that begin with "pri" (ex. including "print")).

This is not happening (the box does not open up).

The only way to get the box open is to hit Ctrl-Space.

Any way I can configure, adjust (or is it a bug / feature) so that I don't need to hit Ctrl-Spapce?

Thank you.
Edward

**Comment by zooba** [comment]
Right now this is disabled at the very start of the line, since our testing showed it was far more annoying than useful. In our next release (available with Visual Studio "15" Preview) we display the list but not automatically select or complete anything.

There's no way to enable this functionality on Visual Studio 2015, unfortunately. It's hard coded to never work.
