### ISSUE TITLE
Debugger confuses breakpoints in multi projects solution

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#176]
Create a solution with 2 bottle projects. 
 In the 1st project, set a breakpoint at the bottle.run line. 
 F5 on the 1st project, it should break correctly. 
 F5 on the 2nd project (which doesn't have any breakpoints) 

 Result: The debugger will break at the location of the breakpoint in the first project, even though it's the 2nd project that's being debugged. You'll wonder why execution has stopped when there is no breakpoint displayed in the margin! 

 Note: If you don't see this problem, try starting over and putting the breakpoint in the 2nd project instead (and see if the 1st project breaks incorrectly).

From: https://pytools.codeplex.com/workitem/2378
Verified it on VS 2015 RC with PTVS 2.2 30515

**Comment by int19h** [comment]
This is actually sort of by design. The debugger doesn't really know anything about projects, and you don't debug projects - you debug processes (that a process is spawned via "Start Debugging" on a particular project isn't actually tracked by VS). In particular, it's perfectly valid for the 2nd project to call code in the 1st project, for example, and we want to debug all that stuff. 

Now, the reason why this particular thing is happening is due to path mapping - if we can't match a filename in breakpoint (or other debugger artifact) exactly, we try to match just the tail of the path that corresponds to a Python package hierarchy, by walking the directory tree up so long as `__init__.py`is there. So if both projects have `foo.py` on the top level, then both will match `foo.py` in the debugged process...

This behavior is not unique to PTVS - C++ debugger does the same thing (in fact, IIRC, they match on filename alone, so it's even more frequent there). I'm not sure what we can do about it... I suppose we can change our debug engine such that it would try to access the currently loaded solution, and avoid fuzzy matching altogether if it gets an match of the path in debuggee to one of the files in the loaded projects. Not sure about the perf implications of this, though, it might be too expensive (fuzzy matching is done in visualstudio_py_debugger.py, so we'll need to marshal things back and forth, and breakpoint checks happen on every line).
