### ISSUE TITLE
No way of managing virtual environments without a project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1780]
With cookiecutter templates, we'll be relying more on opening folders in solution explorer.

Many of those templates will require installing packages, which users will often want to do in a virtual env.

Right now without a project, we lose the UI to:
- create new virtual env, add existing virtual env, delete virtual env
- install from requirements.txt

We need to find a way to expose that functionality when there's no project.

**Comment by zooba** [comment]
This can be done by adding support to our Workspace assembly:
* detect existing virtual environments when the folder has been opened
* add "Install" and "Update" commands on any `requirements.txt` file (or any .txt file in a Python context?)

I'm not sure we can replace the folder view of the env entirely, but that would be ideal. This whole thing kind of flow into the fact that Intellisense is pretty poor without a project, because we don't have a well defined set of files to analyze.

**Comment by crwilcox** [comment]
👍

**Comment by huguesv** [comment]
Add environment dialog is now available when no projects are opened and you can create virtual envs.
