### ISSUE TITLE
Use PIP to install from local directory instead of PyPI?

### ISSUE THREAD

**Issue by ejc1** [Microsoft/PTVS#1802]
I'm trying to use PIP within the VS IDE.  The particular package I want to install exists on PyPI, but I need an earlier version than that.  I can download the earlier version, but how can I point PIP at it instead of PyPI?

(In particular, I want version 0.0.5 of keras_vgg_buddy.  The version on PyPI is 0.1.1)

**Comment by zooba** [comment]
You can type the full version into any of the package name places (e.g. `keras_vgg_buddy==0.0.5`) and we'll install that version, or you can paste the full path.

It's not a well advertised secret, but when we run the install command we really just do `pip install <whatever you typed>`. Only search is actually done by us rather than pip.

**Comment by ejc1** [comment]
Thanks for the quick response.  It did find 0.0.5 on PyPI.  I didn't know PyPI kept older versions.  That all is excellent to know going forward.

However, the installation failed with a long list of errors, probably due to trying to mess with dependencies.  I already have (the versions I want of) all the dependencies installed, so it doesn't need to do that.  So I either need to tell PIP to ignore the dependencies, or install from a local directory where I've removed the dependencies in the setup file.  I think the former has a higher chance of working.  Is there a way to do that?

**Comment by ejc1** [comment]
Never mind.
keras_vgg_buddy==0.0.5 --no-deps
succeeded.
