### ISSUE TITLE
Tutorial for PTVS (django+sql server)

### ISSUE THREAD

**Issue by LeeRuns** [Microsoft/PTVS#1844]
I spent a fair amount of time looking around for a way to get a connection going between Django and Sql server.  Microsoft did a tutorial but it assumes that your running Azure.  I'd like to see one without azure.  Also if possible could the MS staff get the python package used in the tutorial to include the most recent version of django? 

[(Django MSSQL)](https://django-mssql.readthedocs.io/en/latest/)
_the problem with this package is that it stops at django 1.7_

[this tutorial uses azure and python 2.7](https://azure.microsoft.com/en-us/documentation/articles/web-sites-python-ptvs-django-sql/)   

I cannot find a tutorial anywhere online that uses 

- python 3.4 or 3.5  
- -sql server  
- -Both: windows authentication for sql server and django sign in authentication  
- -sql server 2014  

If there is something out there and I missed it then great! :+1: 

Could you also help explain how to find some of the fields for the ODBC connection in the same tutorial?

**Comment by zooba** [comment]
I don't have any great answers for you right now - some of our documentation has fallen behind the ecosystem, and there's certainly a need for more tutorials here.

@eclectir or @huguesv may be more helpful, or at least be able to poke some people closer to the SQL team to think about this case.

**Comment by huguesv** [comment]
djang-pyodbc-azure claims support for Python 3.5 and Django 1.10:
https://github.com/michiya/django-pyodbc-azure/blob/azure-1.10/setup.py

but it fails to install, either from PyPI or from GitHub, on my Windows machine :(

SQL team has some Django samples here: https://github.com/Azure/azure-sql-database-samples/tree/master/django

@meet-Bhagdev do you additional samples or info for @LeeRuns ?

**Comment by meet-bhagdev** [comment]
Sure! Here is a sample app that I wrote: https://github.com/Microsoft/sql-server-samples/tree/master/samples/development-frameworks/django 
If you have questions on how to make this app work let me know 👍 

Adding @michiya for questions about django-pyodbc-azure on Django 10 and Python 3.5

**Comment by tanzeel-bhatti** [comment]
@meet-bhagdev Is there a way to connect to MSSQL using from Django using windows authentication.
P.S: I am trying to connect to MSSQL from a docker container.

**Comment by meet-bhagdev** [comment]
@David-Engel may be more helpful here

**Comment by David-Engel** [comment]
@tanzeel-bhatti Windows authentication from a Windows or Linux Docker container? Either one means that you would need to be using Windows integrated authentication because the Microsoft ODBC Driver for SQL Server does not support an option to send a Windows username/password combination via the connection string.

For a Windows container (note, you may encounter encoding issues in Windows 2019 containers, which default to UTF-8), since you can't join a container to a domain, you'd have to set up something like this:
https://success.docker.com/article/modernizing-traditional-dot-net-applications#integratedwindowsauthentication
Even then, I don't know if it will work.

If you are running a Linux container, similar issue. Right now, I don't think there is a way to join a Linux container to a domain but I'm not on the bleeding edge of containers. I know they have been working on ways to get Kerberos authentication working in a container environment, but I don't know if it's there yet. Once the underlying dependency is there, you should be able to apply the existing documentation to your container environment for integrated authentication:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication

**Comment by tanzeel-bhatti** [comment]
@David-Engel I am using the python:3.7 based image which is based on a ubuntu(debian) distribution.  My SQLServer does not accept connection from username/password but instead it only allows Windows Authentication. 
I have my Djagno DB config something like this below
`DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'ProdDB',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'MYMSSQL.com', # Or an IP Address that your DB is hosted on
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}`

I have followed [this](https://github.com/ESSolutions/django-mssql-backend)  and [this](https://github.com/inunekousapon/sqlserver-django). I am not sure how these guys were able to connect to the DB.

**Comment by David-Engel** [comment]
@tanzeel-bhatti In those links, it doesn't sound like they are running the client in a container. Their clients are probably normal, domain-joined clients. For your service in a Linux container, you ultimately want to generate a keytab file. There are numerous articles written on the subject but you basically want to follow one like this:
https://www.codeproject.com/Articles/1272546/Authenticate-NET-Core-Client-of-SQL-Server-with-In
You might need to read up on Kerberos to understand what's going on, too:
https://help.ubuntu.com/lts/serverguide/kerberos.html
After that, the MS ODBC driver documentation might make more sense:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-2017#deploying-a-linux-or-macos-odbc-driver-application-designed-to-run-as-a-service
