### ISSUE TITLE
Remote execution & debugging of Python scripts

### ISSUE THREAD

**Issue by justas-** [Microsoft/PTVS#1975]
This is more of a feature request, but would it be possible to have remote execution and debugging of Python scripts using VS, as it is possible to do with C++? This would help _a lot_ for users who are using Windows boxes due to the corp policy of Windows desktops, but at the same time has to develop code that runs on Azure/AWS/etc. Linux box.

**Comment by zooba** [comment]
We have about half of this already in [remote debugging](https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging). The bit that we're currently missing making it "single click" (as described by #1237) - essentially, that would make it so that hitting F5 would upload your code, start it running and attach the debugger. Right now, these are all possible, but are not linked together.

We have #1237 to track this already, so I'll close this as a duplicate. We really want to implement this and just have not had the time yet, so it'll show up eventually.
