### ISSUE TITLE
Problem with Visibility of labels/links in cookiecutter options page

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1979]
Probably a regression of switching to data triggers for visibility of labels and links.

![image](https://cloud.githubusercontent.com/assets/1696845/21195062/fc979680-c1e6-11e6-81ae-d3b50dadfbee.png)

To repro, load the template from `Python\Tests\TestData\Cookiecutter\templateforvs`

**Comment by zooba** [comment]
I think it's because the data triggers are set to do "Mode=OneTime", and the values they are bound to apparently change after the view is initialized.

Changing them to "Mode=OneWay" should resolve the issue, though ideally we'd fully construct the model as much as possible before creating the view.
