### ISSUE TITLE
Can debug interactive windows run with IPython mode?

### ISSUE THREAD

**Issue by you4ever** [Microsoft/PTVS#1987]
Wonder how to run interactive debugging also in IPython mode. So that I can plot intermediate variables as I debug my code. Now, when i try the following in debug mode:
```
import matplotlib.pyplot as plt
plt.plot(...)
plt.show()
```
I'm getting error message:

> Traceback (most recent call last):
>   File "<debug input>", line 1, in <module>
>   File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 252, in show
>     return _show(*args, **kw)
>   File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 192, in __call__
>     self.mainloop()
>   File "C:\Program Files\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 149, in mainloop
>     signal.signal(signal.SIGINT, signal.SIG_DFL)
>   File "C:\Program Files\Anaconda3\lib\signal.py", line 47, in signal
>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
> ValueError: signal only works in main thread

Please let know if I'm doing anything in the wrong way. Thanks!

**Comment by zooba** [comment]
This is not supported and as far as I'm aware, there's no way to make it work reliably. IPython mode changes so much state in the running Python process that it would break debugging.

We have future plans to add better visualizations for data and plots, which are very likely to be part of our next major update. Track #81, #747 and #748 for updates (and also see what's already available in [RTVS](https://github.com/Microsoft/RTVS), since we'll likely borrow some of their components for it).
