### ISSUE TITLE
numpy, pandas, scipy in IronPython, PTVS 2.2.40825.00

### ISSUE THREAD

**Issue by aqpavel** [Microsoft/PTVS#1993]
Hello, 

Recently I have read in the news that numpy has been ported to .NET. I am trying to install numpy, pandas, scipy packages into IronPython environment, but I am getting different errors which usually don't make sense. 

My environment: 
VS 2015 Enterprise Update 3
PTVS 2.2.40825.00
IronPython 2.7.5
Anaconda Python 3 (both 32/64 bits, Python 3.5)

Everything works fine with existing Anaconda setup. 

IronPython: I was able to install pip in IronPython. But when I try to add "numpy" using Install  Python Package... menu I get the following runtime error: 

> Installing 'numpy'
> Unhandled exception:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 170, in run_module
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 101, in _get_module_details
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 456, in get_loader
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 466, in find_loader
> ...
>   packages\pip\_vendor\requests\packages\urllib3\packages\six.py", line 320, in exec_
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 109, in _get_module_details
> AttributeError: 'module' object has no attribute '_getframe' 

Tried to add -X:Frames/FullFrames to Interpreter Arguments and Interactive Window Options - no effect. Tried many other things found on SO and similar sites - no effect.

Is this configuration (IronPython + pandas+numpy) should work and is officially supported, or I am just wasting my time? What are the clear steps to get it working? Is there any prebuilt and tested (anaconda style) package bundle for IronPython and PTVS available for download?

Really appreciate your help.

Best regards,
Pavel

**Comment by zooba** [comment]
That was fairly old news. The original attempts to port numpy/scipy were many years ago and they have been abandoned due to difficulty getting it to actually work. There are no clear steps to get it working. If you can, switch to CPython instead, or consider Python.NET if you need interop with .NET assemblies.

The problems with `pip` are due to [this issue in `six`](https://bitbucket.org/gutworth/six/issues/135/have-a-fallback-for-sys_getframe-usage-in), and we have already added a workaround in VS 2017 that should avoid the problem when using IronPython.
