### ISSUE TITLE
No completions on packages

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2034]
New python console project
Add new item, Python package
Add a constant in its `__init__.py`, such as HELLO = 'hello'
Back in the application1.py:
```
import package1
package1.
```
You'll get no completions.

Same thing happens to my stdlib packages.

Tested on 17006.2 and 17006.3.

**Comment by zooba** [comment]
Does it come back eventually? Or if you close/reopen the files?

We may not be attaching the analyzer correctly, or it could be taking a long time to complete its first run. Would be interesting to attach the debugger to the analyzer executable and see if it is deadlocked - especially since we've seen a couple of those recently.

**Comment by huguesv** [comment]
After closing and reopening the solution, I'm getting completions on package1.  I'm still not getting any completions on stdlib though.
![image](https://cloud.githubusercontent.com/assets/1696845/21737884/45fb157e-d432-11e6-8b78-192053ef99a2.png)

**Comment by zooba** [comment]
You also don't have a working analyzer, or you'd get coloured names (we colour all "import"ed names, whether they are resolved or not). There's something else going on here.

**Comment by zooba** [comment]
This is a race condition between project load and document load, which occurs when VS opens the document window during project load.
