### ISSUE TITLE
VS 2015 Community hangs after editing Flask Empty Web Project

### ISSUE THREAD

**Issue by srinivas-narayan** [Microsoft/PTVS#2037]
Please, could somebody help. I have installed VS 2015 Community, Update 3 with PTVS version 2.2.40825. The 'Blank Flask Web Project' builds and runs fine the first time, but then stops working when I try to rerun it. Task manager fails to terminate it even with Admin access.

**Comment by zooba** [comment]
This is not a problem we've seen before. In order to diagnose it, we'll need you collect and send us a process dump. There are instructions [here](https://support.microsoft.com/en-us/kb/931673) on collecting the dump, and you'll need to upload it somewhere for us to download it from (the file should be a few hundred MB). You can email download instructions to ptvshelp@microsoft.com.

Note that the dump may include personal information, such as files you have open at the time when you take the dump. We won't share any of it, but I just want you to be aware that it's part of the collection.

Without this information, we can't get any further. It is very rare for Visual Studio to hang so badly that Task Manager cannot close it.
