### ISSUE TITLE
Python Debug Interactive window does not interact with Call stack window to update frame location.

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#2096]
Hi,

In the Python Debug Interactive window, one cannot examine a local variable of a method higher up the call stack, _after one has navigated up via the call stack window_. One can only examine variables of the lowest method (the one with the break point). 

```
>>> print x
Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
NameError: name 'x' is not defined
>>>
```

This isn't a problem in the Immediate window, _nor the watch windows_.

Regards,

[Edits 30Jan17 in italics.]

**Comment by huguesv** [comment]
Hi HHest,

This is by design, it matches the behavior of the debugger watch windows.

You can use the `$up` (or `$u`), `$down` (or `$d`) as well as `$frame` and `$where` (`$w` or `$bt`) in order to move up or down the stack, display or change the selected frame, and see the list of all frames.

Once you're in the correct frame, you'll be able to inspect its variables.

https://github.com/microsoft/ptvs/wiki/Debugging#the-debug-interactive-window

**Comment by HHest** [comment]
Thanks for the explanation! At first blush this seems like a cumbersome feature (compared to navigating with the call stack window)... Maybe I am just not used to it. :) Will close this issue.

**Comment by HHest** [comment]
Actually, I think this does not exactly replicate the behavior of the debugger watch windows. If I navigate with the call stack, the watched variables updates properly.

![f](https://cloud.githubusercontent.com/assets/3169669/22332996/0e1660bc-e3d4-11e6-874a-a005c2afedc7.PNG)

![g](https://cloud.githubusercontent.com/assets/3169669/22333006/15c9801e-e3d4-11e6-8bb7-9045b6cea9a5.PNG)

**Comment by int19h** [comment]
The Watch window simply shows the last value the variable had when it could be evaluated (hence why it's grayed out). But if you have never opened a stack frame in which it's valid before  - even if one is on the stack - it will show that variable as error.

The Interactive window behaves like Python normally does, and Python is lexically scoped, not dynamically scoped. In your Python code, you can't `print y1` inside `f`, even though it's invoked by `g`, because `f` is not lexically scoped inside `g`. Same rules apply to Python code evaluated in the Interactive - that code behaves exactly as if it were inserted into `f`.

**Comment by HHest** [comment]
Thanks, int19h. Now that I understand the PDI window better, I guess I am making a "usability" suggestion: it feels more natural if the interactive window could be linked to the call stack navigation, so that the frame changes automatically as one clicks up and down the call stack. 

As I mentioned, the Immediate window behaves this way. And the watch windows, in knowing which variables to gray out, show that they know about call stack navigation as well.

1. Start in frame 0. As expected none of the windows knows about y1.

![f 2](https://cloud.githubusercontent.com/assets/3169669/22366511/6641cbd8-e47d-11e6-9586-fd3b6a53ef87.PNG)

2. Switched Call Stack window to frame 1. Intermediate and watch know about y1, as their frames are automatically changed to frame 1 as well. PDI still reports it is in frame 0, and thus, it remains ignorant about y1.

![g2](https://cloud.githubusercontent.com/assets/3169669/22366517/6a7592ac-e47d-11e6-927a-ad19787a6dda.PNG)

**Comment by HHest** [comment]
I have updated the subject of this thread and the 1st comment to clarify the issue.

**Comment by huguesv** [comment]
Thanks, we already have that improvement filed in https://github.com/Microsoft/PTVS/issues/986, so I'll close as a duplicate.
