### ISSUE TITLE
Running script in embedded Python Engine

### ISSUE THREAD

**Issue by hrdelsing** [Microsoft/PTVS#2100]
I have an application that embeds a Python Engine to support executing test scripts.

The Python Tools for Visual Studio works great.  I am able to attach with the debugger to the application and step through python scripts.

I was wondering if there was a way to further integrate the running of scripts from Visual Studio.  In order to set breakpoints in a script, I have to attach to my application with the debugger.  But once I've attached, then I can no longer have VS run a script.  The script must be launched from my application.

I've been tasked with figuring out if there's a way to better integrate this process.  The user already has the script they want to run open in VS.  Is there any way to have PTVS tell my application to run a specific script?

If this isn't the correct place for this post, please point me in the right direction.

Thanks.

**Comment by zooba** [comment]
This is exactly the right place, and apologies for not seeing this post earlier.

What you will likely want to do is create a debug launcher. These are provided by VS extensions and allow you to offer an item in the dropdown list of a Python project's Debug page (where you'll see "Standard Python debugging", "IronPython debugging", etc.). By implementing a few interfaces, you can totally handle how we launch debugging - if you want it to send a message to your application instead of starting a new process, then you can make it do that.

Does this sound like something you'd want to do? I can provide more technical information if it is.

**Comment by hrdelsing** [comment]
That sounds like exactly what I would like to do.  I would greatly
appreciate any information that you could provide.

Thanks,
Heather

**Comment by zooba** [comment]
Okay, here are some starting points:

[DjangoLauncherProvider](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Django/Debugger/DjangoLauncherProvider.cs) class is the MEF export that will be discovered. It doesn't do so much anymore, because we merged its implementation with [PythonWebLauncher](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/WebProject/PythonWebLauncher.cs) - really, you just need to implement [IProjectLauncher2](https://github.com/Microsoft/PTVS/blob/master/Common/Product/SharedProject/IProjectLauncher.cs) which will be available by referencing Microsoft.PythonTools.dll from your own C# project.

We use our [DebugLaunchHelper](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Debugger/DebugLaunchHelper.cs) class for doing most of the launch work. I'd suggest you look at (or use) its `CreateDebugTargetInfo` function to get most of the way, and then you can modify the [VsDebugTargetInfo](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.vsdebugtargetinfo.aspx) structure it returns to do whatever you need (for example, you'll likely want to make it attach to a running process by changing `dlo` to [DLO_AlreadyRunning](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.debug_launch_operation.aspx) and `bstrExe` to `string.Format("\0{0:X}", processId)`).

I hope that helps you get started. The [Visual Studio SDK documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/visual-studio-sdk) will help cover how to build/install/distribute the extension you'll need to create, and we should be able to point you toward other documentation as questions come up.
