### ISSUE TITLE
Consider moving to Roslyn infrastructure

### ISSUE THREAD

**Issue by JoshVarty** [microsoft/PTVS#2141]
Is there any interest in moving PTVS to Roslyn infrastucture (Workspace, Project, Document etc.)?

The same has been done for F# and TypeScript and it seems to have made it easier to support a wider range of features many users expect in Visual Studio. 

Are there any issues that might make this prohibitively difficult or impossible?

**Comment by crwilcox** [comment]
Can you provide more details on what you are looking to change? Do you have particular documentation for this and an idea of the scale of this work? From the original prompt I am not sure of what this is all involving.

**Comment by JoshVarty** [comment]
My understanding is that we can take advantage of common infrastructure provided by Roslyn that will make it easier to support a broader range of language service features. I've been using PTVS daily for a few months now and there are some features from other languages that I miss. eg. (More complete QuickInfo, [HighlightTag](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/Preview/Tagging/HighlightTag.cs), etc.)

When F# moved to a Roslyn-based project infrastructure, non-Microsoft contributors found it easier to implement language service features. 

The scale of the work is large. I would be willing to begin working on this in my spare time in a feature branch. 

The initial commit that kicked off this work for F# can be found [here](https://github.com/Microsoft/visualfsharp/commit/3a36f79dc150ffa61a037a67f877b593d4a5265c).

If we move to Roslyn infrastructure I think we'll have a much easier time reaching and maintaining feature parity with other language services. The APIs Roslyn provides are typically much easier to work with than the Visual Studio APIs themselves.

**Comment by JoshVarty** [comment]
@OmarTawfik @KevinRansom Maybe you guys can comment on why F# moved to Roslyn infrastructure and any benefits you've seen by doing so.

**Comment by int19h** [comment]
Can you clarify what you mean by "Roslyn infrastructure"? Is this about the project system, basically?

If yes, does it support file-based projects?

**Comment by OmarTawfik** [comment]
@JoshVarty Basically, this is a rough road map of the major things needed to be done:

1) Roslyn needs to add PTVS to its IVT list (so that you can reference Roslyn APIs).
2) You start creating a Roslyn workspace and attaching your files/documents to it at solution/project load time.
3) Different services that you implement are MEF exported so that Roslyn picks them up and displays them in IDE.

Integrating with Roslyn was quite fast/straight forward. Most of my time was spent dealing with MEF magic and trying to debug why something isn't loaded correctly in VS.

See the discussion on https://github.com/Microsoft/visualfsharp/issues/913 for more info

Note that this has nothing to do with the project system. F# project system is still legacy VS code. This has some drawbacks like not being able to use language services (like find all references) cross-projects in the same solution. Work spaces are not tied to the project system. BUT it has been critical in getting more contributes to work on the language services, and we've seen amazing progress there.

/cc @Pilchie @CyrusNajmabadi @jasonmalinowski from Roslyn IDE team can provide info as well
/cc @KevinRansom @brettfo folks working currently on F#

**Comment by CyrusNajmabadi** [comment]
This is a fairly large undertaking, but the general value here is in being able to share tons of code, and to deliver features more quickly and with more consistency across the VS languages.

For example, if you were a roslyn language, all you would need to implement outlining/structure-guides would be this API:

https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Structure/BlockStructureService.cs

This is a very simple query + data API.  We do the work of managing threading and backing off.  And we call into you (in cancellable manner).  All you need to do is provide BlockSpans (i.e. data) and we take care of the rest.  i.e. diff those results with the previous spans, and let the editor know about only what has changed.  We also take care of the UI, making it so that collapsed outlining spans are properly classified:

![image](https://cloud.githubusercontent.com/assets/4564579/22849867/4efe4016-efb6-11e6-8875-a28728918b4f.png)

The idea here is that Roslyn handles the orchestration, and the individual language only needs to work on supplying the data.  

Roslyn provides the orchestration for several dozen features, vastly reducing the burden on every language to do that itself.

**Comment by CyrusNajmabadi** [comment]
A similar feature that you would get very cheaply would be the new FindReferences window.  Roslyn has implemented support for this window with lots of cool facilities (including streaming results, highlighted text, and previews):

![image](https://cloud.githubusercontent.com/assets/4564579/22849918/f2c64a40-efb6-11e6-8240-08fe8b78381d.png)

To get support for that new window (with all of that difficult stuff taken care of for you), you'd just need to implement:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/FindUsages/IFindUsagesService.cs

This API gives you a IFindUsagesContext which allows you to push results into the window as your language service finds them:

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/FindUsages/IFindUsagesContext.cs

**Comment by CyrusNajmabadi** [comment]
Now, moving onto Roslyn is not an easy undertaking.  Our infrastructure makes certain assumptions about how a Language Service is implemented.  For example, that it avoids the UI thread like the plague.  That it can generally operate in a very fine-grained, cancellable manner.  That certain types of operations are 'cheap'.  

Impedance mismatches here caused much pain for F# when they tried to move over.  

--

Also, while the Roslyn user-feature-set APIs are relatively simple and reasonably mature, the APIs around the project system are incredibly baroque and harder to deal with.  That's because they're written to interface with all the old IVSHierarchy views of the world, and the ancient csproj/vbproj project systems.  

TS had a reasonable time integrating in here.  but that's mostly because it was very young and didn't need much work to change things.  F# had a harder time being much more established.  And the same will likely be true for PTVS.

--

If PTVS wants to do this, it should be because they see enough value in the wide feature-set that Roslyn provides and simplifies.  And it should be done with deep discussions between the teams about so both sides understand how the other works and good planning can be made around what work would be necessary.

Moving to Roslyn is not simple or cheap.  But it can be very valuable once the initial investments are made.

**Comment by int19h** [comment]
There's also RTVS, where I assume the same costs and benefits would apply. @jflam, @MikhailArkhipov, take a look.

**Comment by zooba** [comment]
Thanks for the info on this. We'll consider it, of course, but since what we currently have works well there isn't a huge motivation to migrate. We've also been burned many times in the past by taking dependencies on Roslyn (we're currently shipping a fork of the interactive window because of this, rather than depending on the "built-in" one), so I'd like to see the API proven stable before we commit to it.

So please do keep us in the loop as development continues, and we're happy to look at API proposals to see how well they suit Python (and R), but I don't think we'll be prioritizing any wholesale migration.

**Comment by DustinCampbell** [comment]
Plus @Pilchie and @CyrusNajmabadi as well.

**Comment by jflam** [comment]
@DustinCampbell, @CyrusNajmabadi wrote a book already in these comments :)

**Comment by DustinCampbell** [comment]
yes, but all of that is just a technical discussion and you're looking for something more.

We've not documented this because, well, it really *isn't* recommended (regardless of @JoshVarty's suggestion). There are a lot of caveats with doing this, such as needing IVT to Roslyn because the APIs TypeScript and F# are using are not public. It's true that they get a ton of mileage out of it, but it's not without problems.

The biggest issue we've had is implicitly breaking other teams when new Roslyn bits are inserted into VS due to the fact that Roslyn's internal APIs do churn. The number of times TypeScript has been broken in VS due to a Roslyn insertion is not small. We are very nervous about providing IVT to other languages, and we only did it for F# because, well, they're on our team. :smile:

Caveats aside, TypeScript and F# have gotten a lot of mileage in being built using Roslyn as a basis for their VS language service. However, the reality is that the language neutral facilities that these languages are using from Roslyn should be pushed down into the VS platform so that *everyone* can use them.

Anyway, if you want to talk seriously about doing this beyond just the engineering water cooler, it's a larger conversation with our management. However, note that there is definitely some aversion to doing this because of past (and current) problems.

**Comment by jflam** [comment]
Thanks for the caveats, particularly the ones around breaking changes around APIs. One of the things that would be very helpful is to adopt a discipline around breaking changes more akin to how Windows deals with them i.e., silently break them at your own peril as you will be yelled at by dev directors across the org. The breaking change notification alias is scrutinized heavily by the entire division because failure to read them means that your being broken is now *your* fault :) 

That said, my suggestion fell mostly upon deaf ears once upon a time.

I do have a chat scheduled with @Pilchie next week. I can bring this up among other things with him then.

Any additional comments about VSCode + VS code sharing? Thanks!

**Comment by DustinCampbell** [comment]
> Any additional comments about VSCode + VS code sharing? Thanks!

Building on Roslyn infrastructure would get you benefits in VS, but it's nothing special for VS Code. The Roslyn API layers that we're talking about here aren't portable and take dependencies on the VS editor.

**Comment by jflam** [comment]
Got it. Thanks!

**Comment by DustinCampbell** [comment]
And if you want to turn that chat with @Pilchie into breakfast over in cafe 16, let me know. :smile:

**Comment by JoshVarty** [comment]
I think I was a little too over-eager here.

I hadn't fully considered the implications of taking a dependency on Roslyn including the fact that we'd be another customer taking a dependency on their internals.

It also sounds like there isn't a huge motivation from PTVS to move either so it probably won't be worth the work right now. There might be a point in the future where we wouldn't need to take an IVT dependency on Roslyn (or the infrastructure was migrated to the VS Platform itself) and it might be worth reconsidering then.

**Comment by zooba** [comment]
Maybe not over-eager - I'm glad the connection has been made - but we have very high priority items right now that are not helped by this change. We will consider this for our next major feature release, but with 100% of our resources committed to very time-sensitive work it's just not possible right away.
