### ISSUE TITLE
PTVSD not listening to port

### ISSUE THREAD

**Issue by ppbrasil** [Microsoft/PTVS#2170]
Sorry if it's a stupid question, I'm new to programming and it's my first time using PTVS.

I've have a Django project running in a local container (Docker) and I'm trying to attach VS debugger to it.

So I:
- Firstly added `ptvsd.enable_attach("secret", address = ('0.0.0.0', 3000))` into setting file.
- Secondly exposed and binded the container's port.
- Thirdly ran the application.

So far so good, app is running and I can access it over the port 8000 (via browser)

But, since I'm getting an error while trying to attach VS2015 debugger to the process.I decided to check if there was any process actually listening to that port. So I ran `lsof -i :3000` in the running container and got no return from it (`lsof -i :8000` returned `python  185 root    6u  IPv4  42821      0t0  TCP *:8000 (LISTEN)`)

Any guesses?

**Comment by huguesv** [comment]
What error are you getting from the attach dialog?

I tried the using the same `enable_attach` values as you (my_secret instead of secret, which souldn't make any difference), for the guess a number example we have here:
https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging

I'm not using docker container, it's just all on the same Windows machine.  I'm also using the latest build of PTVS from master. It's possible you are running into a bug specific to your setup.

Anyway, in our example, if I enter `tcp://my_secret@0.0.0.0:3000` in the connection target, then I get "could not connect, operation not supported."

If I enter `tcp://my_secret@localhost:3000`, then it connects fine.

**Comment by ppbrasil** [comment]
Thanks @huguesv. Problem solved!
I was making a wrong logic while checking if Django was already listening to the port.
[Solution here](https://github.com/Microsoft/PTVS/issues/1057)
