### ISSUE TITLE
Refresh DB is slow / not working

### ISSUE THREAD

**Issue by blitzd** [Microsoft/PTVS#22]
Carrying on from this issue on codeplex:

https://pytools.codeplex.com/workitem/3017

I had a wealth of information to provide to back up what I was saying, unfortunately codeplex decided to take all comments and discussions offline right around that time, and I never got around to posting them when it came back online (if it is back online).

The gist of what I was getting at with regards to the issue was that it was taking upwards of 30 minutes for the code completion database to finish on a system that is capable of 2000MB/s data transfers, with 12 cores (24 with hyperthreading) and 64GB of RAM to analyze the data with (hint: it's the same time even on a slow system, it seems). The end result was that it mostly provided the same method signatures and auto-completion as PyCharm was able to glean in 2-3 minutes of analysis, except that often times the PTVS data was truncated in the display (and PyCharm was not). 

Meanwhile, in an IPython session I am able to get more complete method signatures (many of which neither PTVS or PyCharm appear to pick up), and help easily available through either the console or a notebook - so the data is certainly there, it's just not being analyzed, and what is being analyzed is taking too long (especially when regular virtualenv creation is taken into consideration) and being underutilized (truncated).

**Comment by zooba** [comment]
The data is there in an IPython session because Python makes it available at runtime. Both PTVS and PyCharm avoid running arbitrary code just to figure out what values something might be, since we have no idea what that code does (e.g. a malicious package might rewrite your user configuration on import - IPython will execute that code when you import it, but PTVS and PyCharm will not).

Thanks for the further information. I'm certainly keen to always look at improving this, though conflicting priorities often mean I don't get the opportunities (but more complaints helps this jump up the ladder :) ). There are some architectural limitations in our current code that prevent us from making full use of multiple CPUs and large amounts of RAM, which I'm keen to remove, though we get more complaints about the amount of CPU/RAM we already use, so unleashing that may not be a good default position.

We're also looking at ways to avoid the truncation issues, which are largely due to Visual Studio limitations. For Python code, you can typically hit F12 to be taken directly to the definition, which seems to be a reasonable workaround for most people (myself included - I do that all the time).

**Comment by zooba** [comment]
Closing this because it's a known general issue (with multiple open bugs) and keeping this one open is not any more helpful.
