### ISSUE TITLE
REPL and debugging improvements for productivity and interactive development

### ISSUE THREAD

**Issue by nidleo** [Microsoft/PTVS#220]
The following suggestions would substantially enhance the development speed, especially for scientific computing.

1. When selecting code in the editor and right clicking: "Send to Debug Interactive" option is missing. only "Send to Interactive" exists. Having such an option (+ keyboard shortcut) would allow throwing chunks of code into evaluation much faster.

The next two bullets I suggest are useful for the common scenario where one wishes to put aside in memory some variables that take a while to prepare (long calculation, or loading from large file) and use them for debugging a new function that is being written and receives these variables as input.
One could then prepare the variables once, place a breakpoint in the half written function, inspect local variables and continue adding code. The process repeats until the function is completed.
This is supported in Matlab for example.

2. Allowing global variables that don't disappear between debugging sessions.

3. Calling a function from REPL should stop on breakpoints within that function. (currently, the breakpoints are skipped)

**Comment by int19h** [comment]
Regarding #2, note that you can attach the debugger to the REPL by using `$attach`. Then, you'll be able to set breakpoints in functions and hit them (though that only works for functions that are defined in .py files, not for those that you define on the fly in the REPL itself).

**Comment by nidleo** [comment]
Thanks! this is really helpful, but I'm experiencing some strange behavior.

When I change and save my .py file, say by adding lines, the debugger seems to be working with the older version and ignores the new lines.
This happens even if I detach, apply "del" on the module, and attach again.

**Comment by zooba** [comment]
Yeah, Python isn't really well set up for doing that kind of work. We plan to add some functionality to make it better for that, but it's implemented fundamentally differently from something like Matlab and there's only so much we can do to make it behave differently.

You really need to stop debugging to make changes and then restart the debugger. There are other tricks (like the `reload` function), but the reason these aren't recommended is because they don't work well in many scenarios, such as debugging, so they won't actually be that helpful.

It takes a bit of a mental model change, but the best way to work with Python code is to have an interactive scratch pad for quickly trying things out, but be building up a re-runnable script alongside. That way you can "Send to Interactive" on the initialize/load code, then send individual functions to define and then test them, and work in chunks small enough that you don't really need a full debugger. Then when you have the whole script together, the debugger is *a different way* to do the equivalent of sending each piece into the interactive separately - in some cases the debugger is better, in some you want to be sending sections of the script into the interactive, but right now it's hard to mix-and-match the two approaches effectively.

The end result should be that you have a script that you can run later to do the same analysis on the same or different data, or something you can share along with the results you produced so that others can see how you came to those conclusions.

**Comment by nidleo** [comment]
Thanks for the methodology suggestion, it really helps to get pointers in the right direction. I will try to adapt.

I would still add the "Send to Debug Interactive" option though.

**Comment by zooba** [comment]
I'm closing this because we now have #751 to track planning and progress. I'll copy some of the contents into that post.
