### ISSUE TITLE
Remote debugging: error connecting via Kubernetes port forwarding with a secret

### ISSUE THREAD

**Issue by itowlson** [Microsoft/PTVS#2246]
I have a Python Web server with the following statement:

`ptvsd.enable_attach(None, address=('0.0.0.0', 3000))`

I deploy the Web server to a Kubernetes cluster, and set up port forwarding for port 3000:

`kubectl port-forward pythonmeup-805807444-x9hx2 3000:3000`

I can then attach to the remote process via `localhost:3000`, in my case from Visual Studio Code, and it all works great.

Now I change the `enable_attach` to include a secret (and redeploy to Kubernetes):

`ptvsd.enable_attach("my_big_secret", address=('0.0.0.0', 3000))`

and add that secret to my VS Code configuration (`"secret": "my_big_secret"`), I can no longer attach to the remote process via the forwarded port - when I try, the port forwarder reports this error and the debug adapter process terminates:

```
C:\Users\itowlson>kubectl port-forward pythonmeup-805807444-7kr31 3000:3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Handling connection for 3000
E0308 16:37:32.196247   21836 portforward.go:314] error copying from local connection
to remote stream: read tcp4 127.0.0.1:3000->127.0.0.1:64876: wsarecv: An existing
connection was forcibly closed by the remote host.
```

I realise this may be a Kubernetes issue, but it seems like Kubernetes is just tunnelling the ports, and it works when there is no secret.  What part of the attach protocol might be breaking due to the presence of a secret?  Is there anything I need to set up in the server environment or the port forwarding options to allow the use of a secret?

**Comment by zooba** [comment]
There shouldn't be. Though if you're using VS Code then you may need to ask on [their issue tracker](https://github.com/donjayamanne/pythonVSCode/issues/) rather than ours - while we are responsible for `ptvsd`, we don't currently test against VS Code, and their configuration may do something different.

Alternatively, if you test using Visual Studio 2017 and it's still a problem, we can try looking into it. But the secret is just passed through as data (insecurely, I might add, but probably good enough for most uses), so there shouldn't be anything special.

**Comment by itowlson** [comment]
@zooba Thanks Steve. I can confirm that it works fine in Visual Studio 2015 (haven't tried with 2017 but sure it won't be any different).  So this is definitely something to do with the way either I have configured VS Code, or the way VS Code (or the Python extension for it) attaches the Python debugger to the remote process.  I'll investigate further and update the issue if I find a resolution.
