### ISSUE TITLE
separate installation integration problem

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/PTVS#2247]
install anaconda 4.3.0-1 and then install VS2017 early release

then in python environment tab, there appears 2 environment, Anaconda 4.3.0 and Python 3.6.0

then I choose Anaconda 4.3.0 as a default environment, and click refresh button for making intellisense work.

but even retrieving all data, intellisense still cannot retrieve any information from cached data.

intellisense knows information after I refresh Python 3.6.0 environment also

this is an integration problem.

**Comment by zooba** [comment]
Is it possible that your IntelliSense thought it was using Python 3.6 rather than Anaconda? I know you said you changed the default, but that would be the most likely way for this to happen.

We have seen occasional issues where restarting VS or reopening a project is needed. Could that have resolved it?

**Comment by alanpurple** [comment]
@zooba 
It works well, I was just confused because of "unknown type" for libraries
