### ISSUE TITLE
Start with/without debugging launches the wrong file

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2260]
Open a python project
Drag & drop a python file that doesn't belong in that project into the editor
Right-click on editor and select Start with debugging, or Start without Debugging.

Result: The project's startup file is launched, instead of the file that you right-clicked on.

`DebugProject.StartWithoutDebuggingNotInProject` fails while doing these exact steps.

**Comment by zooba** [comment]
The problem is that the command handler for the active project is getting in first, and the selected file in Solution Explorer is being run rather than the one in the editor. This is likely because we are using the same command in multiple places.

Easiest solution is probably to create separate commands for the editor vs. the project, but we may also be registering it incorrectly.
