### ISSUE TITLE
Mixed-mode attach fails

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2316]
Running Python 3.5.3 32-bit, I open the Attach dialog in VS, select Python+Native, and attach to the process.

I get an invalid operation exception attaching the Python part. Digging in a little bit more, it looks like an invalid parameter error being returned from the `AD7LoadCompleteEvent.Send(this)` in [AD7Engine.cs](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs#L326). This is a stopping event, which IIUC requires a thread object to be passed - but we aren't passing it.

Commenting out this event doesn't appear to break anything - do we need to include it? We don't have a thread object handy at the point where we are currently calling it.

**Comment by int19h** [comment]
We basically need to do the bare minimum necessary to gracefully exit our engine attach without error messages, but while also ensuring that attach is complete (one way or the other) from VS point of view. If I remember correctly, LoadComplete was necessary for that purpose, and not having it broke debugging in general (since VS was still assuming it was attaching).

If that's not the case anymore, we can drop it.

**Comment by zooba** [comment]
Seems like we can send AD7LoadCompleteEvent as an asynchronous event if we don't have a thread, or a stopping event if we do have a thread. In basic testing that seems to work fine.
