### ISSUE TITLE
Python Completion DB updates every time VS updates

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/PTVS#2334]
Completion DB update occurs every time Visual Studio 2017 preview updates

and it takes too long

Is this inevitable?
Necessary?

![image](https://cloud.githubusercontent.com/assets/4515120/24390696/87ef6d0e-13c5-11e7-9369-11ecfde3bdfd.png)

**Comment by zooba** [comment]
Fixed in #2325 yesterday (probably just a few hours before you reported this), because I agree entirely :)

We moved back to a manual versioning system for the completion DB, so we should only trigger re-analysis when something has actually changed, and it's better this time than our old way (which had a tendency to start "fights" between two VS installs).

**Comment by zooba** [comment]
Dup of #2324
