### ISSUE TITLE
Don't use spaces around = when automatically generating method signature

### ISSUE THREAD

**Issue by tobiaswiese** [microsoft/PTVS#2336]
When Visual Studio is automatically generating the method signature when overriding a method, which uses default values Visual Studio adds white spaces on both sides of the `=` char.

According to PEP8 Style Guide this shouldn't be done:
> Don't use spaces around the = sign when used to indicate a keyword argument or a default parameter value.

Yes:
```
def complex(real, imag=0.0):
    return magic(r=real, i=imag)
```
No:
```
def complex(real, imag = 0.0):
      return magic(r = real, i = imag)
```

(https://www.python.org/dev/peps/pep-0008/#other-recommendations)

**Comment by zooba** [comment]
Thanks for the feedback.

PEP8 is not a binding style guide for anything other than the Python standard library, so there is no obligation to follow it (though it is a pretty good starting point for most style guides).

In this case the problem is that when overriding a method, we are not following the formatting options in Tools, Options, Text Editor, Python, Formatting. Whatever option is selected there should be used when generating code.

**Comment by MikhailArkhipov** [comment]
In R users wanted separate option for spaces around = in statements and inside function definitions. Apparently it is common to have `x = 1` but `foo(a=x)`

**Comment by int19h** [comment]
In Python, it is in fact the standard way to format things (see PEP-0008 above). Consequently, PTVS does have two separate options for assignments and for default parameter values:

![image](https://user-images.githubusercontent.com/1175142/32705518-21cf1bb4-c7ca-11e7-84e3-e61f8f988af2.png)

The bug here is that the latter option isn't respected in this particular case (when auto-generating a signature for an override).
