### ISSUE TITLE
PTVS w/Anaconda 3.6 - intellisense not working for .NET dlls.

### ISSUE THREAD

**Issue by AnitaLund** [Microsoft/PTVS#2339]
Hi,

I'm trying to get intellisense to work for .NET dlls in VS 2015 with PTVS 2.2 and Anaconda Python 3.6 without much luck. The dlls are imported and I can use their classes/methods in code, but intellisense does not work for the .NET dlls in the python VS editor. Should this work?

Example:
import clr

clr.AddReference('System')
print( list( clr.ListAssemblies(False) ) )        #Shows that the System assembly is loaded.

from System import DateTime    #in the editor System is underlined w/error Intellisense may be missing for this module.

print( DateTime.Now.ToString() )     #the current date/timestamp is printed when run

It does not seem to make any difference if I add System.dll to References and Search Paths in the VS project.

Should the intellisense work, or am I expecting functionality that is not yet supported in this configuration?

Best regards,
Anita

**Comment by denfromufa** [comment]
I guess you are using Python.NET with Python 3.6, hence this is tracked in this issue:

https://github.com/Microsoft/PTVS/issues/1156

**Comment by denfromufa** [comment]
Some workarounds e.g. using PTVS console or jupyter notebooks are tracked in this issue:

https://github.com/pythonnet/pythonnet/issues/255

**Comment by zooba** [comment]
It's not supported with Anaconda, but only with IronPython (as in, Visual Studio can tell the difference between Anaconda/IronPython and assumes that only IronPython should provide .NET Intellisense).

There's a really good argument here for tying the .NET Intellisense to an `import clr` rather than how we do it now, but that is probably a pretty big change for us to make, rather than being a simple fix.

**Comment by AnitaLund** [comment]
Ok, I suspected as much. Many thanks for your replies.
