### ISSUE TITLE
Intellisense hangs VS when interacting with filepath that contains many files

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/PTVS#2352]
I've got a folder with 90,000 text files in it. (I'm doing some machine learning and this contains my training set).

When I manipulate a string with this filepath, VS hangs momentarily. (I assume when populating the Intellisense object).

Perhaps we should consider setting an upper boundary on the number of elements we're willing to put in this dialog. 

Sample:

![image](http://imgur.com/4VyM42I.gif)

**Comment by huguesv** [comment]
Thanks! Sounds like an issue in our new IntelliSense for file paths.

**Comment by Ark-kun** [comment]
I think Intellisense should never block the UI like that.
P.S. I've seen it stuck for almost half an hour.
![image](https://cloud.githubusercontent.com/assets/1829149/25171547/168d1028-24a3-11e7-92d0-2d62590110ce.png)

**Comment by zooba** [comment]
FTR, we've disabled automatic popups in strings as a workaround for the worst part of this issue. You can manually trigger the completions with Ctrl+Space or Ctrl+J, and if there are a lot of files it will still hang.

The other change is to do filtering based on the last part of the name. This only triggers if we find more than 10,000 files - we have to find all files before filtering them anyway - so if we exceed 10k we will do prefix matching on the names. So if you've types `r"C:\My Files\ab"` and Ctrl+J, you'll only see filenames starting with `ab` (if there are more than 10k in the directory, otherwise you'll see all files but they are filtered down using our usual filtering algorithm - big difference here is we won't show you all files in the >10k case when you delete the `ab`).

I know that sounds like a lot of edge cases, and it is - this is surprisingly complicated :) I'm leaving the issue open because I really want to asynchronously collect the filenames, but right now it's too big a change to take.

**Comment by MikhailArkhipov** [comment]
RTVS has relatively simple approach to non-blocking async list population within existing non-async editor framework (borrowed from earlier work on HTML editor). Might work as inexpensive solution.

**Comment by zooba** [comment]
You'd still end up with over 10k items in the list though, right (eventually)? Being more clever about triggering the completion after a few characters would be better.

**Comment by huguesv** [comment]
Yes to both. Non-blocking list population is near the top of my wish list (for general IntelliSense, not just file lists). If I'm patient enough to wait a second or two after pressing '.', I should see the list appear, not give up after 50ms.

**Comment by MikhailArkhipov** [comment]
Right, but typing will not be blocked. You can still bring list up and filter on the text typed so far OR consider alternative like in VSC where JsonRPC transfer can't handle 1000s of entries in completion and it is better to pre-filter list on the first character.

**Comment by MikhailArkhipov** [comment]
I can take this

**Comment by zooba** [comment]
@MikhailArkhipov Be aware that we've done as much as we can already without doing major surgery on all of our completion infrastructure. You're welcome to do it, but be aware you're getting into a big project with a long bug tail :)

Also, if you do go here, try to fix #507 as you go, since you'll be touching that code.

**Comment by huguesv** [comment]
We've removed this functionality.
