### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by alexanderwehrli** [Microsoft/PTVS#2363]
I am trying to build a native extension in Visual Studio 2015 (Update 3) using the x86 Version of Anaconda3 4.3.0.1 (Python 3.6). PTVS (version 2.2.40623) did not recognize the Anaconda distribution automatically, so I added a custom environment. **Unfortunately, I could only select 3.5 as language version (why?).**

Following the instructions in "Visual Studio Python Tutorial Deep Dive: Creating Native Modules" I have created a C++ Project in the solution containing my Python Project and set the following properties on the C++ project:

- General->Target Extension: .pyd
- General->Configuration Type: Dynamic Library
- C/C++ -> General -> Additional Include Directories: added %INSTALLDIR%\Anaconda3\include
- C/C++ -> CodeGeneration -> Runtime Library = Multi-threaded DLL (/MD)
- Linker -> General -> Additional Library Directories = %INSTALLDIR%\Anaconda3\libs

The C++ project contains one source file:
```
#include <Python.h>

PyObject *dosomething(PyObject *, PyObject *o) {
	double x = PyFloat_AsDouble(o);
	x += 1.0;
	return PyFloat_FromDouble(x);
}

static PyMethodDef TestLib_methods[] = {
	{ "dosomething", (PyCFunction)dosomething, METH_O, nullptr }
};

static PyModuleDef TestLib_module = {
	PyModuleDef_HEAD_INIT,
	"TestLib",
	"Does something",
	0,
	TestLib_methods
};

PyMODINIT_FUNC PyInit_TestLib() {
	return PyModule_Create(&TestLib_module);
}
```

Building the project succeeds, but when I add the C++ as a reference in the python project and execute "import TestLib" in my python code, I get the following error:

**ImportError: DLL load failed: The specified module could not be found.**

When I look at the .pyd file with Dependency Walker, I see that there is a depdency on PYTHON3.DLL which cannot be resolved. What is the issue here?

**Comment by huguesv** [comment]
Python 3.6 support was added to VS 2017, but wasn't backported to VS 2015.

I get the same error as you on VS 2015 (I tried CPython and Anaconda).

On [VS 2017 Preview](https://www.visualstudio.com/vs/python/?wt.mc_id=aka_ms_python), there's a project template that gives you a C++ project already set up to work with Python 3.5 or later.  It worked fine for CPython, but not Anaconda.

![image](https://cloud.githubusercontent.com/assets/1696845/24679608/8965980c-1942-11e7-85f4-2520843597a1.png)

VS 2017 automatically adds the .pyd folder as a search path when you add a reference to a C++ project. I tried doing it manually on VS 2015 that it made no difference.

**Comment by zooba** [comment]
So on VS 2015 you need an actual reference directly to the project (sometimes unreliable) or the .pyd (doesn't handle solution configuration changes) - finding them through search paths is new in VS 2017. But you also need the search path so that it can be found when you start running.

This is likely because of the missing python3.dll reference, which is deliberately loaded by Python to ensure it is resolved at runtime, but appears to not be included in Anaconda. I just dropped a copy from a regular Python install into my Anaconda folder and it worked fine (it's a trivial DLL that forwards to the real one).

That tutorial explicitly enables the limited API, and if you don't do that then you'll link directly against the python3x.dll instead (but will need to rebuild for each target version). We could also file a bug against Continuum and ask them to include python3.dll in their bundle.
