### ISSUE TITLE
at debugging model ,Chinese garbled

### ISSUE THREAD

**Issue by Luzemin** [Microsoft/PTVS#2375]
![image](https://cloud.githubusercontent.com/assets/8761991/24826103/effeca86-1c60-11e7-9014-00fd53b3a25e.png)

**Comment by zooba** [comment]
What version of Python are you using? By default, versions prior to 3.6 can only display characters in your active code page in the console window, while Python 3.6 can display any Unicode-encoded character.

Because your file is utf-8 encoded, it is likely that the transcoding from utf-8 to whatever your active code page is has lost information on the second line. The easiest solution is to update to Python 3.6, or to specify `PYTHONIOENCODING=utf-8` in the environment.

(Note that this is a Python limitation, not a Visual Studio one, so I'm marking this as a question rather than a bug.)

**Comment by zooba** [comment]
Does using `print` instead of `input` make a difference for the second line of text?

**Comment by Luzemin** [comment]
`print('chinese')` is ok.
only use `input('chinese')` ,this problem will appear.
(forgive my poor English.... :( )

**Comment by Luzemin** [comment]
I suggest you try it yourself.
VS2013+PTVS+Python3.5.2

code:
print('中文')
input('请输入')

debugging:
>>中文
>>**wrong!!!**

without debugging:
>>中文
>>请输入

**Comment by zooba** [comment]
Trying it myself is much more work, since I need to be using Chinese Windows.

This is clearly an issue in the debugger though, so we'll take a look when we get a chance.

**Comment by zooba** [comment]
This is the same as #1170, so I'll close this one.
