### ISSUE TITLE
vscode fails binding breakpoint in debugging python files with path containing chinese in Windows

### ISSUE THREAD

**Issue by StevenChenSE** [Microsoft/PTVS#2376]
With a .py filepath containing Chinese characters, PythonTools\visualstudio_py_debugger.py throws following Warning:

C:\Users\Jianwei Chen\.vscode\extensions\donjayamanne.python-0.6.0\pythonFiles\PythonTools\visualstudio_py_debugger.py:1673: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if module.filename.lower() == path.abspath(bp.filename).lower():

This is because python2 fails to decode the first operand to Unicode, it has to be manually specified by:
  if module.filename.lower().decode("gb2312") == path.abspath(bp.filename).lower():

I hope you guys can fix this in next release.

**Comment by zooba** [comment]
You should report this on the VS Code Python extension's repository to get a fix there - this repository is for Visual Studio.

We share this part of code, so it also affects us. However, because Python 2 does not support Unicode properly there may not be much we can do about this. Unless your paths can be encoded in your active code page, it will fail regularly.

Python 3 (and particularly Python 3.6) have resolved this issue, so we would recommend upgrading to avoid these problems.
