### ISSUE TITLE
Paste adds extra whitespaces at the end

### ISSUE THREAD

**Issue by ivannp** [Microsoft/PTVS#2398]
In the attached image, notice how the cursor is a few characters away right after paste.
![capture](https://cloud.githubusercontent.com/assets/1331156/25033469/c9c2f2da-2092-11e7-8b6d-73608eabea6f.PNG)

**Comment by huguesv** [comment]
Thanks.

Exact steps to repro this:
Start by typing this code.
![image](https://cloud.githubusercontent.com/assets/1696845/25048780/0bca10a4-20f3-11e7-963d-ded5cf706543.png)
Because of smart indent, the cursor will be at column 4 after hitting enter after `else:`.
Then paste `timer = time.time`

As you can see in the original screenshot, the white spaces won't be added unless needed (if you type in a char).  If you press enter at that point, they go away.

**Comment by zooba** [comment]
It's actually just virtual whitespace, so it isn't a big deal. However, what it has revealed is:
* we don't correctly handle many Paste scenarios
* we don't correctly add the right Undo item
* we don't allow you to Undo removal of the prompts
