### ISSUE TITLE
Intellisense does not fully work in Visual Studio 2017 Preview, using PTVS

### ISSUE THREAD

**Issue by ikibkilam** [Microsoft/PTVS#2403]
I installed Visual Studio 2017 Preview.  I am learning Python and wanted to use Visual Studio (PTVS).  It installed fine.  I wrote a simple 3 line program.  

class C(object)
  def _init_(self, value):
  self.value = value
a = C(42)
etc..

Intellisense does not fully work. For example, if I start to type in "import", it will prompt correctly with choices.  If I type in "a.value.", it does not prompt with choices, as it should (for example that this could be an integer).  

Can someone please help me identify what is going on.  Microsoft has had a number of years to fix this problem (I saw others complain about this a couple of years ago, but there was no clear fix).

**Comment by zooba** [comment]
In our defence, this symptom appears for a great range of problems, and it's generally a different cause each time (which we fix fairly quickly).

In this case, I'm not entirely clear what the cause would be. The code you entered into the bug is not syntactically correct, which would lead to the problems you have described. Can you test with the code below:

```python
class C:
    def __init__(self, value):
        self.value = value

a = C(42)
a.value.
```
(Note there are two underscores before/after `init`, and an extra indent before `self.value =` - you can write "\`\`\`python" on the line before your code and "\`\`\`" on the line after it to keep the correct formatting.)

If it still doesn't work, there is extra information under Tools, Python, Diagnostic Info that may help us figure out what is going wrong. If you could save that to a text file and attach it to this issue or email it to ptvshelp@microsoft.com, then we'll see if something is not configured correctly or is failing for you.
