### ISSUE TITLE
Python 3.6 support asking

### ISSUE THREAD

**Issue by ghost** [Microsoft/PTVS#2470]
Will PTVS support python 3.6 in future?
Is it in your plan to support python 3.6 ?

**Comment by zooba** [comment]
Python 3.6 is supported in Visual Studio 2017. See https://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/ for information.

**Comment by markusschaber** [comment]
Yes, but for those of us who can't upgrade to VS 2017 (or not yet right now):

Will the downloadable Package of PTVS for VS 2015 be upgraded to support Python 3.6? Is there anything (contributions etc...) we can do to help out?

**Comment by zooba** [comment]
I'm interested in what situation you're in where you can't install VS 2017 but can install an extension to VS 2015 (other than disk space).

But ultimately, no we won't be releasing an update for VS 2015 at this point. You can use Python 3.6 by adding it as a custom environment and calling it 3.5, but new debugging and editor functionality will only be available in VS 2017.

**Comment by markusschaber** [comment]
As far as I know, VS 2017 requires new lienses, the existing licenses for VS 2015 Pro do not allow upgrading to VS 2017 Pro.

**Comment by zooba** [comment]
@markusschaber Ah, yeah, that makes sense (I don't personally know if it's true or not - I don't deal in licensing - but it makes sense).

If you're prepared to build from source, it shouldn't be too difficult to get it running on VS 2015 again. But we are not planning to maintain it, and just to be up-front, won't be considering pull requests to reenable it either.

**Comment by markusschaber** [comment]
Not even considering pull requests? That's sad. I guess there's some corporate policy behind it...

As I'm not in the position to maintain a permanent fork, that basically means "give up" for now, and stick with the "custom environment" solution.

**Comment by zooba** [comment]
No corporate policy, simply a case of we can only handle so much complexity in the code base at a time. Code that is VS 2015 specific is going to go untested and eventually rot, leaving us in a position of having a broken project, or alternatively a maintenance burden that would significantly impede any forward progress. We made the decision to branch and move VS 2015 into extended support (bearing in mind that this project is Apache 2.0 licensed for VS 2015 - there was no guaranteed support included - while for VS 2017 we release under the usual VS EULA+support). Dropping VS 2015 support and moving to our current model where we release as part of VS has freed us up to do much more than we otherwise could have.

I'm sorry that you feel left behind, but at some point that is inevitably going to happen. Customers with MSDN subscriptions have access to VS 2017 included, but that is not a feature of a one-off license purchase.
