### ISSUE TITLE
Color Theme for PTVS

### ISSUE THREAD

**Issue by arqeco** [Microsoft/PTVS#252]
Hello,

Is there any good color theme for PTVS? I would prefer a dark theme, but many are not ready for Python syntax. If you like any color theme for working with PTVS please let me know.

Thank you,
Marcio

**Comment by zooba** [comment]
The built-in Dark theme in Visual Studio is probably the only one that properly handles Python syntax, since that's the one that we can update when we install PTVS.

If you look under Tools, Options, Fonts and Colors you'll find a number of "Python ..." items that can be modified. Other themes will need to set those as well to handle Python syntax, but you can always modify them yourself.

I'm sure the other theme developers would appreciate suggestions on what colours they could use there, but I don't know how best to get in contact with them. Chances are they don't even know about PTVS :)
