### ISSUE TITLE
Project's REPL fails to find DLLs for module, but project's only environment's REPL can find them just fine.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/PTVS#2528]
I'm using Python Tools in Visual Studio 2017 v 15.2

I have a project with a single environment - cntk-py35
When I open the Interactive window for this environment, everything is good - `import cntk` works
When I switch to the "Project : MyProject" environment, the import fails due to missing dlls.

The DLLs are located in the environment root. I've tried to add the root path to "Path environment variable" after PYTHONPATH, but that did not change anything.

During the debug, import also fails.

What's the proper way to make this work?

![image](https://cloud.githubusercontent.com/assets/1829149/25946750/561bd71e-3601-11e7-9642-08b1bfc915f3.png)

**Comment by zooba** [comment]
So we believe the problem here is that CNTK is installing DLLs into the wrong location. We've chatted with them separately about it, so it may be fixed in one of their updates.

As a workaround, you can add code like this to the top of your file (before you try to import CNTK):

```python
import os
import sys

os.environ["PATH"] = os.environ["PATH"] + ";" + sys.prefix
```

It may be affected by other system configuration settings, but in most cases this should enable the DLLs to be resolved correctly.
