### ISSUE TITLE
An existing anaconda 64bit installation(python 3.6.1) could not be automatically found

### ISSUE THREAD

**Issue by timeregained** [Microsoft/PTVS#2530]
I have installed latest Visual Studio 2017 15.2 because finally the python workload is released in this version.

However, an existing anaconda 64 bit installation (python 3.6.1) cannot be found automatically either during VS installation or later launch into the IDE , this performs really differently when I used previous PTVS in VS 2015. The same anaconda installation could be automatically found and integrated into VS 2015 without any manually configuration.

The Diagnostic Info could be found as
[Diagnostic Info 2017-05-11T194241.txt](https://github.com/Microsoft/PTVS/files/992885/Diagnostic.Info.2017-05-11T194241.txt)

**Comment by zooba** [comment]
We changed how our auto-detection worked in VS 2017 (to be consistent with PEP 514, which is the official way to register Python installs on Windows), but Anaconda also updated their installer to write the correct keys.

If you have installed a recent version of Anaconda (which I think you must have, since you've got 3.6.1), they should have set the keys. You may want to try repairing your Anaconda install to see if that fixes it, and be aware that if you select the "set as my default Python" option when installing Anaconda you should see it twice (because it will register itself twice - one will just look like "Python 3.6" though).

**Comment by timeregained** [comment]
I have checked the registry key referred in PEP 514 and found only the keys created by Visual Studio PTVS. I guess it is caused by this Anaconda is installed through conda command "conda install anaconda", not installed by an anaconda installer. However, I have remembered when I installed conda with miniconda3 installer, it also reminded me to "set as my default Python", although it seems not works as expected according to PEP 514.

**Comment by zooba** [comment]
That's strange, but perhaps miniconda does not set the registry entries at all. Certainly I would expect that `conda install anaconda` would not set any registry keys.

Managing conda environments properly is on our roadmap, but for now you will need to manually configure them.

**Comment by timeregained** [comment]
Got it, thanks a lot for your advice.
