### ISSUE TITLE
Open include file header in Visual Studio 2015

### ISSUE THREAD

**Issue by cirmic** [Microsoft/PTVS#2587]
I have a Windows 7 PC with Visual Studio 2015 Upgrade 3 installed on it and I would like to install a library for Python with pip 9.0.1 . 
When I run pip command with administrative rights it often return this error: 
`fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory`

How to include header in pip command?

**Comment by zooba** [comment]
What version of Python are you using?

If it is Python 2.7, then there's really nothing we can do about this. The [compiler for 2.7](https://aka.ms/vcpython27) is very old and does not have that header at all. You'll have to file a bug against the package and ask them to avoid including that header, but typically people are not very keen to do that.

Python 3.5 or later should work fine with the VS 2015 compiler, so in this case we'll need to see the full set of errors in order to figure out what is going wrong. This version _does_ include that header, so there is obviously another problem if that is the error you are getting.

(See [this post](https://aka.ms/vcpython) for more background on why the compiler matters so much.)
