### ISSUE TITLE
"Intellisense may be missing for this module."

### ISSUE THREAD

**Issue by NapsYork** [Microsoft/PTVS#2596]
I'm having issues with an import. Any steps I can take to amend this problem would be greatly appreciated as it has halted my development.

![screenshot 9](https://cloud.githubusercontent.com/assets/28992122/26516769/d9a596a6-4259-11e7-99d6-94fe7b7fbe17.png)

**Comment by zooba** [comment]
Have you got an `__init__.py` file in the top level of your project? That will change your package names to `DjangoRealWorldTut.app.models`, which is why `app.models` is not found.

You shouldn't need that top-level file, so unless it has content in it for some reason, you can just delete it. Running your app is going to insert the correct search path at runtime, which is why your code probably works, but we can't statically determine that is what is going to happen.

**Comment by NapsYork** [comment]
Yes it seemed to resolve the issue. Thank you so much for your help!

**Comment by ligwill** [comment]
Hi, im new to github ... im having a similar issue. The app runs fine but when i try to import a local module (like a custom class or function) the green line below is always there and never goes away. I dont have any __init__ file. Nevertheless, as soon as i "open" that function or class that im trying to import, the green line goes away ... Any idea why is happening? THANKS A LOT!!
