### ISSUE TITLE
wfastcgi error reading WSGI handler- Flask/IIS

### ISSUE THREAD

**Issue by MapZombie** [Microsoft/PTVS#2621]
I've been trying to setup a Flask application on IIS8 using wfastcgi without success.

I have gone as far as being able to successfully bring up a test flask site:
```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello from FastCGI via IISS! TEST"

if __name__ == "__main__":
    app.run()
```

This works perfectly fine. However when I try the same setup with my application I run into the error:

> Error occurred while reading WSGI handler: Traceback (most recent call last): File "C:\inetpub\wwwroot\catalog\geocat\wfastcgi.py", line 711, in main env, handler = read_wsgi_handler(response.physical_path) File "C:\inetpub\wwwroot\catalog\geocat\wfastcgi.py", line 568, in read_wsgi_handler return env, get_wsgi_handler(handler_name) File "C:\inetpub\wwwroot\catalog\geocat\wfastcgi.py", line 551, in get_wsgi_handler raise ValueError('"%s" could not be imported' % handler_name) ValueError: "run.app" could not be imported StdOut: StdErr: 

My project is setup like this:
```
catalog
    geocat
    __init__.py
    web.config
    run.py
    wfastcgi.py
       application
        __init__.py
        views.py

```
**run.py**
```
from application import app

if __name__ == "__main__":
	
	app.run()
```

**views.py**
```
from flask import Flask
app = Flask(__name__) 

#bunch of routes and other things (meat of the app)
```

web.conf

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
	 <modules runAllManagedModulesForAllRequests="true" />
        <handlers>
            <add name="flasksite" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Python27\python.exe|C:\inetpub\wwwroot\catalog\geocat\wfastcgi.py" resourceType="Unspecified" />
        </handlers>
    </system.webServer>
	    <appSettings>
        <add key="PYTHONPATH" value="C:\inetpub\wwwroot\catalog\geocat" />
        <add key="WSGI_HANDLER" value="run.app" />
    </appSettings>
</configuration>
```

**Comment by zooba** [comment]
Firstly, you may want to upgrade your copy of [`wfastcgi`](https://pypi.org/project/wfastcgi) (I can tell by the line numbers in the error that there is a newer version). I'm not sure whether we've made significant changes since the version you have, but we've certainly improved error handling and logging over time, so you might get a more helpful message.

It looks like you can omit the `geocat/__init__.py` file, since you are not trying to import files as `geocat.run.app` and so that file is only going to cause some package names to have extra parts to them. The `PYTHONPATH` setting should prevent that from being an issue, but due to how IIS starts the process there is a period of time before `sys.path` actually receives that value - if we're trying to import the handler before then, and if IIS has started the process in `wwwroot` rather than the directory containing `web.config` (which I don't recall right now exactly what it does here), then it would fail.

Looking at the latest `wfastcgi`, it seems we do updated `sys.path` before loading the handler, but I don't remember when/if we changed that. I'd start by making sure your `web.config` is at the top level of your package hierarchy (that is, there are no `__init__.py` files alongside `web.config` or in any parent directories) and making sure the handler is imported relative to there.

**Comment by MapZombie** [comment]
Thanks @zooba . I upgraded to the latest version, removed the __init__ file. Then it properly printed an oracle issue which I was able to then fix.
Site is now working!

**Comment by parthrawal** [comment]
I am also facing the same Issue. Can you please explain what can be the problem? 
In my case I only have 1 py file which is having all of the code.

**Comment by DanielJBrown** [comment]
Any ideas on how to resolve this error? I am in DMZ zone.

Error occurred starting file watcher: Traceback (most recent call last): File "C:\inetpub\wwwroot\BenchmarkAppsAPI\wfastcgi.py", line 794, in main start_file_watcher(response.physical_path, env.get('WSGI_RESTART_FILE_REGEX')) File "C:\inetpub\wwwroot\BenchmarkAppsAPI\wfastcgi.py", line 567, in start_file_watcher log('wfastcgi.py will restart when files in %s are changed: %s' % (path, restart_regex)) File "C:\inetpub\wwwroot\BenchmarkAppsAPI\wfastcgi.py", line 353, in log with open(log_file, 'a+', encoding='utf-8') as f: PermissionError: [Errno 13] Permission denied: 'C:\\inetpub\\wwwroot\\BenchmarkAppsAPI\\app.log' StdOut: StdErr:
