### ISSUE TITLE
[Interpreter] Invalid interpreter when sharing the .pyproj file in VCS

### ISSUE THREAD

**Issue by sonictk** [Microsoft/PTVS#263]
Hi all:

Not sure if I'm doing things wrong here; I have a virtualenv for a project that is being shared in the git repo in order to make it easy for me to transfer my work around workstations (at least, if they have PyCharm/Wing installed).

I'm trying out PTVS for my workflow, and I'm having an odd issue where if I load the solution on another computer, save it and commit it to VCS, the next time I open it on a different machine, I get an *(unavailable)* error and I need to re-add the virtualenv again.

In the diff, it looks like this might be the issue:

![Image](http://i.imgur.com/K1m0xpT.png)

If this is the wrong approach to take for syncing PTVS projects across VCS, I'd appreciate it if anyone could enlighten me on what I could do to solve this issue.

Thanks!

**Comment by zooba** [comment]
If you're adding the virtual environment as a custom environment, then unfortunately yes, it doesn't transfer well between machines. There are some pretty serious architectural changes we'd need to make to support this properly, so it hasn't happened for fear of destabilizing the product and breaking third-parties who use the APIs involved.

The better way to do a virtual environment is to add it to your project directly. If you right click the Environments node in Solution Explorer then you can add an existing virtual environment. This will do a better job of handling the layered libraries too, as well as being portable between machines (provided the same base interpreter is used for the virtual environment and the relative path from project to environment is the same). This feature is really designed to handle project-specific environments, so it isn't necessarily going to be perfect if you want to share a virtual environment between projects.

One other option is to add a `requirements.txt` file to your project. You can generate or update these by right-clicking the environment, and then on a new machine you can create a new virtual environment and we will install whatever is listed for you. It's an extra manual step, but it is going to avoid basically all of the problems you'll face trying to move virtual environments between machines (venv hardcodes some absolute paths, for example, and there's little we can do to work around these).

**Comment by sonictk** [comment]
@zooba Hi:

> The better way to do a virtual environment is to add it to your project directly. If you right click the Environments node in Solution Explorer then you can add an existing virtual environment. 

That's exactly how I am adding the virtual environment now, though. However, when I save the .pyproj file and try to load it on another machine, it doesn't work (And gives the invalid interpreter error, as mentioned). The virtualenv directory is actually contained within the project structure itself i.e. ``/virtualenv`` I am not sharing this virtualenv *between* projects; they are being used for the same project. It's just that loading the .sln on different machines causes one of them to break depending on where the project was saved last. Perhaps I'm misunderstanding your instructions here?

A requirements file solution also seems unlikely to me in this case, as the virtualenv is set up to append several (esp. when working with DCC applications such as Maya/3ds max) directories to the interpreter PATH. Basically the problem that I described to you here, a few days ago: https://github.com/Microsoft/PTVS/issues/236 If it is possible for me to somehow get this to work with a ``requirements.txt`` file, please correct me, but my understanding is that it meant for pip to auto install packages listed in it.

Also, a thought: I don't really consider myself a Python expert, but this seems a rather perplexing feature implementation, considering the fact that having to make specific working python environments is a critical part of software development for TDs, and especially since doing the same in PyCharm/Wing/Eclipse is trivial. It seems like the GUID for the interpreter ID isn't really necessary? Though obviously I don't know what's going on under the hood, but I hope you guys will consider taking a closer look at this in future releases, even if it entails some serious changes in the way things are handled.

**Comment by zooba** [comment]
It sounds like you are doing it correctly, so the id should be specified further down in your .pyproj file and should not be changing when you move between machines. Can you post the full diff or both files as a gist? We may have an issue here that I wasn't aware of.

You're right that the GUID isn't really necessary - that's the serious architectural change we need to make, but it's part of the public API and so we can't just change it without breaking other people. :( In this case however, it should be a GUID that's local to your project and shouldn't cause any issues.

**Comment by sonictk** [comment]
@zooba Hi Steve, this is what I am doing:

When I pull my project that was saved on my work PC, I get this:

![Image](http://i.imgur.com/fm991sa.png)

I remove it from the project first. 
![Image](http://i.imgur.com/xElD1EA.png)

I add it again, and then quit and save the solution.

![Image](http://i.imgur.com/aDbeoRj.png)

The diff is available at: http://pastebin.com/GLaMN2GM

Thanks for helping to take a look at this!

**Comment by zooba** [comment]
Ah, so it is actually because of the custom environment - notice how the `BaseInterpreterId` is also changing? That's the real problem, and the one that we know we need to fix somehow.

What we'd really like to see happen is someone create an extension that can detect and auto-configure 3ds max (and other programs like this) in PTVS, since then they can use a stable ID. These aren't particularly hard to write (in C#, unfortunately), but it is fairly specialized. Canopy ships one with their package, and because it's their extension, it means they can update paths/versions/etc. as they need to and all our users see it Just Work - something that we can't necessarily do from our side.

For an immediate fix/hack/workaround if you're up for some registry editing, you can find and change all instances of one `BaseInterpreterId` to the other one so they match between machines (I'd only expect you to find 2-3 of them, all under `HKCU\Software\Microsoft\Visual Studio`). Then you'll have a consistent ID and won't have to keep changing the virtual environment.

A fix I probably can get in for 2.2 is to automatically fall back to our autodetection process for finding the base environment. This clearly works okay, since it's what we use when you add an existing environment, but we don't attempt it when loading a project.

**Comment by sonictk** [comment]
Hi @zooba :

I tried searching for any key with ``BaseInterpreterId`` in it, but found nothing. I tried searching those UUIDs as well in the diff, but also turned up nothing?

**Comment by zooba** [comment]
No, virtualenvs are special and don't "need" UUIDs, but that's because they were added much later than the original support for multiple environments. *Custom* environments do require a UUID, and these are automatically generated each time you add a new one.

We may do some unusual formatting when putting the UUID in the registry - it's been a while since I looked at that code - try searching for just the last segment of characters. It has to be there somewhere or it wouldn't be showing up in PTVS :)

(The thing about extensions is a way to not have to add custom environments for well-known products. Largely mentioned in case someone reads this and didn't realise it was a possibility.)

**Comment by sonictk** [comment]
Sorry, I'm a little confused. I didn't add the virtualenv by making a custom environment; this virtualenv was generated completely outside of PTVS, all I did was add it via the method as described above. Or are virtualenvs actually treated as custom envrionments is what you're saying?

I also searched for the following 4 strings:
``71b4a165``
``904797c4``
``e409f0d951d4``
``eef9bcc7c0f6``

But none of them turned up any results. If I search for any registry key/value/string/anything with 'interpreter' in it, these are the results, none of which I can find the matching UUID string in it.
http://pastebin.com/R9vMJWJs

**Comment by zooba** [comment]
Here are the entries I'm referring to (under `f2813aa1-f9a3-4692-88b1-c91e20cc8de0`):

```
59.[HKEY_USERS\S-1-5-21-1664357059-66260914-1444714891-1000\Software\Microsoft\VisualStudio\12.0\PythonTools\Interpreters\{f2813aa1-f9a3-4692-88b1-c91e20cc8de0}]
60."INTERPRETERPATH"="C:\\Program Files\\Autodesk\\3ds Max 2015\\python\\python.exe"
61."WINDOWSINTERPRETERPATH"="C:\\Program Files\\Autodesk\\3ds Max 2015\\python\\pythonw.exe"
...
65.[HKEY_USERS\S-1-5-21-1664357059-66260914-1444714891-1000\Software\Microsoft\VisualStudio\12.0\PythonTools\Options\Interactive Windows]
66."{F2813AA1-F9A3-4692-88B1-C91E20CC8DE0}\\2.7\\USEINTERPRETERPROMPTS"="True"
67."{F2813AA1-F9A3-4692-88B1-C91E20CC8DE0}\\2.7\\INTERPRETEROPTIONS"=""
```

On your other machine you should find similar entries with the other GUID (71b4a165...). These are the custom environment that your virtual environment is linked to via the BaseInterpreterId property in the project.

If you rename one set of these keys to have the same GUID on both machines, you should stop seeing the change every time you move to another machine.

**Comment by zooba** [comment]
Not an immediate solution, and not *ideal*, but the autodetection fix I mentioned above was simpler than I thought. It's PR #282 and should make it in for 2.2.

**Comment by sonictk** [comment]
@zooba Thanks! How often do you guys release dev builds, by the way? I might try to do a build over the weekend (since I saw you just released another dev build like yesterday, I'm guessing the next build is a while away?)

**Comment by zooba** [comment]
Yeah, we'll probably do the next dev build late next week.

**Comment by sonictk** [comment]
@zooba Cool, I'll give it a shot, if I end up newb-ing out, I'll wait for you guys :) Thanks!

**Comment by zjturner** [comment]
Would it work to have an additional user entered field associated with an Interpreter, which is like an Interpreter Key or something?  This way you could assign a key to your interpreter, and that's the value it stores in the project file.  could even be a Guid or something, basically whatever the user wants.  As long as the person with whom the project is being shared has an interpreter with the same key, it just uses that.  I mean it's basically the same thing you're doing here with the InterpreterGuid, except this one is specified by the user, not auto-generated by PTVS, so it can be stable.

**Comment by zooba** [comment]
So we've had the idea to formalise registering Python interpreters in `[HKCU/HKLM]\Software\Python` but _not_ `Python\PythonCore`. If we switch to this, then rather than having a custom environment in PTVS, we'll help you register your environment and the automatically detect it (which you won't notice as a user, but it makes sense when you see how we've currently implemented it).

It would also mean that other interpreters could use `HKCU\Software\Python\[Company]\[Version]` to register their own environments, and other IDEs could inspect these keys to find them.

We may require/want a PEP to make the structure official.

**Comment by zooba** [comment]
The PEP is done (not approved yet), and the change is in.
