### ISSUE TITLE
python debugging won't resume with F5

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2644]
Once I set a breakpoint and hit it in my python project, the debugger won't resume as normal. It will continue to break on the next step of some other thread in my application instead when I hit F5. I want it to resume fully, but it doesn't work.

So, once I hit any issue, I'm stuck and have to restart to get my program to run, it's very frustrating.

I never had a problem with VS2015 and the Python Extensions. I first encountered this with the new integration with VS2017

Originally reported at https://developercommunity.visualstudio.com/content/problem/55527/python-debugging-wont-resume-with-f5.html

**Comment by michael-hawker** [comment]
Sorry, I was OOF.  This was more of a red herring, the real issue I found out later was this one: https://developercommunity.visualstudio.com/content/problem/55532/python-not-showing-exception-hit.html

The problem was VS wasn't telling me an exception had occurred, so I didn't realize *why* it was breaking into the debugger.

**Comment by zooba** [comment]
Yeah, we've seen that one a couple of times now.

@huguesv We don't have an issue on GitHub for the exception popup not showing, but it's also release blocking. @crwilcox was hitting the issue today, but I suspect it's to do with the exception being in a frame that we don't have source code for.

**Comment by huguesv** [comment]
Opened https://github.com/Microsoft/PTVS/issues/2707 for the exception popup issue.
