### ISSUE TITLE
HDF5 + netCDF in Visual Studio

### ISSUE THREAD

**Issue by befuec** [Microsoft/PTVS#2646]
Hello everybody

I#m new to VS and I want to analyze netcdf files and convert them to a excel readable file.

So I installed VS2015 and use Python. I installed  HCF5 and netcdf4, but the problem is that I don't know how to link it to VS. I also wanted to try to install netCDF4 in VS but it said that it can't find the HDF5 headers. It looks like this:

`----- Installing 'netcdf4' -----
Collecting netcdf4
  Using cached netCDF4-1.2.8.tar.gz
    Complete output from command python setup.py egg_info:
    reading from setup.cfg...
    
    HDF5_DIR environment variable not set, checking some standard locations ..
    checking C:\Users\......
    checking /usr/local ...
    checking /sw ...
    checking /opt ...
    checking /opt/local ...
    checking /usr ...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-build-uajc7i6o\netcdf4\setup.py", line 283, in <module>
        raise ValueError('did not find HDF5 headers')
    ValueError: did not find HDF5 headers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-build-uajc7i6o\netcdf4\
----- Failed to install 'netcdf4' -----`

My questions are: How can I link VS to the installed HCF5 and netCDF ? Or how can I install netCDF4 in VS?

Thanks a lot for your support!

Bernd

**Comment by zooba** [comment]
It sounds like you're hitting trouble with general package installation, as opposed to anything specific to Visual Studio.

If you're working with data, I'd suggest installing [Anaconda](https://continuum.io), as it comes with many packages already included (I believe it includes these packages). Alternatively, there is a great [collection of pre-built packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/) that you can download and then install by specifying the full path to the downloaded wheel rather than just the name.

**Comment by befuec** [comment]
Hey zooba,
thanks a lot for your answer.. I tried it for a couple of days but still struggling with this issue. 
One thing is, that I don't know how to specify the full path to the downloaded wheel.

Can you write a few quick lines to this problem?
I would highly appreciate it.

**Comment by zooba** [comment]
Find the downloaded wheel file in Windows Explorer, hold shift and right-click it, then select "Copy as Path". Then go into the package name field and hit Ctrl+V to paste the full path in there.
