### ISSUE TITLE
No autocompletion suggestion when typing the function name

### ISSUE THREAD

**Issue by AlexArcPy** [Microsoft/PTVS#2709]
I have PTVS 2.2.6 for VS 2015 Professional installed. I have a Python module created. There I have:

```
def func(x):
    print(x)
```

If I start typing this function name, I don't get any suggestion on existing items unless I hit Ctrl-Space.
So, if I typed `fu` and then hit Ctrl-Space, I would see the `func` there among others.

However, if I type:

`result = func(5)`

Then, already after typing `f` it start suggesting items in the drop-down list.

Fairly often you would like to call a function without keeping the result in a variable and needing to press Ctrl-Space for this is a pain. Any way to fix that?

**Comment by zooba** [comment]
This is already fixed in Visual Studio 2017 (when typing at the start of the line suggestions will pop up automatically, but they won't default to being selected).

The Visual Studio 2015 support is no longer being updated. If possible, it's worth checking whether VS 2017 already has the functionality or issue you are experiencing before reporting it.

**Comment by AlexArcPy** [comment]
Thank you. I am reporting the issue specifically in the 2015, I am not interested in whether this feature is implemented in VS 2017. Thanks for the info, though.
