### ISSUE TITLE
How to change Python UWP to other version Python?

### ISSUE THREAD

**Issue by hoanganhtuanfsoft** [Microsoft/PTVS#2752]
I created a new universal windows Python project. VS2017 select PythonUWPIot default. (Its version is 3.5 and I installed Python 2.7.13 before). How to change to 2.7.13. When right-click Python environment, i see that:
![image](https://user-images.githubusercontent.com/19376164/27723882-5cf51a0e-5d99-11e7-8817-325db8e59139.png)

![image](https://user-images.githubusercontent.com/19376164/27723859-4968c134-5d99-11e7-817d-aa0864ea877e.png)

**Comment by zooba** [comment]
The UWP template only supports the specific Python version, since it has been modified to run under the UWP restrictions. We currently don't support changing it.

(cc @alanch-ms)

**Comment by hoanganhtuanfsoft** [comment]
@zooba Thank for replying. Which Python version does the UWP support? 3.5? Have I to install Python? or use default Python UWP? How to install addition library as OpenCV for Python UWP?

**Comment by zooba** [comment]
I believe the [latest release](https://github.com/ms-iot/python/releases) of CPython UWP is based on 3.5 still. Since this is a specially modified version of Python, you have to use it for this platform, and installing other versions doesn't make any difference (though of course, you can use other versions with regular Python projects other than UWP).

@alanch-ms will need to speak to the availability of 3rd-party libraries, but it's my understanding that you'll need to build them from source to be able to use them in UWP apps, and I'm not sure that the support for that exists yet.
