### ISSUE TITLE
Warn users when projects have unnecessary search paths

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#276]
Search paths that include sections of the active environment's library are almost always unnecessary, as the completion DB should have the required info. Adding these to the search path will also attempt to load and analyze far more modules than VS can handle, leading to OOMs and other issues.

We should warn about search paths that are within the active environment's prefix path.

(Note there are some legitimate needs for this, so we shouldn't ignore them completely or be too aggressive. The cross-module analysis limit prevents too many major issues.)

(See #236 for an example of this causing trouble)

**Comment by eksod** [comment]
**Please also warn users when there's too many search paths**. I have a very big solution where Intellisense is broken (everything gives "<No Completions>") because there are too many files added to it, and even with empty search paths Intellisense didn't work.

I've created a new solution with the same Python Environment and just a few modules/folders and Intellisense was working. So I've proceeded to clean up all non-essential modules from the original solution (Exclude From Project) and got it working again. It's a bit annoying because then I will need another solution (or Sublime or some other editor) only to do CTRL+SHIFT+F in all files.

**Comment by zooba** [comment]
"Too many" is very hard to define, as it really comes down to the number of files in each referenced search path - "one" can be too many if it happens to be your Lib/ folder (which we see fairly often).

Two alternative fixes for this that may make it into 3.0 are:
* revise code analysis completely to avoid these issues
* generate cached DBs for search paths

**Comment by eksod** [comment]
Yes, I'm sorry I can't be much specific because I couldn't find a way in Solution Explorer to see how many files were added to the solution. Some random numbers:

* There are 2015 .py files total inside the folders of the solution, that were all added in a flin. (4988 files in total with dlls, pyd, pyc, Maxscripts, and other formats), so it's ok to assume there were between 1800 to 2015 .py files added.
* After cleaning the solution I had 763 files listed in <Compile Include /> tag and 246 folders in <Folder Include /> in my .pyproj

Btw, before doing the solution cleaning I've had changed HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0\PythonTools\Options\Advanced@CrossModuleAnalysisLimit from 1300 to 13000, and restarted the computer, without any effect.

The biggest problem was that Intellisense was not giving any reason for failing, and I was left alone only with my the problem and my google-fu to solve it. Which brought me here and I started trying different things. If you could warn users that Intellisense is failing because there are too much references/search paths it would save a lot of time and/or the life of everybody that didn't reached this thread. ;)

**Comment by zooba** [comment]
Yeah, the lack of useful feedback in that case is a much bigger problem :(

We're stabilizing for our next update right now and won't be able to add it, but we'll definitely do something for our next release.

**Comment by eksod** [comment]
Great, thanks!

**Comment by zooba** [comment]
We don't need to provide feedback now because adding unnecessary search paths is no longer a problem (we use them lazily, rather than eagerly loading every .py file we can find).
