### ISSUE TITLE
Is it possible to add Python without removing all other languages?

### ISSUE THREAD

**Issue by MDKimzey** [Microsoft/PTVS#2766]
I would like to add Python to my VS2017 installation.

I go to the File | New Project | Open Visual Studio Installer.  

Workloads for my currently installed languages and packages appear as checked.  

If I select Python, I get a "There doesn't seem to be enough disk space..." message.  I am actually installing to my D: drive which has Terabytes of free space. 

I would very much like to retain my existing languages and add Python.  I fear that if I uncheck existing items the installer will uninstall them (which I do not want to do).

Is there any way to add Python and leave the other packages alone?

**Comment by zooba** [comment]
It sounds like you have multiple issues going on here (including #2765)

The general answer is yes, this is possible. However, you're encountering an issue with the VS installer which is currently being worked on for fixing in the next release. Right now, there are a number of components that will be installed to your system drive regardless of the drive you have selected for Visual Studio. Typically these are because they could affect other applications if they are not installed into their normal locations, however, since people are blocked completely (as you are) we have decided to risk affecting those other applications by moving these components to a different location.

The optional components for Python that are included here are:
* CPython
* Anaconda
* Some parts of "Python native development" (the Windows 10 SDK is the biggest one)
* Some parts of "Python web support"

If you deselect these options (from the right-hand checklist after you select the Python workload) then we won't install them and all the pieces we try to install should go into your Visual Studio directory on your D: drive. You can then install some of these items manually and select any location you like. Our Python support can detect installs of Python (including Anaconda) anywhere on your machine, regardless of whether you used the Visual Studio installer or not.
