### ISSUE TITLE
Cant debug Python when native debugging is enabled

### ISSUE THREAD

**Issue by tinyfx** [Microsoft/PTVS#2775]
In VS2015 I am unable to debug Python when native debugging is enabled. I can hit a breakpoint in C++ code, but not python. Debugging python works fine when native mode is not enabled.

I cant switch to VS2017 because CNTK does not yet support it. Irritatingly, it was working, then stopped for apparently no good reason.

I am guessing this is due to a known issue for which there is no fix planned? If so, is there a work around?

Thanks

**Comment by int19h** [comment]
There were a number of bug fixes in debugger since the last version for VS2015 shipped, so it's quite likely that you're hitting one of the corresponding bugs.

Regarding VS2017 support, can you clarify what you mean by "CNTK does not yet support it"? If it's about C++, if you have VS2015 and VS2017 installed side by side, you can use VS2017 to build C++ projects [using the C++ toolchain (compiler, libraries etc) from VS2015](https://blogs.msdn.microsoft.com/vcblog/2016/02/24/stuck-on-an-older-toolset-version-move-to-visual-studio-2015-without-upgrading-your-toolset/). This way you get all the IDE improvements while retaining backwards compatibility.

**Comment by tinyfx** [comment]
Ok thanks, I'll give it a go.

**Comment by zooba** [comment]
Also, if you select the "Python native development tools" option when installing, you'll automatically get both the 14.1 (VS 2017) and 14.0 (VS 2015) toolsets.
