### ISSUE TITLE
Python 2.6 completion DB is always out-of-date

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#2793]
The usual symptoms - "Refresh" button is always there in the Environments list. Interestingly, clicking on it does not write *anything* to the analysis log, even though the UI shows something happening?

Reproduces consistently for me on a fresh new Python 2.6 32-bit install (no custom packages etc), including if I delete the DB and try again.

Analysis log from the initial analysis run:
[AnalysisLog.txt](https://github.com/Microsoft/PTVS/files/1143337/AnalysisLog.txt)

**Comment by int19h** [comment]
Doesn't happen for any other installed Python version (2.7, and 3.0-3.6).

**Comment by int19h** [comment]
Also happens for IronPython 2.7. Not sure if same root cause, but symptoms are identical, except that in this case it does update the log on refresh. Analysis log:

[AnalysisLog.txt](https://github.com/Microsoft/PTVS/files/1143343/AnalysisLog.txt)

**Comment by int19h** [comment]
For 2.6, it looks like there log file wasn't flushed, so I was seeing a stale version. Here's an up-to-date log for that, which shows refresh attempts:
[AnalysisLog.txt](https://github.com/Microsoft/PTVS/files/1143351/AnalysisLog.txt)

**Comment by zooba** [comment]
Does it fix itself if you restart VS? There's a known issue updating UI state, which I think is due to the absolute mess of event handlers involved here.

If it repros after closing VS, deleting the DB and re-running analysis, this is a new issue. The logs don't look like there's an issue, so we'll have to compare directory listings for differences and then figure out why certain files are not being generated.
