### ISSUE TITLE
Load time of Python modules is slow

### ISSUE THREAD

**Issue by pieroliviermarquis** [Microsoft/PTVS#2805]
I am using Visual Studio 2017 and the loading time for modules are a lot longer than with the python interface. It is getting quite long for some of them. Is there something I can do to reduce it?

Loading time in the python interface:

```
>>> timeit.timeit(setup="import pandas")
0.005933331935494834
>>> timeit.timeit(setup="import numpy")
0.006258085310662409
```

Loading time in VS:

```
import time

def test():
    t0=time.clock()
    import pandas
    t1=time.clock()
    print(t1-t0)
test()
```

The results for pandas and then numpy are:

```
1.7031186076369706
0.28401291796759
```

**Comment by zooba** [comment]
Just so you're aware, the `setup` parameter to `timeit` is run once at the start and is not measured as the test. Also, `import` is optimized and will be much faster for modules that have already been imported. You should really just run the second script with both F5 and Ctrl+F5 to get the "with debugging" and "without debugging" times.

We are already aware that code runs slower while debugging. It's basically unavoidable due to how Python allows debugging, and while we are working towards ways of making it faster, we don't need to keep another bug around for it.

I'll leave this open for now in case you have follow up questions, but we'll close it eventually to keep our tracker from getting busy. Enhancements will show up over time without needing a specific bug.

**Comment by pieroliviermarquis** [comment]
I see. Thank you for the answer. I am still learning. Sorry if this is obvious.

**Comment by zooba** [comment]
It's certainly not obvious, but I don't want to make it sound like it's easy to fix (it's not) or that we don't value your feedback (we do). But people count the number of open bugs we have so it's important for us to close duplicates :)
