### ISSUE TITLE
How to install for VS 2017?

### ISSUE THREAD

**Issue by seandong21** [Microsoft/PTVS#2807]

**Comment by pedoc** [comment]
@seandong21 
1.open "`Microsoft Visual Studio Installer`"（in start menu）
2.select "modify"
3.make sure selected “`Data science and analysis applications`”，（includ Python，R，F#）
4.until the completion of modification

**Comment by mancoast** [comment]
Please update all technet documents to simplify the installation procedures.
I was confused because my VS2017 was not fully updated, and there was not option for python in the installer!?!
Any thoughts>?

**Comment by zooba** [comment]
The VS installer forcibly updates itself to the latest version before you can use it, so that would only happen if you are running an offline install. In this case, you took the installer before we published the documentation, kept it somewhere, and then ran it after updates were released. This is not a normal scenario, so we would rather keep the documentation simple and applicable to most users.

If your installer appeared to be working correctly but was not installing the right version, please use the "Report a problem" button in the installer to report it.

**Comment by mancoast** [comment]
Something was funky with my setup, glad the PVTS is available for 2017.  Thanks for update!
