### ISSUE TITLE
Python in Microsoft Visual Studio Community 2017 : Intellisense issues

### ISSUE THREAD

**Issue by athanhat** [Microsoft/PTVS#2889]
Hi, I thought to share my experience of working with Python tools in the latest version of Microsoft Visual Studio 2017 integrated environment. 

### Environment Information
According to `Help - About...` version I am using

* Microsoft Visual Studio Community 2017
  - Version 15.2 (26430.16) Release
* Microsoft .NET Framework
  - Version 4.7.02046

And according to `Tools - Python - Python Environments` there are two Python environments installed in my Windows 10 (x64) setup
* Python 3.6 (64-bit) - Default environment for new projects
* Anaconda 4.3.0

### Intellisense when you type in IPython interactive mode environment
I think there is a bug in `Intellisense` when you enable the
`Use IPython interactive mode` checkbox that is located under the quick `Overview ` of `Tools - Python - Python Envrionments (Ctrk+K, Ctrl+)`

#### To reproduce the bug follow these steps:

1. First check that `Use IPython interactive mode` checkbox is enabled 

2. **Close all interactive interpreters windows**

3. Open a new `Tools - Python - Python Interactive Window (Alt+I)` or sent to **Enhanced Interactive** default python environment either function definitions (def) or class specifications (class) from a module at an editor window. 

4. Start typing the name of function or class at the environment prompt `In[ ]`. This is exactly the point where `Intellisense` fails to provide `autocompletion`.   Nevertheless do notice it DOES WORK WITH `signature help` when you open the parenthesis after the name of the function/class identifier but not with `quick info`. 

#### Useful observations
Newcomers and developers of `intellisense` notice here that if you do not press `Escape` to leave `Intellisense` mode and you attempt to finish writing the name of the identifier that IS NOT found in `intellisense` list, it will be automatically replaced from auto-completion. This is not good for the default behavior of auto-completion.

Now if you disable `IPython interactive mode` and try to repeat the steps above to reproduce the error you will see that `Intellisense` **does provide auto-completion** when you type in a  **plain interactive** window mode environment. But I noticed that it is not displaying the correct Class type of objects. 

Notice also that it takes significant more time to reset an IPython interactive window or execute the first command than doing the same with a plain interactive Python interpreter.

Is there a way to bypass this bug with `IPython interactive mode` ? Yes, there is, first open `Tools - Python - Python Envrionments (Ctrk+K, Ctrl+)` and click on the window icon that is displayed at the right side of the environment name.

### Intellisense Navigation Bar
There is also an additional issue which I have reported with the editor `navigation bar` that is displayed at the top of each editor window and includes a two-level list of definitions. This list of definitions is EMPTY when you are working with `def` functions within the scope of a module. But it seems it's working fine when you write `Class` implementations.

The `View - Object Browser (Ctrl+Alt+J)` window is also related to this issue. It does not display anything either with Classes or def Python modules. It only displays the `Solution`-`Project` containers.

Has anyone found a way to bypass this error in this latest version of Visual Studio 2017 Community ?

### Kudos
Since I am a newcomer in this group, may I take also the opportunity here to thank Microsoft and the developers behind this superb Visual Studio integrated environment for Python coding. It is perhaps one of the best that one can use for learning, and demonstration purposes as well as working with big projects.

**Comment by zooba** [comment]
There are a number of concerns listed here, but I think they all either have an existing issue or are not addressable by us.

1. No Intellisense at initial Interactive Window in IPython mode

This is because is IPython mode we delegate to IPython to provide completions, rather than using our own logic. However, when you first open the window, we haven't started running IPython yet. If you press "Enter" immediately without typing anything, it will start running and then you should get IntelliSense.

We have an issue somewhere to add a prompt along the lines of "Press Enter to start the interactive session". It isn't strictly necessary, as whatever you type will be executed correctly, but it does make it clear that you'll have the best experience by sending an empty statement first.

2. IPython takes a long time to start

Yes, it does. This is entirely in their project. The only workaround we can offer is to disable IPython mode - but if you enabled it, you probably want something it has, so you'll just need to suffer the startup time. Again, pressing Enter to start the session makes it a bit more obvious why this happens.

3. IntelliSense completes names you didn't intend

This occurs when we think that what you've typed matches an entry, that you're probably in a location where you want an existing name (this won't happen at the start of a statement, for example), and you press one of the keys configured to [commit the current completion](https://docs.microsoft.com/en-us/visualstudio/python/options#advanced-python-editor-options). That link will show you where the option is to change these keys - if you delete all of them, then you will have to explicitly press 'Tab' or 'Enter' to insert the current selection, and anything else will leave exactly what you've typed there.

4. Object Browser does not show Python classes and functions

We disabled this for Visual Studio 2017 due to a combination of instability (our old implementation was a huge performance hog) and lack of usage. We currently have more important issues to work on, but we'll take this as another vote to add back support for it when we get a chance.

5. Navigation Bar is empty

This is a bug, covered by #2678.

---

Please let me know if you're not happy with any of those answers and I'll see what else I can add. Otherwise, thanks for the feedback!

**Comment by athanhat** [comment]
Hi Steve, thank you for your prompt reply on the issues I mentioned. This is some more feedback after testing again.

1. No Intellisense at initial Interactive Window in IPython mode
I have not reported a complete absense of intellisense in IPython interactive window. I said there is a problem on auto-completion. It fails to find the names of Classes or functions I have defined in my module. Pressing <Enter> is completely irrelevant, for example I can send my code immediately with <Ctrl+Enter>. 

But as  I tried this again, it seems the bug is also inconsistent, sometimes Intellisense auto-completion does include names of newly defined identifiers the first time you type them, and if you try again a second time, in the same window they disappear. This is very confusing !

3. IntelliSense completes names you didn't intend
Let me make this more clear. I am not talking about pressing a key configured to commit the current completion. I am referring to the case that you reach the end of a fully typed word, i.e. identifier, and you attempt to open the left parenthesis (. If the name of your identifier is not in the auto-completion list, it is replaced automatically with the closest it found. For example I have sent a Person class and Intellisense fails to include the class name in its auto-completion list. Then as you type me = Person(, it will replace it with e.g. PermissionError(. It is a bit annoying because in that case I have to press `Escape` to end auto-completion.

**Comment by zooba** [comment]
1. I think you've hit a bug that we fixed in 15.3. Once you update to the next version, try this again and let us know if you're still having that problem.

2. Yep, this is one of the reasons you may want it. Python's normal interactive window does not support multiple statements at a time.

3. What you describe is exactly what I was describing. If you remove the left parenthesis from the option I mentioned, then when you press it you won't commit the selected word and it will leave exactly what you typed.

I don't understand the very last line, unless this is related to one of the bugs causing items to be missing in the interactive window. As I said, once you've updated to 15.3 (not quite released yet, but we're very close, or you can install [Visual Studio Preview](https://visualstudio.com/vs/preview)) please try these again and see if we have already fixed them.

**Comment by athanhat** [comment]
Regarding to 1 and 3 it seems to me there is a bug as you acknowledge too. Especially the bug I report in (3) is consistent and it appears only when IPython mode is enabled, this is the meaning of my last sentence there. I will be waiting for VS 15.3 to test again and let you know. Meantime shouldn't this issue tagged with the bug label ?

**Comment by zooba** [comment]
Since we believe the bug is fixed, there's no need to tag this. When we confirm there is a bug that needs attention, it will be tagged, and when we commit to fixing it for a certain release then it will get a milestone. If this is actually a bug, but we already have other issues for those bugs, then we'll close this as a duplicate (unless it adds significant new information, in which case we may close the existing ones).

If the bug is already fixed, this issue will be closed. Until then, this is just a discussion (this is our process - it isn't necessarily going to be the same as for other projects).
