### ISSUE TITLE
Create IronPython2.7 virtual environment in Visual Studio 2015 fails

### ISSUE THREAD

**Issue by Prodigio** [Microsoft/PTVS#2901]
I'm trying to create an virtual environment in Visual Studio 2015 by right-clicking on Python Environments in my Python Project. But it ends with an error:

```
> Unhandled exception:
> Traceback (most recent call last):
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 13, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\exceptions.py", line 6, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 701, in <module>
>      File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 692, in exec_
> AttributeError: 'module' object has no attribute '_getframe'
> System.InvalidOperationException: Virtual environment was not created at 'C:\Users\Fred\Documents\Visual Studio 2015\Projects\Marty\MartyPython\env\'
>    at Microsoft.PythonTools.Project.VirtualEnv.<CreateAndInstallDependencies>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__148.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
```

This line: `AttributeError: 'module' object has no attribute '_getframe'` was leading me to set `-X:FullFrames` or `-X:Frames` in Visual Studio 2015 `Options > Python Tools > Interactive Windows > Interpreter Options` (for IronPython2.7). Unfortunately it doesn't work.

How to solve this? Am I missing something?

**Comment by zooba** [comment]
Ultimately, the answer is that IronPython does not properly support pip or virtual environments, at least until six removes their (unnecessary) dependency on `sys._getframe`, and Visual Studio doesn't have the ability to always include the `-X:Frames` option.

Right now there are too many places where this option needs to be injected specifically for IronPython, and they are in places where we don't necessarily know that it's IronPython (and we don't want to add the if statements everywhere). There isn't one central way to do it yet, and if there was it would by necessity have to affect everything, including debugging your own code.

This is also a relatively uncommon problem, and so higher priorities have been keeping us from adding specific workarounds. We _have_ submitted bug reports and patches to fix the underlying projects, but they are waiting on the other projects to adopt them and there's nothing more we can do right now.

Your best workaround is to switch to a console window and run the operations from there. Once you've created a virtual environment, you can add it by selecting the path in VS and it should work just fine. The problem is only in using IronPython to create it in the first place.

**Comment by Prodigio** [comment]
Alright, thanks for you answer. Will try the workaround.
