### ISSUE TITLE
Any way use PTVS without Experimental Instance

### ISSUE THREAD

**Issue by amos402** [Microsoft/PTVS#2912]
Since 3.0 can't compile the installer, how can I use my building on normal instance,  I tried copy and override the release binaries, but it didn't work.

**Comment by zooba** [comment]
Right now there's unfortunately no easier way than copying the binaries. Because of the timeframe we had to follow when updating for VS 2017, there was no choice but to rely on an internal tool for producing our VSIX files, and changing to use the public tooling now is actually a huge task with very little return from our point-of-view, so it keeps being prioritised lower than other work. New components that we have added are using the public tooling, and their VSIX files should be easy to install normally.

We should write up a guide for manual installation. It will essentially be "start from the layout folder in build output and copy these into your Common7\IDE\Extensions folder, then move certain files to other locations". It's generating the full list of exceptions that is the hard part - I suspect it's only project templates, item templates and MSBuild targets, but there are probably a handful of other files that need to move too. Off the top of my head, I can't think of them all right now.
