### ISSUE TITLE
How does PTVS/VS2013 activate Virtualenv (and how can I set environment variables in the Virtualenv)

### ISSUE THREAD

**Issue by adambrazier** [Microsoft/PTVS#297]
Wrote this over at Codeplex earlier, didn't realise that it was also questions (ie, all discussions) that had moved to Github).

Anyhow, I'm asking about Virtualenv activation because I want to know how to set environment variables for the virtualenv when debugging from Visual Studio 2013.

If it was using activate.bat or the powershell version I could set the environment variables in there, but it doesn't work when debugging from VS, so presumably it's not executing all of those activation scripts, if any (if I activate the virtualenv in cmd outside Visual Studio, setting the environment variables in activate.bat, it obviously does work, as normal), or else has them cached.

**Comment by zooba** [comment]
We don't "activate" the environment in the activate.bat sense because whenever we run Python from VS we use the full path.

If you're on the latest version of PTVS, you can set environment variables under project properties for when you run your projects. We don't currently have a way to set variables for a specific environment - they're attached to the project. (This is a little unfortunate if you want to set PYTHONPATH differently for different environments, as using Search Paths will keep them the same.)

**Comment by adambrazier** [comment]
Aha, OK (and setting at the project level is perfect for this use case). Hadn't seen that before (but have only just switched to 2.2 so if it wasn't present before that'd explain why I missed it). Obviously per-environment would be better in some cases, but it doesn't make any difference to me, here.

Thanks very much!
