### ISSUE TITLE
[Mixed Mode] Step over os.path.join steps in instead of over from inside a function

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#3]
**Pre-requisites:**
- Mixed Mode Debugging enabled
- Debug Python 2.7 Interpreter

**Repro script**

``` python
import os

foo = os.path.join("foo", "bar")   # (1) Step over this line

def some_func():
    foo = os.path.join("foo", "bar")   # (2) Step over this line

some_func()
```

Stepping over (1) works, but stepping over (2) ends up inside the middle of `os.path.join()` inside of ntpath.py.

**Comment by zjturner** [comment]
Any idea if this will make the 2.2 release?  It seems kind of serious that stepping over steps into, so it would be great if this coudl be fixed.

**Comment by int19h** [comment]
It doesn't meet our bar at this point (basically, not a crash nor a major regression), especially as it has the obvious workaround of just stepping out right away. I would be more worried if we had a case where stepping in would step over instead, since that one is harder to work around ...

In general, I'm aware that there are some issues around stepping in some corner cases - this is mainly because figuring out where a step ends, when there are potentially interleaving native frames, is kinda tricky (the "double step" bug, where you occasionally have to do Step Over twice to actually step over, is in the same category and has the same underlying root cause). This is something that I'd like to tackle eventually, but it'll have to wait until we get another chance to do sweeping bug fixes.

**Comment by zjturner** [comment]
Any particular reason this is a wontfix?

**Comment by zooba** [comment]
We have made a number of changes that may affect it since it was filed, and don't have any easy way to validate it. The issue has sat quietly for years, so as part of our cleanup we have to assume that we won't get to it.

If you still see it occurring on VS 2017 Update 15.4 Preview, please let us know and we'll reopen.
