### ISSUE TITLE
How do you install this for VS2017?

### ISSUE THREAD

**Issue by griffin2000** [Microsoft/PTVS#3042]
The readme.md says Python was included in the main VS2017 installer but it was removed in the RC: 
https://blogs.msdn.microsoft.com/visualstudio/2017/01/27/update-to-visual-studio-2017-release-candidate/

Is it possible to install this on VS 2017? Or failing that could the readme.md get updated to show that it is no longer supported.

**Comment by int19h** [comment]
Yes, it is possible to install this on VS 2017 - in fact, the most recent bits are only available in VS 2017 at this point. You just need to make sure that you're installing a recent version of VS, since Python is only available from 15.2 on:

https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes
