### ISSUE TITLE
Some tests do not appear in VS 2017 that do appear in 2015.

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/PTVS#3076]
Our project has a number of tests that use the Python VCR library to record HTTP responses. In VS2015, these tests all appear in the test explorer. However, in VS2017, these tests no longer appear--only regular Python unit tests do. This seriously inhibits our ability to debug into these tests without going back to the old version of VS.

**Comment by zooba** [comment]
From our internal discussion, this seems likely to be because the base class of the tests is in an installed library. We use static MRO analysis to determine if it inherits from `unittest.case.TestCase`, and if that information gets lost (in the completion DB) then we won't accept the test class.

We're planning to completely replace the completion DB with a new approach (already available in 15.4 Preview under a [reg key](https://blogs.msdn.microsoft.com/pythonengineering/2017/08/25/python-updates-in-visual-studio-15-4-preview-1/)) that may resolve it. Since we plan for this to become the main way we handle installed packages, we're not going to investigate too deeply into the existing implementation, but we will keep this open as a reminder to try to make it work better in the new system.
