### ISSUE TITLE
unable to resolve "pyperclip" Intellisense may be missing for this module

### ISSUE THREAD

**Issue by ibigpapa** [Microsoft/PTVS#308]
I've refreshed completion db after using the _python setup.py install_ command for the [Pypi download of pyperclip](https://pypi.python.org/pypi/pyperclip/1.5.11).   The completion db has completed and reports up to date.  I still get the **unable to resolve pyperclip Intellisense may be missing for this module** on the import statement for pyperclip

Diag info too big to paste into here. [PasteBin](http://pastebin.com/w4Y8iQV1)

**Comment by zooba** [comment]
I suspect that it's installed into a .egg file, which we currently aren't able to scan correctly (there's an open feature request for it).

I'd suggest using pip to install the package rather than calling setup.py directly. You should be able to point pip at an extracted sdist to install from source if you need to, or it'll quite happily get the latest version from PyPI automatically.

**Comment by ibigpapa** [comment]
You are correct sir it was installed as a .egg file.  Good to know I'll look into getting it installed with pip instead.  Behind a proxy so it's easier for me to download the package from pypi and install using setup as dealing proxy creds is a pain in the arse

**Comment by zooba** [comment]
Yeah, understandable. FWIW, the pip developers are aware of the issues people have with proxies, but you can remind them again at https://github.com/pypa/pip if you like
