### ISSUE TITLE
Intellisense working in interactive window, but not .py file

### ISSUE THREAD

**Issue by ericcarter122** [Microsoft/PTVS#3083]
The issue is that when typing in the .py file in VS, not everything autocompletes like it does in the interactive window. In the first image, you can see VS autocompletes for the pandas_datareader (as web) library, but then it doesn't properly autocomplete for a datareader object. 

In the third photo, you can see that the autocomplete is working in the interactive window for this object. 

Any suggestions about why it might be working in one place and not the other?

Thanks

![image](https://user-images.githubusercontent.com/26468174/30976048-72ab8658-a439-11e7-95cf-56e15a83b13e.png)

![image](https://user-images.githubusercontent.com/26468174/30976076-88c5e776-a439-11e7-8115-afe9b3c5163f.png)

![image](https://user-images.githubusercontent.com/26468174/30976024-62c2023a-a439-11e7-8c10-521802d84e2b.png)

**Comment by huguesv** [comment]
In the interactive window, completions are usually more accurate because we have a live session where we can query the object to ask which methods it has.

In the regular editor, we don't have any live session, so we analyze the code without running it. That's a much more difficult task with a dynamic language like Python. Some libraries work better than others.
https://github.com/Microsoft/PTVS/issues/3046

In this case it probably depends on how your created your `df` object.

**Comment by zooba** [comment]
Thanks for the report. These are all being tracked under #3046
