### ISSUE TITLE
Cannot create IoT project

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#309]
I have a clean install of the latest VS Community build and I get the following dialog when creating the IoT project.

```
---------------------------
Microsoft Visual Studio
---------------------------
The vstemplate file references the wizard class 
'Microsoft.VisualStudio.WinRT.TemplateWizards.PlatformVersion.Wizard', 
which does not exist in the assembly 
'Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
---------------------------
OK   
---------------------------
```

I haven't installed any of the IoT bits, which may be where the referenced wizard lives? Ideally we would have a better message here.

(Ping @juanyaw)

**Comment by juanyaw** [comment]
yes, it appears this was recently changed to Universal instead of WinRT.  Other templates where fixed today, I'll fix this

**Comment by ELC** [comment]
Solution here:
https://github.com/MonoGame/MonoGame/pull/4999/files

Locate this file: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates\CSharp\Windows Root\Windows UAP\1033\BlankApplication\BlankApplication.vstemplate

(In my case was 3082 instead of 1033)

And delete these lines:
<WizardExtension>
    <Assembly>Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName> Microsoft.VisualStudio.WinRT.TemplateWizards.ApplicationInsights.Wizard </FullClassName>
</WizardExtension>
