### ISSUE TITLE
Debugging debug-version of Python crashes

### ISSUE THREAD

**Issue by Bananacoder** [Microsoft/PTVS#3152]
Hello,

I compiled my own Python binary with VS20**15** (x64 and **debug**) and need to debug my Python source. I use the following code and after executing the script and attaching the process to Visual Studio.

    import ptvsd
    ptvsd.enable_attach(None)

    ... my python code...

After my script is executed my process crashes while cleaning up some stuff. I am sure this is related to the fact that my Python version is a debug version (since the same attempt works flawless with my self-compiled release version of Python). Can I, or do I have to tell ptvsd somewhere that the attached Python version is a debug version? Any ideas? Thanks a lot!

Python Version: 2.7 debug x64

PTVSD Version: 3.2.1.0

Visual Studio Version: 2015

**Comment by zooba** [comment]
Firstly you'll need to use `ptvsd==2.2.0`, as that is the version matched to VS 2015 (assuming you have installed the latest available PTVS installer for it). The newest `ptvsd` is only for the latest update of Visual Studio 2017.

But since `ptvsd` is entirely pure Python, there should not be any problem using a custom build. You may want to use a second copy of Visual Studio to attach the native debugger to the Python process and see what happens when it crashes - because the debuggers are not the same, you can connect using `ptvsd` to a `python.exe` that is being debugged already.

If that doesn't help, we'd need to see at least an error message and ideally a full stack trace of the crash to have any hope of making suggestions. It's not easy to help when we don't know what you've built or why it isn't working :)
