### ISSUE TITLE
Test framework has trouble printing utf8 char

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#3177]
def test_utf8Char(self):
        print '\xc5'

Test works when I run it directly. However, in the Test framework (e.g. Test Explorer, right click on test) it fails with the error: "Message: 'utf8' codec can't decode byte 0xc5 in position 0: unexpected end of data"

Regards.

VS pro 2017 version 15.4.0. Python 2.7.13

**Comment by zooba** [comment]
To be clear, that isn't a UTF-8 character you're printing there. If you want to test encoding/decoding, I'd suggest using `'\xc5'.decode('utf-8')`, as then it is not dependent on ambient state (and will always fail, since it is not a UTF-8 character).

I don't think we should make any changes to our test adapter to "handle" this case.
