### ISSUE TITLE
Assertion failed while scraping a .pyd library

### ISSUE THREAD

**Issue by jesse82** [Microsoft/PTVS#3183]
I have attempted to compile and test the latest version of PTVS to test the new scraping method.

Currently it throws an "Assertion failed" message when trying to load the .pyd file
![capture](https://user-images.githubusercontent.com/26267556/31787662-712009a6-b4da-11e7-8407-391dd0f4fdc1.PNG)

I should note that I do not think its possible to load these libraries in general, they are from an API and meant to be run inside the .exe

Trying to load them from a Python cmd line gives:

 ```
# trying C:\Python34\lib\site-packages\NXOpen.pyd 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1715, in load_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by zooba** [comment]
Thanks for trying it out! Right now the assertion is there just to be extra noisy when scraping fails, but as it settles down we'll stop popping it up. Since you can't import the module manually either, it's obviously just one that we'll have to skip, though if you know a way to make it work (e.g. by importing another module first) you can add that into the `initial_import` function in `scrape_module.py` (like we already have for `win32ui` and `tkinter`).

Also, when you get a popup like this, you can press Ctrl+C to copy the full text of the dialog and paste it directly. There's no need to use screenshots.

**Comment by jesse82** [comment]
Hi, thanks for the reply, sorry for the kind of dumb question, but your response did help me down the right path!

After playing with dependency walker and getting a bunch of DLLs in the same folder as the .pyd, it works!
The auto complete and function description popups are showing up perfectly.

Between this and the ability to debug in mixed mode (attaching to the .exe) PTVS is a really great tool.
Thanks for you work on this,

-Jesse
