### ISSUE TITLE
How to delete the tcp listening after enable_attach?

### ISSUE THREAD

**Issue by naeco2008** [Microsoft/PTVS#3230]
Hi, 

if i enable attach with PTVSD, a tcp listener will be created on the given port. My question is if there is someway to delete the tcp listener to release the port?

Thanks, 
-Neil

**Comment by zooba** [comment]
I don't think so right now - enabling attach is a bit of a one-way operation. @int19h may have a better suggestion (once he's back from vacation), and we'll take it on board as something we'd like to support in the next iteration of our debugger.

**Comment by naeco2008** [comment]
@zooba, thanks for your reply. 

Another question is about PTVSD compatibility. I plan to embed ptvsd (3.0.0) into my program (C++ based), so that the customers can debug the Python scripts based on my program Python libries in VSCode. The problem is if the ptvsd i embed into my program does not match that in vscode (or vs2015/2017 etc), the debug will not work. Do you have some advice about how to resolve this issue? Why do you not keep ptvsd compatible with other versions?

Thanks, 
-Neil

**Comment by zooba** [comment]
Long term we are going to keep it compatible between versions, but to get to that point we've had to make breaking changes. In particular, we didn't have any sensible way to maintain the old binary protocol (with all its security issues that we were getting in trouble for) and the newer JSON protocol. We also didn't have time to do the full conversion to a standard JSON protocol, so that work is still ongoing, but once we get there then we should be good forwards/backwards (for some minimum version of the tools).

VSCode is simpler right now, as you can basically assume that users have the latest version of it. If you want to support VS 2015 and VS 2017, I'd suggest embedding multiple copies and having some way for users to select (e.g. an environment variable, and then you import ptvsd from a different location at runtime).

This sort of use was not one of our requirements, so we didn't really design well for it. Initially (6-7 years ago) we never even thought people would use ptvsd separately from VS (remote debugging was added later), so versioning between different installers was not a concern. We're slowly catching up, but it's hard to just do everything all at once :)

**Comment by naeco2008** [comment]
Thanks @zooba for the help!
