### ISSUE TITLE
[NoDatabaseFactory] Cross-path Intellisense can't detect information about functions and variables

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#3276]
Branching this off from #3248.  The issue described at #3248 involves the default installation configuration.  In that scenario, when you import something that isn't in the current project and is not from a system library, there is no IntelliSense.

Upon enabling `NoDatabaseFactory`, this is better but not quite solved.  See this screenshot.  Note the active file is from the `llvm` project, and has a search path pointing to the `lit` project.

![screen2](https://user-images.githubusercontent.com/11823433/32389768-005e78b4-c089-11e7-9b33-3701a828a83b.png)

Notice here that now `FindTool` and `ToolSubst` are colored (compare to screenshot in #3248), and it properly detects that these are classes and I get Intellisense from them.  But as you can see, `llvm_config` finds no completions.

If I do this same thing from a file that is inside the `lit` project, everything works.  See here:
![screen1](https://user-images.githubusercontent.com/11823433/32389767-004e65be-c089-11e7-8916-79da78323236.png)

Here we are inside of `config.py` which is included in the same project, so I get completion.

**Comment by zooba** [comment]
@MikhailArkhipov This bug covers the improvements to `AstFunctionAnalysisWalker` we discussed.

Looking at that class, the first thing to implement is `AssignStatement` so that functions that return a local variable also work, and then I'd consider having one level of lazy calls for functions in the current module that haven't been analyzed yet. That way the process (in `AstAnalysisWalker`) can look like:

* collect top-level names (already implemented)
* walk each function to determine return type (already implemented)
* resolve each lazy function call result (not yet implemented)
