### ISSUE TITLE
Interactive Console stops running code from CTRL+E, CTRL+E periodically with VS2017

### ISSUE THREAD

**Issue by lcorrigan** [microsoft/PTVS#3386]
Using VS2017 Pro on Win10x64, IronPython 2.7.5, CPython 2.7 - both x32 bit.
After an unpredictable amount of time, the act of running lines of code in the interactive console, with CTRL+E, CTRL+E, has no effect.  It probably happens at least 1 time for every hour of coding.  It's not that it won't just print variables or 'print' statements, but doesn't actually run the code.  I've gotten into the habit of doing a small print statement to wake it up - if you type directly into the Interactive Console, it becomes responsive again.  I've been using VS2017 + PTVS since VS2017 came out and it's always done it on 3 machines.  I've never had this in the VS2015 version.

**Comment by lcorrigan** [comment]
Just learned that when I get in this state, issuing the commands from CTRL+Enter work!
I only learned about this way of running script lines a few weeks ago and have been programmed to use (CTRL+E) x 2 for so long, I never think of using CTRL+Enter.

**Comment by zooba** [comment]
Does this happen when you've selected text in the interactive window?

We had a bug (that we've fixed for the next version) where if you put the cursor in a read-only area then we would not move it back to the input. Then when we tried to insert the text the editor would silently ignore it (because it's read-only) and nothing would happen. Clicking back into the input area first should make it work again.

If you're seeing a different problem to this, we'll need more information to track it down (maybe some screenshots or a video? You can use the record feature in Help/Send Feedback/Report a Problem to report it that way).

**Comment by lcorrigan** [comment]
@zooba I'm not selecting text in the interactive window. I was selecting one or more lines of text in a .py file in the editor window that was part of my project, and then pressing CTRL+E, CLTR+E to run them in the interactive console.  Although I can't make the issue happen at will, I did try my action after putting my interactive console cursor in a read-only area.  It didn't cause the issue to happen.  I'd like to add, regarding my last comment, that the workaround I found of using CTRL+Enter to run code when my issue occurs, doesn't always work.  I've also seen this happen when using a) IronPython, b) CPython. I typically have my project selected as the Interactive window Environment target.  I've attached my VS PTVS diagnostics if that helps.  I will try to capture the lack of output error in a video when it happens again.  I've got win7 and win10 machines and seen this happen on both.  The attached is from my win10.
[Diagnostic Info 2017-11-29T112401.zip](https://github.com/Microsoft/PTVS/files/1514554/Diagnostic.Info.2017-11-29T112401.zip)
