### ISSUE TITLE
Missing analysis colorization

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3394]
When i open an existing project, I often am missing colorization (imported modules are not purple).
I wait for a while and they still don't appear.
Doesn't happen all the time, but it's frequent enough.

Workaround is to scroll down and up, and then colors appear.

![image](https://user-images.githubusercontent.com/1696845/33284431-ee80eeb8-d363-11e7-96e4-fbb45d89aaf4.png)

**Comment by zooba** [comment]
I have a partial fix for this in a bigger change (see my typeshed branch), but it’s probably worth someone taking a closer look at it sooner. I think there’s a race between the classifier being created and the first analysis of the file.

**Comment by zooba** [comment]
This is super hard to track down... I think it's a race-condition between the classifier triggering and our transfer from the old (default) analyzer and the new (project) analyzer. This race can show up with issues in multiple places, so it's not trivial to fix.

I'm not sure we can get around connecting the editor to the default analyzer without breaking the not-in-a-project case. VS doesn't give us any real indication that I'm aware of when a file is being opened as part of a project that hasn't actually loaded yet (since if it had, we'd have had the correct analyzer already). We may just need to hit all the open editor windows harder when the analyzer changes to make sure they have the latest info.
