### ISSUE TITLE
Cannot debug files without extension

### ISSUE THREAD

**Issue by mkwiczalayandex** [Microsoft/PTVS#347]
Hi,

How can I debug files without extension?

I have huge python repo some of files has *.py extension (i.e. file_name.py) some of them are without extension (i.e. file_name). Renaming file_name to file_name.py it is not an option...

Currently I cannot debug files without extension neither locally nor remotely (https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging).  

On local machine I do not know how to start debug session.
On remote Linux machine I can attach to python script but breakpoints, break_into_debugger do not work. 

Regards,
Mariusz

**Comment by int19h** [comment]
For local debugging, is your problem that you cannot set the extension-less file as a startup file in your project? It won't have the "Set as Startup" command in the context menu in Solution Explorer, but you can still go into project properties, and on the General tab you can specify the startup file by typing in the name. 

For remote case, I find it really interesting that `break_into_debugger` would fail. Can you describe what exactly happens in that case? Does it simply not break, or you're not getting a call stack when it does? Also, what happens if you use Debug -> Break All?

Also, can you clarify which version of PTVS you're using?

**Comment by mkwiczalayandex** [comment]
Thank you for answer.

To reproduce this you may follow steps and use python file from https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging - just use file name without extension. 

Local debugging:
I setup startup file in General Tab started debugging (press F5) but breakpoints do not works. "Debug->Break All" does not nothing as well.

Remote debugging:
break_into_debugger - nothing happen program does not stop execution
Debug->Break All - nothing happen program does not stop execution
breakpoints - do not work

It works fine (local, remote debugging) when file has extension.
My configuration:
Windows 7, Visual Studio Express 2013 for desktop Update 4
Python Tools for Visual Studio   2.1.21008.00

Regards,
Mariusz

**Comment by int19h** [comment]
Ah, I see the problem now. Because VS supports debugging using multiple languages at the same time, it uses file extension associations to route the breakpoint request properly. Because an extension-less file is not considered to be Python by default, the breakpoint is not treated as a Python breakpoint.

You can change this by right-clicking the file in Solution Explorer, clicking "Open With", selecting "Python Editor" in the list, and clicking "Set as Default". The immediate effect is that the file will be opened in the Python editor from there on (so you get syntax highlighting, completions etc). But it also has the subtle side effect of telling the debugger that this file is associated with the Python debug engine, and the latter will receive breakpoints now.

Note that this is a VS-wide, global setting - i.e. there's no way to treat extension-less files as Python files in Python projects only, unfortunately.
