### ISSUE TITLE
Refresh DB does not complete fully with Python 2.7 based environment

### ISSUE THREAD

**Issue by fabio86d** [Microsoft/PTVS#3507]
I have Visual Studio 2015 with PTVS. I use Anaconda3. I have generated with conda two different virtual environments, one based on Python 2.7 and one based on Python 3.5. When creating the Python environments on VS with "Custom" and refreshing DB as requested, the one based on Python 3.5 runs successfully until the end, while the one based on Python 2.7 gets stuck almost at the beginning of the DB refresh.

Why does this happen? How could I solve this issue? I need to use Python 2.7 for my VS project. 

My Diagnostic info are:I have Visual Studio 2015 with PTVS. I use Anaconda3. I have generated with conda two different virtual environments, one based on Python 2.7 and one based on Python 3.5. When creating the Python environments on VS with "Custom" and refreshing DB as requested, the one based on Python 3.5 runs successfully until the end, while the one based on Python 2.7 gets stuck almost at the beginning of the DB refresh.

Why does this happen? How could I solve this issue? I need to use Python 2.7 for my VS project. 

My Diagnostic info are:

**Comment by fabio86d** [comment]
Diagnostic info https://pastebin.com/sRzTDkhk

**Comment by zooba** [comment]
It appears to be crashing for some reason, but we don't have enough information from that log. Best I can suggest is to try uninstalling packages until it works, but with Anaconda that's not a great suggestion as there are so many :)

However, there's a good chance this issue has been fixed in Visual Studio 2017. Since we're not updating the older version's Python support anymore, the best solution is to upgrade to the latest release.

**Comment by huguesv** [comment]
Closing since this is no longer applicable in latest release.
