### ISSUE TITLE
Multiple analyzer processes and interactive windows started on project change

### ISSUE THREAD

**Issue by lcorrigan** [microsoft/PTVS#3545]
My PTVS / VS2017 has gotten itself into a state where it opens a new interactive window and a new PythonTools.Analyzer.exe process every time it senses a project save change and I send a few lines of code to the (current?) interactive ironpython console.  See attached graphic. It can be cause by simply adding a new line to a file and issuing a CTRL+SHIFT+S to save all.  A message in the interactive window says: "The associated project 'Vjenkins' has changed its configuration. These changes will not be reflected until you reset this interactive window."  When you run a few lines with CTRL+E+E or CTRL+ENTER, it opens a new window and a new background analyzer process.  

I spent a full day a few weeks ago, removing _everything_ related to VS2015, VS2017 and PTVS (all registry items / hidden folders/databases etc) because the analyzer was killing the PC and intellisense was pretty much dead for project code.  Seems to be heading there again.  This time I only have VS2017, PTVS and no CPython installed - just IronPython. I.e.: Pretty clean.

![capture](https://user-images.githubusercontent.com/12451259/34782452-b97374f6-f5f6-11e7-9151-9ab4efd44962.PNG)

**Comment by huguesv** [comment]
Thanks.

This message is intended to appear when the active interpreter is changed, or when search paths are changed.

It's normal to have one analyzer per interactive window, and from your screenshot you seem to have a lot of them open. So that part might be ok. Note that you can show the 'Command Line' in Task Manager (right click on list header and click Select Columns). It's a pretty long command line for the analyzer, but its arguments will tell you what each one is for (you'll know if they are all for different interactive windows).

I tested with our latest sources and I'm not seeing that message come up just by saving all files. I'll check with 15.5 when I get a chance.

**Comment by zooba** [comment]
IIRC, we use the interpreter ID and the project path to find an existing window. If there's something in the project path that isn't comparing properly, that may do it. Or if there's something in the configuration that doesn't save properly (virtual environment related perhaps?) that could cause the "configuration changed" message.

We have a fairly long-standing idea to make targeting interactive windows a manual option rather than trying to be clever about it. That would help here.

**Comment by lcorrigan** [comment]
Hi guys,  I'm not using a virtual env, and my colleages are not having this issue with the same project in VS2015.  Here is a workaround I've found.  I don't know how much of these steps apply, but this combo has me running smoothly with fast Intellisense and no console auto-creation actions - like my past life with VS2015 PTVS. For context, all of our custom .NET .dlls and and importer scripts, are in the project directory:
1. Cleaned out CompletionDB folder.
2. Stop using the Console Environment option drop down to '[project]' and instead, only use the IronPython 2.7 32bit option for the Console.
3. Created a console startup file in C:\Users\lcorrigan\Documents\Visual Studio 2017\Python Scripts\IronPython 2.7 (32-bit).  The file just imports os and then os.chdir("To our Project root dir").

From this point, I can change things in the editor and save them, and keep running snippets of my editor code without VS firing off new Consoles or telling me the current one is no longer valid.  Technically, only the code I touched is invalid to the interpreter at that point, so at least I'm back in control of when to reset the Console.  
Cheers.

**Comment by lcorrigan** [comment]
Would anyone happen to know how I might be able to get the path of the current project or (or maybe solution?) that the IDE had open when it starts the Console? I'd like to make my workaround a little more flexible by having the startup script do something like: os.chdir("%CURRENT_SOLUTION%) etc.

**Comment by geographika** [comment]
I had the same issue with multiple interactive windows opening each time a script was run. 
Removing "." from my Search Paths for the project meant running a script reused the Interactive Window each time rather than creating a new one.
