### ISSUE TITLE
PreBuild Events 

### ISSUE THREAD

**Issue by JackGrinningCat** [Microsoft/PTVS#3580]
Hey,

first things first. Thanks for your efforts. My colleague is working with an python/unix environment and is using his know tools to provide data. Without your work, I would need to work around. 
But because you provided this environment I could easily made an proof of concept within a day.

After i beat our proxy iron wall and installed all needed packages I did get comfortable and wanted to automate build steps for googles protocol buffers.

I need to regenerate the python code and I'm pretty used to the Pre-Built steps from C#/C++ project.
But there was none in this project properties. 
I helped myself with an other c# project which does it now. But to be sure i tried to set a build dependency. I could not do it. 

Well, that's all. Not an issue, more a feature request. :-)
Pre-built Steps and/or Project dependencies

Chris

**Comment by zooba** [comment]
So you should be able to use a project dependency to a C++ project or C# project, and this will enable build.

I suspect solution build dependencies are not available because Python projects do not support building by default, but you can enable it by editing the `.pyproj` file directly (there are comments). Once you've done this, you can also implement before/after build steps directly in that file and they should work just like any other MSBuild-based project - we simply don't have UI for it because very few people have the need.
