### ISSUE TITLE
Error creating virtual env when picking anaconda as base intepreter

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3622]
Filing this for awareness. AFAIK this is fixed for the next release of Anaconda (they will have ensurepip).

```
Virtual environment is being created at 'c:\users\huvalo\source\repos\BottleWebProject1\BottleWebProject1\env'
Error: Command '['c:\\users\\huvalo\\source\\repos\\BottleWebProject1\\BottleWebProject1\\env\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Virtual environment was not created at 'c:\users\huvalo\source\repos\BottleWebProject1\BottleWebProject1\env'. Exit code: 1
Virtual environment was not created at 'c:\users\huvalo\source\repos\BottleWebProject1\BottleWebProject1\env'
```

Workarounds:
- Pick CPython as a base instead of Anaconda
OR
- After you get the error, pick Add Existing Virtual Environment and select the environment folder (it will exist despite the error).
- Right click the environment and select Install Package, this will open environments window
- Click the "download and install pip package manager link"

**Comment by zooba** [comment]
Is it using `venv` to create the environment or `virtualenv`? If the latter, `virtualenv` doesn't copy all the required DLLs (even for CPython), so that may be another issue.

Perhaps we should make it use `conda` by default when we can? So use `conda` -> `virtualenv` -> `venv` as the priority list (and if you _really_ want a regular virtual environment from Anaconda, you can do it from the console and add it).

**Comment by zooba** [comment]
(For precedent, we already don't let you select `venv` when `virtualenv` is installed, and we don't let you enable `with-system-site-packages` from the UI.)

**Comment by huguesv** [comment]
I verified that this is no longer an issue with Anaconda 5.1.
