### ISSUE TITLE
iPython Interactive Window Hanging, Crashing, or Occasionally Crashing Visual Studio

### ISSUE THREAD

**Issue by RGAlexander216** [Microsoft/PTVS#3652]
Let me know what information you need from me, but every single time, no matter which python environment I use, the issue described in the Subject is occurring.

it crashes when I import anything (including the standard library). I have no idea where to begin, but apparently I'm the only one that's having this issue.

**Comment by zooba** [comment]
Could you open Tools, Python, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

Generally this issue comes up because of either a misconfigured environment, or recently if you've done something unusual with your Documents folder like moving it to a removable drive (if it's the latter, we've fixed it for the next release already).

**Comment by RGAlexander216** [comment]
Actually, you started this issue here: #3528. I found that today. The preview version also forwarded the problem for me. I'm closing this.
