### ISSUE TITLE
Fail to launch python debugger from Visual Studio

### ISSUE THREAD

**Issue by emiliavanderwerf** [Microsoft/PTVS#3653]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

**Comment by int19h** [comment]
Could you tell more about what kind of Python you're using? It looks like yours is missing `ctypes`, which is a standard Python module.

**Comment by emiliavanderwerf** [comment]
Sure. I'm using Python 3.6.4 installed from https://www.python.org/downloads/release/python-364/. I downloaded the following installer: Windows x86-64 executable installer

I uninstalled Python and Visual Studio and reinstalled them both in order to try to fix this issue. However, this didn't seem to work. If I'm missing `ctypes`, I do need to uninstall & reinstall C/C++?

I did not intentionally delete `ctypes` from my computer.

**Comment by emiliavanderwerf** [comment]
Now that I have reinstalled and the traceback looks like this:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Users\emili\AppData\Local\Programs\Python\Python36\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .

I ran a recursive list of all of the files in C:\Users\emili\AppData\Local\Programs\Python\Python36\Lib\ctypes. Does that help?
[ListOfFilesInCtypesDir.txt](https://github.com/Microsoft/PTVS/files/1671183/ListOfFilesInCtypesDir.txt)

**Comment by zooba** [comment]
The `_ctypes.pyd` file (which will be in `Python36\DLLs`) appears to have a problem, it kind of looks like it's loading the wrong version.

Do you get a similar error message if you run Python directly and type `import ctypes`? If so, we're probably looking at either registry or environment corruption, and I'm guessing the latter. Check your `PATH`, `PYTHONHOME` and `PYTHONPATH` variables to see whether (a) they are set, and (b) they are pointing to a different Python install. If so, you can clear `PYTHONHOME` and `PYTHONPATH` (they don't need to be set) and if any directories in `PATH` include a different `_ctypes.pyd` then you'll either want to remove them or clean it up - depending on how it got there.

Since it's loading the right `ctypes\__init__.py` file, my guess is there's something in `PATH`. If not, and the other variables aren't being problems, we can check out if there's anything in your registry that shouldn't be there.

**Comment by huguesv** [comment]
This is likely due to a broken virtual environment. Please see my comment in https://github.com/Microsoft/PTVS/issues/3668.
