### ISSUE TITLE
Allow disabling Quick Info

### ISSUE THREAD

**Issue by dwkrueger2** [microsoft/PTVS#3716]
The location of the pop up intellisense tool tips are painfully located and drastically interfere with the product.  There are numerous requests for a fix on this problem on multiple coding help sites (stack overflow etc...).... I just happend upon the repository for this product when there was a sudden error that popped up when I was using the python tools in Visual Studio.

--The quick fixes... (for those in the know on addin programming)
1) Move the hover offset to a better location and do a bit of usability testing on it.  I suggest it moves at least 15 pixels to the right so that it is not right under the curser... Personally it would be better to offset it 15 to the right and nearly always above the cursor because most of the time we are programming in downward motion/vision... so that means the pop up obstructs the view.
2) Add the option to turn off the hover pop ups... I know this is possible because I've seen the options on  other text editor add ins... This needs to be under the options-->Text Editor --> python menu item.

It'd be cool it this gets resolved.
+

**Comment by zooba** [comment]
Thanks for dropping in! I have a feeling I was just looking at your report on Developer Community yesterday (searching for the duplicate, actually, but got distracted...)

We've made one really helpful change here for the next release already (which you can try at https://visualstudio.com/vs/preview) by no longer showing the contents of string literals in the tooltip. That deals with the unnecessarily huge tooltips. I don't believe we have the ability to adjust the location (as a language service, we're merely extending what VS provides and it is responsible for the tooltip itself), but I agree it would be better to go above the line containing the applicable span rather than below or over it.

It would certainly be possible for us to disable tooltips completely, so I'll rename this issue to reflect that being the problem to solve here.

**Comment by dwkrueger2** [comment]
Thanks for the feed back and categorizing this better. Ill Check out the preview.  Glad to Know someones working on this.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/194700/disable-pop-up.html

**Comment by dwkrueger2** [comment]
One more comment... You stated that " I don't believe we have the ability to adjust the location"

The tool tips in different add in's have different characteristics that look a lot like .css ... Someone made the background grey and set the font and font color... So I suspect there is a setting somewhere

**Comment by zooba** [comment]
We can add any arbitrary WPF control as the contents of the tooltip, so that allows for formatting, but the IDE is responsible for calculating the size and location (which I know because we had to work with one of the core teams to fix a bug a couple years back if there was too much content to fit on the screen).

**Comment by ellisonch** [comment]
I'd also like to disable the tooltips, or at least add a delay to them showing up.  I'm having the problem that they're appearing underneath my cursor (and even chase my cursor if i try to move out of its way), preventing me from clicking on identifiers that show large tooltips.
