### ISSUE TITLE
How can I use build a pyproj project on TFS build server

### ISSUE THREAD

**Issue by zeeLondon** [Microsoft/PTVS#3840]
Hi 

How can I build a python project on TFS build server?

Is there a install available that will install all the build targets?

Cheers

**Comment by zooba** [comment]
Coincidentally, just yesterday I checked in some changes to the [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017) installer so that it will include the core set of Python targets and tasks (by default - it isn't an option, they're just there). This will become available in 15.7 Preview 2, and then release in 15.7.

Note that it doesn't install any versions of Python itself, so you'll still need to do that while setting up your build servers, but it should ensure that running `msbuild` on a solution that includes `.pyproj` projects will work just like when you've installed the Python workload.

Once we have the preview out (and it'll be a few weeks at least, as we haven't even released 15.7 Preview 1 yet), we'd love if you could give it a try and let us know how it goes. You can report feedback here, and since this will be the first release we intend to be very active about fixing issues.

**Comment by zooba** [comment]
The updated build tools are now available. If you install those on your build server, you will get the required targets.

Note that we generally recommend running Python tools (such as `pytest`) directly rather than trying to do it via Visual Studio, as you'll get a much better experience that way.
