### ISSUE TITLE
When Run Django (python 3.6) project Visual Studio 2017 IDE closes automatically

### ISSUE THREAD

**Issue by dgopikumar** [Microsoft/PTVS#3859]
I have installed VisualStudio2017  with python option enabled.    I am trying to migrate my existing Django project (python 2.7)  to python 3.6 . The solution build successfully in visual studio 2017 but when i am running the application (F5)  ,  python exe opens but not executing & shows black screen and also Visual studio closes automatically.

**I have  same issue in visual studio 2013 (python 2.7) , That's why i am trying to migrate to Visual Studio 2017.  But the issue i had faced not solved.** 

![image](https://user-images.githubusercontent.com/15888260/37243516-8cc7e616-24a0-11e8-97a1-572c92161690.png)

**Comment by zooba** [comment]
Welcome! Sorry for the trouble you are having.

Could you try running your application with Ctrl+F5? This will run without our debugger enabled, which sometimes reveals problems that you otherwise wouldn't get to see. That may help us understand what is going on.

Also, please let us know if you have enabled any Experimental options, as those could have an impact.
