### ISSUE TITLE
Intall python package from GUI

### ISSUE THREAD

**Issue by subhasis789** [Microsoft/PTVS#3860]
When I try to install python package by right click on environment it gives me the below error.

Any suggestion for this?
----- Installing 'PyPDF2' -----
Collecting PyPDF2
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002101EBFDB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /simple/pypdf2/

**Comment by zooba** [comment]
@subhasis789 Do you have an internal proxy that needs to be configured? See [this answer](https://stackoverflow.com/a/22229387/891) for help doing that.

Otherwise, this would seem to suggest that you either have an old version of `pip` (so try updating it first if you can) or there was a network issue and it is worth trying again.
