### ISSUE TITLE
Missing completions for Os.Path.

### ISSUE THREAD

**Issue by GemmanAster** [Microsoft/PTVS#3876]
When attempting to use the VisualStudio 2017 Python functionality I find that Intellisense does not supply completions for the 'os.path' library--such as 'os.path.isdir()' and so on. It does however provide completions for functions directly from 'os' such as 'os.listdir()'.

If I attempt to switch back to what is apparently the 'old' Intellisense DB completion method I get a crash notification every time I attempt to update the database. It hangs and then crashes at the 'Analysing Standard Library' step no matter how many times I retry this procedure.

Is there some way to include the 'os.path' functions--and perhaps other missing completions--to the 'new' system?

**Comment by zooba** [comment]
We've been working on the crashes in the database analysis (as they also could affect your code), and are hoping to get those updates out soon.

We're also aware of the missing `os.path` completions, and I suspect the problem is due to the weirdness around it not being a real module. We track these issues under #3046, so I'll make a note there.
