### ISSUE TITLE
Wrong Parameter suggestion in IntelliSense when using Decorator

### ISSUE THREAD

**Issue by Bananacoder** [Microsoft/PTVS#388]
Using a decorator with *_args and *_*kwargs as params should display the parameters of bar(), not of the decorator.

``` python
def foo(*args):

    def _foo(fn):

        def __foo(*args, **kwargs):
            fn(*args, **kwargs)

        print("Return callable")
        return __foo

    print("Registered")
    return _foo

@foo("arg")
def bar(a, b, c):
    print("Function called with %i, %i, %i" % a, b, c)

bar(1, 2, 3) # <-- Should show a, b, c in the IntelliSence, not *args, **kwargs
```

**Comment by zooba** [comment]
Actually, since decorators are totally able to change the parameters of a function, we really ought to display what the wrapped function expects.

Though I guess we could try and detect when it's doing simple parameter forwarding, at least when the `@wraps` decorator (or `functools.wrapped`) is used.

**Comment by donelgreeko** [comment]
You mean functools.wraps? Yes, that would also work as a proper workaround.

**Comment by gmonkman** [comment]
Yes, it appears to ignore the expected behaviour of functools.wraps, certainly intellisense isn't displaying the docstring of the decorated function, which is pretty frustrating.
