### ISSUE TITLE
Display version for conda environments

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3906]
![image](https://user-images.githubusercontent.com/1693688/37621425-26e700b0-2b7c-11e8-92ed-fb6c267b1797.png)

With so little information there, it's going to be hard to tell them apart.

The extra fields after Anaconda are auto-generated. Perhaps we should just do that for all environments that don't have enough information, rather than the ones that are ambiguous?

**Comment by huguesv** [comment]
I made it look like the Anaconda entry, I suppose we should change the virtual env entries so they're consistent `env (3.6, 64-bit)` instead of `env (Python 3.6 (64-bit))` but then a virtual env and conda env of same name will look the same and be hard to pick from the Add/Remove environments dialog.

**Comment by zooba** [comment]
I wouldn't worry about that. The virtual env is just copying the description from its base environment into its display name, rather than trying to clarify its own settings (e.g. if you have a custom environment called "MyEnv" then you'll see "env (MyEnv)")
