### ISSUE TITLE
Flask wfastcgi WSGI handler

### ISSUE THREAD

**Issue by jmalik999** [microsoft/PTVS#3947]
My flask app works fine on IIS without flask_admin or flask_security, I get the following message
when I add either flask_admin or flask_security or flask_mail
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\techfiles\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "C:\techfiles\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "C:\techfiles\wfastcgi.py", line 616, in get_wsgi_handler
    raise ValueError('"%s" could not be imported%s' % (handler_name, last_tb))
ValueError: "app.app.wsgi_app" could not be imported: Traceback (most recent call last):
  File "C:\techfiles\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 2, in <module>
    from flask_admin import Admin
ModuleNotFoundError: No module named 'flask_admin'

My web.config file is
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="Techfiles" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Python36-32\python.exe|C:\techfiles\wfastcgi.py" resourceType="Unspecified" />
        
        </handlers>
    </system.webServer>
    <appSettings>
       <!-- Required settings -->
       <add key="WSGI_HANDLER" value="app.app" />
       <add key="PYTHONPATH" value="C:\TECHFILES" />
     </appSettings>
</configuration>
```

**Comment by zooba** [comment]
Hi

The important part of that error message (and thanks for including the whole thing!) is the very last part, where it can't import `flask_admin`.

I'm not sure how you've set up the rest of your project, but I'd first make sure that running `app.py` directly with the same Python interpreter works (or at least gets past that import), as that may indicate that you don't have the extension installed properly.

It also appears that you've made some changes to the file? The error message says `app.app.wsgi_app` but the web.config quote just says `app.app`. Did you perhaps copy from the wrong file?

Sorry for providing more questions than answers - these errors can be a caused by a lot of different things.

**Comment by jmalik999** [comment]
Hi
Yes I copied the wrong file. the actual file is:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="Techfiles" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Python36-32\python.exe|C:\techfiles\wfastcgi.py" resourceType="Unspecified" />
            <add name="TilleyIntra" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\Python36-32\python.exe|C:\inetpub\wwwroot\Theme\wfastcgi.py" resourceType="Unspecified" />
        </handlers>
    </system.webServer>
</configuration>
I uninstalled the extensions and re-installed them 
The bottom message is the same if either I use flask-security or flask-mail
File ".\app.py", line 4, in 
from flask_security import Security, SQLAlchemyUserDatastore, UserMixin, RoleMixin, login_required, current_user, roles_accepted,utils
ModuleNotFoundError: No module named 'flask_security'
