### ISSUE TITLE
Feature request: Please add impersonation support to wfastcgi

### ISSUE THREAD

**Issue by fzzylogic** [Microsoft/PTVS#4018]
Hello all, thanks for PTVS, it's great. If i understand correctly, within a domain, impersonation support in wfastcgi would allow IIS to impersonate the current user, for example when initiating connections to MS SQL, which would in turn allow MS SQL to see incoming connections as the domain user that initiated them, instead of the Application Pool account. PHP's fastcgi has the .impersonate option. Maybe it's hard to do, or a bad idea. Maybe this is already possible using some configuration I'm not aware of and haven't found after days of net scouring. Maybe the approach is wrong and there's a better way. Would appreciate any insights on this.

**Comment by zooba** [comment]
I believe this would need to be a configuration option in the FastCGI module, rather than wfastcgi, as it needs to be applied before starting the worker process. wfastcgi only applies after the process is started, so there's not a lot we can do by then.

You may want to ask this on an IIS forum. We are not IIS experts here, and the people who know are unlikely to drop by.
