### ISSUE TITLE
PTVS incorrectly infers return type as int when it should be bool

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/PTVS#4030]
In this case BankAccount.overdrawn is inferred to be (self) ->int
Should be (self) -> bool

```python
class BankAccount(object):
    def __init__(self, initial_balance=0):
        self.balance = initial_balance
    def deposit(self, amount):
        self.balance += amount
    def withdraw(self, amount):
        self.balance -= amount
    def overdrawn(self):
        return self.balance < 0

class SecuredBankAccount(BankAccount):
    def withdraw(self, amount):
        if amount > 10000:
            print("must be verified")
        return super().withdraw(amount)

my_account = BankAccount(15)
my_account.withdraw(5)
print(my_account.balance)
print(my_account.overdrawn())
```

Microsoft Visual Studio Community 2017 
Version 15.6.5
...
Python   15.6.18072.2

Interpreter: Python 3.6

**Comment by zooba** [comment]
Because of comparison chaining (e.g. `2 < 4 < 6`), we need to treat the return type within an expression as the type of the "successful" value. Changing this is going to require adding a feature to the analyzer to determine the type of an overall expression instead of just evaluating it on each operation.

Not saying we won't do it, but it's currently working as designed.
