### ISSUE TITLE
Consider making Server.DidChangeTextDocument async

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#4060]
With recent changes, it synchronously waits for analyzer creation to complete, which may take some time.
`DidChangeTextDocument` is already called from async method in VS analyzer. @MikhailArkhipov , what changes are required in VSC?

**Comment by zooba** [comment]
It was async when I created it :) - Mikhail had reasons for making it synchronous in VSC, mostly to do with sending subsequent messages (though we shouldn't "async" back to our message loop here, as it's waiting on processing to complete)

My most important criteria here - this is public, stable API. We need to stop changing it at some point very soon. This is why I made all these APIs async even if they don't currently need to be.

**Comment by AlexanderSher** [comment]
If it has to be sync, we need to provide some reasonable waiting timeout.

**Comment by zooba** [comment]
If we need a timeout, it has to be async.

Adding a document change shouldn't need to wait for initialization to complete fully - it's deliberately designed to be "ready but still loading" and awaiting on completely loaded is optional. Perhaps this is just the hack to make it load synchronously for tests (which should be able to explicitly wait in the test, IMO, rather than forcing the server to do it).

**Comment by MikhailArkhipov** [comment]
The problem was that async yields. So when user types '.', we get text change and if we yield we insta-get `completion()` while document text change hasn't been processed yet.

**Comment by zooba** [comment]
That's only if the caller doesn’t await. You can add that in the adapter layer for VSC. In VS it gets awaited by the message processing loop and no further messages are handled until it’s done (the parse is done fully asynchronously, but then anything using it should WaitForCurrentParse – this keeps it quick to load lots of files but also ensures consistency for the AST).

And since you’re probably wondering, we can use a newer AST to query an older ModuleAnalysis, which is why we don’t have to wait for the new analysis to complete.
