### ISSUE TITLE
wfastcgi 3.0.0 + IIS 7 + Flask 0.12.2 + Python 3.6.4 -- strange 404

### ISSUE THREAD

**Issue by susodapop** [Microsoft/PTVS#4061]
This is similar to issue [#1240](https://github.com/Microsoft/PTVS/issues/1240). I followed the instructions [here](https://pypi.python.org/pypi/wfastcgi) to configure `wfastcgi.py`. I'm using a virtualenvironment. My Flask app runs as expected on the command line so I don't think this is a Flask issue. But navigating to _myURL_.com/python_g21 returns a 404. The wfastcgi log appears to show no problems.

`web.config` file:

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  <system.webServer>
    <handlers>
      <add name="Python FastCGI"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="c:\inetpub\wwwroot\python_g21\venv\scripts\python.exe|c:\inetpub\wwwroot\python_g21\venv\lib\site-packages\wfastcgi.py"
           resourceType="Unspecified"
           requireAccess="Script" />
    </handlers>
  </system.webServer>

  <appSettings>
    <!-- Required settings -->
    <add key="WSGI_HANDLER" value="main.app" />
    <add key="PYTHONPATH" value="C:\inetpub\wwwroot\python_g21; C:\inetpub\wwwroot\python_g21\venv;C:\inetpub\wwwroot\python_g21\python_g21" />
  </appSettings>
</configuration>
```
`wfastcgi.py` log file:

```
2018-04-13 10:19:50.706933: wfastcgi.py will restart when files in C:\inetpub\wwwroot\python_g21\ are changed: .*((\.py)|(\.config))$
2018-04-13 10:19:50.708933: wfastcgi.py 3.0.0 initialized
```

My directory structure looks like this:
```
python_g21
├───Logs
├───python_g21
│   └───blueprints
│   └───static
│   └───templates
├───venv
│   └───Include
│   └───Lib
│   └───Scripts
│   └───tcl

```
The root python_g21 folder includes `main.py`:
```
from python_g21 import app

if __name__ == '__main__':
	app.run()
```

...where `app` is a Flask() object.

Any idea why I'm only getting 404's. I've tried everything I can think of and I'm drawing a blank.

**Comment by zooba** [comment]
Are you able to see what path is being passed to `flask`? In general, the section of path after the folder containing `web.config` should be passed directly to the app (because of the `path="*"` configuration) while the path above it should have been "consumed" in locating the `web.config`.

So in this case, `http://myURL.com/python_g21` gets you to the `wwwroot\python_g21\web.config`, which then _should_ try to resolve `/` in the Flask app (or maybe not, and maybe you need to go to `http://myURL.com/python_g21/`).

I'm not entirely prepared to rule out the extra prefix being included though, so it's actually trying to resolve `/python_g2/` in Flask. In this case, you probably need to tell your Flask app what its prefix is, as this is going to be necessary when it generates links.

I forget the exact spec, but if you add some request logging middleware or even something as simple as below, you should be able to inspect exactly what is being passed to your app and figure it out from there:

```python
from python_g21 import app as original_app

def app(*a):
    print(a)
    return original_app(*a)
```

**Comment by susodapop** [comment]
Thanks for your insight. I troubleshooted with the Python snippet you used above and inspected the request. Just as you suggested, the WSGI container was not stripping the string `python_g21` from the URL request.

At first I tried to fix this in Flask by changing `app.config['APPLICATION_ROOT'] = '/python_g21'`. This didn't change the behavior. After extensive Googling, I determined that Flask's `APPLICATION_ROOT` configuration variable is _not_ used for routing (see [this issue](https://github.com/pallets/flask/issues/1714) from 2016). In the end it was [this gist](https://gist.github.com/Larivact/1ee3bad0e53b2e2c4e40) that solved the problem. I updated my `web.config` as follows:

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  <system.webServer>
    <handlers>
      <add name="Python FastCGI"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="c:\inetpub\wwwroot\python_g21\venv\scripts\python.exe|c:\inetpub\wwwroot\python_g21\venv\lib\site-packages\wfastcgi.py"
           resourceType="Unspecified"
           requireAccess="Script" />
    </handlers>
  </system.webServer>

  <appSettings>
    <!-- Required settings -->
    <add key="WSGI_HANDLER" value="main.app" />
    <add key="PYTHONPATH" value="C:\inetpub\wwwroot\python_g21" />
    <add key="SCRIPT_NAME" value="/python_g21" />

    <!-- Optional settings -->
    <add key="WSGI_LOG" value="C:\inetpub\wwwroot\python_g21\logs\python_g21.log" />
    <add key="WSGI_RESTART_FILE_REGEX" value=".*((\.py)|(\.config))$" />

  </appSettings>
</configuration>
```

This adds a `SCRIPT_NAME` environment variable which `wfastcgi.py` uses when sending requests to the Flask app.

Thanks again for your help!
