### ISSUE TITLE
An unexpected error - not sure what this is  - VS thinks I don't have any Python environment? That's not true.

### ISSUE THREAD

**Issue by maxxwu** [Microsoft/PTVS#4098]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

System.IO.FileNotFoundException: The project cannot be launched because no Python interpreter is specified. Please check the Python Environments window and ensure the version of Python is installed and has all settings specified.
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.CreateProcessStartInfo(IServiceProvider provider, LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.StartWithoutDebugger(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by maxxwu** [comment]
This error occurred after I ran the Update through VS Installer, which resolved the Pip installation failure. 

It appears now I have broken Python environments.  The default Python 3.60 environment now displays a message: "! Help me fix this broken environment." which is a link to the related section of the Microsoft PTVS docs cite, which I have not really looked through yet, since I don't really use the default Python environment, at least that was what I thought.

But this issue is puzzling, because I do have two other Python environments that I worked with until this error showed up. What I don't understand is that the broken default Python 3.60 environment also affects the other two environments that I configured myself, and they are in totally different disk locations away from the default. How is that possible?

**Comment by huguesv** [comment]
Based on the call stack, it looks like you are debugging a standalone file which doesn't belong in a project. In that case, it will use the global default environment.

When an environment is detected as broken, it is because the python interpreter executable was not found. The Python environments window should show you the path where it expects it to be.

If the broken environment is auto detected (not custom added) and broken, then that is likely caused by an installer issue (registry keys were left behind).

The VS bundled Python 3.6 changed location starting in 15.6, so if you updated from a version prior to that, you may have a mostly empty folder where it used to be installed.

In any case, we shouldn't be crashing here, we need to handle that FileNotFoundException.

**Comment by maxxwu** [comment]
Thanks for the response quickly. I'm not certain I see the first thing you said above - "Based on the call stack, it looks like you are debugging a standalone file which doesn't belong in a project. In that case, it will use the global default environment."

Let me be very specific about what I was doing before the error popped up. I have two custom Python environments. Let's call them env1 and env2. 

You're correct that I was debugging a single file outside of a project. But still, on the Environment window, I selected "env1", which is highlighted by the VS and showing the path as you said it should. 

I don't understand what you suggested that, even thou I specifically chose "env1" as I intended, the VS would still run the script from the default environment! Is that how the VS works in the background in general? Not just for Python?

It seems to me that it would be sensible if the VS actually does what it says it does, when a specific environment is selected and highlighted. Otherwise, it can be confusing.

**Comment by huguesv** [comment]
The Python environments tool window is a master/details view. Selecting an environment from the list shows its details in the bottom part of the tool window. That's the only thing selection does, it does not change the active interpreter.

To change the active environment, you'll need to click on Make this the default environment for new projects. The default appears bolded in the list.

![image](https://user-images.githubusercontent.com/1696845/39198397-d194ea32-479b-11e8-83ca-a7fb4f02502d.png)

**Comment by maxxwu** [comment]
Thanks for pointing out the not-so-obvious! Did you guys document this little "feature"? I honestly thought and assumed that being able to pick an active interpreter so conveniently to test a piece of code on the fly was an intuitive feature provided by this new version of VS. I didn't even bother to look it up in the docs. 

But really, I think you guys probably wasted a perfect function by letting it do nothing - not just confusing a user like myself. Maybe it's just me, but I found the default Python environment useless. The reason I chose to test a piece code outside of a project was to make it work in more than one Python environment. Python is evolving rather fast. What's the real use to have a default environment, when one is far better to have the code to work in more than one environment?

I think the concept of working under a custom "active Python environment" is practical and intuitive. And being able to pick any existing environment on the fly as the active interpreter is an elegant feature that you guys should pursue. Does the VS team guarantee to keep the default Python environment come with the VS always up to date? Do you need to do that? Do/should the user base trust the default environment comes with the installation as the latest official Python release? Or maybe it is intended as a starting point for the installation after all?

If I wasted your time by sharing my thoughts, I apologize in advance.

**Comment by huguesv** [comment]
We've been having discussions these past weeks regarding future improvements to this area, so this is great timing and your thoughts are much appreciated.

**Comment by huguesv** [comment]
Oh, and here's a link to a couple of relevant pages in the docs:
https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages
https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio

**Comment by kraigb** [comment]
@maxxwu I'll clarify the behavior of the selected environment in the docs (that it doesn't activate that environment). As Hughes mentioned, there's discussion about environment behaviors for future releases, so watch for those in announcements on the Python Engineering Blog (or find/file an issue requesting the behavior you'd like when working with a standalone file).

I wanted to mention that https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project describes how you can easily switch between environments when you have a project, which is one of the benefits of having a project in VS. There's also a "From Existing Code" template that wraps a folder with Python code with a project so that you can take advantage of such things.
