### ISSUE TITLE
PTVS(python 2.7; vs2010) does not auto-importing the __builtin__

### ISSUE THREAD

**Issue by ECJana** [Microsoft/PTVS#430]
Our team has been working with the PTVS for months now with no issue.(not adding in any imports for **builditin** etc)

Today, any types that are found in **builtin** are flagged with 'unknown type'.

The funny thing is that if you right click, in the import options, the **builtin** comes up as an option. The environment database have been deleted and recreated; we then refreshed the database. It says that is it is up-to-date, but the issue persists.

I do not want to start referencing the native imports, so that the upgrade to 3.X is not as bad.

Any direction on what could have caused this would be great.

**Comment by zooba** [comment]
Interesting that you've started seeing this in VS 2010... we had a bug recently in the latest versions that I just fixed, but that shouldn't affect PTVS 2.1 or earlier.

You should definitely *not* start referencing `__builtin__` explicitly - this is our fault, so don't write bad Python code because of our bug :)

I'm interesting in things that may have changed recently. Have you upgraded to Python 2.7.10? Are you using virtual environments and have you upgraded virtualenv recently? Any other sort of package manager other than pip?

**Comment by ECJana** [comment]
We are on version 2.7.7, and have been for a while now. There have been not Microsoft updates recently, and we don't use virtual environments for development.

We use NuGet for getting the packages.

**Comment by zooba** [comment]
Which packages are you getting with NuGet?

**Comment by ECJana** [comment]
version 2.1
