### ISSUE TITLE
IntelliSense slow to propose variable defined on the previous line

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4432]
Type the following code manually. Even though it will take you several seconds to type the print statement, by the time you type `format(` it will not propose `std` variable. You need to wait a few more seconds before it is available.
```
if __name__ == '__main__':
    donations = []
    variance = 1
    std = variance ** 0.5
    print("the standard deviation of the list of numbers is {0}".format(std))

```

**Comment by huguesv** [comment]
Same thing for variable declared as part of a `for` statement. It took a real long time for `yi` to appear in completions.
![image](https://user-images.githubusercontent.com/1696845/41875026-79dad748-787e-11e8-8ca4-39820737a7e5.png)

**Comment by zooba** [comment]
This is due to us deferring publishing of the new analysis until after it's complete. Before, we were clearing values and giving poor completions if you triggered it too quickly.

We may need to figure out some way to include new names in lists of members, at least at the top level, in order to have them there. If we only worry about module scope, we can probably union the current analysis variable names with the one that's currently running. @MikhailArkhipov - thoughts?
