### ISSUE TITLE
We Cannot Create a Virtual Environment at the Specified Path - VS2017

### ISSUE THREAD

**Issue by dmitryponv** [Microsoft/PTVS#4604]
Issue occurs when adding a virtual environment using "Python Environments->Add Virtual Environment" 

When browsing to a folder containing python.exe and pythonw.exe Visual Studio shows 
"We Cannot Create a Virtual Environment at the Specified path. Choose a folder that does not exist, is empty, or contains and existing virtual environment"

Therefore the user must create a virtual environment using a different menu "Tools->Python->Python Environments" which lets you enter the exact path of python.exe and python.exe

**Comment by dmitryponv** [comment]
Do I need to have the virtual environment set up before adding it in visual studio, or does visual studio set one up for me? Is there a feature in visual studio that would allow me to select the directory where python libraries are where the python executable is without having to write scripts by hand, like in C++?

**Comment by huguesv** [comment]
Add Virtual Environment will create one for you, just enter a name for it in the dialog, and it will be stored in a subfolder of your project.
https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project#using-virtual-environments

To add an already existing virtual environment, you can use the same dialog and enter the path instead of a name, or use the Add Existing Virtual Environment command. Here I created a virtual env using command line and I'm adding it to the project.

![image](https://user-images.githubusercontent.com/1696845/43533916-d6b5e288-956a-11e8-9f26-f6eca5874f01.png)


If you want the virtual env to be available globally like the CPython installations, you can add it as a custom environment in the Python Environments window.

![image](https://user-images.githubusercontent.com/1696845/43533976-0f17c376-956b-11e8-8742-5db2d579bdab.png)


Then you can use Add/Remove Python Environments in your projects like this:
![image](https://user-images.githubusercontent.com/1696845/43534060-44418dca-956b-11e8-994c-166c8ee9a7ab.png)

**Comment by huguesv** [comment]
Closing since we haven't heard back. Hope you got it figured out.
