### ISSUE TITLE
PTVS code completion does not work

### ISSUE THREAD

**Issue by syagev** [Microsoft/PTVS#4687]
Since upgrading to VS 1.5.8.1 (PTVS 15.8.18201.1) I am unable to get code completion, Go To Definition, variable renaming etc.

This applies both to my modules and 3rd party modules.

The status bar in VS has the message "Python source analysis is not up to date". I've tried deleting the `.vs` folder and that didn't help. I tried reverting to the "old" intellisense engine but that just caused VS to run on very high CPU and even after I waited almost 12 hours (with the computer on) I couldn't get proper completions. The Python Environment window just showed that the vast majority of packages were still not processed. Tried "Refreshing Db" a few time but that did not help.

[Diagnostic info](https://www.dropbox.com/s/wt8ub2hj2t8za0f/Diagnostic%20Info%202018-08-24T012214.txt?dl=0) attached.

**Comment by zooba** [comment]
@huguesv - this is the crash fixed in #4623 - we may need to consider getting it into the next VS update.

@syagev Changing back to the old IntelliSense engine won't help you here, I'm afraid. That only affects installed packages, and this is more likely coming from something in your own code. (Though if it doesn't occur on an empty project, then it might be one of the libraries you have installed - in that case, if you could provide us your `pip freeze` output we may be able to figure out which one.)

**Comment by huguesv** [comment]
@syagev if you can provide us with a minimal repro, we may be able to suggest ways to change the code to avoid the issue. Right now we are not sure what code triggers this.

We've fixed the crash for the upcoming 15.9 Preview 2.

We're also submitting it for 15.8 servicing. If that is accepted, it will take a couple of weeks.

**Comment by huguesv** [comment]
The fix will be included in 15.8.3.

**Comment by ejc1** [comment]
I have 15.8.6 and code completion does not work on the code in my own project.  It does work on installed packages.  Go to definition, and find all references also do not work, unless it's within the same file.
