### ISSUE TITLE
Intellisense, Auto-Complete

### ISSUE THREAD

**Issue by sajeebchandan** [Microsoft/PTVS#4838]
Code intellisense is not good at all compare to VSCode. In most of the case there is no 'Go To Definition' or 'Peek Definition' options available.

Please fix these.

Thank you.

**Comment by huguesv** [comment]
Thank you for the feedback.

We are working on improving analysis, which will improve go to definition results.

The work is being done at https://github.com/microsoft/python-language-server and VS Code releases with that code base every month. Language server code originated in VS, and will be reintegrated in VS for 16.0 release.

Since VS Code releases more frequently and the language server team is focused on VS Code right now, it would be pretty useful if you could verify if you are using the MS Language Server in VS Code (it is currently off by default).

https://blogs.msdn.microsoft.com/pythonengineering/2018/10/09/python-in-visual-studio-code-september-2018-release/
(see Improvements to Language Server Preview section for how to enable)

If you find that there are cases where MS Language Server provides worse results than Jedi, then please let them know the specifics of what doesn't work as expected. As I said, any improvements to language server will make it back in VS.

thanks!

**Comment by jmh-aira** [comment]
Intellisense auto completion as really been screwy for the last 15.8.x versions.  I haven't upgraded my vs at home from 15.7.x because I'm afraid that my autocomplete will break.  The Package that has the most problems, and which VS will not show me any autocomplete options is wxpython.  I'm on vs 15.8.9 and python 3.7 and wxpython 4.0.3.  it worked great on vs 15.7.x.  I'm hoping for vs 15.9 to come out soon to see if it is fixed there.

**Comment by huguesv** [comment]
We've integrated an updated language server in 16.0 Preview 4 (aka RC). It's the language server from 15.8/15.9 but with additional fixes.

There are better more significant improvements coming in the language server, VS Code users will be able to test them soon, and we'll work on integrating those in VS later.

**Comment by gramster** [comment]
We are working on bringing the VS Code latest language server to VS. Tracking this elsewhere.
