### ISSUE TITLE
Commit characters other than enter/tab should not apply within a word

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#507]
Type `x = d`, then go to before the `d` and type `int(`. The result should be `x = int(d` but is actually `x = InterruptedError(` because we committed `intd`.

When the caret is within the applicable span and the completion is being committed with anything other than enter/tab/mouse, we should dismiss rather than commit.

**Comment by zooba** [comment]
Won't get back to this for a few days, but here's my plan:
* add a flag to `IntellisenseController.TriggerCompletionSession` to indicate manual/auto trigger
* change to create and start the session in two steps
* attach a flag to the session indicating trigger type
* use the flag when getting the applicable span to determine whether the span can extend to the right of the caret (manual) or not (auto)

**Comment by MikhailArkhipov** [comment]
I can take this

**Comment by MikhailArkhipov** [comment]
a) applicable span is calculated from the classifier and in `i|d` it gets 'id' which then grows and `d` is eaten by to completion commit.
b) C# does not bring completion when typing in front of the existing construct, it requires space.

So options are 

a) If we still want completion, determine applicable span from the previous snapshot and/or tell completion invoked via `Ctrl+J` from typing: the first replaces construct, the latter does not.

b) Suppress completion line C# does.

RTVS does both (a) and (b) but it uses AST rather than classifier so it does not take into account just typed text.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/PTVS/commit/deccfe5b202d9c9e9e9edbaeb46d10ed1f2435a1
