### ISSUE TITLE
Debugging python embedded in xml file

### ISSUE THREAD

**Issue by Trigve** [Microsoft/PTVS#5156]
I just finally made to work PTVS with our software (C++), which embeds the python. I can now debug the .py files etc. But I would like to ask if something else is possible.

We're also using .xml files which could embed the python code. From this .xml, we generated the string which is python definition of the classes, methods etc. which is then run using boost::python::exec() (which does use PyRun_String() internally) and class type object is extracted from the local dict for later use - creating instance of it.

Now, when the instance of the generated class is created, and it's methods are called, I would like to breakpoint in those methods. But I don't know if it is somehow possible. It seems I would need to map the lines from the "string" to the lines in the .xml file. I was searching through the python C API but haven't found the needed functions.  
Another option is to dump the generated string to some temp .py file and then do as usual. Then at least in call stack I may be able to go to the location in the given temp .py file.

Is it somehow possible or I shouldn't even try?

Thanks

**Comment by int19h** [comment]
The trick is to make sure that the code objects for your compiled code have filenames (`co_filename`) and line numbers (`co_lnotab`) that correspond to where they come from in XML. I don't know enough about Boost.Python, but in Python itself you'd do it by calling `compile()` first - which takes an optional filename argument that you can set to your .xml file - and then using `eval()` on the resulting code object. In C, `PyRun_CompileString...` also has that option. 

With line numbers it's a bit trickier since there's no way to tell the parser to start counting from some other value, it always goes from 1. But you can first parse to AST with `ast.parse()`, then do `ast.increment_lineno()` to "move" it to where it was in your XML, and finally give that to `compile()`.

This assumes that you preserve line endings from XML - if not, then you can adjust line numbers in the AST for every node as needed to map them.

**Comment by Trigve** [comment]
Thank You very much for the reply @int19h . I've made the proof of the concept and it is working well! Thanks again ;)
