### ISSUE TITLE
Invalid digital signature on samples and ml vsix

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#523]
PTVS 2.2 30626.00

![sig](https://cloud.githubusercontent.com/assets/1696845/8420357/5ea9423a-1e76-11e5-8e41-db2b7f63087c.png)

**Comment by zooba** [comment]
So this is because VS 2015 has stopped accepting SHA1 certificates on VSIX files, and VS 2013 doesn't accept SHA256. We'll probably have to start shipping separate VSIX files or replace this with an MSI.

What I don't understand is how you got this error with only VS 2013 installed. Had you already installed the samples into VS 2015 on that machine?

**Comment by huguesv** [comment]
Yes on that last question, that's why it wasn't in the list in the screenshot.

**Comment by zooba** [comment]
I tried making separate VSIX files for VS 2013 and VS 2015 and signing the latter with a SHA256 certificate, but they still appeared as invalid.

Workaround is to validate the signature using `VSIXInstaller.exe` from a VS 2013 installation explicitly (not by double-clicking the VSIX file).

**Comment by zooba** [comment]
This will be fixed for 3.0 when we drop VS 2013 support, but it won't be fixed any earlier than that.
