### ISSUE TITLE
Send to Interactive doesn't correctly handle indented code and comments

### ISSUE THREAD

**Issue by joseortiz3** [microsoft/PTVS#5278]
Highlighting code and hitting "Send it to Interactive" is an extremely important feature to have working robustly.

However, the handling of indentation is extremely buggy.

One of the easiest demonstrations is the following: put this in a python script

```python
def something_that_has_indented_code():
    x = 1

    y = 1

    # A comment
    z = 3

    return
```

now highlight starting from the line above `y=1` to the end of the line `y=1`. You'll get randomly either
![image](https://user-images.githubusercontent.com/18585219/57171852-85ade480-6dcd-11e9-9ac5-533e3ea902c6.png)
or
![image](https://user-images.githubusercontent.com/18585219/57171858-9c543b80-6dcd-11e9-8e0d-87ad2b0c43fa.png)

Now send it to interactive.
```python
>>>     y = 1
  File "<stdin>", line 1
    y = 1
    ^
IndentationError: unexpected indent
```
Now highlight the comment and z-line:
![image](https://user-images.githubusercontent.com/18585219/57171887-dfaeaa00-6dcd-11e9-8fb1-edc54e3275a9.png)

Send to interactive
```python
>>> # A comment
...     z = 3
... 
  File "<stdin>", line 2
    z = 3
    ^
IndentationError: unexpected indent
```

Loops don't execute properly because of indentation handling. Test code:

```python
def something_that_has_indented_code():
    x = 1

    y = 1

    # A comment
    z = 3

    while(True):
        if x == 10:
            raise Exception('paste fail')
            break

        # this is a comment
        x = x + 1
        bob = 'bob'

        # ------ Hello ------ #


        # some comment
        # another
        print('Counter is %s' % x)

        if x == 4: 
            break

    a = 2
```

highlight the following
![image](https://user-images.githubusercontent.com/18585219/57172097-64022c80-6dd0-11e9-9475-5714cf3e9be2.png)

Send to interactive

```python
>>> x = 1
>>> y = 1
>>> # A comment
... z = 3
... 
>>> while(True):
...         if x == 10:
...             raise Exception('paste fail')
...             break
...         # this is a comment
...         x = x + 1
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
Exception: paste fail
>>> bob = 'bob'
>>> # ------ Hello ------ #
... 
... 
... # some comment
... # another
... print('Counter is %s' % x)
... 
Counter is 10
>>> if x == 4:
... 
  File "<stdin>", line 2
    
    ^
SyntaxError: unexpected EOF while parsing
>>> break
  File "<stdin>", line 1
SyntaxError: 'break' outside loop
>>> a = 2
>>> 
```

All of this demo was in VS 2019 16.1.0 preview 2.0. These problems are very old (years).

**Comment by joseortiz3** [comment]
Hello again. I know the PTVS team is very busy. I would just like to reiterate what an annoyance this bug must be for everyone relying on PTVS. I would say my workflow is about 20% slower because of avoiding highlighting comments in code when sending to interactive, and the delay associated with accidentally sending comments to the interactive session causing it to choke on a snippet of code.

**Comment by RaymonGulati1** [comment]
@joseortiz3, thank you for reporting this issue. I'm going to take a look at it.

**Comment by joseortiz3** [comment]
@RaymonGulati1 Please do. This is still a big time waster for python development. I write a lot of scripts and there's a lot of "Send to Interactive" happening in my workload, sure other people do too.

**Comment by RaymonGulati1** [comment]
@joseortiz3 I’ve looked into this and everything is working as expected. You are encountering those issues because of the way you are selecting code and sending it to interactive. 

In your example #3 and 4, you are only partially selecting the first line of code . Since Python is indentation sensitive, partially selecting the first line means that the indentation for that line isn’t sent to Python which results in the errors you see in VS. This can be easily fixed by selecting the entire line before sending it to the interactive window. See examples below. 

In your example #1 and #2, you are sending an additional space character (the line above “y = 1”). Instead, you should only send the line of code you want to execute in the interactive window (put cursor on that line and press "Control + Enter"). 

Side note: If you send multiple lines of code and all of them are indented, then VS will ignore those indentations before sending it to Python. This is what allows the interactive window to execute code that is already indented (such as the while loop in the example below)”

![example1](https://user-images.githubusercontent.com/3315992/69375221-a865f480-0c5c-11ea-9783-b09e6a62ba53.png)
![example2](https://user-images.githubusercontent.com/3315992/69375240-b287f300-0c5c-11ea-9db7-d574101b550e.png)

**Comment by joseortiz3** [comment]
I don't think the current behavior is expected behavior. Handling indentation should be smarter than that.
