### ISSUE TITLE
Attach to debug (legacy) does not work for debug python

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/PTVS#5295]
In legacy debugger, "attach to process"  for a script running in "python_d.exe" results in an error. Sometimes attach will pass and sometimes it will fail--both result in an error.  

If the attach is successful, debug will continue as normal, until the script finishes execution and then it will produce an error
![image](https://user-images.githubusercontent.com/3315992/57488037-d2c70600-7266-11e9-8f11-d8a7fd26abe2.png)

If the attach fails, it shows an error immediately
![image](https://user-images.githubusercontent.com/3315992/57488085-e83c3000-7266-11e9-98d7-3a540773fafd.png)

Both outputs are from the console running the python script on "python_d.exe"

Related to Fix #5219 and PR #5290

**Comment by int19h** [comment]
This worked at some point in the past, given that we have a bunch of code specifically to support this scenario in PyDebugAttach. So it regressed at some point.

I had a close look at the code, but didn't notice anything there that's obviously wrong. There are a few places where we decref an object before removing a reference to it (see [this](https://docs.python.org/3/extending/extending.html#thin-ice) for why this can be a problem), but I couldn't come up with any way for those to actually break. 

Note that even though it only repros in debug Python builds, there's a possibility that whatever we're doing wrong is not specific to debug Python, and it just happens to detect it in this manner because of all the extra checks.

**Comment by judej** [comment]
Exceptional uncommon scenario
