### ISSUE TITLE
The Project cannnot be launched because the startup file was not found when rename the startup file under open folder. 

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5306]
VS Version: 16.1.0 [28916.193.d16.1]
Python Tool Version: 16.1.19129.1
Repro step:
1.Open new folder in VS
2.Right click folder and select add-> add new item->python->Empty Module->open
3.we can see module1.py was created under this folder
4.Set module1.py as start up file.
5.click module1.py and renamed to test1.py
6.F5 to start project

Expect:test1.py file can be started successfully
Actual: cannot find module1.py and the start up does not changed to test1.py in the  toolbar
![image](https://user-images.githubusercontent.com/39871640/57920289-4ef7c400-78cd-11e9-986b-b98f23ded31d.png)

**Comment by xiaofeng0123** [comment]
When I add a new item in workspace and rename it as test1.py, debug button displays the default name module1.py. At this point, I need to manually switch debug button to select current document(see follwing imag), otherwise debug button will always display module1.py no matter which file selected, and the file cannot be found when starting to debug
![image](https://user-images.githubusercontent.com/41426540/64753852-4d769980-d557-11e9-9d31-fdea92b05217.png)
[current document.zip](https://github.com/microsoft/PTVS/files/3603694/current.document.zip)

**Comment by judej** [comment]
This scenario is not support in the workspace
