### ISSUE TITLE
Where is simple but complete tutorial on how to install packages in PTVS, like matplot, and its dependencies?

### ISSUE THREAD

**Issue by scottz1** [Microsoft/PTVS#532]
I have cpython 3.4 in ptvs in vs2015. I can't find any conclusive documentation on how to do this efficiently. I read the docs page on "environments" but it doesn't give an example, and half way through the article it says "you can stop reading here".

**Comment by scottz1** [comment]
Found it in Solution Explorer, under your project, you'll see Python Environments. Expand it, you should see pip and setuptools. Then right click either the (global default) environment or one that you've added. Choose Install Python Package. Then type the name of the package to be installed. I was hoping dependencies would be automatically installed as well, but I got an error with matplotlib that it requires numpy. Then it gets an error apparently about blas. Is there a better way to do this?

**Comment by int19h** [comment]
pip (which is the standard Python package manager, that PTVS uses for this purpose) does install dependencies - the problem is that some packages are tricky to install on Windows because they need to compile a bunch of C code as part of their installation, and that code often comes with (C) dependencies of its own. numpy is a particularly prominent example of it, but there are others, such as PyQt.

The best way to deal with it is to use a Python distro that has them preinstalled out of the box, such as Anaconda, WinPython, or Canopy. Alternatively, you can use Miniconda to get the conda package manager on top of an existing stock Python install, and use it to install precompiled packages like numpy (and PTVS will give you the option to use conda rather than pip when the former is available in a given Python install).
