### ISSUE TITLE
Breakpoints assigned to wrong source file

### ISSUE THREAD

**Issue by FSchu** [microsoft/PTVS#5338]
When having a project with mutiple packages which in turn contain modules with the same file name, a breakpoint set in one module is also set in the other modules.

Example:
Create a project with a package structure like this
packageA
   __init__.py
   dialog.py
packageB
  __init__.py
  dialog.py

Set a breakpoint in packageB.dialog and make VS execute the line with the same number in packageA.dialog. 

Result VS stops in packageA which is not intended.

**Comment by int19h** [comment]
Is this with mixed-mode (native code) debugging?

**Comment by FSchu** [comment]
Sorry, left out some details. Actually it happens without native code debugging, but using IronPyton and executing a C# exe, which executes python code structured in packages and modules. As it happens a bunch of standard modules have the same name in different packages as described.

**Comment by int19h** [comment]
Are you using Python or generic .NET debugger to attach?

In the .NET one, if I remember correctly, filename matching ignores the full path.

**Comment by FSchu** [comment]
The generic .NET debugger - VS -> Start debugging

**Comment by FSchu** [comment]
Anything we can do about this?

**Comment by int19h** [comment]
I don't think so, but I'm not really qualified to answer. In this scenario, the debugging is pretty much entirely handled by code outside of PTVS. I *think* that behavior is there, so that you can copy a DLL from one machine to another which has the source in a different place, and still debug. Since it's not really aware it's Python, a simple filename match is the best it can do.

@huguesv, is there a still way to do Python attach to legacy ptvsd in PTVS? That would work better in this scenario.

**Comment by huguesv** [comment]
I don't recall when someone tried to do remote attach with ptvsd 3.x / legacy debugger on IronPython. There is a chance of it working.

You can install ptvsd==3.2.1 into your environment, and check "use legacy debugger" in python/tools/options/debugging page. If you have a mismatch between the 2, you'll get an error when attaching.

https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2019#using-ptvsd-3x

FYI you have to use ptvsd 3.x/legacy debugger because ptvsd 4.x doesn't support IronPython.

**Comment by FSchu** [comment]
Many thanks for your effort. Unfortunatly I'm stuck on a customer system and can currently not install a different debugger version. So for now I guess I have to live with the situation.

**Comment by int19h** [comment]
Depending on how limited your access is, you might still have options. While we normally recommend `pip install` for simplicity and convenience, it should still work so long as the old version of ptvsd is anywhere in the search path - i.e. you should be able to just copy the package to any folder you have write access to, and then e.g. edit the Python source code to explicitly add that folder to `sys.path` before doing `import ptvsd`.

If you cannot edit the Python source, then it's not an option at all, since it requires you to call `ptvsd.enable_attach` in there somewhere.
