### ISSUE TITLE
No "Python/Native Debugging" option when debugging a native (embedding) application crash dump

### ISSUE THREAD

**Issue by komrad36** [microsoft/PTVS#5407]
Hi,

After installing the Python native tools I am able to attach the mixed-mode debugger to my application, which embeds Python, and that works great.

However, I sometimes have to debug minidumps-with-heap from customers, and for those I do not see any way to get Python stack frames except for hacking up the Natvis file and then inspecting the `autoInterpreterState` manually.

The only option on the dumps is Debug with Native Only.

Thank you!

**Comment by int19h** [comment]
This is not a supported scenario at the moment, unfortunately.

The debugger itself is written with minidump debugging in mind. But if I remember correctly, the VS UI for minidumps was not extensible originally. I think there was some API added later that made it possible to add more debuggers to it, though. 

I doubt that it would "just work" if you wired it up, given that we have never tested it. One bit that's most likely to break is expression evaluation - I think it might be incorrectly assuming that Python in-proc is available, and try to use that. But the changes required to make it all are all likely relatively small, and not requiring any sort of massive refactoring.

**Comment by komrad36** [comment]
Hi,

Thank you for your prompt reply!

I see. Looking around online, there appears to be the [IDumpExtension](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.vsdebugpresentationextension.idumpextension?view=visualstudiosdk-2017) API, but documentation is very sparse and there do not appear to be any examples of its use online. There is one [forum post](https://www.msdevhelp.com/article/89910433/Implementing+IDumpExtension) which adds the additional info that 

> it looks like this needs to be an MEF component placed under the .....\Extensions\Microsoft\Debugger\Dumps subdirectory

Is this something the PTVS team would consider adding? I could also attempt to wire up the `IDumpExtension` and report how it behaves, although I suspect I may encounter some difficulties given the obscurity of this interface...

**Comment by int19h** [comment]
MEF is the way most new extensibility points work in VS, so this sounds about right. The placement in a specific directory is likely so that it can be located by msvsmon.exe (which is used in 64-bit debugging scenarios). If so, then for a 32-bit debuggee, you can probably stick the implementation of that interface into any stock VS extension, export it, and it'll work - and it would be the easiest way to test this quickly...

Looking at that API, though, what's not clear to me is how to specify two engine GUIDs *at the same time*. Which is what you'd need to make mixed-mode work - because it requires both Python and Native GUIDs. The way the docs read, it sounds like every entry returned from `IDumpExtension.Engines` represents a single button in the UI - and each entry only has a single GUID, so that would be a no-go.

But maybe I'm reading it wrong, and instead every `IDumpExtension` represents a single entry in the UI, and `Engines` are all used in conjunction to attach. But then it's not clear to me where the title for the corresponding button comes from?

@gregg-miskelly might be able to clarify.

**Comment by gregg-miskelly** [comment]
Yes, IDumpExtension isn't going to work correctly in your scenario as it was just designed to allow replacing a single startup engine. It would also require either re-reading the dump file yourself to decide if there is Python code loaded, or always adding Python as a choice for all dump files.

My suggestion: You don't actually need to use the Dump Launcher page to debug dump files. So I would suggest investigating how much work it is to get dump file debugging to work, and if you think it is worth pursuing we can figure out how to get Python to show up as a choice in some future version of VS. To debug a dump file without the Dump Launcher page, you just call LaunchDebugTargets[2/3/4] as you normally would, but set the dump file as `bstrExe`. You can probably do this by just changing the launching command in a normal python+native interop project.

**Comment by komrad36** [comment]
Hi, thank you @gregg-miskelly !

I see! Here are the results of experimenting with this:

I created a C++ project, enabled python/native debugging, set the launch path to point to a dump file instead, and ran the project. Unfortunately, no Python menu appeared in Locals, nor any other evidence of mixed debugging. (Could this be because the project itself did not have any actual Python integration?)

I then tried the opposite: a Python project in which I enabled native debugging too, and set the Interpreter path to point to the dump file. This **did** cause the Python submenu to appear in Locals, but it had no effect. Apparently, `$PTVS_ShowPythonViewNodes` was still no. The call stack also appears purely native.

I edited the Natvis to remove all the `$PTVS_ShowPythonViewNodes` conditions. Now Python view nodes appeared on some Locals and objects within the `autoInterpreterState`, but they either show no Python-ness or explicitly error out with "Python view is unavailable for this object".

Testing with Python 2.7.14 x64, sources and symbols available.

**Comment by int19h** [comment]
Thanks, Gregg!

@komrad36 
When you say "enabled python/native debugging", how did it work in a C++ project? I don't recall us having an option there. The checkbox that we do have is in the Python project settings on the Debugging tab - but that only applies to that Python project. 

It has never occurred to me that you can set launch path to the dump file in the Python project - do you mean the interpreter path? Or the Python script path?

**Comment by huguesv** [comment]
@int19h we integrate into the C++ project property pages by installing files in the correct msbuild directories. This only works when you install Python workload with the Python native development tools optional component. It doesn't work when you build/run ptvs in experimental hive.

![image](https://user-images.githubusercontent.com/1696845/60850085-83d41900-a1a2-11e9-9dfd-8f584bed46e7.png)

**Comment by komrad36** [comment]
@int19h If `Python native development tools` is checked in the VS2017 installer, `Python/Native Debugging` can be selected as the `Debugger to launch` in the Debugging tab of the project property pages. Didn't seem to have any effect though...

Because setting the `Script Path` would just pass the dump file to `python.exe`, I set the `Interpreter Path` to the dump file instead, hoping that would end up passed as the debug target. It was certainly a hacky thing to try, but it did seem to sort-of work, as the dump file was then loaded and the Python submenu appeared! However, the call stack was unchanged and no Python views appeared.

**Comment by int19h** [comment]
@komrad36  Thank you for trying it! Clearly there's some logic there that isn't handling this scenario well - but the fact that it does at least show the context menu indicates that the debugger itself gets loaded correctly. Nice hack!

Past this point, you'd have to build PTVS to investigate what's going on there. Most likely, it's in the initialization sequence, where the debugger has to notify VS that the Python runtime is considered loaded - I suspect that there's something in that sequence that breaks when it's a dump rather than a live process. Probably something to do with the helper DLL that we inject into the process to handle stepping and breakpoints - obviously, this can't be done with a dump, but it also shouldn't be necessary in that scenario. 

I might also take a look at this in my free time, and see if it's something simple.

**Comment by gramster** [comment]
We have no plans to add features to native debugging; its a low-use feature so not high priority.
