### ISSUE TITLE
Invoking / Calling python method from c#.net

### ISSUE THREAD

**Issue by dipikaM2011** [Microsoft/PTVS#560]
I wants to call python method from C#.net. But I'm still not getting proper solution for it..
I have done following things - 
1. Created .net code for invoking python method. Used IronPython library in .net for calling python at starting phase. it was working but when I added import packages in python scrip it's giving me error - "no module named json".
2. I have tried PVTS option for getting the output but still not able understand how it will be helpful for me to achieve my output. 

Please anyone have a solution for it then let me know.
I'll be very grateful if any one could please help me

**Comment by int19h** [comment]
PTVS is not an implementation of Python, it is just an IDE. It is not going to help you with this.

Most likely, your problem is that you're trying to use a library that just doesn't work with IronPython. Generally speaking, you will be able to use more libraries with regular Python, and you can use Python.NET (http://pythonnet.sourceforge.net/readme.html) to call into your C# code.

**Comment by denfromufa** [comment]
@int19h @dipikaM2011 pythonnet has moved to github last year:

https://github.com/pythonnet/pythonnet/tree/develop

people look at sourceforge and think that it is abandoned!
