### ISSUE TITLE
Can't get native code debugging to work with 3.7+ virtual environment

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5623]
Create new project
```
import sys
print(sys.version)
```
Add breakpoint to 2nd line
Add new virtual env based on 3.7 32-bit
Enable native code debugging
In Debug->Options, add these symbol directories:
C:\Program Files (x86)\Python37-32
C:\Program Files (x86)\Python37-32\DLLs
F5

Result: Debugger doesn't break

If you repeat these steps with a 3.6 32-bit venv, and add the 3.6 folders to symbol paths, then it works fine.

**Comment by int19h** [comment]
Can you check that the symbols do in fact get loaded for the Python DLLs in the process? It should be visible in the Modules window, and from the log in Output.

**Comment by huguesv** [comment]
Symbols don't get loaded, and there's no task dialog to tell me it couldn't find Python symbols either.

![image](https://user-images.githubusercontent.com/1696845/63377346-ce6db700-c344-11e9-81c0-f5dbdf62d799.png)

**Comment by huguesv** [comment]
![image](https://user-images.githubusercontent.com/1696845/63377614-4f2cb300-c345-11e9-9274-529ea1a30d68.png)

**Comment by huguesv** [comment]
Contrast that with 3.6 venv:
![image](https://user-images.githubusercontent.com/1696845/63377723-7be0ca80-c345-11e9-9ef1-2a483b3e06dc.png)

**Comment by int19h** [comment]
Can you verify that the DLLs are actually from the 3.7 install that you're using? I wonder if ended up being created by a different one - e.g. the one from Windows Store.

**Comment by huguesv** [comment]
None of the dlls appear in the output window for Python 3.7. The path to the python.exe is from the venv folder:
```
'python.exe' (Win32): Loaded 'C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\python.exe'. 
```

I don't have the Python from the Windows Store installed.

FYI file list for the environment:
```
C:\Users\huvalo\source\repos\PythonApplication2\env37\Include
C:\Users\huvalo\source\repos\PythonApplication2\env37\Lib
C:\Users\huvalo\source\repos\PythonApplication2\env37\pyvenv.cfg
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts
C:\Users\huvalo\source\repos\PythonApplication2\env37\Lib\site-packages
(lots of files in site-packages ...)
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\activate
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\activate.bat
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\Activate.ps1
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\deactivate.bat
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\easy_install-3.7.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\easy_install.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\pip.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\pip3.7.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\pip3.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\python.exe
C:\Users\huvalo\source\repos\PythonApplication2\env37\Scripts\pythonw.exe
```

**Comment by int19h** [comment]
So, it's the consequence of this change:
https://docs.python.org/3/whatsnew/3.7.html#notable-changes-in-python-3-7-2

Basically, python.exe inside venv is not a real Python interpreter anymore. It's a wrapper that locates the real python.exe, and launches it as a child process. If you use a test script that doesn't exit immediately - e.g. with `input()` - and then look at Task Manager, you can see both binaries in the process list.

From the debugger's perspective, the redirector script is the one that it launches, and so it's also the one that's it's trying to debug. Since it's not actually Python, it's basically debugged as native. The child process is not even attached to.

The generic solution to this is to support child process debugging in mixed-mode debugger. I don't recall if Concord has any APIs for this, but I'd start looking there first. If not, then direct detouring of CreateProcess etc is also an option - we do that in ptvsd for multiproc. 

I'm not sure if there's any narrower and more specific solution that can be done for venv redirectors specifically, but probably not.

**Comment by maranov** [comment]
If you're like me and have little or no system-wide packages installed, then a workaround for this is to run the global interpreter, but set the PYTHONPATH to a dir with your packages installed. This has limitations, but the debugging works fine.

You can install your dependencies into the specified directory with pip, e.g.:
```
pip install --prefix ptvsenv -r requirements.txt
```

Then set the `ptvsenv\Lib\site-packages` as a search path in VS.

You could also set the PATH to `ptvsenv\Scripts` to gain access to any installed tools, like pylint or coverage. Just bear in mind you are still working in the global environment and e.g. running just pip without the `--prefix` will install system-wide.

Hope this gets addressed at some point.

**Comment by gramster** [comment]
Closing as won't fix.

**Comment by drxyzw** [comment]
My quick fix is to replace python.exe and python_d.exe inside a virtual environment with ones in the original python environment.
After that, I don't see an issue so far.
