### ISSUE TITLE
Newbie question on installing packages

### ISSUE THREAD

**Issue by MMeketon** [Microsoft/PTVS#570]
I am having a difficult time doing a basic task:  installing a package and referring to the package.  In particular, I wanted to learn Python, and especially the Pyomo modeling language.  I am using Visual Studio Express for Desktop.  Here were my steps:
- 1.  Installed PTVS.  This occured without an issue.  
- 2.  Choose Python 64-bit 2.7 as my environment.
- 3.  In Solution Explorer, right-clicked on that environment, clicked on "Install Python Package", typed in pyomo.
- 4.  This appears to have worked.  pyomo is now listed as a package underneath the environment, and I can see it in Solution Explorer
- 5.  Began to write my first Python app.  I began with

from __future__ import division
import sys
import pyomo.core
print(sys.version)

But VS does not find pyomo.  The Pyomo documentation also suggests that instead of "import pyomo.core" I use "from pyomo.environ import *".  I tried that as well.  Either case VS does not find pyomo.

It's probably something silly I hadn't done, but having searched through the online documentation and watched some video tutorials, I still don't have a clue what to do to get started.

Any help would be very appreciated.

-Marc

**Comment by zooba** [comment]
This is actually a missing feature on our side - pyomo uses special magic to create a package without actually putting an `__init__.py` file in it, and so when we are scanning for code files we ignore it. The reason it works in Python is because there is a namespace package definition, which is effectively some runtime code that loads the modules at startup. Because we avoid arbitrary code execution as much as possible, we can't evaluate this.

The easiest fix is to go to `Lib\site-packages\pyomo` and create an empty `__init__.py` file. This generally should not break anything[1], as the file is only omitted to avoid install/uninstall conflicts.

We have some ideas about how to fix this in the general case, but haven't been able to dedicate the resources to it for this release. I also spotted some other related limitations, so I'll file a few issues from this and we'll try and get to them for our next release - it's too late now for 2.2 unfortunately, so the workaround I describe above will have to do.

1: It depends whether submodules use `import pyomo.my_name ...` to access their own modules or just `import my_name...` - the latter is technically incorrect but often works in this case.

**Comment by MMeketon** [comment]
Thank you!

At first, adding an empty __init__.py file did not work, despite refreshing the DB and stopping/starting VS.  But then I added an empty line __init__.py and it worked.  I successfully ran my first (albeit simple) model in Pyomo from VS.

**Comment by denfromufa** [comment]
this was discussed before:

https://pytools.codeplex.com/workitem/2817
