### ISSUE TITLE
ptvs mixed-mode is TOO SLOW for cpython embedded in .net using pythonnet

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#578]
I'm able to get cpython (embedded in .net using pythonnet) debugged using mixed-mode in ptvs (native, managed 4.0+, python attached).
But it is TOO SLOW. It took about one hour to get to my source, and all of that time was spent tracing third-party packages. I can send you the output log in email.
Managed 4.0+ and python combination does not work.

**Comment by int19h** [comment]
Managed/Python without Native in the picture is never going to work - we rely on the Native debugger to provide some functionality that we wrap. We should be warning about this when debugging starts, though, rather than failing silently.

Regarding it being slow, there are two primary contributors to this. The first one is detection of exceptions - this basically works by setting a native breakpoint inside `PyErr_Set*`. Because Python uses exceptions a _lot_, even inside interpreter guts (so they're both raised and caught in native code), this gets hit a lot, too; and breakpoints are slow because every time one is hit, the process is frozen and then unfrozen. If you're on VS 2015, as of 2.2. you can suppress this by disabling stopping on _all_ exceptions in Debug -> Exceptions.

The second contributor is the handling of code loading. That's another breakpoint that basically gets triggered every time a new code object is created. If your codebase is large, and particularly if you have lots of small functions and classes, this is also going to be hit a lot. Back when this was implemented, there wasn't really any better way to work around this if you want module names to be reported in stack traces, but this may have changed - I will look into ways to avoid this slow path in future releases.

**Comment by denfromufa** [comment]
I just tried yesterday with Python 3.5, 64-bit and pythonnet 2.3.0 - the mixed-mode debugging is not working anymore. PTVS can break in python code, but cannot step through it, instead debugger jumps to C# code.
What kind of troubleshooting info do you need or I can just share solution with Python & c# projects to reproduce this.
I would like to get this working by PyData.

**Comment by denfromufa** [comment]
@int19h I don't know what you guys did, but the speed of debugging improved significantly in VS 2017:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython
