### ISSUE TITLE
Python Unittest Test Explorer no longer searching subfolders in 16.3.3

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#5851]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/771449/python-unittest-test-explorer-no-longer-searching.html)._

---
<p>[regression] [worked-in:16.3.2]<br>
I have unit tests in <strong><em>&lt;project&gt;\</em>data\tests</strong> and that’s been fine until the update this morning but now I have to explicitly set <strong>Root directory:</strong> data\tests to find them which is a problem as I have other <strong><em>&lt;project&gt;\&lt;folder&gt;</em>\tests </strong>folders elsewhere.</p><p><strong>Root directory:</strong> data also finds no tests. It seems it’s not <strong>Root directory</strong> but <strong>Test directory</strong>.</p>

---
#### Visual Studio Feedback System on 10/10/2019, 06:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bschnurr** [comment]
Sorry to hear you're having issues.

In the mean time, I would try adding __init__.py to your test folders, for more info on unittest discovery see this https://docs.python.org/3/library/unittest.html

Another solution might be to manually add your test folders to the interpreter searchpath. project settings->Debug->searchpaths

You could also try using pytest as your test framework, since it also supports unittest definitions.

**Comment by TonyWhitley** [comment]
Thanks, I never knew the bit about "_In order to be compatible with test discovery, all of the test files must be modules or packages (including namespace packages) importable from the top-level directory of the project"_ and haven't had an __init__.py in my test folder but it's been working for years.

Anyway, adding one fixed the problem.

**Comment by sterred** [comment]
Hi, found this topic while googling for a solution to my problem. I do have the `__init__.py` files in all my test(sub)folders. Nevertheless, I still need to explicitly set the **Root Directory** to the particular test folder where a test is in. If I define the **Root directory** as the main folder called `test\`, it will not find the tests that are in `test\subfolder1\` or `test\subfolder2\`, etc. Adding the subfolders paths to Debug>searchpaths also does not help. What else can I do in Visual Studio 2019 so that ALL my tests in all subfolders are discovered? My current work around is that I adapt the **Root Directory** each time I want to run a test in a different folder. Which is of course quite cumbersome. I've got Microsoft Visual Studio Professional 2019, Version 16.6.3.

I would appreciate your help! Thx

**Comment by sterred** [comment]
Update: solution has been found: by using as **Root Directory** the main folder and two dots as subfolder, it will discover all tests in all subfolders under the main folder! (**test\\..**)
![image](https://user-images.githubusercontent.com/71386513/94654625-9ed9fe00-02fd-11eb-8c09-8f7300e26074.png)
