### ISSUE TITLE
Disable IntelliSense only works after close and reload python project.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6201]
**Steps to Reproduce**
1.Create Python project in vs
2.Typing code
```
import decimal
decimal.
```

**Expected behavior**
Disable IntelliSense(Tools/Options/Python/Language Server) is not selected by default, so the code's IntelliSense works.
When Disable IntelliSense is selected , the IntelliSense, go to definition, find references, refactor rename and a lot more should be disabled and does not work.

**Actual behavior**
When Disable IntelliSense is selected , the IntelliSense, go to definition, find references, refactor rename also work well, I need to close this  python project and reopen it, these functions can only be disabled.

**note**
In python workspace, I should reopen workspace to enable this feature.

**build info**
![image](https://user-images.githubusercontent.com/39871640/90103279-d0f6c700-dd74-11ea-86aa-3d2cf53ba0e6.png)

**Comment by huguesv** [comment]
This is by design. This is a setting that will be changed infrequently, so I did not want to potentially introduce more problems by trying to shut down existing IntelliSense. I considered putting "Disable IntelliSense (requires restart)" as the label, but that was technically not true, since all you need is to reload your existing file/solution/workspace. Hopefully the few users that need this option will figure out they need to do that.
