### ISSUE TITLE
Intellisense in Live Share client is not correct.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6212]
**Steps to Reproduce**
1.Typing code in python file in client.
```
import decimal
decimal.DT
```

**Expected behavior**
Typing only letters that are at the start of words, such as 'DT' to find 'DecimalTuple', like this:
![image](https://user-images.githubusercontent.com/39871640/90375567-b475ca00-e0a7-11ea-8622-17656361c8c3.png)

**Actual behavior**
Only the first letter can be located, like this:
![image](https://user-images.githubusercontent.com/39871640/90375621-c8b9c700-e0a7-11ea-858a-3aecd44d39c7.png)

**build**
![image](https://user-images.githubusercontent.com/39871640/90375724-ee46d080-e0a7-11ea-94f1-2d70d45fa0b0.png)

**Comment by huguesv** [comment]
This happens because the filtering is done by the IntelliSense implementation in: PTVS for the host, LiveShare for the client.

PTVS has more advanced filtering fuzzy matching capabilities that aren't present in the LiveShare IntelliSense implementation.

So it's the expected behavior. Things will change slightly when we integrate Pylance, because Pylance does some of the filtering on the language server, so the results will be more similar between LiveShare host and client.
