### ISSUE TITLE
Python Unit Test disappearing

### ISSUE THREAD

**Issue by cebess** [microsoft/PTVS#6245]
I've been playing around with Python in Visual Studio Community edition. I am fairly familiar with VS but not in the Python support. Python seems to work well, but sometimes when I am creating a unittest, I'll include the include line and the test disappears from the test explorer. For example:

I have temp.py python code that I'd like to test

and create

test_temp.py

It shows up in the test explorer (since I have told it I want to test using unittest). But sometimes when I add in the include at the top:

**import temp**

or

**from temp import ***

the test_temp test will disappear from the test explorer. If I remove the line containing the import, the test reappears in the test explorer -- but doesn't work since it doesn't know the function/class.

Any idea what might be happening?!??! I am running Version 16.7.1 of Visual Studio Community Edition.

Thanks

**Comment by cebess** [comment]
I think I figured this out. If there is a syntax error in the temp.py I mentioned above, the test disappears. Once the syntax error is fixed, the test reappears.

**Comment by huguesv** [comment]
Yes, that is the expected behavior. The discovery is done via the same mechanism that unittest and pytest use when running tests via command line. This ensures that the discovery results are the same whether you use the IDE or command line, but it does introduce the same requirements as when running from command line: the code must be loadable without errors by the Python interpreter. Discovery is done when a file is saved, so that provides a bit of control over when you want Test Explorer to refresh.
