### ISSUE TITLE
My custom snippets are not working with VS 2015 and PTVS 2.2

### ISSUE THREAD

**Issue by Luis-Palacios** [Microsoft/PTVS#631]
Hello,

First let me thank you all for this awesome tools but i have an issue with the last version.

I've made some snippets to work in django templates such as block and for, etc. They were working great with VS 2013 and PTVS 2.1 but now that i've updated to VS2015 and PTVS 2.2  they are not working properly.

This is what i mean:

intelisense is working

![screenshot_1](https://cloud.githubusercontent.com/assets/4844997/8793431/b6ad52a0-2f33-11e5-958c-ed9fbb67b1f3.png)

after i hit tab tab, so far so good

![screenshot_2](https://cloud.githubusercontent.com/assets/4844997/8793537/aa817946-2f35-11e5-9fd0-a713cd1d0c21.png)

but once i write the first item name and hit tab, instead of switching to next item it add a space

![screenshot_3](https://cloud.githubusercontent.com/assets/4844997/8793563/0127075c-2f36-11e5-962d-236503681e4d.png)

and if i hit enter

![screenshot_4](https://cloud.githubusercontent.com/assets/4844997/8793567/08fc3ab0-2f36-11e5-968a-3bcffdbc2986.png)

this is the code for the [snippet](https://github.com/LRPalacios/vs-django-snippets/blob/master/djangofor.snippet) and i've tried comparing with one of the native html snippets such as form which is working normally for me leaving the code like [this](https://gist.github.com/LRPalacios/f8a45e17882d02db4989) but the problem persist

any idea of what could be going on?

**Comment by zooba** [comment]
We've just added support for Python code snippets, so it may be affecting this editor (though I don't recall us making any changes over this side, so I could be wrong).

We'll take a look.

**Comment by zooba** [comment]
Oh wait, did you upgrade to VS 2015 at the same time? (Title suggests you did, but it's not clear in your post.) That could also be related, as *a lot* of things could have changed in the HTML editor.

**Comment by LRPalacios** [comment]
Yes i notice the new python snippets pretty cool feature, and yes i've instaled VS2015 and then PTVS 2.2 in VS2015

**Comment by LRPalacios** [comment]
FYI,

I've tried in VS 2013 with PTVS2.2 and is doing the same, the snippets only work with PTVS 2.1

**Comment by zooba** [comment]
Yeah, I suspect it's due to us properly supporting snippets in Python, so where before we were inheriting the HTML behavior in the Python zone, now we're confusing VS by having a Python zone within an HTML snippet.

We have someone on the team now who knows the HTML editor well, so I'll see if he can help us find the issue.

**Comment by LRPalacios** [comment]
I discover something, the snippet start acting strangely when the cursor gets inside a {%  %}.

Example:
Using this boostrap modal snippet:

![screenshot_24](https://cloud.githubusercontent.com/assets/4844997/11157651/44bc3a04-8a18-11e5-97af-55b16a2b8af8.png)

I set the id and hit tab:

![screenshot_25](https://cloud.githubusercontent.com/assets/4844997/11157666/5416e1e8-8a18-11e5-9e59-516e4d8d99f4.png)

so far so good, but then i add a {% trans %} and hit tab:

![screenshot_26](https://cloud.githubusercontent.com/assets/4844997/11157678/6e45c368-8a18-11e5-99ca-4a63a37aff58.png)

instead of moving the next part of the snippet it add the spaces:

I hope this help, i am really missing the snippets for django html in the editor

**Comment by LRPalacios** [comment]
still not fixed on VS 2015 Update 2 and PTVS 2.3 :(

**Comment by zooba** [comment]
Yeah, sorry about that. I made a few attempts to debug the issue but didn't figure out how to fix it. We also had some other issues come up that are nearly forcing us to abandon integration with the HTML editor completely :( (turns out we aren't actually supposed to be extending it, which is why there are problems)

Still no ETA on when we may get it fixed - depends very much on what we get time to work on.

**Comment by LRPalacios** [comment]
All right thanks for your answer, i can survive with this, i will like to somehow help, i've been a c# developer for quite a long time but taking a look a the code it was very difficult for me to understand what was going on or even where to start, is there any other resource to help get started the developers that wants to contribute?

**Comment by zooba** [comment]
Unfortunately, you'd be diving in the deep end here - even the people who work on this aspect of the editor full time don't want to have to debug this :)

We'd love to have you contribute though. The "help wanted" tag on issues means we think it's a good place to get started, generally because the change is going to be fairly limited in scope. Feel free to check out some of those (we don't have written resources, mostly because there haven't been enough contributors that we've been unable to help them all in person).
