### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6349]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/RuntimeError/1300617)._

---
<p>I am a python user and I installed pandas in python but it is not working it is showing &quot;RuntimeError: The current Numpy installation ('C:\\Users\\Dhruv Kaushik\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86&quot; how should I fix it plz suggest me</p>

---
#### Feedback Bot on 1/4/2021, 09:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
An Insider Preview Windows build with the fix is now available. Build 20270 is now in the Dev Channel: https://blogs.windows.com/windows-insider/2020/12/03/announcing-windows-10-insider-preview-build-20270/. If you are affected by this issue and want to test against the fix that will come via Windows Update, you can use this build. This is an insider build with other changes included, of course, so it is not entirely representative of the version that will be serviced, but it can be used to test for specific cases where the bug used to reproduce.

We are still on schedule for servicing Windows build 19041 (the current release version) at the end of January 2021.
