### ISSUE TITLE
"Attach to Process" for Python/C++ processes says it will hit C++ breakpoints when it won't

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6350]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Attach-to-Process-for-PythonC-processe/1055062)._

---
<p>[Update: changed title to reflect a potential mitigation from the discussion.  When attached to a Python/C++ process but only debugging Python code, the debugger still indicates that C++ breakpoints are active though they will not be hit.]</p><p>I am debugging a library for Maya, a C++ application that embeds Python.</p>
<p>When I select “Attach to Process” on maya.exe, if I leave “Attach to” set to “Automatic”, it detects “Python code” and will not hit C++ breakpoints.  (It will hit Python breakpoints though, as expected)</p>
<p>If I instead manually select “Native” in the “Select…” box, I can attach to Maya’s native code and the debugger stops at the C++ breakpoint correctly.</p>
<p>I’m not sure now whether this happened in VS2017 or earlier.</p>

---
#### Feedback Bot on 5/29/2020, 02:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Chris Bevan ☕ [MSFT] on 5/29/2020, 09:45 AM: 

<p>Why is this important?  Every developer who tries to debug our C++ library seems to hit this problem and digs around trying to figure out why breakpoints aren't working.  We can add this to our list of "troubleshooting tips", but not everybody will spot it.</p>

#### Feedback Bot on 6/10/2020, 10:38 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 6/16/2020, 04:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Hugues Valois [MSFT] on 6/17/2020, 10:16 AM: 

<p>Sorry, as you can probably guess from my reply, I did not see the existing conversion (our internal feedback ticket didn’t show it). I’m reactivating for now.</p>

#### Chris Bevan ☕ [MSFT] on 6/17/2020, 11:00 AM: 

<p>No problem - it's not obvious in the list of feedback here so that's understandable!</p>

#### Feedback Bot on 7/2/2020, 11:17 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Chris Bevan ☕ [MSFT] on 7/6/2020, 09:40 AM: 

<p>I changed the title to reflect the discussion, in the hope that this will make the bug seem more actionable.</p>

---
#### Austen Ott [MSFT] solved on 6/16/2020, 03:12 PM, 0 votes: 

<p>Automatic engine selection picks the single highest priority debugger based on the types of code detected.<br>
In this case, both Python and Native code have been detected, and Python is “higher priority” (every process is also native, so if another runtime is present that’s more likely to be the one of interest).<br>
Manual selection of debug engine will let you override and pick the type (or types, multiple engines can usually be selected) of code that you wish to debug.</p>

#### Chris Bevan ☕ [MSFT] on 6/16/2020, 04:08 PM: 

<p>Maybe there's not an obvious choice as to what the debugger should attach to, assuming that it can't attach to both at once.  (We could discuss heuristics but I realize those are of debatable ROI)</p><p>The reason that I reported this is because it lost several hours of developer time for us on the team collectively, and will continue to do so for others.  Everybody goes through this same process of trying to discover why the debugger "is not working", and later discovers that it's actually invisibly doing something different from what we expected.</p><p>Rather than working out what the best code type to attach to would be, why not make the debugger just indicate on the breakpoint that it won't be hit?  This already happens in other cases, such as when the source code is different, etc.  Using that notification system with a tooltip of "This breakpoint will not currently be hit.  The debugger is not attached to this type of code." would have been enough for us to figure out what was going on.</p><p>This will probably hit every major VFX application and plugin developer, since they're generally all massive C++ applications with native plugin APIs and also Python embedded.  You'll probably find many of them reporting the same issue whenever they switch to VS2019.  If they're attaching a VS debugger, they probably want native code in this case; Python debugging is more of a bonus.  We normally use VS Code for Python.</p>

#### Austen Ott [MSFT] on 6/16/2020, 04:52 PM: 

<p>Ah - so it's not just that the breakpoint doesn't hit, it's that it doesn't hit while showing as being successfully created.</p><p>This is an issue in the python debug adapter, so I'm reactivating and sending it to the appropriate team.</p>

#### Hugues Valois [MSFT] solved on 6/17/2020, 09:32 AM, 0 votes: 

<p>Thanks for the feedback.</p>
<p>This is the intended behavior for automatic mode. If the process as a win32 module loaded that is recognized as the python.dll (where the exact name includes a version number), then the regular Python debugger is used.</p>
<p>To get both C++ and Python debugging at the same time, select Native and Python, like in the Select Code Type screenshot at <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019#enable-mixed-mode-debugging-in-a-python-project">https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019#enable-mixed-mode-debugging-in-a-python-project</a></p>

**Comment by judej** [comment]
Already answered on 6/17/2020

**Comment by mscbevan** [comment]
Hi - please note that this issue has not been resolved.  The answer on 6/17/2020 reactivated the bug because it had been closed due to a misunderstanding.  This is still a bug that affects my team and, presumably, anybody else who develops C++ applications that also embed Python.

**Comment by mscbevan** [comment]
Also please note that due to the unusual ordering of the replies, the "This is the intended behavior" comment looks like it was the last, but this was actually a misunderstanding; it's not the intended behavior.  Please note this comment:

> Sorry, as you can probably guess from my reply, I did not see the existing conversion (our internal feedback ticket didn’t show it). I’m reactivating for now.

**Comment by int19h** [comment]
FWIW, the reason why Python debugger is different in that regard from e.g. C++ is that the latter can actually enumerate loaded modules and their symbols, and thus it knows exactly which source files are present in the process, and which aren't - and mark breakpoints as resolved/unresolved accordingly. It doesn't actually look at file extensions at all (which is why stuff like e.g. .inl files and other rarely seen patterns "just work").

There's no equivalent mechanism in Python; indeed, there isn't even any reliable way to get the complete list of source files currently loaded in the process. Thus, it assumes that *any* file is a potentially valid Python program that might be executed by the process. 

It could check file extensions, but it's not actually a hard requirement for Python source files to be named .py - indeed, it's not uncommon to see extensionless scripts (meant to be used with chmod+x on Unix-likes, but they work just fine on Windows as well). Furthermore, there are some common scenarios where a .py file is actually native code - for example, when using Cython, and requesting it to produce output with `#line` directives, the resulting symbols will reference the original .py[x], but you'd still need a native debugger to them. 

This isn't a regression, either - it worked like this ever since we introduced the feature back in PTVS for VS 2012.

**Comment by mscbevan** [comment]
Interesting; thanks for the explanation.  I guess maybe having the Python debugger detect whether a breakpoint that it knows about is a C++ breakpoint or not could be a little tricky.

However, from a user's perspective, what every member of my team says when first trying to debug our C++ code is: "Why doesn't the Visual Studio debugger work?"  (We tell people and have wiki pages etc., but everyone forgets in ramp up)  I guess we're less concerned about which module handles the issue or which way; just that "Automatic" surprisingly attaches to Python code *only*, and that means that C++ breakpoints won't be hit, although they're displayed as if they will be.

I think this will happen for all C++ apps with embedded Python - e.g., basically all VFX software.  Most VFX software is cross-platform, though, so maybe devs on other software just debug on other platforms instead; not sure.

**Comment by int19h** [comment]
Since *every* Python process is technically also a native process (since even python.exe is just a host app written in C using standard Python hosting APIs; not any different from AutoDesk, Maya etc), if "Automatic" was fully truthful, it would always enable Native.

And if the mixed-mode debugger had full feature parity with the pure Python one, that wouldn't be an issue - we'd simply always attach in mixed mode, and that would be that. But, unfortunately, that is not the case - and, due to the constraints placed by the native debugger on evaluation of Python code (e.g. consider the case where you hit a breakpoint while Python GIL is held by something), it's unlikely that the mixed-mode debugger will ever have feature parity.

Thus, we have to consider the probabilities of various scenarios here when picking the default. In general, it is more common for our users to only need Python debugging, and it would be surprising for them if they got the less-featureful Python debugging experience offered by the mixed mode debugging, especially once their expectations have already been set by the non-attach scenarios. Hence why it defaults to Python only, with Native being an opt-in that somewhat degrades your Python experience. 

One thing we could do here is make that default configurable - that is, give you some checkbox in Tools -> Options that would enable detecting all Python processes as Python+Native in the Attach dialog. Would that help?

**Comment by mscbevan** [comment]
Thanks for looking for options, but I don't think that would help, really.  Once people know about the problem, they (like me) just specify "native" or "Python" in all cases and stop using "Automatic" - so I can't imagine that having an option would help, because if they knew to set the option, they'd also know to just switch the debugger type.  If there were a way to set a default for a repo, that could be useful, but I imagine that's a bit more complicated.

Interesting to hear about the mixed-mode debugger; I hadn't really thought about how that would work, and just assumed that it was just picking a debugger for each breakpoint, or something.  (Easy to make a mental shortcut when we don't have to implement it!)

So I guess maybe there's no easy way to solve this.  If anyone can think of one, it'd certainly save some developer pain; but then, I guess maybe not that many people are seeing it if this is the only report, so ROI on a fix might be low.  Thanks for the explanations anyway!
