### ISSUE TITLE
Intellisense missing when chaining?

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#644]
Hi

I noticed that when I have a Dataframe, I do not get the right autocomplete options after a groupby: I do not see an aggregate option. However, if I save the result of the groupby in to another variable, and then try to aggregate, I do see the correct options.

E.g. df_Data.groupby(['A',]).#No aggregate autocomplete found - the closest is _agg_by_level
v = df_Data.groupby(['A',]); v.# Now I see the autcomplete agg method.

Also, is there a way to prevent the autocompletion? In the first case, if I type agg( manually after the groupby, it replaces the agg by _agg_by_level(.

This is on PTVS 2.2, with VS2013.

Thank you

**Comment by int19h** [comment]
Is this in the Interactive Window?

**Comment by sriksrid** [comment]
Hi
This happens both in the interactive window and the editor.
Thank you

**Comment by int19h** [comment]
In the interactive window, this is by design because it uses live object inspection to construct completion lists, and to avoid undesired side effects, it will stop trying to figure something out if it sees a function call like that (because otherwise that function would effectively be called every time it needs to construct the list, and it has no way of knowing whether the function has side effects or not).

In the editor, I would expect that you don't actually get completions either way, probably because groupby is too complicated for the analyzer to handle (and possibly also because it involves native code, and doesn't provide information about its return type). If you can confirm that this is so, then it's by design.

**Comment by sriksrid** [comment]
Hi

I'm not sure how to confirm that the function involves native code. However, your explanation does clear things up.

Thank you

**Comment by zooba** [comment]
There are instructions for disabling those completions on [our wiki](https://github.com/Microsoft/PTVS/wiki/Editor-Features#completions) (and yes, I find them fairly annoying there too... haven't figured out the best way to solve that yet as they are pretty nice in many other places).
