### ISSUE TITLE
Dropdown menu appears when typing a word

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6452]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Dropdown-menu-appears-when-typing-a-word/1359915)._

---
[severity:It's more difficult to complete my work]
Hello, I’m using VS 2019 Community, my environment is Python 3.7, and I’m editing a .sh script in my solution. When I type part of a word, a drop-down list of words appears. It is extremely annoying! How can I disable this drop-down list? Of note, when I type part of a word in a .py script within the same solution, the drop-down list thankfully doesn't appear. (I had previously disabled IntelliSense for Python, so maybe that explains the difference in behavior?)

---
#### Feedback Bot on 3/7/2021, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AJVincelli** [comment]
It looks like my Feedback issue was automatically added to this GitHub repository. I'm not sure it belongs in PTVS, considering the behavior is with .sh scripts in my VS solution?? Sorry if it got bot-dropped here mistakenly. But I still definitely have this issue, and I'm hoping that it can be resolved!

**Comment by AJVincelli** [comment]
Microsoft, please fix this issue! If you need any more info, just let me know.

**Comment by greazer** [comment]
Hi @AJVincelli, you're right that this bug has been miscategorized as being related to Python for VS which is a set of tooling I manage. The fact that it moved to github was just because of the association with Python.

That being said, to try and help you anyway I'm wondering two things:
- What is the intent of your .sh file? Can I assume it's a bash script?
- What extensions do you have loaded in VS? By default, it appears to me that there is no auto-complete or highlighting in .sh files. However, there are extensions you can load that will enable it. I'd think that removing that extension (assuming you have one) will do the trick.

**Comment by AJVincelli** [comment]
Hi @greazer, thanks for your reply! Yes, you are correct that the .sh script is a bash script. Though I don't recall explicitly installing any extensions, if I go to Extensions --> Extension Manager --> Installed --> All, I can see three extensions: Visual Studio IntelliCode, NuGetRecommender, and Visual Studio Rich Navigation. I just disabled all three, and the dropdown menu still appears. Is there anything else you can recommend??? I can't believe this is an issue, and that it hasn't been solved yet! I feel like it must just be a tiny setting somewhere that I'm not seeing. Thanks so much for your help.

**Comment by AJVincelli** [comment]
Here is a screenshot of the ridiculous and annoying dropdown menu that appears whenever I type a character in a .sh script within a Python-environment solution:
![Dropdown Menu](https://user-images.githubusercontent.com/46507729/126736149-ba12c05f-881e-408f-803d-bc016c69b0fa.png)
