### ISSUE TITLE
Native code debugging does not work

### ISSUE THREAD

**Issue by mikolajpiecuch** [microsoft/PTVS#6456]
**Describe the bug**
I have c++ project which is tested in python (I have written python interface in pybind11). Some time ago I was able to debug python and c++ code simultaneously with native code enabled. I upgraded VS19 to to the newest version and wanted to try Python 3.8 last week. Unfortunately, since then I can't debug with native code enabled. I have several exceptions while debugging is starting. I tried reinstall VS19 to previous version (16.7.6 and 16.8.6) and reinstall python to 3.7. It is still not working. 

**Steps to Reproduce**
1. Install newest VS19
2. Try debug python and c++ project with native code enabled

**Expected behavior**
Debugger is attached without exceptions

**Additional context and screenshots**
Exceptions after click debug on some test with native code debugging enabled:
1. Python37\Lib\ctypes\__init__.py
![image](https://user-images.githubusercontent.com/12502108/112313758-80e7c780-8ca8-11eb-8450-4c8d5374a033.png)
2. Python37\Lib\genericpath.py
![image](https://user-images.githubusercontent.com/12502108/112313883-a543a400-8ca8-11eb-8325-5f0192a358f4.png)
3. Many exceptions from testlauncher.py:
![image](https://user-images.githubusercontent.com/12502108/112313947-bab8ce00-8ca8-11eb-9f42-e9e26cdaf460.png)
![image](https://user-images.githubusercontent.com/12502108/112314027-d2905200-8ca8-11eb-9c8b-f860974415e1.png)

Pytest is of course installed because I can debug only python without native code debugging

**Comment by int19h** [comment]
These exceptions are most likely non-fatal (certainly the case for the first two, given that they're inside `try` blocks). The last one is likely reported in Python import machinery when it tries to find the module. You should be able to just press F5 to continue running; uncheck the "break when this exception type is thrown ..." so that you don't hit it again.

Pure Python debugger behaves differently, because by default it doesn't report exceptions at the point where they're raised, and instead waits for them to bubble up all the way to the top of the stack; if they do, it considers the exception unhandled, and reconstructs the original call stack from Python traceback. Unfortunately, this technique doesn't work in mixed-mode. Thus, when you enable Native, exceptions are always reported when raised, and there's no way to distinguish handled/unhandled. So you have to fiddle with checkboxes manually, to make sure that only the ones that you actually care about are reported.

**Comment by mikolajpiecuch** [comment]
Thank you for your answer. Uncheck specific type of exception doesn't stop reporting all types of that exceptions in all projects? I would check it out, but I encountered another problem after testing previous issue a lot. Now, debugger is never attached - code is executed in background. I noticed that arguments to testlauncher.py are invalid and never change, even after disabling native code debugging:

Command copied from test output:
(...)\testlauncher.py pathToMyProject pytest "" 0 "" "" dummyfilename myTestCase --junitxml=(...)\junitresults_b18e6c13-6311-41bb-9cb5-4e9412b16545.xml --rootdir=pathToMyProject -o junit_logging=all -o junit_family=xunit1

Restarting VS or even my computer does not help. Is this known bug? Does exists some workaround for this issue?

**Comment by int19h** [comment]
Exception Settings in VS are global, not per-project (since they also apply to multi-project debug scenarios, Attach to Process etc). So yes, unfortunately this means that you'd have to adjust them as needed if switching projects.

Regarding the command line - it sounds like a different issue; can you file it as such, so that we can track it properly? A step-by-step repro, mentioning things such as various paths involved, and names of tests you're running, would also be helpful.

**Comment by mikolajpiecuch** [comment]
I've just reinstalled VS and problem with command line arguments disappeared. If I see it again I will open new issue with proper information. 

Proposed solution to first problem works fine. I restored default exception settings for python exceptions. Thank you for your help!
