### ISSUE TITLE
Visual Studio 2013 crashes, sends error and restarts randomly.

### ISSUE THREAD

**Issue by joeizang** [Microsoft/PTVS#646]
Visual Studio crashes and restarts randomly after I installed PTVS 2.2. I am running Visual Studio 2013 Update 4 and I mostly do Asp.net MVC dev. Had to revert to PTVS 2.1. Dunno where to find the details of the crash would have added it to this post. Any tips on how to get them.

**Comment by zooba** [comment]
The log in Tools, Python Tools, Diagnostic Info should include crash details, but you can also find them in Event Viewer, typically listed as ".NET Runtime" errors. If you are allowing error reports to be sent to Microsoft then we'll eventually find them that way too.

**Comment by joeizang** [comment]
ok thanks will do that.

**Comment by pushrbx** [comment]
Same happens for me too. I get Stack Overflow exception with my django project.
"The program '[7444] devenv.exe' has exited with code -1073741571 (0xc00000fd) 'Stack overflow'."
I have Visual Studio 2013 Update 5, PTVS 2.2, Windows 10.

**Comment by zooba** [comment]
Are you able to share your project with us? Stack overflows are unfortunately difficult to debug unless we can reproduce the error ourselves.

You can email an attachment or a link to ptvshelp@microsoft.com (which only includes our dev team).

**Comment by pushrbx** [comment]
I've sent my project. (2 emails, because i forgot about the attachment in the first email)

**Comment by zooba** [comment]
Still digging, but it looks like you may have set a record for the largest completion DB I've ever seen :)

We probably need to refactor some of our lazy loading so that we aren't going too deep when loading that much information. Can't promise that will happen for PTVS 2.2.1, unfortunately, but I'll see what can be done.

I'll post here when I have more details about what's involved, but there's no good workaround unless you can remove some packages from your environment. You may see some benefit from finding `Microsoft.PythonTools.Analyzer.exe.config` and adding rows like:

```xml
    <add key="django_extensions.CallDepth" value="0" />
```

For some of the bigger packages, then delete the `.ptvs` folder again. This will make analysis faster (and more likely to be incorrect), but may also bring down the overall size and make things possible to load.

**Comment by zooba** [comment]
You'll find that file in PTVS's [install directory](https://github.com/Microsoft/PTVS/wiki/Where-is-PTVS-installed).
