### ISSUE TITLE
Do you still do the "Shell" releases

### ISSUE THREAD

**Issue by James-Parsons** [Microsoft/PTVS#651]
I was reading a rather old blog post on PTVS at: http://www.hanselman.com/blog/OneOfMicrosoftsBestKeptSecretsPythonToolsForVisualStudioPTVS.aspx

I was wondering if you still do the release that contains only VS Shell and PTVS preferably with Visual Studio 2015. If so, where can I find these releases, if not, this is a feature request to bring them back.

**Comment by int19h** [comment]
We stopped doing these since VS Community appeared, as it has a strict superset of features that Shell offers (unlike Express releases that had some things missing that you could get in Shell).

Can you tell a little bit more about your scenario - i.e. why you would prefer Shell to either Community or Express?

**Comment by James-Parsons** [comment]
Last time I tried to intstall Community 2015, things went berserk and I did
a factory reset.

**Comment by zooba** [comment]
Was that before or after July 20th?

I don't believe we've blocked installations into shell yet, but it's very likely we have a dependency on some component that is not included. Feel free to try it, but we strongly recommend using at least Express for Desktop if not Community.
