### ISSUE TITLE
How can I specify search paths for unusual modules in PTVS?

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/PTVS#652]
I am using VS2013 and PTVS 2.2 to develop a Python application that uses Kivy. PTVS intellisense is not finding a couple of the Kivy modules, and I would like to ask how to define search paths for these.

1) garden.graph

The Kivy garden.graph (https://github.com/kivy-garden/garden.graph) class is defined in:

`C:\Kivy-1.9.0-py3.4-win32-x64\kivy34\kivy\garden\__init__.py`

Can PTVS support a search path where the .py filename is not the same as the class name?

2) Another Kivy module: kivy.properties is defined in:

`C:\Kivy-1.9.0-py3.4-win32-x64\kivy34\kivy\properties.c`

(with associated .pxd, pyd and .pyx files)

Can PTVS cope with this?

Best regards

David

**Comment by zooba** [comment]
We support the same lookup semantics as Python does (anything else is a bug), so the first case is definitely supported, but the search path is a little unobvious.

Generally, you need to leave the importable name out of the path. So for the first case, you'd add `...kivy34\kivy` as the search path and then type `import garden`. Alternatively, you might add `...kivy34` as the search path and then `import kivy.garden` (if there's also a `kivy\__init__.py` file). This is because `__init__.py` is special and the name comes from the containing directory.

For the second case, we may have trouble with an extension module that is in a subpackage. Generally extension modules need to be added as a Reference rather than a Search Path, but this does not provide any way to use a dotted name. So it may end up as `import properties` rather than `import kivy.properties`. Really, we need to add support here for automatically analysing native extension modules on import, which is something we currently don't do (and possibly for a good reason, though I don't remember what that is right now).
