### ISSUE TITLE
How to web publish to Azure without publishing the virtual environment?

### ISSUE THREAD

**Issue by blelem** [Microsoft/PTVS#655]
I would like to publish my ptvs based project to Azure, but without uploading my virtual environment. 
Here: https://azure.microsoft.com/en-us/documentation/articles/web-sites-python-configure/ it is said that "Packages listed in requirements.txt will be installed automatically in the virtual environment using pip. This happens on every deployment, but pip will skip installation if a package is already installed."

I however could not get that to work, using PTVS django project and the VS web publish tool. By default, the web publish tool picks up every files in the project, including the virtual env. So I went ahead and removed my virtual env folder from being published by editing my deployment .pubxml. The publishing goes ok, but apparently the python server doesn't get up and running and all I get is a server error. 

Would there be a blog entry/documentation how to do this properly?

**Comment by zooba** [comment]
I don't have the documentation links handy, but the short answer is:
* git deployment does **not** upload virtualenv files
* VS deployment **does** upload virtualenv files

Because of technical limitations around how these are implemented, we can't really swap these - you get one or the other (but at least you get to choose).

**Comment by blelem** [comment]
Arg! Wish I would have read the manual. It's indeed mentioned here:
https://github.com/Microsoft/PTVS/wiki/Web-Project#templates

But the short answer above was most useful. Thanks.
