### ISSUE TITLE
Image - no such file or directory found

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6554]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Image---no-such-file-or-directory-found/1438140)._

---
[severity:It bothers me. A fix would be nice]
In my python project, in the source code, I have included an image and a wav file and it gives me error that says "no such file or directory found. The image and wav file is located in the repos folder. I even tried to give it full path in the quotation marks. Where should these files be stored and do you include it in the project?

---
#### Feedback Bot on 6/1/2021, 06:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the feedback. We're not 100% sure what the scenario is that your trying to achieve. It sounds as though you've added a wav file and an image to the python project, but when you run your python code, it cannot find those two files. If that's the case, then the problem is likely in your code. You need to make sure that either the current directory that python is running in contains those files. or you need to specify the full path to those files in your script.
