### ISSUE TITLE
The browser could not automatically start after set webBrowserUrl in launch.vs.json file.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6637]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/127970802-4b071dde-a911-4573-9bc3-b306d16a5590.png)

**Steps to Reproduce**
1. Open cookiecutter explorer
2. Load the following template: https://github.com/brettcannon/python-azure-web-app-cookiecutter
3. Keep default values and click Create and Open Folder
4. Right click on webapp.py and choose Debug and Launch Settings
5. try changing the following attributes in the json:
     webBrowserUrl: set it to http://127.0.0.1:5555 
![image](https://user-images.githubusercontent.com/59192491/127971214-dab42cb2-1901-446a-ba30-d104a3af90ac.png)

**Expected behavior**
The browser will automatically start when you press F5.

**Actual result**
The browser could not automatically start
![image](https://user-images.githubusercontent.com/59192491/127971276-04911983-9019-4983-8deb-8e91dd94b217.png)

**Comment by rchiodo** [comment]
I don't think this will work because the app doesn't output the localhost address on startup.

This code here is responsible for connecting to a web URL:
https://github.com/microsoft/PTVS/blob/c0bc0fefd0fea5584cbfe520f2e2c97495a3eff1/Python/Product/PythonTools/PythonTools/Debugger/DebugAdapter/DebugAdapterProcess.cs#L63

And it assumes an output message from the debugger comes back with the URL.

**Comment by greazer** [comment]
This is actually working by design. The template needs to be updated to output the url.
