### ISSUE TITLE
The breakpoint is not removed when hit the breakpoint.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6665]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/128983058-d0ee41ca-f42a-408f-83d1-b65707332ec4.png)

**Steps to Reproduce**
1. Create a Python Application project
2. Type the code as following or the code you are desiring 
```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
		s = make_dot_string(i)
		print(s)
	main()
```
3. Check the code works properly by pressing F5 or select the Debug > Start Debugging
4. Set a breakpoint on the "for" statement 
5. Open breakpoint setting
6. Check "Remove breakpoint once hit"
7. Debug and observe

**Expected behavior**
The breakpoint was removed once hit.

**Actual result**
The breakpoint is not removed.
![breakpoint](https://user-images.githubusercontent.com/59192491/128986238-95725ea9-1ee3-4071-828e-acc504cdbbd3.gif)

**Comment by rchiodo** [comment]
We probably don't support this condition.

**Comment by int19h** [comment]
I would kinda expect the removal to be done by VS itself. If not, we'll need to see what this translates to on the wire.

**Comment by int19h** [comment]
I tried to repro this on preview 3. What happens for me there is that the breakpoint actually gets removed (it won't be hit again if you continue running rather than step), but the editor margin doesn't reflect that properly. However, you can see it get removed in the Breakpoints tool window.

@linette-zyy, can you check if this is the same for you? If so, this is definitely a generic VS issue. It might also be worthwhile to check this on a C# project just to be sure.

**Comment by linette-zyy** [comment]
@int19h I try on the lasted build and found this issue is not reproduced.
The breakpoint is removed when hit.
![image](https://user-images.githubusercontent.com/59192491/129324441-d608d3f9-e113-42d8-acca-a9ded04eccf0.png)
