### ISSUE TITLE
file name 'select.py' in python project is unable to debug 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6666]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/file-name-selectpy-in-python-project-/1499678)._

---
[severity:It's more difficult to complete my work]
This strange behavior exists not only in the current beta version, **but also in earlier versions**. **If a file named **'select.py'** in the python project and is set to start, the debug will unable to run totally.** 

In this beta release, an error is reported where earlier versions (such as VS2017) get stuck in the adapter loading interface and end up unexplained.

VS language: zh-chs
OS version: Win10 Pro 20H2
python environment : Anaconda 5.2.0

Maybe you would investigate reasons, or simply ban on (these) keyword(s).

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
I can't repro this problem. Can you include an example project that repros the issue? Thanks.

Here's what I used to test:
![image](https://user-images.githubusercontent.com/19672699/129110545-a79e3e1b-0a51-43e5-9a83-c958796e76a0.png)

**Comment by int19h** [comment]
It might have something to do with the fact that `select` is a standard module, which is imported by a bunch of other standard modules (e.g. `asyncio`). If anything in the app would pull that as a dependency, even indirectly, it would end up loading the local module instead of the standard one, and then the app would likely error out.

**Comment by WHYFred** [comment]
Thank you for your help. This is the ticket I opened. I re-checked my import items and found that the debugger problem would repro as soon as I added **'import nltk'**. So your analysis is probably correct, and some of the dependencies that Python modules has do sometimes produce strange behavior.

I am a full-stack developer, and I notice that VS doesn't seem to be as good at syntax checking in python as some languages such as C#, making simple syntax errors sometimes difficult to troubleshoot. If I understand correctly, errors will only show up in VS after a successful compilation, while errors during compilation can only be viewed in the terminal, which is extremely vague and helpless most of the time.

Of course, some of these problems may be due to the feature of the Python language itself, which makes it less robust in some ways. But the lesson for me is, don't use select as the file name next time. ;-)

**Comment by WHYFred** [comment]
By the way, **another question**, do you change the default Charest of files in VS2022?  If I create a new Python file in VS2022 and open it in VS2017, I get an error message and Chinese characters are not displayed correctly.
![image](https://user-images.githubusercontent.com/88811260/129138282-3b14a490-5d85-47c7-84d8-590475f396d0.png)
![image](https://user-images.githubusercontent.com/88811260/129138384-84cafe13-8bd7-4d0e-9dc7-5d20b19b3d46.png)

**Comment by rchiodo** [comment]
@WHYFred I don't believe we changed the default encoding, but I wouldn't be surprised if VS 2017 didn't handle UTF-8 correctly.
