### ISSUE TITLE
Visual Studio Automation

### ISSUE THREAD

**Issue by tomkcook** [Microsoft/PTVS#667]
Is it possible to script Visual Studio in Python using PTVS?

I mean things like editor automation, interaction with the native C++ debugger etc.

**Comment by zooba** [comment]
Currently no, and we don't have any plans to enable this (mainly because the cost/benefit equation very quickly results in "not really worth it").

You can (theoretically) use IronPython (or possibly Python.NET, or even comtypes) to get access to the DTE object and control VS using that (as we do from C# fairly often), but that is not going to be the same as the old macro support.
