### ISSUE TITLE
Set as current option should be checked and disabled when project uses default

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6718]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/133743824-6056584d-74b8-4700-8b26-fff852c41e4a.png)

**Steps to Reproduce**

1. Create a Python Application. ( The project has a default environment )

![image](https://user-images.githubusercontent.com/82852072/133744354-dca629f9-14e6-408f-975f-198207d60810.png)

2. Add a virtual environment, and uncheck "Set as current environment".

![image](https://user-images.githubusercontent.com/82852072/133744998-236dddd1-d304-4405-9285-15d4312ee9e6.png)

**Expected behavior**

The Project current environment is using the default environment.

**Additional context and screenshots**

The Project current environment is using the new virtual environment.

![image](https://user-images.githubusercontent.com/82852072/133745310-aea85d3d-7ce4-4886-9c38-1a8c040d4f2c.png)

**Comment by ttSpace** [comment]
I can repro in today's build ```17.1.0 Preview 3.0 [32030.14.main]```.

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/185588426-18488af7-1651-4b58-b46e-6d6f8bb69007.png)
I can repro similar situation in today's build

**Steps to Reproduce**
1.Launch VS and open a folder
2.Add a python file
3.Add a virtual environment 'env' in toolbar combo box, **check the 'Set current environment'**
4.After 'env' created successfully, make sure the active environment is 'env' in Python environment node
5.Add a new virtual environment 'env1' in toolbar combo box, **uncheck the 'Set current environment'**
6.After 'env1' created successfully, check the Python environment node


Expected behavior:
The active environment is still 'env'

Actual behavior
The active environment is changed as 'env1'
