### ISSUE TITLE
PTVS 2.2 changes Visual Studio debugger behavior

### ISSUE THREAD

**Issue by seechew** [Microsoft/PTVS#674]
While doing ctypes call from python to c functions. Breakpoint in Visual Studio on the c side no longer work. Once uninstalled PTVS 2.2, everything is back to normal.

**Comment by int19h** [comment]
Can you tell a bit more about the problem? What's the exact sequence of actions that you're trying to perform, and what is the observed behavior?

**Comment by seechew** [comment]
I use C to produce a DLL. I then use Python ctypes to make a python binding to the DLL so that I can drive my DLL from python. I thought it would be nice to be able to debug from Visual Studio 2013, so I downloaded PTVS 2.2. Once the package is installed, I tried to debug my C code. To do that, I insert "raw_input()" to my python driver. The code will halt at "raw_input()" line, then I attach Visual Studio Debugger to python process. Put some breakpoints inside the C code and attempt to let it break there. Now I go back to my command prompt and hit "Enter" to continue my python code. Usually, I can hit the breakpoint, but once PTVS is installed, my breakpoints didn't get hit. I uninstalled PTVS, and repeat the process, and my break points will get hit.

**Comment by int19h** [comment]
When you're attaching to a process, in the Attach to Process dialog, take a close look at the "Attach To" textbox when you select a process in the list (it's right above that list). By default it is set to auto-detect, and will attach to the primary code type that is detected in the process. E.g. if you're attaching to python.exe, it will attach to Python _only_ (similarly, if you attach to a managed process, it will only debug managed code, even if you call into a native DLL).

So if you want to debug C code, you should manually change Code Type to Native. Better yet, check both Native and Python, and then you can set breakpoints in both at the same time.

**Comment by seechew** [comment]
Thank you for the comment. However, using python to drive DLL, the DLL is loaded up by the python process isn't it? At least that is what I am trying to do. Therefore, there is no separate process. I will try your approach tomorrow. However, why will PTVS change the behavior? Without PTVS I can debug just find with python driving DLL.

**Comment by int19h** [comment]
Yes, there is only a single process there. But VS uses different debug engines for different code types running within that process - native debugger for C, PTVS debugger for Python etc. And unless you specifically select the right code types, it will pick one (and just one) by default, and any other code type overrides native.

PTVS changes this behavior because it adds the Python debug engine to VS. Without it, python.exe is not treated specially, and thus native debugger is the only one that knows how to handle it - and so the default code type when attaching will be Native. With PTVS, Python debug engine will detect Python code type within python.exe, and so the default code type for it will be Python. 

This is what you should be seeing:

![image](https://cloud.githubusercontent.com/assets/1175142/9078202/52ccc8de-3aef-11e5-9723-81020aa954d5.png)

The part I've highlighted with the red rectangle is code type selection. Note that it says "Python code". If you pick some other process from the list, it'll probably say "Native code" instead, and this is also what it says for python.exe without PTVS. If you click on "Select", you can pick the specific code types manually, and that way you can check Native for python.exe even with PTVS (or you can check Python and Native at the same time, and then you'll get mixed-language debugging):

![image](https://cloud.githubusercontent.com/assets/1175142/9078217/9b12a230-3aef-11e5-96ad-3e1fe82dd35d.png)

**Comment by seechew** [comment]
I see. I tried it, and it worked as you said. Thank you for point it out to me.
