### ISSUE TITLE
Profiling: Error prompted , Python install from Microsoft Store.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6775]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/140488761-8cd42c8d-7a46-4934-b49a-9b455ca8e37c.png)

OS : Windows 11 Enterprise 21H2
Python install from Microsoft Store

**Steps to Reproduce**
1. Create python application project named PythonApplication2 and typing code in it.
2. Debug->Launch Python Profiling …
3. Checked the option "Open project" and select the current project in drop-down list.
4. Click "Start".

**Expected behavior**

Start without any errors.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/140488074-ec525b16-4199-4080-bbe1-d6fb1ed4ad10.png)

**Comment by ttSpace** [comment]
I can repro in today's build ```17.1.0 Preview 3.0 [32030.14.main]```.

**Comment by StellaHuang95** [comment]
Running `Marshal.GetLastWin32Error()` after [this line](https://github.com/microsoft/PTVS/blob/84add9c25ff26c1f39ab998400a8a66fb16ee60f/Python/Product/Common/Infrastructure/NativeMethods.cs#L38) gave me an error code of 5, which is `ERROR_ACCESS_DENIED`. Seems like the issue is that it does not have access to "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\\python3.8.exe"

**Comment by ttSpace** [comment]
In today's build ```17.3.0 Preview 2.0 [32506.377.main]``` , Python Package```17.0.22119.1``` , I can repro this. 
Python install from Microsoft Store

![image](https://user-images.githubusercontent.com/82852072/167244421-a8167fc7-0b2d-46c2-8de0-97f4b2fce819.png)

![image](https://user-images.githubusercontent.com/82852072/167244266-feae2927-e310-4785-b511-1351f73940c8.png)

![image](https://user-images.githubusercontent.com/82852072/167244311-1d67cc2f-d72c-437b-9624-7a5cd5fb0175.png)
