### ISSUE TITLE
Syntax Highlighting for 'in', 'not in', and 'is' appears to be missing

### ISSUE THREAD

**Issue by lexected** [microsoft/PTVS#6782]
**Describe the bug**
The code editor highlights most of the Python keywords and built-in functions but appears to omit the following keyword expressions: `in`, `is`, `not in`, `is not`.

**Steps to Reproduce**
1. Open a Python code file in the Code Editor.
2. Type in the sample code below
3. Observe the effects of syntax highlighting

**Expected behavior**
I would expect `in`, `is`, `not in`, `is not` to be coloured the same way `for`, `while`, or `pass` are. I understand that `in` and `not in` can be overloaded, and that they could have been left uncoloured to mark overloading when present, but I that is certainly not the case for `is`, is it?

**Additional context and screenshots**
<img width="599" alt="Screenshot_4" src="https://user-images.githubusercontent.com/9163389/141463910-f6bf0fbb-bed6-4e44-abdf-9742da6b5a03.png">

**Sample Code**
```
class ConcreteCompass(Compass):
    invariables: dict

    def __init__(self):
        self.invariables = {}

    def findLastInvariables(self, name):
        invariablesOfThisName = self.invariables.get(name)
        if invariablesOfThisName is not None:
            return [ invariablesOfThisName[-1] ]
        else:
            return None

    def registerInvariable(self, name, invariableNode):
        invariablesOfThisName = self.invariables.get(name)
        if invariablesOfThisName is not None:
            invariablesOfThisName.append(invariableNode)
        else:
            invariables[name] = [ invariableNode ]

    def hasCertainlyModified(self, name):
        return name in self.invariables
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: Microsoft Visual Studio Community 2022 Preview (64-bit), Version 17.0.0 Preview 7.0
Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

**Comment by int19h** [comment]
They are classified as operators rather than keywords, for some reason. And the default color theme for VS uses black for operators, hence why no highlighting. This can be changed in Tools -> Options -> Environment -> Fonts and Colors; look for "Operator" in the item list. 

Highlighting is done by TextMate and we don't control it. That said, the TextMate grammar should probably list those as keywords rather than operators.

**Comment by lexected** [comment]
> They are classified as operators rather than keywords, for some reason. And the default color theme for VS uses black for operators, hence why no highlighting. This can be changed in Tools -> Options -> Environment -> Fonts and Colors; look for "Operator" in the item list.
> 
Yes, sadly that changes the colour for all operators that have not been overloaded. So, trying to make them the same colour as keywords, say, would also turn all the brackets and arithmetic operators blue.

> Highlighting is done by TextMate and we don't control it. That said, the TextMate grammar should probably list those as keywords rather than operators.

Is it possible to modify the TextMate grammar locally?

**Comment by int19h** [comment]
Yup, it's just a bunch of .tmlanguage files on disk. They should be at `C:\Program Files\Microsoft Visual Studio\2022\Common7\IDE\CommonExtensions\Microsoft\TextMate\Starterkit\Extensions` assuming the default installation path. 

It also seems that it might be something that changed in VS 2022, since the corresponding .tmlanguage has been like this all along:
```xml
		<dict>
			<key>comment</key>
			<string>keyword operators that evaluate to True or False</string>
			<key>match</key>
			<string>\b(and|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.python</string>
		</dict>
```
I suspect that VS wasn't doing anything special about "keyword.operator" before, but now it does.

**Comment by lexected** [comment]
Thanks. So, as a quick fix one can just put them under `keyword.other.python`, or skip `operator` and classify them as `keyword.logical.python`. This is not a real solution and most likely also breaks VS's ability to highlight overridden `in` and `not in` differently, but it definitely makes my code more readable to me.

**Comment by AdamYoblick** [comment]
We need to forward this to the VS team because something changed in VS2022 that broke this.

**Comment by StellaHuang95** [comment]
**More info:**

- Our textmate language grammar: https://dev.azure.com/devdiv/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FTextMate%2FVSWindows%2FSetup%2FStarterkit%2FExtensions%2Fpython%2Fsyntaxes%2FPython.tmLanguage&_a=contents&version=GBmain
- The upstream version:
https://github.com/textmate/python.tmbundle/blob/master/Syntaxes/Python.tmLanguage

**Cause:**
VS has separate categories for keywords and operators. The categorization for those words is "keyword.operator.logical.python", not keyword, so that's mapped to just "operator" in VS color settings, just like `+` and `-`. The VS categories are all in Tools -> Options -> Environment -> Fonts and Colors. Changing the color for "Operator" there would be the easiest way to test this theory.

**What VSCode does:**
They actually use a different tmlanguage for Python from a different source: https://github.com/microsoft/vscode/blob/main/extensions/python/syntaxes/MagicPython.tmLanguage.json
Related issue is https://github.com/microsoft/vscode/issues/2208
Related pr is https://github.com/microsoft/vscode/pull/10681 to change vscode to use MagicPython

**Comment by StellaHuang95** [comment]
Submitted a PR to fix some of the syntax highlighting issue. https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/440869. This change didn't fix all the issue though, for example, the words with keyword.operator.logical.python scope still don't have highlighting, but that can be fixed in a separate pr.

**Comment by StellaHuang95** [comment]
In vscode, you can use the Developer: inspect editor tokens and scopes command to inspect info like textmate scopes and foreground color.
