### ISSUE TITLE
Visual Studio Community 2022 - UTF-8 codec problem

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6784]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Community-2022---UTF-8-cpd/1577132)._

---
[regression] [worked-in:Visual Studio Community 2019]
Today I have Visual Studio Community 2022 (64-bit) – Current Version 17.0.0 installed, including the Python extension.

When executing Python code that contains German special characters (ä, ö, ü), the debugger aborts with the following error message:
_„SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe4 in position 7: invalid continuation byte“_

The problem is not related to the Python interpreter or the code. The code runs flawlessly with Visual Studio 2019 and VS Code. Debugging also works fine with Visual Studio 2019.

Is there a new UTF-8 encoding setting in Visual Studio 2022 that I missed?

I thank you for your help.

---
#### Feedback Bot on 11/9/2021, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
Can you share the full traceback associated with the error message in the terminal?

**Comment by e16384** [comment]
For me is the same, if use ñ letter in Spanish in a variable name when execute it, says: SyntaxError: invalid character in identifier
And the ñ character has been substituted for a like-square character:
![imagen](https://user-images.githubusercontent.com/77391025/146600030-9a780ac2-4ebe-4f1b-b128-e817976d8530.png)

The original definition is:
![imagen](https://user-images.githubusercontent.com/77391025/146600132-b3f65ca8-0520-44c1-88f9-f878d8b958d0.png)


In VS 2019 was ok and VS Code it's OK too.

My version of VS 2022 is 17.0.1

In C# there is no problem using the ñ character. But in Python doesn't work.

Regards.

**Comment by re-mark** [comment]
Same problem with Cyrillic symbols. Not just in ".py" files, but also in Flask ".html" templates

**Comment by StellaHuang95** [comment]
`PythonEncodingDetector` in [this file](https://github.com/microsoft/PTVS/blob/84add9c25ff26c1f39ab998400a8a66fb16ee60f/Python/Product/PythonTools/PythonTools/Project/PythonEncodingDetector.cs#L29) does not get invoked when creating new python files. Might be a MEF issue.

**Comment by int19h** [comment]
I took a quick look at it from VS side of things, and when the file gets loaded and encoding detection kicks in, its ContentType is `{text}`, so our detector isn't considered at all. This is possibly something that has changed in VS 2022, since there are no obvious corresponding changes in PTVS.

Either way, further investigation needs to figure out why the content type is not assigned at the right time despite the .py extension.

**Comment by StellaHuang95** [comment]
Some updates to add based on conversations with Pavel and Oleg:

In VS 2019, the older version of PTVS used to explicitly set the encoding of the document before text document is loaded, but the current one does not. However, since the VS side knows the filename, they should to be able to determine the content type without us having to explicitly set it. So it's a design bug as it wasn't properly documented.

Possible fixes:

- Have VS team use the content type registration info to set the appropriate content type for newly created document instances. 

- Have VS team default to UTF-8 in the absence of decoders, on the basis that it's more likely to be a correct guess. But it doesn't really help us, since we still need to handle Python "coding" comments - we need the detector to kick in. 

- Look up the method names in the stack that comes from the older version of PTVS, figure out where those lines of code should go in current source to reproduce the old behavior.

@int19h Pavel, is there anything else you'd like to add?

**Comment by StellaHuang95** [comment]
Also, got some info from Hugues:

The editor factory was needed before in PTVS 16 because PTVS was handling all client side editor integration, but by switching over to language server client, that part of it is now handled by that component. If we take ownership of editor factory, that might break the language client

**Comment by StellaHuang95** [comment]
Will be fixed in 17.3.

**Comment by Arnau2010** [comment]
The problem still occurs in Visual Studio 2022 Community 17.3.2

![image](https://user-images.githubusercontent.com/69428681/187093340-54e6120c-01e9-4aa2-954f-557d55b30db0.png)

Reconsider reopening, @StellaHuang95

**Comment by bifacil** [comment]
It does not work eighter with VS Pro:

![image](https://user-images.githubusercontent.com/4572969/187093601-514f87ca-1689-42bc-a15e-3b49b211d9ba.png)

**Comment by bifacil** [comment]
I found a work around in #6837

You can "Save as... (with codification).

![image](https://user-images.githubusercontent.com/4572969/187093864-785f51fd-0b52-4622-92f8-31aa483a2bfa.png)

Now, it works...

**Comment by 8oris** [comment]
> I found a work around in #6837
> 
> You have tpo "Save as... (with codification).
> 
> ![image](https://user-images.githubusercontent.com/4572969/187093864-785f51fd-0b52-4622-92f8-31aa483a2bfa.png)
> 
> Now, it works...

I tried your work around and it works like a charm. Thanks a lot.

**Comment by olastrom** [comment]
I still have the same problem as above when using Python in Visual Studio Enterprise 2022 v 17.7.3

SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf6 in position 548: invalid start byte

**Comment by olastrom** [comment]
My solution was to:
- open Notepad and paste the code from the .py file into a new Notepad document.
- close the project. 
- save the Notepad document with the old .py file BUT USING the UTF-8 ENCODING.
- open the project again.
Now the .py file is in UTF-8 and it is now working...

**Comment by DrDrProfRosenthal** [comment]
> My solution was to:
> 
> * open Notepad and paste the code from the .py file into a new Notepad document.
> * close the project.
> * save the Notepad document with the old .py file BUT USING the UTF-8 ENCODING.
> * open the project again.
> 
> Now the .py file is in UTF-8 and it works...

solutions works for me as well, just save in nodepad as .py (dont know what you mean exactly with using UTF encoding in nodepad) 
but the fact that it does is just ridiculous - so theres is propably an easier way somewhere deep in the settings no one found yret

**Comment by Bubenchuk** [comment]
Is there an option to solve this problem by changing settings in the Visual Studio program itself? Over the long haul of time, it's not comfortable.

**Comment by thrust26** [comment]
4 years later and we are still facing the same problem (C++) when using e.g. 'á' in a path. This is encoded as 0xe1, which is not a valid UTF-8 code. And as a result, the path is not found by e.g. SQLite which assumes valid UTF-8.

The workaround using another editor works. Then it is encoded as 0xc3, 0xa1. "Save as with encoding" does NOT work. It looks like VS is completely ignoring the UTF-8 encoding settings.

These are my encoding settings:
![Image](https://github.com/user-attachments/assets/2197405b-a297-4a77-9bfd-898bcbf36249)

Note: This does not happen with my colleagues computer. He is located in Canada and I am located in Germany. Maybe that's a hint.

**UPDATE**: Changing my settings to this solves my problem. So something is wrong with "UTF-8 **with** signature".
![Image](https://github.com/user-attachments/assets/d11c2716-d46f-4ae2-bd80-69366466b8e0)

![Image](https://github.com/user-attachments/assets/87c2ad5b-3eb9-46b6-9f0d-b01ff78eef4d)
![Image](https://github.com/user-attachments/assets/7ef18848-c012-48a5-9e36-d221047a2d3e)
(Region and Language set to Germany)
