### ISSUE TITLE
Cannot use Cookiecutter to load template.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6872]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/151646065-ebc69d89-d620-450e-8c35-913c96ec03c4.png)

**Steps to Reproduce**

1. Open Cookiecutter Explorer.
2. Load the following template: https://github.com/brettcannon/python-azure-web-app-cookiecutter 

**Expected behavior**

The Template loaded successfully.

**Additional context and screenshots**

Error cloning the repository.
BTW, load the template from the "Recommended" section, you can repro it.

**Output info**
```
----- Cloning template 'https://github.com/brettcannon/python-azure-web-app-cookiecutter' -----
The system cannot find the file specified
A task was canceled.
----- Failed to clone template 'https://github.com/brettcannon/python-azure-web-app-cookiecutter' -----
```

**Comment by ttSpace** [comment]
I can repro in today's build ```17.2.0 Preview 2.0 [32219.17.main]```.

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/160738365-f43bf52e-98f6-4650-b2bf-89dad14b122f.png)
Today's environment still failed to load template.
![image](https://user-images.githubusercontent.com/59192491/160738396-feac2f35-e071-4b24-aba6-d050669356f5.png)

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/167073280-3e24bd4a-a7cd-48d3-b731-7576f01b3854.png)
This issue still occurred on this environment.
![image](https://user-images.githubusercontent.com/59192491/167073324-402fcb09-5438-4b3e-a965-30275fad81b5.png)

**Comment by StellaHuang95** [comment]
I can't repro this in the latest build. @linette-zyy Could you verify if the issue still exists in the latest version? Thanks.
![image](https://user-images.githubusercontent.com/100439259/172703822-3f0faa7c-8200-4722-bd74-85a54d69a18e.png)

This is the version I used:
![image](https://user-images.githubusercontent.com/100439259/172703912-c08f8f32-63ce-4206-80ee-3db50ebb583d.png)

**Comment by linette-zyy** [comment]
@StellaHuang95 
I use the latest build to verify
![image](https://user-images.githubusercontent.com/59192491/172781476-c58bf6bb-cc10-47a4-a168-689419714623.png)
And found this issue is still occurred.
![image](https://user-images.githubusercontent.com/59192491/172781336-630ddfc8-575b-43e3-85a7-51269ad2d598.png)

**Comment by AdamYoblick** [comment]
Hi @linette-zyy ,

This issue seems to be caused by Visual Studio trying to run git.exe and not being able to find it.

1. Can you confirm that git is installed on your machine?
2. Can you confirm that git is in your PATH variable? The entry should look something like `C:\Program Files\Git\cmd`, but it might be different based on where you installed it. Basically, just run `set path` and search for "git".

If it's not in the PATH, the clone will fail as you have seen.

Thanks!

**Comment by linette-zyy** [comment]
@AdamYoblick 
Thank you for your comment. We didn't install git when we tested it before.
And today I try to install git and then to load template. The Template loaded successfully.
![image](https://user-images.githubusercontent.com/59192491/173029317-c3fd973c-8bab-42dd-8d11-93064c1532b5.png)

**Comment by AdamYoblick** [comment]
So yeah just to summarize - this only happens in two cases:

1. Git is not installed OR
2. Git is not on the PATH

Stella is in the process of providing a more graceful error to the user 😄
