### ISSUE TITLE
Pylance version not kept current 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6912]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pylance-version-not-kept-current/1680258)._

---
[severity:I'm unable to use this version]
Checking today, Visual Studio Code is using pylance 2022.2.4.  Visual Studio is still using 2021.11.0 (as per package.json - I cannot find any information in the GUI)

How can I update Pylance to the latest stable version? Of course it would better if this update were done automatically, given their frequency.

---
#### Feedback Bot on 3/1/2022, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Pylance ships as part of the PTVS product, it's not a separate extension, and can't be updated independently. That being said, every build of PTVS we do grabs the latest pylance and uses it. So you are correct, the latest VS public preview uses pylance 2021.11.0. But the latest Internal Preview uses a higher version. That version will be in the next public preview.

The reason VS sees updates less frequently is because the Python/Pylance extensions can be developed independently in vscode. In Visual Studio, that's not the case, the product is bundled into VS.

**Comment by AdamYoblick** [comment]
Just to clarify my above comment - we don't kick off a new PTVS build every time pylance is updated, but we DO pull the latest pylance every time a PTVS build is kicked off.

**Comment by excubo-jg** [comment]
Many thanks for our explanation. What confuses me are the time delays in the process. Is Pylance only updated in major updates? Alas, 17.1 got released mid February with pylance dating back from November. Any chances of tightening the cycle? If I understand you correctly even the public preview is still on the 2021.11.0 version and I am not too enthusiastic about moving to preview because of Pylance... (I am impacted by bugs that got fixed last week in pyright)

**Comment by AdamYoblick** [comment]
There is no set upgrade cycle. 😄 

Whenever PTVS changes make their way into VS, they bring the latest pylance with them. We can certainly be more pro-active about upgrading, like whenever a pylance update releases, kick off a build of PTVS so the new version will get bundled into VS. But I'll have to talk to the rest of my team to see if that's something we are willing to do.
