### ISSUE TITLE
An error "Cannot access a disposed object..." pops up when save Python Project File.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6937]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/159846749-c6e3d849-64fa-4114-a9b7-185343aabb92.png)

**Steps to Reproduce**
1. Create a new Python project
2. Create a virtual environment
3. Close the VS
4. Click “Save” to save some changes
![image](https://user-images.githubusercontent.com/59192491/159846945-4eab51ef-13ad-44e9-9be5-2a2881261d16.png)
![image](https://user-images.githubusercontent.com/59192491/159846972-fbbb588e-c55e-4c2d-a1cf-b270f0b2b1a9.png)
5. And then click "Yes"
![image](https://user-images.githubusercontent.com/59192491/159847048-5088ee4a-cd7c-4b8e-a5c0-4e518e9b561f.png)

**Expected behavior**
The changes can be saved without any error.

**Additional context and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/159847160-20dcbb9d-8d50-4aa7-8db4-9b5da7f05fb9.png)

**Comment by AdamYoblick** [comment]
I'm able to repro this, but it has nothing to do with my previous bug like I thought it did.

This only seems to happen when you try to exit visual studio immediately after modifying the pyproj (by adding a new environment). You'll know you did it right because it opens the `Save File As` dialog, when it really should just be saving the file over the existing one without opening that dialog.

I don't think this is a PTVS problem, I think this is a race condition in Visual Studio itself, since we don't own the process of saving files, nor do we have anything called `FileChangeService`.

I will reach out to the Visual Studio team about this, I don't think its ours.

**Comment by linette-zyy** [comment]
I can repro in today's build 17.2.0 Preview 3.0 [32328.412.main].
when a project add reference

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/162130503-10f79473-2144-40bf-9ba3-251a35a82030.png)
This issue still reproduced on today's build.
![image](https://user-images.githubusercontent.com/59192491/162130450-1d3a1117-2b7b-498b-a722-1359be237e28.png)

**Comment by AdamYoblick** [comment]
@linette-zyy Does this still repro?

**Comment by linette-zyy** [comment]
@AdamYoblick 
I can not repro this in today's latest build:**17.6.0 Preview 1.0 [33402.156.main]**,Python Packages:**17.0.23033.1**
