### ISSUE TITLE
Unexpected error pops up in the console when attach a running python.exe

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6993]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/167242994-259462d2-5732-4f7f-b58c-e262fe6a30e3.png)

**Steps to Reproduce**
1.Launch VS and create new python application
2.Add an input('>') or raw_input('>') at the top of your code - depends on version of python
3.Add some more python code after that with breakpoint(s)
4.Start WITHOUT debugging
   a. Console will wait for you to input something
5.Debug > Attach to Process, select the appropriate python.exe (easiest if there's only one, you may want to close interactive windows first)
6.Type enter in the console
7.Check that it stops at the breakpoint

**Expected behavior**
It stops at the breakpoint without any errors

**Actual behavior**
The cmd console shows this
![image](https://user-images.githubusercontent.com/59192491/167243337-16ceff42-123e-4156-afeb-1a1120f626e4.png)

**Additional context and screenshots**
![attach](https://user-images.githubusercontent.com/59192491/167243351-a6e28141-2b05-4fe4-a394-5dd670dbb153.gif)

**Sample Code**
```
input('>')

from math import cos, radians 

 

# Create a string with spaces proportional to a cosine of x in degrees 

def make_dot_string(x): 

    rad = radians(x)                             # cos works with radians 

    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces 

    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces 

    return st 

 

def main(): 

    for i in range(0, 1800, 12): 

        s = make_dot_string(i) 

        print(s) 

 

main() 
```

**Comment by linette-zyy** [comment]
On today's environment
![image](https://user-images.githubusercontent.com/59192491/167779565-2dfaf741-887c-462d-8823-32ac39b3eb17.png)
Still failed to hit the breakpoint and an error dialog displayed at the end of the attach.
![image](https://user-images.githubusercontent.com/59192491/167779515-9d40cdfa-ca58-4cdf-89d8-ded56bab203f.png)

**Comment by int19h** [comment]
Does it make any difference if you do `import threading` in the script?

**Comment by linette-zyy** [comment]
@int19h 
on today's build, i can repro these two phenomena ,though i do  'import threading' in the script
![image](https://user-images.githubusercontent.com/59192491/177521057-e9079959-9899-4170-beb1-4da065eff1e0.png)

**Situation1**（the breakpoint is hit）
![image](https://user-images.githubusercontent.com/59192491/177521692-56360341-b360-410b-9806-113fe43a4e6b.png)

**Situation2**(the breakpoint isn't hit)
![image](https://user-images.githubusercontent.com/59192491/177521898-c4b92e1f-73a7-4a7c-b165-408648101a56.png)

### NOTE: 
The operation steps are the same in both situation, the only difference is that the waiting time is different before Type  enter in the console(situation1 is typing enter after waiting some seconds, situation2 is typing enter immediately)

**Comment by int19h** [comment]
Without `import threading`, the warning printed to console is expected. Note that it must be imported *before* you attach (i.e. before `input()`)!.

The error message box you sometimes get with `import threading` about server failing to attach appears to be a timing issue. Attach-to-PID is inherently asynchronous as it has to inject itself into a running Python thread using `Py_AddPendingCall`. It is entirely possible for the app to run to completion before the pending call is actually processed by the runtime, at which point the app exits while PTVS is still waiting for the injected code to connect back to it. There's nothing we can really do here as we don't have control or even insight over the debuggee until injection actually completes. This is usually not an issue in practice because attach-to-PID is normally used to attach to long-running processes; in this case, you can simulate it by calling main repeatedly in  a loop, and in that repro, the breakpoint is consistently hit as espected.
