### ISSUE TITLE
Many Problems with VS2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6998]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Many-Problems-with-VS2022/10028581)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.11.13]
I just installed Visual Studio 2022 Community Edition. It is missing many items and is not really usable.

For example, under View | Other Windows, there are just three items:

- Stack Trace Explorer
- Package Manager Console
- IntelliSense

1. There should be many more. In particular I installed the Python Development workload, and I later installed the VS History 2022 extension. (Both show in the installer.) The Python Environments window and the Visual Studio File Histories window should be there, but they aren't. Alt-I should bring up the Python Environments. It just dings.

I have checked the installer. Python development is checked. Python is, in fact, installed. It is at:

C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\Python

There is no evidence in the IDE that Python development is installed.

2. Under Tools | Options there is nothing for Git, Python, or VS History Files as there is for Visual Studio 2019.

3. I have also installed Markdown Editor v2 and Editor Guidelines. There is no evidence they are bring used.

4. There is no Git item on the Toolbar. See screenshot. There is no evidence Git is installed.

5. In the lower right where it should show the Commit button (for a solution which has a Git repository) there is "Add to Source Control" (which does nothing). See screenshot.

6. In addition there is no External Tools option under the Tools menu as there is for Visual Studio 2019.

7. In the lower right where it should show the Commit button (for a solution which has a Git repository) there is "Add to Source Control" (which does nothing).

I have Googled and found no one else with these problems. There are plenty of articles, such as how to use the Python Interactive window and Tools | External Tools explicitly mentioning Visual Studio 2022. So it must something I have not done, but I cannot find it nor determined how to fix it.

I have restarted the computer several times. It has not fixed it.

I have been using Visual Studio since at least Visual Studio 2008 and am an experienced user. I have never had these kinds of problems installing the next version. I am able to work on a Windows Forms project, at least to build and run it (but not to commit the changes). I do not seem to be able to do anything else. 

It is unusable.

---
#### Feedback Bot on 5/4/2022, 10:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
This sounds like maybe a corrupt VS install? This doesn't seem like a PTVS-specific problem, as you mentioned that many other things are missing from your install (git, etc...).
Can you please uninstall and reinstall your VS2022? Also, try installing python from python.org, as VS2022 doesn't install the python interpreter by detault.

Also, it's certainly possible that existing VS menus and UI have changed form 2019 -> 2022.

**Comment by KennethEvans** [comment]
I just found out this issue was moved here.  Yes, it is corrupt, but I have no idea how to fix it. I already completely deleted it and reinstalled. This was shortly after it was released. I figured I would wait until it was stable. However, it did exactly the same when trying recently.

It also modified a lot of settings in VS 2019. I really need to have VS available, so I have deleted it again, and restored my settings for VS 2019, which is what I am using. There are no problems in VS 2019, but it is no longer supported, and I would like to move to the new version.

There were no notifications of issues during the VS 2022 installation, and no notification of any problems after. It is just that much of it is not there as described above.

I already install and use my own Python version. I haven't used the one that comes with VS for some time. I do note above that it is installed, though. Since there is no way to access a Python project, there is no way to see what it is using. Python is not available, period. Nor Git.

Python works fine for me in VS 2019. Although I primarily do Windows Forms, I have a lot of Python projects and am reasonably competent in Python.

I could do Windows Forms ok in VS 2022, but with no Git, it was not feasible.

>> Also, it's certainly possible that existing VS menus and UI have changed form 2019 -> 2022.

Well yes. I am willing to start from scatch, but it seemed to import a lot of stuff from VS 2019, including the Start Page, where all the projects are in the usual VS 2019 location in Documents. I did not open any of those. What I did was with copies moved to the VS 2022 Documents projects directory.

And also note it screwed up VS 2019 in the import process. I saw that as a bug which was supposedly fixed. It isn't, and the problems are likely in how it is doing import. I'm hardly alone in upgrading from VS 2019, so it is unclear why it works for others and not me.

Thank you for your interest.

**Comment by kusleikar** [comment]
The solution now as far as I am aware is to keep a source file open from the import module, say you import pygame.
ctrl-click on pygame, that should take you to __init__.pyi, okay now keep that tab open and you should be good. This happens to me too, but sadly, I can't tell what causes it or instructions on how to replicate it. 

I would really like if template for the python setup project could include an environment setup, also the Python Interpreter that comes with the Python Workload doesn't do anything in the "Python Add Environment" window, nor does it show up in the "Python Environments Tab", beside the solution explorer. 

Other than that, I am pretty happy that I can work on Python in Visual Studio, it's really fast.

**Comment by KennethEvans** [comment]
I am satisfied with the Python support in VS2019. Yes, creating environments was not easy in the beginning, but once you understand how it works, it's fine. For complicated things, there's usually a corresponding learning curve. It's just a matter of getting through the learning curve.

That is not my issue, however. With VS 2022, I don't even have a Python environment, as well as not having a lot of other things that should be there. I'm not getting any help on this. The original Microsoft support issues (two of them now) were closed and I was directed here. Nothing addressing my problem is happening here.

**Comment by AdamYoblick** [comment]
Feedback issue has been re-opened and marked as "Under Investigation". I will forward that to the appropriate team and I will close this out. Thanks!

**Comment by KennethEvans** [comment]
Thank you. I agree it is an installation issue, and it doesn't seem to be common. I think there is a conflict with the existing VS2019 somehow. It modified the VS2019 sertings, which it should not have.

I am not sure where to go to access the re-opened issue, however.

**Comment by AdamYoblick** [comment]
The feedback item is on Developer Community at https://developercommunity.visualstudio.com/t/Many-Problems-with-VS2022/10028581
