### ISSUE TITLE
Pytorch package debugging unavailable due file naming

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7031]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pytorch-package-debugging-unavailable-du/10059666)._

---
[severity:I'm unable to use this version]
I am trying to debug some Pytorch example with prelearned packaged model, But when I go deeper into code inside package VS starts to search file with name ".multi_acc_v3_package.py".

I unpacked .pt model to provide sources for debugger, but inside package i founded **multi_acc_v3_package.py**, but not **.multi_acc_v3_package.py**. And  i of course tried to rename **multi_acc_v3_package.py** into **.multi_acc_v3_package.py** - but it has illegal symbols ("<",">") in the filename.

How i can debug this things with visual studio ? Or how i can just avoid this situation?

See screenshot below:
![image.png](https://aka.ms/dc/image?name=B2bb9520995b74f179c776cebe1d19407637896912974829846_20220601-174136-image.png&tid=2bb9520995b74f179c776cebe1d19407637896912974829846)

I attached sample project and pytorch model:

[PythonApplication1.zip](https://aka.ms/dc/file?name=Bee29d9c49cdd4473ba33b5cf8a346af2637896915020003265_PythonApplication1.zip&tid=ee29d9c49cdd4473ba33b5cf8a346af2637896915020003265)

---
#### Feedback Bot on 6/1/2022, 05:37 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vvitnes** [comment]
While copying this issue link to attached image was broken. Attaching this image here.
![B2bb9520995b74f179c776cebe1d19407637896912974829846_20220601-174136-image](https://user-images.githubusercontent.com/31817919/172993369-739e7832-25f9-4f28-ab91-0f56ef5e02f5.png)

**Comment by int19h** [comment]
The debugger gets the name of the file that it expects from the `__file__` attribute of the module. It looks like PyTorch does something weird here, because your module's name is mangled to `<torch_package_0>.multi_acc_v3_package.py`.

Unless there's a way to force PyTorch to provide the correct filename here, I'm afraid there's no workaround until we implement #6610 - I don't think VS will allow you to select a file with a name different from what the debugger reports.
