### ISSUE TITLE
Is there a way to have "Find in Files" skip the env folder when searching the project or solution?

### ISSUE THREAD

**Issue by KennethEvans** [microsoft/PTVS#7049]
I often search for a string in *.py using **Find in File**s for the whole project.

This picks up many matches in the environment folder (env) that I don't care about and which make it difficult to find the ones in my own files.

Is there a way to keep it from searching env?

This is in VS 2022.

**Comment by StellaHuang95** [comment]
Hi there, yes the File types folder now also can exclude files. Any path or file type prefixed with the “!” character will be excluded from the search. For instance, you can add `!*\env_virtual\*` to the file types list to exclude any files in a env_virtual folder. Please reopen the ticket if the problem is still there. Thanks!

**Comment by KennethEvans** [comment]
That works. I was not aware of that feature.

Thank you.
