### ISSUE TITLE
Visual Studio crashes when adding a new Python virtual environment and typing a slash in the `Name` field

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7089]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-crashes-when-adding-a-new-/10093909)._

---
I wanted to add a Python virtual environment to my project under a subdirectory called `.venv`, so that I can add the `.venv` to my `.gitignore` file. I attempted to add a new virtual environment called `.venv\my_virtual_environment_v3.10.5`, but Visual Studio crashes as soon as I type the slash. See screenshot:

![image.png](https://aka.ms/dc/image?name=Bb0215f4f4ae74cd596073c799301f4db637932944283085505_20220713-033347-image.png&tid=b0215f4f4ae74cd596073c799301f4db637932944283085505)

---
#### Feedback Bot on 7/13/2022, 01:36 AM: 

(private comment, text removed)
#### Ed Peguillan III on 7/13/2022, 01:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
I've looked into this bug and it looks like it's a stack overflow because of a recursive call to get the parent directory of the current directory + the env name. Since the env name contains a slash, the parent directory is the same as the current directory, and when the recurse happens, the same values are used over and over, causing an infinite loop.

The correct fix for this is to not allow path separators in the env name. This can be done using Data Validation on the data binding in wpf.
