### ISSUE TITLE
python sys.exit() breaking on default no value

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7099]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-sysexit-breaking-on-default-no/10099153)._

---
[severity:It bothers me. A fix would be nice]
When calling sys.exit() in a pygame module, the debugger will throw an exception if 0 is not entered as the exit value: ie sys.exit(0)

---
#### Feedback Bot on 7/19/2022, 07:34 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
Can you clarify if this happens when you're calling `sys.exit()` with no arguments, or `sys.exit(n)` where `n != 0`? If the latter, this is by design - `sys.exit` throws `SystemExit`, and we break on that same as any other exception if it has a non-zero exit code, as that generally indicates an error.
