### ISSUE TITLE
Frame not in module

### ISSUE THREAD

**Issue by mykela** [Microsoft/PTVS#716]
I'm remote debugging from Windows7/VS2015 to a remote Ubuntu 14 installation running in VMWare 10. Source is on a shared drive between the two and packages are loaded at run time. When I break in the package code, I get a 'Frame not in module' error and the source is not displayed even though the reason for the break is the break point I set in that source. The stack shown is correct and I can set further break points in the source and they also break correctly but no source - just the error. How do I fix this so I can remote debug?

**Comment by int19h** [comment]
When you end up in this state, can you still see variables in the Locals window, or does Watch work, at least? If it does, what is the value of `__import__("sys")._getframe().f_code.co_filename` ?

**Comment by mykela** [comment]
Thanks for the response. 

 

Locals and the Watch windows seem completely sane. I don’t notice anything missing and the values are right. The value you asked about returns the string

‘<debug input>’.

**Comment by int19h** [comment]
Okay, so I need to amend that a little bit. Instead, try this: 
```
'\n'.join([__import__("sys")._getframe(i).f_code.co_filename for i in range(0,10)])
```
(if it fails with "error: call stack not deep enough", then replace 10 with 9, and repeat until you get a string with filenames)

You might need to use the tiny magnifier icon in the value field to open the string in a separate window where you can see and copy/paste the individual lines.

Basically, if it can't determine the module, then it's likely that the filename matching logic is confused for some reason, and I'd like to see the actual remote filename that the interpreter uses to identify source, and also the local filename that you have opened in your VS, so that I can figure out why they don't properly match...

**Comment by mykela** [comment]
Here’s what I get with just what you originally suggested. I bolded my source file in case that’s useful. (Sorry it’s late. Busy day.)

 

'<debug input>\n/usr/local/lib/python2.7/dist-packages/ptvsd/visualstudio_py_debugger.py\n/usr/local/lib/python2.7/dist-packages/ptvsd/visualstudio_py_debugger.py\n/usr/local/lib/python2.7/dist-packages/ptvsd/visualstudio_py_debugger.py\n/usr/local/lib/python2.7/dist-packages/ptvsd/visualstudio_py_debugger.py\n/usr/local/lib/python2.7/dist-packages/ptvsd/visualstudio_py_debugger.py\n/usr/local/lib/python2.7/dist-packages/etcs_wifi-0.0.1-py2.7.egg/etcsext/wifi/wfconfig.py\nbuild/bdist.linux-x86_64/egg/pyetcs/core.py\nbuild/bdist.linux-x86_64/egg/pyetcs/core.py\nbuild/bdist.linux-x86_64/egg/pyetcs/server.py'

 

Thanks!

**Comment by int19h** [comment]
It didn't get bolded on GitHub (I think you need to respond directly on the ticket instead of via email, it looks like it just strips all formatting in the latter case). But your code is probably this?
```
/usr/local/lib/python2.7/dist-packages/etcs_wifi-0.0.1-py2.7.egg/etcsext/wifi/wfconfig.py
```
Is `etcs_wifi-0.0.1-py2.7.egg` a directory or a file? If it's a file - i.e. a zip archive - then this may very well be hitting the limits of our support for eggs in the debugger (we support them fully for code analysis, but debugger only has some very limited support). That said, quickly trying this with local debugging doesn't break in the way that you're describing for me, so there's something about these Unix paths that's making it worse than it should be. I'll see if I can get a repro with a Linux system.

**Comment by int19h** [comment]
In the meantime, try installing it in a way that unpacks the egg on the machine on which you're debugging. If you're using `pip`, it should do that by default. If you're using `easy_install`, then you should really just use `pip` :) but otherwise you can invoke it with `--always-unzip` to force the egg to be unpacked.

**Comment by mykela** [comment]
That’s the file in question, yes. 

 

And, in fact, it’s located in a directory, not a zip file and the files seem to be all there. I’ve deleted the lot and re-installed too – same results.

 

(Thanks again for looking at this! I’d really like be able to use VS to debug.)

**Comment by mykela** [comment]
We are using a generic (I think) setup.py based on setuptools to install. (‘python setup.py build’, then ‘python setup.py install’) (Sorry, I don’t know very much about this part of python.)

**Comment by mykela** [comment]
Anything new on this? Anything I can do to help?

Thanks.

**Comment by mykela** [comment]
(Sorry. Wrong button.)

**Comment by int19h** [comment]
I tried to repro this on a Linux box, but had no luck doing so. One thing in particular that stands out is that when I made a simple package with setup.py, and used the latter to install it (`python setup.py install`), I did not end up with a folder having an .egg extension on either Windows or Linux. My layout looks like this:
```
/usr/local/lib/python2.7/dist-packages/foo
|-- foo.py
|-- foo.pyc
|-- __init__.py
|-- __init__.pyc
`-- pkg
    |-- bar.py
    |-- bar.pyc
    |-- __init__.py
    `-- __init__.pyc
```
So I'm curious as to how you've got that .egg there. 

Would it be possible for you to share the package, and provide a full step-by-step repro guide on how you build & install it?

**Comment by mykela** [comment]
Sorry for the delay - got diverted for a bit.

I'm not sure if it's totally solved, but that was exactly the right question to ask. I still don't know why the folders have a .egg file extension or if that was even the problem, but installing differently lets me fully debug now. If I use the develop option instead of the install option on setup.py, a lot less goes on during the install (including creating folders that end in .egg) and I can debug into everything. 

So that's more than good enough for me. If you are still interested though, I think can send the setup.py file and the output from running setup. There's really not much in the setup.py though.

For now though, this is good. Thanks very much for the help!

**Comment by int19h** [comment]
>  I think can send the setup.py file and the output from running setup.

This would be handy. I'm still hoping to arrive at a logical explanation for the original behavior - there is still a distinct possibility that it is exposing some kind of bug in our filename matching logic that I'm not seeing.
