### ISSUE TITLE
No Python (Byte Array) Variable Isolation Between Functions

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7191]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-Python-Byte-Array-Variable-Isolatio/10158480)._

---
[severity:It's more difficult to complete my work]
Different functions are supposed to have different memory spaces, thus changing of a variable in one function should not affect another variable (no matter the similarities in names) in a different function. In Python3, this seems to be the case for an integer but not for a bytearray. Screenshots will be attached. Although not 100 percent sure about the behavior of bytearrays, I am quite sure this is a bug. This behavior is not defined, as no pointers are involved, and Python does do the correct action with integers.

![image](https://user-images.githubusercontent.com/29436557/196794710-5a149656-3d84-4af5-9780-11aefebee377.png)

**Comment by AdamYoblick** [comment]
Hello!

This is an example of passing by value vs passing by reference. 

Integers are passed by value (they are immutable), so a copy is made in the function. Therefore, changing this value only changes the copy, which is why the original remains unchanged.
`bytearray` is a class (https://docs.python.org/3/library/stdtypes.html?highlight=bytearray#bytearray), which is a mutable object, and is passed by reference. Therefore, changing it from within a function will change the original object.

Please see https://docs.python.org/3/tutorial/controlflow.html#id1 and take a look at the footnote at https://docs.python.org/3/tutorial/controlflow.html#id2. 😄
