### ISSUE TITLE
Memory leak in cross-module class instantiation

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#727]
Given the following two modules, each time `modA` is reanalyzed, memory is leaked until `modB` is reanalyzed.

`modA.py`:
```python
from modB import B

def f():
    x = B()
```

`modB.py`:
```python
class B:
    def __init__(self):
        self.__init__
```

It seems that the call to `modB.B.__init__` from the first analysis sticks around as a dependency of the getattr in `self.__init__`. `modA.f` is a dependency of this call, so it also sticks around, which keeps the entire v1 of `modA`'s analysis in memory.

**Comment by zooba** [comment]
Simplified it to just getting a member of `self` - assigning wasn't relevant.

**Comment by DinoV** [comment]
The problem seems to be that we create a new FunctionAnalysisUnit for analyzing def __init__ - that's because we throw away all of the old calls in the call chain because modA has a new version.  

We then have the VariableDef for self.__init__ and add the new FunctionAnalysisUnit is added as dependency to that variable.  Those never get cleared out.

Presumably we need to somehow invalidate the old dependencies based upon the project entries that are captured in the call chain.

**Comment by DinoV** [comment]
And the place to see the leak is in InstanceInfo.GetMember where we do def.AddDependency(unit)
