### ISSUE TITLE
Survey Prompting 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/PTVS#7372]
**Describe the feature you are requesting**
Prompt a user to complete a PTVS survey through the gold bar notification. 

**Reasons for requesting this feature**
Engage users in a channel for feedback in order to better understand our customer profile and actionable enhancements. 

**Additional context**
Similar to the top notification shown below: 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/60238438/216431256-47a599f8-4d80-450d-9f37-eeec315e8e26.png">

The prompt can be triggered for a random set of PTVS users after 1hr of use in a single session.

The survey has already been created to link in a button.

**Comment by AdamYoblick** [comment]
Talk to Steve Dower or Hugues about this, did we do something similar in the past?

**Comment by StellaHuang95** [comment]
[Targeted Notifications](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/1031/Targeted-Notifications?anchor=what-capabilities-does-targeted-notifications-have-today%3F) has the capability to send promotions to VS users via the [Promotions Service](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/2356/Survey-and-Feature-Promotion-Notifications), with support to display an InfoBar (aka "Gold Bar") with custom text and buttons.


Getting Started:

1. Go to https://aka.ms/uxboard  and create a UX board ticket by the [request template](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?wikiVersion=GBwikiMaster&pagePath=/Team%20Pages/VS%20IDE/Survey%20and%20Feature%20Promotion%20Notifications/Notification%20Request%20Template)
2. Create a [Dev16 or Dev17 test rule](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?wikiVersion=GBwikiMaster&pagePath=/Team%20Pages/VS%20IDE/Survey%20and%20Feature%20Promotion%20Notifications/Creating%20a%20Dev16%20or%20Dev17%20promotion) and validate the scenario works locally
3. Create a [Dev16 or Dev17 production rule](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?wikiVersion=GBwikiMaster&pagePath=/Team%20Pages/VS%20IDE/Survey%20and%20Feature%20Promotion%20Notifications/Creating%20a%20Dev16%20or%20Dev17%20promotion)
4. Ping RuRios once the rule is approved by the UX board and ready for a final review

@cwebster-99 Could you help with step 1 since most fields need PM input? Or we can do it together if that works better for you😊.

**Comment by StellaHuang95** [comment]
Update from the TiP Insights Team:

- To collect information on the number of users who choose to take the survey versus those who exit, it is NOT supported to add a new telemetry event to the survey info bar. However, this data can be found in the Statistics tab on the Rules page, which updates overnight. Alternatively, if you require real-time data, you can access the 24 Hour Debugging tab, which has a latency of approximately 30 minutes.

- Regrettably, it is not currently possible to set the info bar to display one hour after the user has used the Python tools in Visual Studio. However, it is possible to trigger the info bar based on a specific event. Right now I am using the "vs/python/launch" event to trigger the survey.

/cc @cwebster-99

**Comment by StellaHuang95** [comment]
I have created a UXBoard ticket here: https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/17776

The test rule can be found here: https://targetednotifications.vsdata.io/Rule/43b060de-e704-4a4c-8905-992508f361ea

**Comment by StellaHuang95** [comment]
UXBoard ticket has been approved. Now waiting for production rule approval.

Snapshot of the latest rule: https://targetednotifications.vsdata.io/rule/62c49447-9767-402a-9230-3653ae2d60b0/snapshot/latest
Rule details: https://targetednotifications.vsdata.io/Rule/62c49447-9767-402a-9230-3653ae2d60b0

**Comment by StellaHuang95** [comment]
The rule has been approved, view the active rule here: https://targetednotifications.vsdata.io/rule/62c49447-9767-402a-9230-3653ae2d60b0/statistics

I believe the statistics and debugging tabs collect data about survey responses. Close the issue as complete.

**Comment by StellaHuang95** [comment]
Targets will be uploaded for this rule tomorrow morning and subsequently receiving the rule.  The 24hr rule debugging tab will have the latest and greatest data available if you want to look at things tomorrow.  Otherwise, the stats will start populating at a later time.
