### ISSUE TITLE
Code navigation is not available, when creating a new python project in visual studio 2019. 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7382]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-navigation-is-not-available-when-c/10258635)._

---
While creating a python project in visual studio 2019, the code navigation and hinting functions cannot be used, when the number of python files is larger than 15; However, instead of creating a python project, the code navigation function is normal by opening the folder directly. How can I solve it? Thank you!

---
#### Feedback Bot on 1/23/2023, 06:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I tried creating more than 15 python files as you described but was not able to repro in VS2019. Could you provide more detailed repro steps or code samples so that I can further investigate? As an alternative, you can also try upgrading to VS2022 and see if the issue still persists. Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
