### ISSUE TITLE
Problem in Python console error utf-8

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7383]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-in-Python-console-error-utf-8/10261203)._

---
Unicode's error in Python console, utf-8. How can fix this problem?
[Unicode utf-8.png](https://aka.ms/dc/file?name=B51d73e91c1b94ce986cb5d298221a13a638102517223870768_unicode_utf-8.png&tid=51d73e91c1b94ce986cb5d298221a13a638102517223870768)

---
#### Feedback Bot on 1/27/2023, 07:07 PM: 

(private comment, text removed)
#### Athanasios Athanasarakis on 1/28/2023, 01:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, seems like the issue was caused by the scripts not being UTF-8 encoded. Could you go to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the script? Please re-open the ticket with a copy of your script if the issue still persists, thanks!
