### ISSUE TITLE
Installing VS 2022 v17.5.0 update removed Python that wasn't installed by VS

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7439]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Installing-VS-2022-v1750-update-remove/10291661)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.4]
I had Python 3.9 installed on my machine, completely separate from Visual Studio.  I do not have the Python workload installed.  I never asked VS to install Python.

After installing the VS 2022 v17.5.0 upgrade, my installation of Python 3.9 was uninstalled and replaced by Visual Studio.

If VS wants to install an isolated copy of Python for its own use, that's fine.  But destroying an existing installation is not.

Notes:

(1) I zipped up dd*.log from %TEMP% and attached it to this bug report.  This should include all the logs from the upgrade.  It may also have other extraneous logs.  Y'all are the ones who create the log file mess -- y'all can figure it out! :-)

(2) I have multiple versions of Visual Studio installed on my machine.  I upgraded VS 2017, 2019, and 2022 today (in that order).  I believe it was VS 2022 that damaged my existing Python installation based on the log files.

(3) My existing copy of Python 3.9 was installed in the "C:\Tools\Python39" directory, not the default location under "C:\Program Files".  It shouldn't matter, but I wanted to mention it.  Perhaps the VS installer checks for the default location, and leaves it alone, but wiped out my installation because it was in a different directory.

---
#### John McNamee on 2/26/2023, 06:00 AM: 

(private comment, text removed)
#### Feedback Bot on 2/26/2023, 05:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
@AdamYoblick Does this have to do the changes we made a while back on updating the VS bundled python versions?

**Comment by Sedeniono** [comment]
Installing 17.5.0 also uninstalled another Python for a few colleagues, but they were the minority. We couldn't really figure out what was different.

Also, the issue already occured in the past (again, unfortunately, without a clear pattern). See #5952.

**Comment by AdamYoblick** [comment]
Ok so we investigated this and here's what we found out. The windows registry uses the python major.minor verson as the key. See below:

![image](https://user-images.githubusercontent.com/29436557/224129394-156d113d-0731-42f2-8899-dee4767544a2.png)

So if you install python from any source (including the VS installer), and your new install shares the major and minor version of an existing install, the existing install will be upgraded. This is because the registry keys collide, so you can't have 3.9.7 and 3.9.13 installed side by side, for example.

This is unfortunate, but it's due to how the python windows installer works. So the workaround is not to install the python interpreter through the VS installer. The good news is that we've marked this component as out of support moving forward (for future VS releases), so it should always be unchecked by default.

I'm going to do some final testing to make sure what I said above is accurate. For example, I'm going to install python 3.7 myself, then install python 3.9 through VS. In this case, 3.7 should remain untouched because it doesn't share a reg key with 3.9.

**Comment by mcnameej** [comment]
The issue I had with the VS 17.5.0 upgrade may be a bigger problem.

I never had the Python _workload_ or the Python _individual component_ installed in Visual Studio. I just had my own Python installation, which I didn't use with VS.

I did have the “C++ CMake tools for Linux” component installed in VS. It had no dependency on Python at the time I installed it, but it appears that a dependency was added in 17.5.0. So the VS installer decided to fulfill that dependency by installing the Python component, and that is how my existing copy got nuked.

This seems like a problem with the VS installer. IMHO, it's not OK to install new dependencies without user consent.

**Comment by StellaHuang95** [comment]
We need to better document this.

**Comment by AdamYoblick** [comment]
Unfortunately we can't change how the VS installer works, but marking the component as optional or out of support will make it unchecked by default, which should help avoid this from happening again. There's not really any other way around this (that I know of) because of the windows registry key collision.

I've reached out to the cmake tools team to see if they can mark it as optional.

**Comment by AdamYoblick** [comment]
I'm closing this out because unfortunately there's not much we can do here. 😞 

After speaking with the Cmake Tools team, I learned that they do in fact use this dependency, and it's required for them. And the VS installer just installs the cpython version provided to it. 

As previously mentioned, python version information is stored in the registry and the key is major.minor. If you manually install python 3.9.1, then manually install 3.9.13, your 3.9.1 will be nuked. This is the same behavior you're seeing when the VS installer does it. Cmake adding a cpython dependency is really beyond the scope of PTVS.

**Comment by AdamYoblick** [comment]
FYI the cmake team has updated their workload to no longer include cpython as a dependency. It will take a bit for this to flow into a public release but the work is done :)
