### ISSUE TITLE
Breakpoints are not hitting in while debugging Python Flask app

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7450]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Breakpoints-are-not-hitting-in-while-deb/10300327)._

---
[severity:I'm unable to use this version]
Breakpoints are not hitting in while debugging Python Flask app

See https://code.visualstudio.com/docs/python/tutorial-flask

---
#### Feedback Bot on 3/5/2023, 09:43 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for reporting this. The tutorial is for vscode. Can you provide detailed repro steps so that we can further investigate?

**Comment by shalevy1** [comment]
Repeat steps: Start flask under a debugger
Place a breakpoint @app.route("/") function
With your browser open the end point
Breakpoint isn't honored :(

**Comment by StellaHuang95** [comment]
Thank you for providing that information. Unfortunately, I am unable to reproduce the issue on my end. In order to better understand and troubleshoot the problem, I would appreciate it if you could provide additional information such as code samples or recordings. For instance, a recording similar to the one shown below would be helpful.
![flask](https://user-images.githubusercontent.com/100439259/225993241-b12877b3-9398-47d9-8278-4eefde0bbb73.gif)

**Comment by int19h** [comment]
@shalevy1 The most common cause of this is when you run Flask in auto-reload mode, which interferes with the VS debugger. Can you make sure that `--no-reload` and `--no-debug` are passed correctly when launching your app under debugger?
