### ISSUE TITLE
'Completions for type Hints via stub files' need restart VS is unacceptable

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7472]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/227129460-9fa764b0-7022-47fa-a43e-ac653a27c6d8.png)

**Steps to Reproduce**
1.Create a Python Application project
2.Add a module file named employee.py and enter below code: 
```
def is_valid_employee(name, id): 

       return False 
```
3.In default .py file which has no type: 
![image](https://user-images.githubusercontent.com/59192491/227131119-a7038ff2-71ba-4c30-a656-ff5fc33983b6.png)
4.Add a stub file named employee.pyi and enter below code: 
```
def is_valid_employee(name:str, id: int) -> bool: pass 
```

**Expected behavior**
In default .py file, tooltip that shows VS proposes the types found in the .pyi 
![image](https://user-images.githubusercontent.com/59192491/227132064-19ea5514-18aa-40c4-9c2b-9fa06deef6b1.png)

**Actual behavior**
I need restart VS
![employee_pyi](https://user-images.githubusercontent.com/59192491/227132616-75211252-1d95-43eb-a750-32d9bdd18a2d.gif)

**Comment by StellaHuang95** [comment]
The cause is that Pylance currently doesn't start service instance for any python projects. The reason that it doesn't start is that no workspace is created for python project on load.

**Some context:** 
Pylance creates workspace either in [handleInitialize](https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/workspaceFactory.ts#L114) or in [handleWorkspaceFoldersChanged](https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/workspaceFactory.ts#L128). In PTVS, it's supposed to create the workspace in `handleInitialize` with the `workspace/didChangeWorkspaceFolders` notification sent from client to server.

This notification is sent by default if both client capability `workspace.workspaceFolders` and the server capability `workspace.workspaceFolders.supported` are true; or if the server has registered itself to receive this notification. To register for the `workspace/didChangeWorkspaceFolders` send a `client/registerCapability` request from the server to the client. 

We used to register for this capability on onInitialized in PTVS, meaning it is dynamically registered. However, [this change](https://github.com/microsoft/pyright/pull/4666/files) made in pyright has made it no longer supports dynamic registration for `workspace.workspaceFolders` capability, so it will be enabled on initialized instead.
