### ISSUE TITLE
Failed to load the template when use the python installed from Microsoft Store.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7518]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/232973967-dcfe3635-467e-44d8-8a9c-84f8e68d2226.png)
The python installed from Microsoft Store

**Steps to Reproduce**
1. Launch VS and create a new python application.
2. Select View > Cookiecutter Explorer
3. Load every template from the "Recommended" section
4. Check the Output window.

**Expected behavior**
The template loaded successfully without any error.

**Additional context and screenshots**
Failed to load the template.
![image](https://user-images.githubusercontent.com/59192491/232974893-f692f91f-39eb-4cf1-84d3-1df52a3b28ee.png)

When use the python install from python.org, the template can be loaded successfully.
![Python3 9](https://user-images.githubusercontent.com/59192491/232975087-35bc9bee-3e59-4e3d-9419-b9a96def2f46.png)

**Comment by StellaHuang95** [comment]
This error message suggests that you are trying to install a Python package using the `--user` option, which installs the package into the user's site-packages directory, but the virtual environment you are using does not have visibility to the user site-packages directory. Maybe for some reason Python downloaded from the Microsoft Store has a different configuration that sets the `--user` option by default? Could you do `pip config list` in terminal window and see what the outputs are? Does the issue only repro with Microsoft Store Python?

**Comment by linette-zyy** [comment]
@StellaHuang95 
![image](https://user-images.githubusercontent.com/59192491/233235624-6e7ba87e-b24e-4a65-a2e1-c96850671067.png)
The issue only repro with Microsoft Store Python

**Comment by StellaHuang95** [comment]
@linette-zyy Thanks, so it's more like a config issue. To change the values of these configuration options and disable the `--user` option by default, you can use the following commands:
```bash
pip config set user.install.user false
pip config set user.list.user false
pip config set user.uninstall.user false
pip config set user.freeze.user false
```

This will set the configuration options for your current user. Could you try above and see if the issue persists?

**Comment by linette-zyy** [comment]
@StellaHuang95 
I get some errors
![image](https://user-images.githubusercontent.com/59192491/233519543-45613980-d90f-4a51-a5f6-6d803b247bba.png)
![image](https://user-images.githubusercontent.com/59192491/233519595-ce9ce501-cc54-4d05-b09d-94211a8c1c9a.png)
![image](https://user-images.githubusercontent.com/59192491/233519628-a7f4ba3a-06ef-4d5b-a922-f633a1bb6cc1.png)

**Comment by StellaHuang95** [comment]
@linette-zyy, it may be because you do not have sufficient permissions to modify the pip configuration file. I found a workaround to modify the pip.ini file, which is:

1. Right-click on the pip.ini file and select "Properties".
2. In the Properties window, go to the "Security" tab -> "Advanced" -> "Change" Owner.
3. Type in "Everyone" in the "Enter the object name to select" dialog.
4. Click on "Add" to add a new user or group.
5. Type in "Everyone", click OK, Apply, OK.
6. Next go to the "Add" button to add permission entries.

![image](https://user-images.githubusercontent.com/100439259/233733698-ea0f3b57-c569-4df6-9f04-dee90915b424.png)

8. Click "Select a principal" and type in "Everyone"
9. Check the box next to "Full control" to grant full permissions to the file.
10. Click "OK" to save the changes.

Then you should be able to delete the .ini file or modify it. Could you try above? I think it's an issue with Microsoft Store python, but that's the workaround I found after some trial and error.

**Comment by StellaHuang95** [comment]
@linette-zyy, it may be because you do not have sufficient permissions to modify the pip configuration file. I found a workaround to override the global configuration file located in the Program Files directory. 

1. Go to %APPDATA%\pip\pip.ini, if the pip directory does not exist in the specified location, create it.
2. You can use any text editor to create and edit the file, try adding the following, save and see if you can repro the issue in VS.
```
[install]
# user=yes

[uninstall]
# user=yes

[freeze]
# user=yes

[list]
# user=yes
```

**Comment by linette-zyy** [comment]
@StellaHuang95 
Today I can load the template successfully in this build:**17.7.0 Preview 1.0 [33618.354.main]** without any other configuration
And I can  load the template successfully in latest build:**17.7.0 Preview 1.0 [33622.66.main]**, I can not repro this issue
