### ISSUE TITLE
Need to clear Python Interactive Window

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/PTVS#752]
Hello,

I need to clear / reset the Python Interactive Window, and figured I should be able to use code similar to the following:

``` python
import os
os.system('cls')
```

However, this simply returns `0`, and doesn't clear the screen.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by int19h** [comment]
There is a button on the toolbar of the window that will clear it.

There is no way to do it programmatically, though. `cls` won't do the trick because it's not really aware of terminals other than the standard Windows one. The more appropriate way to do this would be `print('\x1b[2J')` (i.e. issue the ANSI term sequence for clearing), but the Interactive Window does not support it currently - perhaps it should; e.g. Canopy does.

**Comment by pcgeek86** [comment]
I'm familiar with the UI button to clear the window. However, as a heavy keyboard user, especially with Visual Studio's awesome framework, I would prefer to automate this, and have it available in PTVS out of the box. :smile:  

Cheers,
Trevor Sullivan

**Comment by zooba** [comment]
When you say "automate" what do you mean? Is typing `$clear` good enough (scripts run with Send to Interactive or $load can use this command too, IIRC)? Or does it have to be portable Python code that also works elsewhene (in which case, `os.system` is no good because that launches a new `cmd.exe` process - I don't think we want to get into the business of inspecting arguments and override behaviour like that).

**Comment by pcgeek86** [comment]
Sorry, poor wording. I was up late last night.

A Python script should be able to clear / reset the Python Interactive window, regardless of whether the code is run on-demand in the Python Interactive Window, or as part of a Python script run in the debugger.

I don't know what `$clear` or `$load` are. I'm a Python noob. What are those?

Does that help clear it up a bit?

Cheers,
Trevor Sullivan

**Comment by crwilcox** [comment]
$clear or $load would be terms available in the interactive window.  They aren't python commands but instead are shortcuts to do operations in the interactive window that we provide to let you do operations using the keyboard.

On your comment:
> A Python script should be able to clear / reset the Python Interactive window, regardless of whether the code is run on-demand in the Python Interactive Window, or as part of a Python script run in the debugger.

Why would a python script be aware of your development environment? I would appreciate it if you could elaborate on the usefulness of this. Unfortunately I can only seem to see the things you are going to lose by doing this and I can't see much upside.

**Comment by int19h** [comment]
I think the point is that Python script should be able to do this _without_ being aware of the specific development environment - i.e. it should be able to simply use the standard way to clear the screen, and it should just work in the REPL.

Basically, we need to implement the ANSI terminal sequences that correspond to clear screen. Right now I think we only do colors?

**Comment by pcgeek86** [comment]
Correct, Pavel hit it on the head. Python should be able to clear the host, regardless of the development environment. Look at the PowerShell architecture, for example. The PowerShell engine can be hosted inside of a process, which abstracts the details of the development environment from the engine itself.

You might want to talk to the folks who work on the PowerShell Tools for Visual Studio (PoshTools) project. They recently had to deal with this same issue. Incidentally, I was the same person who filed this feedback. :) 

https://github.com/adamdriscoll/poshtools/issues/265

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by zooba** [comment]
PowerShell also has a standard command for clearing the screen, which Python does not. ANSI terminal sequences are less than ideal and I don't want to get onto the slippery slope of adding more and more. (Do we intercept calls to the console APIs via ctypes? Do we add curses support? These are far more accessible ways of clearing the screen.)

Basically, there is currently no way for a Python script to clear the screen without making assumptions about its environment. Our interactive windows are meant to be user focused, which means the user is the one to issue the `$clear` command, choose to execute a script in a way that it can execute the `$clear` command, or click on the toolbar button. I'm -1 on trying to handle other terminals' secret handshakes here.

**Comment by int19h** [comment]
curses and equivalents should detect the terminal and use ANSI codes for it (just like it does for colors). So that is, effectively, the standard way of clearing it - and not really any more secret than the colors.

The bigger problem is that there isn't really just a single sequence for "clear the screen". It's done as a compound sequence that moves the cursor and then clears stuff below it, and can come in many variations, so supporting it properly would basically require implementing full support for cursor movement. That may have some interesting interactions with things like REPL prompts...

**Comment by zooba** [comment]
Apologies - everywhere I've mentioned `$clear` previously, it should be `$cls`.

**Comment by alexranaldi** [comment]
Functionality to clear the interactive window with only keyboard input would be valuable (without having to click anything). Either a hot-key or a brief command that can be typed in interactive would be acceptable. I don't see why it has to be python code - something PTVS specific would suit my needs.

**Comment by int19h** [comment]
`$cls` will do that.

**Comment by legoninjago** [comment]
you could use `import os
os.system('clear')`

**Comment by legoninjago** [comment]
use

`import os`
`os.system('clear')`
