### ISSUE TITLE
Weird behavior with Automatically adding brackets for functions

### ISSUE THREAD

**Issue by Jacob-Friedberg** [microsoft/PTVS#7523]
### Discussed in https://github.com/microsoft/PTVS/discussions/7521

<div type='discussions-op-text'>

<sup>Originally posted by **Jacob-Friedberg** April 20, 2023</sup>
![image](https://user-images.githubusercontent.com/7202146/233322346-32152ae9-5988-45da-b0c9-749234a8efb6.png)

I am getting some weird behavior when I use the automatically add brackets for function feature in text editor python settings. 
If i type print and perform a tab complete I get this: 
![image](https://user-images.githubusercontent.com/7202146/233322832-65fdce81-d5ff-413f-ad1e-f83c12bfd5f0.png)

parentheses are properly placed at the end of my function call, but there is a $0 sitting in the middle and my cursor is placed at the end if the line rather than in the middle where I would expect it to be placed.

Is this normal behavior? The behavior I would expect from this feature would be to put the parenthesis at the end and then place my cursor in the middle so I can type in my arguments.

This is a fresh install of Windows 11, and a fresh install of Visual Studio 2022. I am using python 3.11 downloaded and installed from python.org</div>

**Comment by StellaHuang95** [comment]
Hi @Jacob-Friedberg, thanks for reporting this issue. It has been fixed in https://github.com/microsoft/PTVS/issues/7432. VS has a long release cycle, which means that once we have identified and fixed an issue, it may take some time before the fix is incorporated into a new version of Visual Studio that is publicly available. Could you please try it again in the latest preview version of VS and let us know if the issue still persists? Thanks.

**Comment by Jacob-Friedberg** [comment]
I can confirm this issue is fixed in 17.6.0 Preview 4.0. Thank you for pointing this out.
