### ISSUE TITLE
Send to Interactive command should work with no text selected

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/PTVS#753]
The `Send to Interactive` command (default keyboard shortcut sequence: `CTRL + E, CTRL + E`) should still work, even if no text is selected in the text editor. If no text is selected in the Editor window, the behavior should be to select the line that the cursor is currently on, and send that to the Python Interactive Window, instead of disabling the feature altogether.

![image](https://cloud.githubusercontent.com/assets/466713/9266764/b8f69698-4202-11e5-9f63-94a290331040.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by zooba** [comment]
The problem with this is that many more questions arise.

What if you have the cursor in a function? Do you want the entire function, or just the current line? Do we trim the leading indentation? Do we append to the current input or replace it? What if you're in a nested function - do we send the whole thing or just the inner function? Or just a single line, now dedented completely? If you're on an `if` statement, do we send just that line or all the `elif` and `else` blocks too?

We considered this a while ago, but all of these arose and we realised we didn't have the time to fully spec out this feature, test it with users, and implement it. There are also going to be hundreds of edge cases that will cause problems and will make it very hard to avoid lowering the overall quality of the product.

I'll leave this open as an enhancement, but I'm marking it as help-wanted in case someone wants to help fully specify the behavior before we commit to implementing and supporting it.

**Comment by pcgeek86** [comment]
@zooba Are you by chance familiar with how the PowerShell Integrated Scripting Editor (ISE) handles this? The way it handles this is pretty straightforward, and easy to understand. If the cursor is on a line, and there is no text selected, then it simply selects the line that the cursor is currently on.

The question of "*what if the cursor is inside a function*?" still comes up in the PowerShell scenario, but I don't think it's realistic to make assumptions about which parent scope the user wants to execute. Executing the line that the cursor is currently on seems to make the most sense, and doesn't make any assumptions beyond "*the cursor is already on this line, so I'm going to use that.*"

That being said, I do see the difference with Python indentation, however. That does present a unique challenge, and I'm not sure that it would be appropriate to assume that the user wants to execute the "current line" and strip it of its indentation. Hmmmm, back to the whole "assumptions" thing ....

I can see why you haven't implemented it yet. I think the overarching concept here (where I'm coming from) is that users should be enabled, rather than having a feature be completely disabled. There are often cases where I simply want to execute the "current line," but don't want to have to use the extra keystrokes to select it on my own. My hope was that the tool could accomplish this for me, similar to PowerShell ISE.

Thanks for your feedback, and I look forward to hearing what you think about my thoughts.

Cheers,
Trevor Sullivan

**Comment by FrankNiemeyer** [comment]
Note that F# also uses significant whitespace and the pragmatic "send the current line without indentation" works pretty well in my experience and certainly better then the current PTVS way of doing things, although it is not perfect (no support for "incremental function definition").

IPython seems to reduce the indentation of all pasted lines by the indentation of the first pasted line. It also recognices e.g. function definitions, if, and loop statements and instead of executing them directly expects further (indented) input. I think this is very reasonable behavior and I would be very happy if "send to interactive" simply did what pasting into an IPython-powered Python Interactive window already does.

**Comment by pcgeek86** [comment]
@FrankNiemeyer That seems like a reasonable solution for PTVS. Thanks for chiming in. @zooba what do you think, mate?

Cheers,
Trevor Sullivan

**Comment by zooba** [comment]
Yeah, that's basically the only way it could be done and explained simply enough that people would actually be able to use it. The indentation trimming is our code as well, and it should work just fine for a regular Python interactive (assuming you've selected all the indentation on the first line), but it does make sense in this case.

Extract Method is the comparison I normally use, and people often hit roadblocks there when they haven't selected enough code to be extracted and still be valid, so we try and extend it. I can certainly see a number of cases where that behavior would be preferable, but those are probably served just as well by a separate "Send this function to interactive" command (like we sort-of-have for "run this unit test").

We might also end up with some sort of cell definitions in the editor, like the `# region` comments we already support, and being able to execute the current cell with a simple shortcut has been requested at least as often as sending the current line.

All that said, I do agree the best way to implement this is:
* if text is selected
 * insert all selected text at the current caret location in the interactive window
 * leave the editor selection unchanged
 * move the interactive caret to the end of the inserted text
 * if the interactive input is a complete statement, execute it
 * move focus to the interactive window
* if nothing is selected
 * insert all text on the current line at the current caret location in the interactive window, except leading whitespace, including the line ending, even if there is not a complete statement on the line
 * move the editor caret to the start of the following line
 * move the interactive caret to the start of the following (currently blank) line
 * if the interactive input is a complete statement, execute it
 * move focus to the interactive window

The last points about moving focus *could* be changed to keep focus in the editor window, but that would certainly need to be tested with a broad range of our users. I can't make any clear argument for switching or not switching to the interactive window at this step, and I'm fairly sure it'll depend on exactly what you're doing at that time (so having an option for it doesn't necessarily help).

It may also help people more if instead of moving the editor caret to the next line we instead select the text that was just sent, such that the same end-state exists regardless of whether you started with a selection or not. These are probably things we need to test with an actual implementation rather than speculate about, but there is certainly *something* we can implement here, so I'll add it to the plan for 3.0.

**Comment by zooba** [comment]
Here's another thought: what if we did #88 and used this command with no selection to send the entire cell (defaulting to the entire file if you have no cells marked)?

Ctrl+A, Ctrl+E, E is admittedly not far away for when you want to send the whole file, but if we went for cells then I think sending the whole file when there are no cells would be the only thing that made sense. It also doesn't really have the same behavior choices we face with a single line.

Thoughts?

**Comment by pcgeek86** [comment]
I only briefed over #88, but on initial though, I like that idea. Makes a lot of sense, like "code regions" in PowerShell. In fact, it would be awesome if PowerShell Tools for Visual Studio supported the same concept. :) :)

The reason I don't like `CTRL + A, CTRL + E, E` is because the `CTRL + A` (Select All) moves the cursor and text editor view all the way to the end. This is a jarring effect for a developer, who simply wants to test something out, and keep typing.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
