### ISSUE TITLE
Error List doesn't refresh after creating a new project

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7534]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/234492154-3ebb2a70-bbeb-4697-93b4-7522da183af7.png)

**Steps to Reproduce**
1.Create a python project
2.Type some problematic code in default file
3.File->New->Project
4.Check the Error List

**Expected behavior**
Error List should not display any error and warnings

**Actual behavior**
Error List doesn't refresh and still exist previous project's error and warnings

**Additional context and screenshots**
![errorlist_not_refresh](https://user-images.githubusercontent.com/59192491/234494572-c63847f1-850c-44d2-a99c-ffe5422e8b00.gif)

**Comment by StellaHuang95** [comment]
Per LSP spec, diagnostics notifications are sent from the server to the client to signal results of validation runs.

Diagnostics are “owned” by the server so it is the server’s responsibility to clear them if necessary. The following rule is used for VS Code servers that generate diagnostics:

- if a language is single file only (for example HTML) then diagnostics are cleared by the server when the file is closed. Please note that open / close events don’t necessarily reflect what the user sees in the user interface. These events are ownership events. So with the current version of the specification it is possible that problems are not cleared although the file is not visible in the user interface since the client has not closed the file yet.

- if a language has a project system (for example C#) diagnostics are not cleared when a file closes. When a project is opened all diagnostics for all files are recomputed (or read from a cache).

When a file changes it is the server’s responsibility to re-compute diagnostics and push them to the client. If **the computed set is empty it has to push the empty array to clear former diagnostics. Newly pushed diagnostics always replace previously pushed diagnostics. There is no merging that happens on the client side.**

Right now pylance server seems to do its job, now investigating if the client overwrites the diagnostics everytime it receives new ones.

**Comment by StellaHuang95** [comment]
By observing the VS LSP file logger live telemetry, on solution/project close, `workspace/didChangeWorkspaceFolders` with `params.event.removed = workspace` is sent out first, then `textDocument/didClose` gets sent, then server shuts down. 

Because of the sequence of the messages, and the fact that pylance only sends empty diagnostics on file close, pylance is not able to find files that belong to the workspace after `workspaceRemove`.

This doesn't repro in the single root workspace scenario in vscode because vscode just disposes the old workspace and re-creates a new one on workspace open. 

This repros both in VS and the multi-root workspace scenario in vscode. To repro in vscode:
1. Add "python.analysis.diagnosticMode": "workspace" to workspace.json
2. remove one folder from workspace
3. diagnostics of the files from the removed folder are still displayed

**Comment by StellaHuang95** [comment]
This should be fixed once Pylance ships the fix in stable.
