### ISSUE TITLE
Is the Package update method aware of PIP's special update method?

### ISSUE THREAD

**Issue by 13steinj** [Microsoft/PTVS#754]
I don't know the exact terminology, but via the GUI you can update your packages. However, on windows, [pip needs to be updated differently than usual](https://pip.pypa.io/en/latest/installing.html#upgrade-pip), Otherwise, the update will either fail or it will "succeed" (but in reality, it renders PIP unusable). Is this known? And if it is, for other packages, may we be allowed to specify special update methods that would be written in that module's docs?

**Comment by int19h** [comment]
It will use `python -m pip` for any package (not just pip) on Python 2.7+, and it will use an equivalent longer-winded form of `python -c ...` on older versions.

https://github.com/Microsoft/PTVS/blob/9dd230510c6806e5205099ff8e5ede0c67a2bec6/Python/Product/PythonTools/PythonTools/Project/Pip.cs#L48

There is no customizability for how specific packages are updated.

**Comment by zooba** [comment]
The reason pip has a "special" command for updating it is because simply running `pip.exe install -U pip` needs to change the `pip.exe` which is currently running. As @int19h says, we avoid that completely by never using `pip.exe` from Visual Studio and *always* using the form that will work for uninstalling/updating pip.

No other packages should need special consideration like this, unless they are trying to uninstall pip.
