### ISSUE TITLE
Add python interpreter from WSL

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7554]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-python-interpreter-from-WSL/10080853)._

---
Currently, Visual Studio 2022 allows to add python interpreters installed locally in Windows. It would be nice the option to add python interpreters installed in WSL. Some developers like me work on WSL with C++, and many times we mix both python and C++

---
#### Feedback Bot on 6/27/2022, 02:29 AM: 

(private comment, text removed)

**Comment by cbakersdl** [comment]
This would be a fantastic feature.

**Comment by cwebster-99** [comment]
Thanks for submitting this feature request - we appreciate you taking the time providing suggestions to improve PTVS. 

If you are hoping for more robust support, we recommend checking out VS Code with the Python and WSL extensions which supports discovery of Python interpreters in WSL. 

In order to provide Python interpreter in WSL discovery or project system support, it would require a significant lift. Given our current limited resources, it's unlikely we will be able to add this in the near future, so we're closing it to focus on higher priority issues. However, if this is a critical issue for you, let us know, and we can reevaluate. Thanks!
