### ISSUE TITLE
VS 17.5.3 Error List tab shows nonsense

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7589]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-1753-Error-List-tab-shows-nonsense/10352406)._

---
[severity:It bothers me. A fix would be nice]
The attached screenshot shows the error list. The 1st entry is "Propane is not defined". You can see in the edit window there is no "Propane" on the first line. The 2nd entry says "TANK" is not defined. That, also is not on the 1st line of the edit window.

---
#### Feedback Bot on 5/3/2023, 07:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for reporting this issue. It has been fixed in https://github.com/microsoft/PTVS/issues/7068. VS has a long release cycle, which means that once we have identified and fixed an issue, it may take some time before the fix is incorporated into a new version of Visual Studio that is publicly available. Could you please try it again in the latest preview version of VS and let us know if the issue still persists?
