### ISSUE TITLE
import could not be resolved for from flask import render_template

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7595]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/import-could-not-be-resolved-for-from-fl/10356244)._

---
Created my first Flask blank Web project. The 2 lines below have green squiggly lines with warning "reportMissingImports import could not be resolved". So how do I resolve that. The code is
from flask import render_template
from FlaskWebProject1 import app
I used all default options when installing python/Flask and when creating the project.I  I did not change anything nor add anything myself other than the project name. I tried both with and without virtual environment. VS details re Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.5

---
#### Feedback Bot on 5/5/2023, 07:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for reporting this issue. It has been fixed in https://github.com/microsoft/PTVS/issues/7068. VS has a long release cycle, which means that once we have identified and fixed an issue, it may take some time before the fix is incorporated into a new version of Visual Studio that is publicly available. Could you please try it again in the latest preview version of VS and let us know if the issue still persists?
