### ISSUE TITLE
Add O16N project / publishing support

### ISSUE THREAD

**Issue by DinoV** [Microsoft/PTVS#760]
The AzureML SDK now has support for defining and publishing services.  We should add support to PTVS that enables a O16N project type and support for publishing it to AzureML.

The project type should start with an empty service.
You should be able to publish multiple services per project.
Publishing the project should publish the entire thing, with each service published independently.
The workspace ID and authorization token support should somehow be integrated in.  We should support reading this from the .ini file which the AzureML SDK supports reading, and we should also support auto-discovering it from cloud explorer if possible.

**Comment by zooba** [comment]
Ideally, most of this would be doable using the SDK first, so that the project can call into the SDK to do most of the work. That will enable many more scenarios without having to duplicate code, as well as ensuring that we can update the behaviour by updating a pip-installable library instead of PTVS proper.

What does "workspace ID and authorization token support" constitute? Do we need login dialogs for AzureML within VS? Browse dialogs for the .ini file? Hopefully Cloud Explorer will be able to support this easily, especially once they have an extensibility model, but we can probably go directly to them if needed here.

**Comment by brettcannon** [comment]
Closing as out of date; looking into Azure Functions instead.
