### ISSUE TITLE
O16N auto-generation

### ISSUE THREAD

**Issue by DinoV** [Microsoft/PTVS#761]
The AzureML SDK now has support for consuming AzureML web services.  We should make this as simple as pointing it at the URL and generate code which uses the AzureML SDK for defining the function.

The user should provide the help URL and API key.
We should read the help URL and auto-generate the corresponding Python function with appropriate decorators.
We need to support functions which were published from Python, as well as functions which were published from within studio.  Functions published within studio can have multiple names.

**Comment by zooba** [comment]
What sort of interface do you have in mind here? A wizard? A code snippet? A lightbulb? Tool window? Project command?

Can the AzureML SDK generate a stub function from the help page? I kind of feel like this should be part of the SDK anyway, and since the user will require it we can make sure we generate the correct code for the version they're using if we call into the SDK. But then if the user can't access pip for whatever reason, they also can't use this feature. I'm not sure if that's a blocking issue or not.

**Comment by DinoV** [comment]
It'll be an editor command...  It would be nice if it was a code snippet but I'm not sure if we can do that.  It may be an inline experience but more likely it would pop a dialog and then insert the code.

The AzureML SDK cannot currently generate a stub function.  I would think this would actually live in PTVS rather then the SDK.

**Comment by zooba** [comment]
I can see the stub generation being useful in the SDK too, just from the POV of printing out what it would look like so people can copy into their notebooks, and it'll certainly be easier to maintain/update there than in PTVS. Might be able to handle different Python versions better too, or at least streamline it (PTVS can just invoke the SDK in whatever environment is active and it'll get the right code).

**Comment by brettcannon** [comment]
Closing as out of date; looking into Azure Functions instead.
