### ISSUE TITLE
Python editing: impossible to disable auto-suggestion dropdown list

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-editing:-impossible-to-disable-au/10398923)._

---
[severity:It's more difficult to complete my work]
When editing Python files, the editor after most actions opens a drop-down list with suggestions. This is **extremely annoying**. There doesn't seem to be a way to disable it.
**Auto list members** setting doesn't affect this mis-feature.

---
#### Alex G on 6/23/2023, 11:36 AM: 

(private comment, text removed)
#### Feedback Bot on 6/24/2023, 07:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there! Thank you for reporting the issue. We have already submitted a fix to address the auto suggestion issue including some of the issues you encountered(see https://github.com/microsoft/PTVS/issues/7597). Please note that VS has a long release cycle, which means that once we have identified and fixed an issue, it may take some time before the fix is incorporated into a new version of Visual Studio that is publicly available. 

If you would still like to see the option to disable auto-suggestion, please upvote this discussion item: https://github.com/microsoft/PTVS/discussions/7334. Thanks!
