### ISSUE TITLE
PowerShell project debug module debugger is needed like Spyder

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7674]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PowerShell-project-debug-module-debugger/1356010)._

---
Unlike dotnet core or standard projects we have PowerShell module that we have to debug in vs2019 but there is no provision for debug module scripts individually also in group 
I see spyder is better for python to debug module 

When vs2019 will bring PowerShell moduled
 Debug feature?

---
#### Feedback Bot on 3/4/2021, 01:44 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Thanks for the issue. Unfortunately, we currently do not have specific information about when Visual Studio 2019 plans to introduce new debugging features due to the limitation of our capacity. However, we value your input and feel free to share the specific use cases or examples where this feature would be beneficial. Thanks!
