### ISSUE TITLE
You can't use pip in a normal environment with cmd to view help, install other libraries, etc

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7682]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/You-cant-use-pip-in-a-normal-environmen/10418767)._

---
[severity:It's more difficult to complete my work]
Instead of using pip in a normal environment to view help, install other libraries, etc., I have to add two files named C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Scripts and C:\Program Files (x86)\Microsoft Visual Studio\ Shared\Python39_64 variable, the following picture is the changed variable.

---
#### Feedback Bot on 7/19/2023, 01:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, it is expected. In order to run the `pip` command in the Command Prompt (cmd), you need to ensure that the directory containing the `pip` executable is added to your system's `PATH` environment variable. By doing so, you enable the Command Prompt to locate and execute the pip command from any directory.

Please reopen the ticket if you have any PTVS specific problems. Thanks!
