### ISSUE TITLE
I attempted to reinstall both Windows and Visual Studio to resolve the problem, but the issue persists. The lack of automatic configuration for enviro

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7688]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-attempted-to-reinstall-both-Windows-an/10421023)._

---
Dear Microsoft Support Team,

I hope this email finds you well. I am writing to seek assistance regarding a persistent issue I am facing with the automatic configuration of environment variables in Visual Studio.

I recently installed Visual Studio on my computer, and during the installation process, I selected multiple language packs, including Python. According to the normal behavior, the installation should automatically set up the environment variables for the installed languages. However, to my disappointment, the environment variables for Python were not added as expected.

I attempted to reinstall both Windows and Visual Studio to resolve the problem, but the issue persists. The lack of automatic configuration for environment variables with two fresh installations is perplexing and frustrating.

I have checked the installation logs, reviewed the installation options, and ensured that I have sufficient administrator privileges during installation. Still, the problem remains unresolved.

As a developer, having to manually set up the environment variables for each language separately is extremely time-consuming and inconvenient. I believe this should not be the expected behavior for a professional development environment like Visual Studio.

I kindly request your expertise and guidance in resolving this matter. Is there a specific step I might be missing during the installation process, or is there a known issue causing this behavior? Any help or insights you can provide would be greatly appreciated.

If you require any additional information or logs to assist with troubleshooting, please let me know, and I will be more than willing to provide them.

Thank you for your time and attention to this matter. I look forward to your prompt response and a resolution to the environment variables configuration problem in Visual Studio.

Best regards,
Andre Lübke

---
#### Feedback Bot on 7/23/2023, 05:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for sharing your issues with different programming languages. While some of these might be outside the scope of PTVS, I can help with the Python issue you mentioned. Regarding the installation of Python and its environment variables, could you please provide more details about the specific problem you encountered during the Python installation? Were you trying to set the PATH variable, or is it related to other environment variables?

Additionally, we could use more detailed logs to see what's really going on. Can you please collect more logs by running http://aka.ms/vscollect.exe and uploading %temp%\vslogs.zip? Thanks.

**Comment by Andre-Leubke-97** [comment]
Hello everyone,

I recently encountered an issue where the automatic addition of environment variables during program installation was not functioning correctly in Visual Studio. After trying various solutions, I ended up resolving the problem by performing a fresh installation of Windows, which seemed to fix the issue.

However, as this was the third Windows reinstallation to address the problem, I'm left wondering about the root cause. I'd like to inquire if Windows has any built-in function or setting that might prevent or interfere with the addition of environment variables during program installation.

Could there be a Windows feature or setting that disabled the automatic configuration of environment variables during Visual Studio installation? It would be helpful to know if there's a specific setting I should check or configure to avoid facing the same issue in the future.

I appreciate any insights or experiences you can share regarding this matter. Thank you for your time and assistance!

Best regards,
A-L
   .
……

**Comment by StellaHuang95** [comment]
Not that I am aware of. Did that happen to just python or also other languages? What's the version of Visual Studio you were using before encountering the problem and the version after the issue has been resolved?

**Comment by Andre-Leubke-97** [comment]
Translate to English:
"I used Visual Studio 2022 during the first and second installations, and now, on the third installation, I reinstalled Windows, but this time, I also recreated the installation stick. After each installation of any program, can I use environment variables? I haven't installed Visual Studio yet, but the main issue with the environment variables is no longer present. So, there are no settings that prevent adding them during an installation, right?"
