### ISSUE TITLE
Color images from capture and run bodytracker at 30fps

### ISSUE THREAD

**Issue by brandontip** [microsoft/PTVS#7795]
I want to get color images from the capture and run the body tracker at 30fps. More specifically, I have a loop of the form:

while tstamp < 3000:
    capture = device.update()    
    ret, color_image = capture.get_color_image()
    body_frame = kinect_body_tracker.update()
    skel = body_frame.get_body_skeleton()
    tstamp+=1

That I want to run at 30fps. 

Right now, the above loop runs at 15fps. Precisely: the above loop takes roughly 200 seconds to complete. I know the camera is running at 30fps because if comment out the body tracking lines it takes only 100 seconds.

**What I have tried**
I have tried using multithreading (making one coroutine for capture.get_color_image() and another for kinect_body_tracker.update()), but that seems to cause a race condition that leads to the error "Body tracker capture enqueue failed" in k4abt\tracker. 

I have also tried feeding the existing capture, by calling kinect_body_tracker.update(capture= capture), but that seems to have no impact on performance.

**Comment by StellaHuang95** [comment]
Hello, and thank you for reporting the issue. It appears that your concern is more related to specific Python code, and we, as PTVS, focus on providing tools for Python development within Visual Studio rather than addressing code-specific issues. We recommend checking popular developer platforms like Stack Overflow for assistance with your specific Python code issue. If you have any questions related to using PTVS within Visual Studio, feel free to reach out. Thanks for your understanding.
