### ISSUE TITLE
Failed to select the process after filtering the processes.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7810]
**Describe the bug**
![image](https://github.com/microsoft/PTVS/assets/59192491/38dac0dc-2aaa-43bf-9e55-9ff7d57eeaaf)

**Steps to Reproduce**
1. Launch VS and create new python application
2. Add an input('>') or raw_input('>') at the top of your code - depends on version of python
3. Add some more python code after that with breakpoint(s)
4. Start WITHOUT debugging
	a. Console will wait for you to input something
5. Debug > Attach to Process, type "python" on the filter box
6. select the appropriate python.exe

**Expected behavior**
The process is selected.

**Additional context and screenshots**
Faile to select the process.
![attach](https://github.com/microsoft/PTVS/assets/59192491/01f4d53e-071d-444f-9d81-6df2e6705bf7)

**Comment by StellaHuang95** [comment]
@int19h Do you know what might be happening here?

**Comment by int19h** [comment]
Unclear. It looks like the Attach to Process dialog got a revamp. So if it's not a VS bug, it must be triggering some new code path in our code, possibly something that returns E_NOTIMPL because it wasn't needed before. 

The entrypoint for our code in this scenario is `AD7ProgramProvider`, which returns an instance of `AD7ProgramNode` to the caller - I suspect that that part succeeds given that it does briefly show "Python" as code type before reverting, but then it fails while calling some method on the returned node.

**Comment by StellaHuang95** [comment]
@linette-zyy Does this still repro?

**Comment by linette-zyy** [comment]
I verified this issue with the latest build and found this issue is not repro.
![image](https://github.com/microsoft/PTVS/assets/59192491/810e5e05-f7a8-4ca9-b94b-37c06f7af653)

![image](https://github.com/microsoft/PTVS/assets/59192491/326be3a2-1251-41b3-b7d9-2995e4882c75)
