### ISSUE TITLE
Prevent users from creating bad environments

### ISSUE THREAD

**Issue by gilbertw** [Microsoft/PTVS#790]
We should do more to validate the environment.  This will help prevent invalid environments.  One idea from Steve is to block the environment at Create step until they've gotten all fields correct.

**Comment by zooba** [comment]
I'm not actually sure that we can block users at that stage - by design, it's meant to be a non-blocking process.

What we *can* do is flash red warnings at them until they've filled everything in, though that will probably be fairly offensive to everyone else who knows what they're doing. I don't think it's easy to miss what's required when you start adding a new environment, but maybe there's a window layout that hides the examples?

**Comment by gilbertw** [comment]
Its odd to let them create something that won't work.  However we maybe don't want to be completely blocking.  I'm thinking we put a little red (!) next to the field that isn't correct.  Then when they click save we save if no issues.  Same experience as today with a single click.  
In the case where we've detected errors we pop a confirmation (2nd Yes click) that indeed they do want to create with the invalid values.  Lets them do it if they want while preventing users from the accidental mistake
