### ISSUE TITLE
Python version incorrect in Python Environments Window

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7901]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-version-incorrect-in-Python-Envir/10653152)._

---
[severity:It bothers me. A fix would be nice]
I have two python environments installed on my machine. One is the Python 3.8 and it is in the %PATH%. The other is an Anaconda distribution and is not in %PATH%. The Anaconda distribution is updated to Python 3.11, but in Visual Studio the distribution version shows Python 3.1. If I chose this environment from the Python Environments window and then click "Open in Powershell", 'python --version' returns Python 3.11.9. Why doesn't Visual Studio show the correct version?

---
#### Feedback Bot on 5/6/2024, 06:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, It seems like the description may not have been updated properly during its creation. To update the description of your python environment to match its version, you can go to the Python Environments window. From there, click the `Configure or remove environment`, and edit the description as needed.
![image](https://github.com/microsoft/PTVS/assets/100439259/4a07401c-e27e-474d-9924-8ffee1af628b)

**Comment by arpetris** [comment]
I don't have the "Configure or remove environment option". 
![PythonEnvironmentsWindow](https://github.com/microsoft/PTVS/assets/59852056/788a1c2d-7aeb-4bd0-b2a7-56e82e60c46d)

**Comment by sh1nryu** [comment]
Hi @arpetris @StellaHuang95 @AdamYoblick,

I was able to fix this using a hint from the Microsoft [documentation](https://learn.microsoft.com/en-gb/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2022#modify-the-registry-to-correct-an-environment).

There, it mentions about modifying and deleting entries under your registry Python path. 

> ❗Warning: Always backup your registry before making any changes (see below)❗ 

![image](https://github.com/microsoft/PTVS/assets/22617094/f8b43ffa-0988-4b79-9bef-73946790aa58)

> ❗Warning: Always backup your registry before making any changes (see above)❗ 

For me, my path was `Computer\HKEY_CURRENT_USER\Software\Python`. It looked like this:

![image](https://github.com/microsoft/PTVS/assets/22617094/49785f01-e9fb-45cd-9312-be6eb9e050f9)

It looks like Visual Studio is by default looking at the PythonCore folder and versions within it to carry out its naming logic. But there does seem to be a bug there, because it should show the the full version number, and it currently is not.

Instead in my Visual Studio, the Environments showed this:

![image](https://github.com/microsoft/PTVS/assets/22617094/ba2a13d9-8ea6-4546-8f96-1c5a8918b4d4)

To test, I changed the folder name within the registry itself, from 3.12 to 3.22 (I know, its not released yet!).

![image](https://github.com/microsoft/PTVS/assets/22617094/303d0958-6837-4d7a-b778-2bcdb222fd84)

This was the result (immediately visible when the registry changes):

![image](https://github.com/microsoft/PTVS/assets/22617094/e0f2eced-9a4c-46fe-8993-808f98aba102)

I then created a custom environment and noticed there were some differences in the registry entries. Specifically the `DisplayName` entry. So I added the String Value entry to the PythonCore version of my python environment, using the value that I expect (in my case, the 64 bit 3.12 version):

![image](https://github.com/microsoft/PTVS/assets/22617094/c9b88c2a-877c-4249-91f4-60a9ee2178c7)

![image](https://github.com/microsoft/PTVS/assets/22617094/c29d17c0-f07e-4582-9240-5c5e971837de)

That's it!

![image](https://github.com/microsoft/PTVS/assets/22617094/99be145c-f848-4cf3-b19a-2bb1fb72d041)

**Comment by StellaHuang95** [comment]
@sh1nryu, thank you for sharing this finding with us! It's a great observation and could potentially be very helpful in addressing this bug. Really appreciate your input!
