### ISSUE TITLE
go to definition (F12) on sympy 

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#794]
if you try go to definition inside *\sympy\**init**.py on these lines:

```
from .core import *
```

Then PTVS message pops up:

Cannot go to definition ".core"

**Comment by denfromufa** [comment]
even sublime+anaconda can do this

**Comment by zooba** [comment]
I thought we already had an issue for this, but I guess not.

This is because `.core` is not a defined name in the file, so (for our current analysis design) it doesn't make any sense to find its definition.

What we need to do is specially handle `from ... import` and assign a value to the module name without interfering with the rest of the file. That will also fix the tooltip showing that the name is undefined.
