### ISSUE TITLE
/MTd /fsanitize=address /LD: OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7986]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MTd-fsanitizeaddress-LD:-OSError:-W/10723837)._

---
[severity:I'm unable to use this version]
I use Visual Studio Build Tools 2019

1) x64 developer command prompt
2) 
>cl /MTd /fsanitize=address /LD main.c
where main.c is empty file (or not, this is minimal case)
main.dll is created

3) however when in python
>import ctypes
>ctypes. CDLL("main.dll")

i get:

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "C:\python3\lib\ctypes\__init__.py", line 374, in __init__
>    self._handle = _dlopen(self._name, mode)
>OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

This normally works with Visual Studio Professional 2022 17.9.2 (same workflow, same flags, etc)

When i omit /MTd, it works as expected but thats what i do not need

---

Forgot to mention build tools version:
happened in both 16.11.39 and 16.11.34 for me

---
### Original Solutions
(no solutions)

**Comment by debonte** [comment]
Thanks for the detailed repro steps. I was able to reproduce this.

You're hitting a limitation of the version of the address sanitizer (ASAN) that shipped in VS 2019. When using /MT or /MTd, the ASAN implementation is statically linked into your DLL and expects the hosting EXE to supply certain ASAN functionality that would only be available if the EXE (python.exe) was also built with ASAN enabled.

You can read more about this at https://devblogs.microsoft.com/cppblog/msvc-address-sanitizer-one-dll-for-all-runtime-configurations/#motivation-and-effects. It appears that starting in Visual Studio 2022 version 17.7 Preview 3, when you build with /MT or /MTd, you end up using the ASAN DLL rather than a static lib, which solves this issue.

Also the discussion on this Developer Community issue provides some more details. I found it interesting: https://developercommunity.visualstudio.com/t/C-Address-Sanitizer:-statically-linked/1403680
