### ISSUE TITLE
gradual slowdown of IDE

### ISSUE THREAD

**Issue by nidleo** [Microsoft/PTVS#806]
The IDE experience is getting noticeably slow at times. That is, slow REPL response, scrolling and selecting code, intellisense and so on.

This happens first when I bring up VS and open a Python solution. I see VS is using up 1 CPU core for a few minutes. Then everything seems much more responsive and the CPU usage drops to near zero.

As I continue working I see VS is taking up plenty of memory (I tried resetting the REPL) e.g. from 500MB initially to 2GB. The slow down is again evident after a couple of hours. Resetting VS and waiting a few minutes helps.

I'm using PTVS 2.2 with Visual Studio Ultimate 2013

**Comment by zooba** [comment]
You've either got a very large code base or something in it is causing trouble with our analysis (probably both).

If you're able to share your project with us, that would be really helpful for us to rule out the latter, and would also be helpful as we prepare to tackle the former. You can email ptvshelp@microsoft.com to keep things out of the public if appropriate.

**Comment by nidleo** [comment]
Hi,

My own code base is rather small consisting of 20-30 reasonably sized python files.
I understand now what is causing the first type of slow down - right when I open my solution VS is taking up lots of CPU for a few minutes. It is the presence of the "WinPython-64bit-2.7.9.5" folder. It's not part of the project but it is in the same the folder. I can see it when I enable "Show All Files".

Looks like VS is scanning "WinPython-64bit-2.7.9.5" which is really large. I'm not sure if it's PTVS doing the scanning or not.
I guess a temporary workaround is to move this folder away. It might even alleviate the second type of slow down (the gradual one), but I'd have to work with it for some time to see.

I hope this helps. Do you still want me to share my project?

**Comment by zooba** [comment]
I'd strongly recommend moving either WinPython to another folder or your project to another folder. Having it in the same location is telling VS that your project includes every file in that folder, and so it's going to cause huge problems when we treat it all like your code. (Frankly, I'm surprised you aren't seeing things break sooner!)

If you keep WinPython separately, we'll scan it once and save the results, then only update pieces as they change. But we don't do that for projects because they typically change very frequently.

**Comment by nidleo** [comment]
Ok so I moved the WinPython directory away. I've been working with PTVS for a couple of days now without restarting VS and the gradual slow-down is there. VS memory usage went from 500Mb to 1500, and things are definitely slower now.

I don't think it's the size of my code, which is roughly 20 files.

**Comment by zooba** [comment]
It's generally not the size of the code, especially over a couple of days. Sometimes there are interactions between things in your code that make it impossible for us to release some memory (technically it's by design, but fixing the design is incredibly difficult so we haven't been able to release a fix yet).

The easiest workaround is to periodically close and reopen your solution, which should take only a few seconds in your case. We may release an automatic workaround in an update that periodically resets our state to avoid these issues (hopefully without having any obvious effects - maybe IntelliSense is extra slow once an hour or so). Avoiding the leak entirely probably means rewriting our code analysis from scratch, which we simply can't afford to do (though I may be trying to do it on the side because I really want to :) ).

**Comment by kdriedger** [comment]
Seems all the members of my team are having the same issue.  Currently after a few days my devenv.exe process is taking 2617 MB (over 2 GB).  Given that devenv is a 32-bit process, I am wondering when it'll run out of memory.  Restarting the VS does reset the memory to a more reasonable level (but it takes a while to re-parse the solution and during that time F12 (Go To Definition) doesn't work).

**Comment by zooba** [comment]
@kdriedger How many Python projects do you have in your solution? I've been considering a change for PTVS 3.0 that would make many-projects be much faster than today, though it won't have any effect on a single large project.

**Comment by kdriedger** [comment]
My solution only has one (1) python project.  To give an idea of size the line count for the .py files is 11285 (which feels small to me).    The lib directory has some python libraries (total LOC 25615) which also doesn't feel large but perhaps it is.

**Comment by zooba** [comment]
It really depends on the actual code, as we break it up into functions very early on. So for example, if you often define nested functions then things will bloat much more quickly than 25KLOC of script with no functions or classes. Lines of code is not a good predictor of memory usage.

**Comment by kdriedger** [comment]
Here's another analysis that is hopefully helpful:
145 classes in my code
     400 functions (very few nested functions)
241 classes in the project that are 3rd party code
    1065 functions (unsure of how nested)

**Comment by zooba** [comment]
I suspect this was some cross-module analysis leaks, which we've resolved some of but probably not all. We're still interested in code that causes leaks so we can track down any remaining ones.

**Comment by kdriedger** [comment]
I'll see how it performs on the new code drop.
