### ISSUE TITLE
Automatic Brace Completion

### ISSUE THREAD

**Issue by moleschott** [Microsoft/PTVS#808]
Hi guys.
In settings, Automatic brace completion is disabled.It's very annoying thing to close all opening braces. Is there any way to handle this issue.

**Comment by zooba** [comment]
Currently it isn't supported for Python - we need to write the support to enable it. Marking it as an enhancement.

**Comment by moleschott** [comment]
Thanks zooba.

**Comment by crwilcox** [comment]
If you are interested in making a contribution I did this for Node.js Tools.  I am not sure it will be a verbatim copy, but this changeset (and future changes to BraceCompletion.cs) should provide a good idea of how you can use the IVS interface (IBraceCompletionContext) to provide this support for PTVS.

https://github.com/Microsoft/nodejstools/commit/95eb76d875384493dcaa481901e327c0d6c49f56

**Comment by romanvm** [comment]
The same for quotes. It's very annoying to have different experiences for C++/C# (where brace/quote completion works) and Python.

**Comment by moleschott** [comment]
Any improvements on this issue @zooba .

**Comment by zooba** [comment]
Not yet - it won't be in our next update (we've been focusing on crash/bug fixes and avoiding enhancements). We're certainly willing to do it, but it's a matter of having time and balancing it against other features.

(Many enhancements like this get into the product because one of the core developers really wants it. However, I personally don't like this feature so it's unlikely to be me who forces it in :) )

**Comment by moleschott** [comment]
You mean that followers opinions are not important and can be easily ignored. I get that we will always write code in your teams planned style. If you wish something, it will be a gift for us. This is an embarrassing comment @zooba from a Microsoft supported project manager.

**Comment by zooba** [comment]
Not at all, it just means that we have to prioritise everything and this is fairly low priority. But because we accept contributions, if anybody wants to bypass our prioritization, they are more than welcome to and we will accept the change. The point of the "help wanted" tag is to indicate that (a) we probably won't get to this ourselves and (b) we think it's a suitable change for someone to contribute.

Occasionally our own team will bypass the prioritization outside of work hours, but recently I've been the only one who has done that. I'm simply saying that I'm not going to do that for this feature, and so unless someone steps up to contribute it then it isn't going to make it ahead of the other things we need to work on.

**Comment by int19h** [comment]
The team has a limited number of people, and those people have a limited number of hours per work day to spend doing things. This includes implementing new features and fixing bugs, as well as the inevitable engineering overhead (testing, maintaining infrastructure etc), and things like writing documentation. You can take a look at the entire tracker to see just how much stuff is on the backlog already - realistically, there's no way we can implement any of that within a single release even if new bugs and feature requests weren't constantly streaming in, which they do.

So, we have to decide what exactly we need to work on, and which things are going to go into each release. And the opinions and desires of our users do factor heavily in those decisions. It was, perhaps, more obvious back when we were on CodePlex, where you could go into the bug tracker and sort issues by user votes - you would quickly see that every release would have several top-rated requests implemented. Nevertheless, there will always be some things that never quite make the bar, because of limited resources, and because there are always items popping up that are simply more important - e.g. because they are requested by more users, or because they block a major scenario for a lot of users.

When people care about something strongly enough, they can contribute some of their extra time to do it. This is an option available both to team members and to users of the product, since it is open to code contributions from anyone. It largely circumvents the schedule and the feature prioritization, because the time invested is not accounted for when planning, and because we are not going to turn down well-written code that does something useful that is within the scope of the project (at worst, it may be delayed if we're in stabilization phase for an imminent release). This particular feature request qualifies - if there's a quality implementation for it, we will definitely take it (and we'll also help anyone who would express a desire to implement it to get started). 

All @zooba was saying is that if we had someone on the team who really, really wanted this feature for themselves, they'd probably just do this sort of thing, and then you'll see it in the next eligible release. But since there are no champions for it, it remains in the general priority queue, along with over 300 other things that we need to do at some point in the future. And because there's a constant influx of new bugs etc, it's hard to say how long it'll take for us to get to it without any shortcuts such as an external code contribution.

Please don't let yourself be discouraged by this, though, and keep reporting any issues and filing feature requests. There may not be an immediate resolution, but we do pay attention to all feedback, and having it in writing in the issue tracker is the first step towards resolving it at some future point.

**Comment by Lenbus** [comment]
Really good to know this feature is embedded know! Unfortunately I can not find where to enable it... Under 'Options -> Text Editor -> Python' the option 'Automatic Brace Completion' is still greyed out... :(

**Comment by zooba** [comment]
It'll be in our next major release (coming with the next version of Visual Studio). The VS 2015 release is in maintenance mode, so we aren't adding new features.
