### ISSUE TITLE
Provide a "compile" option

### ISSUE THREAD

**Issue by assafmendelson** [Microsoft/PTVS#816]
Often, I write code and make mistakes. The problem is that usually I only find those mistakes when I run the code. I often use pylint to find them but a more useful option would be to "compile" the code and check if there are errors.
The way I see it there are several layers of doing this:
1. The "compile" option would simply run a properly configured pylint which would only check for warning and errors related to running (i.e. no coding style stuff).
2. The "compile" option could add additional analysis tools to find errors.
3. We might have something which would update this in the background so we can see the warnings in the editor while writing.

**Comment by zooba** [comment]
One way to do this now is to add `<Target Name="CoreCompile"> ... </Target>` to your `.pyproj` file, filling in the '...' with whatever you like (probably along the lines of `<Exec Command="command line" />`).

Simply adding this target will enable the Build command within VS, and it should put output into the output window and errors into the error list (though this can be a bit fiddly).

As for regularly showing you errors, that's something we should be able to do based on our existing code analysis, so it doesn't require installing or running anything. We just haven't had time to do it. (And it looks like the issue was not transferred from our old site yet...)

**Comment by lennoncork** [comment]
I have been able to get the target to build successfully, but only with the "Rebuild" command. Running "Build" always skips as Visual Studio thinks everything is up to date. 

`========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========`

I've tried adding a dummy file to "Outputs" in the "CoreCompile" target but not luck. "Clean" works as expected, and "Rebuild" always builds, but "Build" always skips. 

`
<Target Name="CoreCompile" Outputs="BuildSuccess.log">
    <Exec Command="python RunBuild.py -c '$(Configuration)' -p '$(Project)'" />
  </Target>
  <Target Name="Clean">
    <Exec Command="python RunClean.py -c '$(Configuration)' -p '$(Project)'" />
  </Target>
`
Should Outputs work with the CoreCompile target, and chance you could provide an example?

**Comment by zooba** [comment]
The Outputs parameter won't work, but if you add an item group called `OutputFiles` then we will compare date/time stamps against those when deciding to build:

```xml
<ItemGroup>
    <OutputFiles Include="BuildSuccess.log" />
</ItemGroup>
```

You might also want to consider using our `RunPythonCommand` task instead of `Exec`, if you always want to use the currently selected Python environment:

```xml
<RunPythonCommand
    Target="RunBuild.py"
    TargetType="script"
    Arguments="-c '$(Configuration)' -p '$(Project)'" />
```

(See the comments in [Microsoft.PythonTools.targets](https://github.com/Microsoft/PTVS/blob/master/Python/Product/BuildTasks/Microsoft.PythonTools.targets) for all the options. These are deliberately undocumented, but definitely intended for people to use when they need them.)
