### ISSUE TITLE
Code Suggestions doesn't show up automatically

### ISSUE THREAD

**Issue by HellHunter** [Microsoft/PTVS#823]
Hey there. 

I tried to get this working for the past 3 days now, but I can't seem to find a solution. 

These are my settings:

![](https://i.gyazo.com/bdf3e97197311d066263a328bc0cb332.png)

Even though everything is enabled, the code suggestion only shows up when I press CTRL+J.

Kind regards,
HellHunter

**Comment by zooba** [comment]
Are you using PTVS 2.2? If you're on an earlier version, they only appear automatically after you type a space or a dot.

In PTVS 2.2, there are new options under Advanced to control when we automatically pop them up, but it still isn't all the time because some situations are more annoying than helpful.

If you type:

```
x = a
```

We should pop up automatically on `a`, but not `x`.

**Comment by HellHunter** [comment]
Oh wow, thank you! That is just amazing!

I was just typing in some random letters and never tried this approach. Well that just fixed my whole problem.

Thank you very much and thanks for this awesome Plugin!
