### ISSUE TITLE
PTVS extensibility API using C# or/and Python

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#829]
Is there PTVS simplified API using Python or C# for extending intellisense, debugger, REPL, build tools, etc.?

E.g. conda manager

**Comment by int19h** [comment]
Can you clarify? Are you asking about extensibility points in PTVS itself (i.e. custom package managers, launchers, interpreter handling etc)? Or whether there is some kind of layer provided by PTVS to simply VS extensibility in general?

**Comment by denfromufa** [comment]
Not VS, but PTVS extensibility. I know some people asked for Python macros
in VS, but this is not what I'm after :)

**Comment by zooba** [comment]
Yes, there are, though they aren't necessarily simple :) Also, there's a very good chance that we'll break some of them for PTVS 3.0 (at least, I hope we do, because it will mean we've cleaned up some of the poor architecture we're currently dealing with)

For something like a conda manager, have a look at the [EnvironmentsList](https://github.com/Microsoft/PTVS/tree/master/Python/Product/EnvironmentsList) project (this will all be in C#). If you implement [IEnvironmentViewExtensionProvider](https://github.com/Microsoft/PTVS/blob/master/Python/Product/EnvironmentsList/IEnvironmentViewExtensionProvider.cs) and MEF Export it, you can provide a VSIX package that adds new items to the "Overview", "pip", "Intellisense" list (see [screenshots here](https://github.com/Microsoft/PTVS/wiki/Python-Environments#global-environments)). It's a fairly simple interface, but you'll want to look at (or copy) the pip extension from the project.

To extend IntelliSense, right now you either need to extend the project system (see the [Django](https://github.com/Microsoft/PTVS/tree/master/Python/Product/Django) project) or provide a new environment provider (see the [CanopyInterpreter](https://github.com/Microsoft/PTVS/tree/master/Python/Product/CanopyInterpreter) project). Once you have those hooks in, you'll see in [DjangoAnalyzer.cs](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Django/Project/DjangoAnalyzer.cs) calls into `SpecializeFunction`.

For 3.0, we're keen to provide easier ways to extend IntelliSense. Right now we know it's a pretty big ask.

The REPL is fairly easy to extend. In the Interactive Mode box (visible in the [screenshot here](https://github.com/Microsoft/PTVS/wiki/Interactive-REPL#code-completions)), where you can select "Standard" or "IPython", you can actually write a `module.class` name and we will try to import and use the class. [visualstudio_ipython_repl.py](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/visualstudio_ipython_repl.py) has the `IPythonBackend` class which is referenced as `visualstudio_ipython_repl.IPythonBackend` (there are registry keys to register these, but putting the name in directly also works). This way, you can provide a custom REPL experience through a pip-installable package.

To extend build tools, we basically leave you alone with MSBuild. The one trick is that regular Python projects won't build by default until you add a target named `CoreCompile`. But once you've done that, you'll get the Build commands in VS and it will build every time you run, and you can make it do whatever you like. The MSBuild docs and probably [this walkthrough](https://msdn.microsoft.com/en-us/library/dd576348.aspx) will be helpful here.
