### ISSUE TITLE
configurable depth of code analysis for large projects

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#834]
For large projects PTVS is quite slow with intellisense and completion database. But what if the user has ability to select the level of introspection by PTVS for large projects?

**Comment by zooba** [comment]
Your wish is granted :)

Create a registry key at `HKCU\Software\Microsoft\PythonTools\14.0\Analysis\Project` and add values for any of the items in [AnalysisLimits.cs](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/AnalysisLimits.cs) (smaller means faster/lower quality). Reducing `CallDepth` and `NormalArgumentTypes` seems to have the most impact.

It's not perfect as it applies to all projects for a user, but it is an escape hatch for when you need it. We don't expose them through the UI (a) because it's hard to write good UI for this, and (b) it will lead to poor results, and we don't like it when we have to explain to people that they have "errors" or "bugs" because they changed their own configuration.

As I mentioned in another reply to you, I'm working on some major changes to this area that will likely make it much easier to handle exposing more information and options to users.
