### ISSUE TITLE
Running tests from UI does not support module structure without package

### ISSUE THREAD

**Issue by omtinez** [Microsoft/PTVS#840]
Using the following structure:

```
/module
/module/module.sln
/module/module.pyproj
/module/__init__.py (empty)
/module/module.py
/module/test/__init__.py (empty)
/module/test/test_module.py (from module import class)
```

PTVS is unable to run the tests because it tries to do an import of "module.test.test_module.py" from within /module, which results in an error saying that "module is not a package". The only way to successfully run the tests without turning a simple module into a package, is to modify the visualstudio_py_testlauncher.py file and remove the package part of the path when import fails:

```
try:
    __import__(opts.module)
    module = sys.modules[opts.module]
except ImportError:
    opts.module = opts.module.split('.',1)[1]
    __import__(opts.module)
    module = sys.modules[opts.module]
```

It seems hacky, but it fixed my issue without breaking previous behavior. Would this be good enough for a pull request?

**Comment by int19h** [comment]
Given that you have `__init__.py` in both directory here, `module` _is_ a package. I think the problem is rather that it tries to import it from the wrong path - it should rather start from the parent directory of `module`. IIRC, this is actually something that the project home directory in project properties controls. Alternatively, you can use a different layout for the solution - if your solution is a package, it's best to have the .sln and .pyproj files outside of the package directory (i.e. one level above `module` in your case). Or if module shouldn't be a package, then it should not have `__init__.py`.

**Comment by omtinez** [comment]
This is an existing project for which a Visual Studio solution has been added, which I think must be the single most common usage scenario. Importing all the code into the solution works perfectly, and I can even run the solution pressing F5 with no issue. It is, then, my expectation that, if I can run `python -m unittest discover` from the folder where the solution exists, the Visual Studio test harness should work.

Given that the creation of the module/package predates the Visual Studio solution, I don't think that refactoring it and adding another nested level of folders is a viable option. Your other proposed solution, moving the .sln and .pyproj files outside of the folder, does not work either because it would mean creating yet another folder to contain both the Visual Studio solution and the package; besides, even though importing the package works then, the imports within my test_module.py file don't.

What I'm proposing is something that fixes the issue and does not change existing behavior. Do you have any technical arguments against it?

**Comment by int19h** [comment]
I'm just curious why this:

> our other proposed solution, moving the .sln and .pyproj files outside of the folder, does not work either because it would mean creating yet another folder to contain both the Visual Studio solution and the package

is bad, especially given that you have to do it anyway if you use setup.py to package your code - in other words, it's essentially the standard convention - and .pyproj is basically the IDE-specific equivalent of setup.py in many ways.

Also, have you tried editing the project home directory to be `..` in project properties and see if that helps? I expect that it would.

I agree that, in general, if running tests from command line works, the UI test runner should also work (and generally strive to behave identically). I'm just trying to figure out how much of an edge case this particular instance is, and what is the most appropriate way to address it. I'm not entirely sure that your suggested fix is it - it only strips the top-level package from the fully qualified name, i.e. `a.b.c` would become `b.c`. What if there's an `__init__.py` in the parent directory, too? I'm not actually sure if we'd count the parent folder as a package then, but if we did then the tests would still not run even with this fix.

It's also not clear whether this is a right thing purely from a Python perspective, because it constitutes an implicit relative import of a module from within the package. Will it even work in Python 3.x?

**Comment by omtinez** [comment]
My only concern with my proposed solution is, frankly, just aesthetic. A slightly better approach would be to check if the solution is in the same folder as the package and import conditionally based on that. It appears to work in both Python 2.x and 3.x. The reason why a "proper" folder structure is not being used is because these are very small packages, often containing a single actual Python file; and adding 3+ folders seems rather wasteful for that purpose. Some of these packages don't even have a /module/test folder, since the unit tests consist of a single file as well so it all ends up in a flat folder structure with 4 or 5 files, including those used by Visual Studio.

I acknowledge that this might differ from the primary use-case, but I really don't like the disparity in behavior between the command line and running the UI. If there is some project setting that can handle this, I'm more than happy with that solution. So far, I have fruitlessly tried modifying the References, Search Paths, etc. Changing that allows the package to be loaded, but the relative imports break and, if fixed to work in Visual Studio, then running the tests from the command line stops working.

**Comment by omtinez** [comment]
Ping... I think that the behavior of running tests through Visual Studio should be the same as running `python -m unittest discover` from the project root.

**Comment by zooba** [comment]
That's not a solution we'd be willing to take. What we need to do here is to change our algorithm for determining module names to take into account search paths that jump in partway through the hierarchy (as you have done here). As Pavel mentioned, if the parent directory also has an `__init__.py`, we need to ignore the first two segments, which the proposed fix would never do.

I agree that matching the command line behavior is ideal, though we typically use the specified working directory rather than the project root for operations like this (typically they are the same, but not always - using the working directory allows user customization).

**Comment by DomenicD** [comment]
This issue effectively makes the Visual Studio Test Explorer useless. I would even be fine with a solution that required the user to define a test config file in the same directory as the .sln that defined the root of the project. Or some other convention where we could pass in this information.
