### ISSUE TITLE
It is possible to write an universal app with python?

### ISSUE THREAD

**Issue by GERMANOCARELLA** [Microsoft/PTVS#842]
Hi,
I installed python 3.5, ptvs and Python uwp sdk.
Now, I can't find a way to build an universal app. I don't know if it's possible, python UWP is for windows 10 IoT applications.
I'm very confused, I don't know if there is an interpreter for UWP or if I can use python 3.5 interpreter. I downloaded binaries of ptvs and python uwp sdk.
Can anyone help me to understand?

**Comment by denfromufa** [comment]
https://github.com/Microsoft/PTVS/issues/841

**Comment by datnamer** [comment]
+1

**Comment by zooba** [comment]
Right now the IoT SDK is as close as we have for UWP apps. The interpreter is bundled with that SDK, as it needed to be modified for running in UWP (there are a number of changed/removed APIs that Python was using).

In theory it will work on any supported platform, but since we don't have Python bindings for the UI frameworks or platform APIs yet (the IoT team manually wrote bindings for their important APIs), it's very difficult to write apps for platforms that rely on user interaction. We currently are not working on these bindings - see my response in #841 for more info.

**Comment by drillep** [comment]
Support for Python for Win IoT would be well utilised in education.  I teach Python to students due to its simple syntax, most Raspberry Pi robotics examples use Linux but with a Windows network it can be difficult to support two OS's in the classroom simultaneously.  Additional support for the Python libraries would encourage further adoption.

**Comment by zooba** [comment]
@drillep There is support for Python for Win IoT. Unfortunately, the team doing the libraries has the view that until they get adoption, there's no point further supporting the libraries - a real chicken and egg problem.

A couple of blogs (or news articles) about it being used in classrooms would be very valuable encouragement for them. If you link something here, we'll make sure they see it.

**Comment by gjkhw** [comment]
I know that this thread is dated, but I'll mention that I work on a team that is evaluating Windows 10 IoT Core as part of a refresh to an existing Windows-based hardware product.  

Python support is a gating factor for us in the choice of an embedded OS. We prefer IoT Core for other reasons, but lack of Python support would be a showstopper.  In particular we embed Python into a C++ app, and will be evaluating how we can port that app to IoT Core.  At the moment, I don't see an python import library for ARM distributed with the IoT SDK, which is going to present some problems.  

As we work through issues we'll have other feedback that we will pass on through official channels, but would appreciate any feedback that you can pass on.

**Comment by zooba** [comment]
@alanch-ms may have something to add, but I'm not aware of anything new recently.

**Comment by gjkhw** [comment]
Thanks!

**Comment by earonesty** [comment]
Few are adopting UWP and the security situation on desktop is such that app containers are sorely needed.  Better to intercept kernel calls with the existing windows api and apply more granular app permissions based on the calling application.   This can be tricky (calls to CreatFile, and FindFirstFile, etc could now be blocking calls that wait for user interaction).   But ultimately it's a workable solution that can yield a secure windows kernel quickly.   Registered exemptions could also be included so legacy apps still work in the meantime.
