### ISSUE TITLE
Python 3.5  unsupported for Visual Studio 2013 Professional

### ISSUE THREAD

**Issue by chawk** [Microsoft/PTVS#850]
I've updated Visual Studio and PyTools and it does not work.

**Comment by zooba** [comment]
Can you provide a little more detail?

Are you seeing an error message? Is some code failing to run? What functionality are you expecting to see that you aren't seeing? Which version of PTVS have you installed (check in Programs and Features to get the full number)?

**Comment by agentraymond232** [comment]
For me, once I installed PTVS 2.1 for VS2012, I selected New Django Web Project in Menu->New-> New Project-> Languages->Python. Just then the project selector dialog box closes (as expected) and an error dialog box open showing that Python 3.5 is not supported.

**Comment by udayguntupalli** [comment]
I have the same problem . When i installed Anaconda for python 2.7 - it worked fine , but when I try to install anaconda for python 3 - I am getting an error that says python 3.5 is not supported

**Comment by zooba** [comment]
This is by design - Python 3.5 is only supported in PTVS 2.2 or later. PTVS 2.2 can be installed into VS 2013 or VS 2015.

If you manually configure the environment and mark it as 3.4, most of the functionality of PTVS 2.1 will work (but you'll get syntax errors for new syntax constructs). PTVS 2.1.1 should not detect 3.5 at all, which will avoid the error message.
