### ISSUE TITLE
Viewing a watch of a PyUnicode with a 2.7 interpreter crashes MSVS

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#876]
2.7 interpreter, debug build

    PyObject *p = PyUnicode_FromString("This is a test");
    // set breakpoint here

hover over `p` and try to expand the down arrow.  devenv does a hard crash.

**Comment by int19h** [comment]
Which VS version is that?

**Comment by zjturner** [comment]
VS 2013.  Specifically, 12.0.31101.00 Update 4.  PTVS 2.2.30821.01.  Sorry, should have mentioned all this originally.

In this case I was not using a Python project / solution.  This was 100% native code debugging.  I was debugging my extension module by linking against it from a native program and running some tests.  (i.e. just call Py_Initialize etc from an EXE).

PythonTools still seems to be involved in this scenario, because with some types of PyObjects when I watch a variable, it adds an entry called Python View.  I guess this is some kind of natvis thing.  Seems like it's the natvis integration that was crashing.

**Comment by int19h** [comment]
Oh, then the bug is that those entries appear in the first place. They shouldn't show up if you only had Native code type selected when attaching, only when you have both that and Python. No surprise that it crashes then, that visualizer needs the Python debugger to do its job.

**Comment by zjturner** [comment]
To be honest I'm not sure if I have Python selected or not.  When I F5, where does one choose that?  I know when you get the Attach to Process dialog, you can choose the types of code to debug, but when you launch a native code project from the debugger, I can't find where (or even if) that is selectable.

I know I've seen the Python View working in the past, but now that I think about it I bet that was when I was debugging a Python project with "Enable native code debugging" selected.  

Is there a way to have F5 on a native project also load the Python debuger?  Either way, like you said, I guess the bug is that it's trying to show the Python View when the Python debugger isn't loaded.

**Comment by zjturner** [comment]
Ahh, I see it.  it's under Configuration Properties -> Debugging -> Debugger Type.  I have it set to Auto.  it's weird that it displays these broad categories like "Mixed" or "Script", without displaying specific Debug Engines like the Attach to Process dialog does.  I'm not sure which (if any) of those would enable the Python debug engine.

**Comment by int19h** [comment]
When you do F5 from a C++ project, you basically cannot get Python in there, unfortunately. "Script" really just means "JavaScript" (as in, IE/Chakra), and is a legacy thing - it's also named the same in Attach. By "Mixed" they mean Native+Managed.

**Comment by int19h** [comment]
But do file a feature request on them to add it (or better yet, make it extensible so that we can add ourselves there). I'll also ping the team internally, but it always helps when a customer specifically asks for something ;)

https://visualstudio.uservoice.com/forums/121579-visual-studio

**Comment by zjturner** [comment]
is there any way to fix it so it doesn't crash when I hover over a PyObject?  Somehow or another it's recognizing that you have some natvis visualizers hooked up for objects of type `PyObject`, but I don't know if it's the extension's responsibility or VS's responsibility to ensure that MSVS doesn't crash in this scenario.  So I'm not sure whose bug it is.

**Comment by int19h** [comment]
This is a PTVS bug. C++ provides an extensibility point for the visualizer, and we register ours there, but it's supposed to suppress itself if it detects that Python debugger is not loaded in the process.

You can suppress the visualizer from loading entirely by deleting its .natvis file. It's in PTVS installation folder under "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft" (or your local equivalent).

**Comment by zooba** [comment]
@int19h Where is the code for this?

**Comment by zjturner** [comment]
Honestly any trivial program should reproduce it.

    #include <python.h>
    int main(int argc, char **argv)
    {
        PyObject *py_obj = Py_None;
        return 0;   // set breakpoint here
    }

Run this via F5 from a pure native code project.  When you stop at the breakpoint, hover over `py_obj`, click the plus sign, Visual Studio should crash.  If this doesn't reproduce it for you let me know and I will work on creating a sample.

**Comment by zooba** [comment]
@zjturner The repro is appreciated still, but yeah, this is an area of PTVS that I very rarely venture into but @int19h knows well (a.k.a. is responsible for writing).

**Comment by int19h** [comment]
https://github.com/Microsoft/PTVS/blob/e95e158f7f9392d7baef31766dd7a3bf91baff88/Python/Product/Debugger/DkmDebugger/PyObjectNativeVisualizer.cs#L145

This is the function that's referenced in natvis to determine whether the node is displayed or not, e.g.:

https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/DkmDebugger/PythonDkm.natvis#L24

The implementation should return 0 if the corresponding option is disabled, or if the Python runtime is loaded. Looking at the code, however, I can't see any immediate problems there. This probably needs some debugging to figure out how exactly it managed to locate a runtime when one cannot possibly be loaded there.

It's also possible that VS itself invokes `EvaluateVisualizedExpression` even when the node is hidden. I would consider it a bug on their side, but it should be trivial to work around by adding the runtime check to that function as well, and bailing out immediately instead of trying to construct the evaluation result for it.

**Comment by zjturner** [comment]
That code is inside of an `#if DEV14_OR_LATER`.  Does that apply if I'm using VS 2013?

**Comment by int19h** [comment]
Oh yes, you're right! I think I see the issue now. Here's how the VS 2013 version looked before the changes needed for VS 2015:

https://github.com/Microsoft/PTVS/blob/09b1e4590245e63bde68d38ca95885e92df0fbd3/Python/Product/Debugger/DkmDebugger/PyObjectNativeVisualizer.cs#L120

Note the null check; and then `GetPythonView` does the actual check for the runtime:

https://github.com/Microsoft/PTVS/blob/09b1e4590245e63bde68d38ca95885e92df0fbd3/Python/Product/Debugger/DkmDebugger/PyObjectNativeVisualizer.cs#L220

In the new code, the helper function is gone:

https://github.com/Microsoft/PTVS/blob/e95e158f7f9392d7baef31766dd7a3bf91baff88/Python/Product/Debugger/DkmDebugger/PyObjectNativeVisualizer.cs#L261

So the null check, which remained, no longer includes that runtime check, and the "[Python View]" node is always being created. So it should be fixed by simply adding `process.GetPythonRuntimeInstance() != null` to that condition.

**Comment by zjturner** [comment]
Sweet!  Incidentally I'm in the process of porting my extension module to Python 3, which requires VS 2015, so hopefully in the future this won't affect me (assuming I'm successful anyway, it's kind of a painful rewrite)  :)

**Comment by int19h** [comment]
Side note: you can use VS 2015 to debug native binaries built with any version of VS. It can be handy sometimes if you want the newer features.

Also, if you have VS 2015 installed side by side with earlier VS versions, you can build your projects using compilers from those older versions, while working with them from VS 2015. In C++ project properties, on the "General" page, there's a property titled "Platform Toolset". You should see all the compilers you have installed in the dropdown there.

**Comment by zooba** [comment]
@int19h I could also fix it by checking that `pythonViewEvalResult` is not-null too, right? Since that was the old check that was removed.
