### ISSUE TITLE
Web Tooling Improvements like the ones from ASP.Net

### ISSUE THREAD

**Issue by LRPalacios** [Microsoft/PTVS#884]
Hello, 

I been using PTVS for django development for like 9 months now and loved so far, i am also a ASP.NET developer, i choose framework depending on the type of project i am going to be working, but thanks to PTVS i've been able to remain always on the same IDE.

The thing is ASP.NET had done an amazing [Tooling Improvements](http://blogs.msdn.com/b/visualstudio/archive/2015/09/24/a-summer-of-asp-net-catching-up-with-net-web-developments.aspx)(see Tooling improvements) and I would love to have some of those when doing django development too, because i use bower, gulp, angular, bootstrap etc etc, and what they have done to the javascript editor is also impresive, and when i am doing django development on VS, i really wish i had those features in both html, and javascript editors.

**Comment by zooba** [comment]
Looking at that list, most of the improvements are only really applicable to C# and don't transfer well.

The HTML, JS and JSON improvements should carry over automatically, since we don't try and do anything special there, but it's more likely that the `{{...}}` handling they've implemented will conflict with our own (again - we'll take a look asap as to whether they've broken Django editing) rather than improving it.

Thanks for making sure we're checking these - might have missed them otherwise (there's so much going on here that we can't track everything :) )

**Comment by zooba** [comment]
There are bugs filed for the issues that have arisen from the changes referenced here, so no point keeping this issue open.
