### ISSUE TITLE
Store the Interpreter guids in the .suo file

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#905]
Currently it is very difficult to share a .pyproj file in a source code control system, for example.  When I create some Python environments and configure my project to use a particular environment, it embeds something like this into the .pyproj file.

    <InterpreterId>{8d9a2989-1e82-4fd4-affc-8fefd395e7d0}</InterpreterId>
    <InterpreterVersion>2.7</InterpreterVersion>

    <ItemGroup>
      <InterpreterReference Include="{2af0f10d-7135-4994-9156-5d01c9c11b7e}\3.5" />
     <InterpreterReference Include="{8d9a2989-1e82-4fd4-affc-8fefd395e7d0}\2.7" />
    </ItemGroup>

These guids will be different on someone else's machine, and as a result it makes the project unshareable.  If these were in the .suo file, similar to Debugging settings, it seems like this problem would be solved.

**Comment by zooba** [comment]
Unfortunately it would not solve it, as we consider the interpreter information a critical part of the project and so it needs to be shared (akin to saying that your project requires .NET 4.6 - you can't leave each contributor to figure that out on their own!).

The problem is the reliance on GUIDs to identify interpreters, which I hope to fix for 3.0 (as fixing it requires public API changes) and am already tracking in #263

**Comment by zooba** [comment]
A small aside, it would be stored in the `.pyproj.user` file, as that is the one that we have access to. VS itself owns the `.suo` file and we don't get to write directly into it.
