### ISSUE TITLE
Can't run ML projects - MatPlotLib won't install

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/PTVS#910]
Matplotlib will not install on a windows 10 box with visual studio 2015 community edition.

The error code is:
                            \* The following required packages can not be built:
                            \* freetype, ping

I am willing to help make this work, just let me know what I need to do to assist having this resolved asap.

**Comment by zooba** [comment]
Our current recommendation is to install Anaconda to use those packages, as they are fairly complicated to build. Since you're already up and running, have a look at our [Python Package Installation Options](https://github.com/Microsoft/PTVS/wiki/PTVS-Installation#python-package-installation-options) docs for some other ways to get (at least) `numpy`, `pandas`, `scipy`, `scikit-learn` and `matplotlib`.
