### ISSUE TITLE
Jupyter notebook integration

### ISSUE THREAD

**Issue by denfromufa** [microsoft/PTVS#94]
One thing that would be great is support for IPython notebooks. What I have in mind is essentially what the Canopy editor provides right now: if you open a ipynb file it opens a tab that shows the normal IPython notebook UI, so you can just do all the nice things within the IDE. Ideally this would connect to the same IPython kernel as the interactive window. 

Things that would be nice about this:
1. I could stay within the IDE for all my work
2. the steps of starting a IPython notebook server and starting it in the right directory would be hidden from me, one could just interact with IPython notebooks as we other normal files as well
3. integration with the standard open/save file buttons in the IDE etc 

I can think of two levels of support for this: a simple one like the editor in canopy has, where I assume they just host a web browser control and have some thin layer around it to integrate with the IDE save/open file infrastructure. A more complex one where maybe in code cells we would get e.g. VS code completion, debugging etc. Not sure this one would be even possible... 

I think really I am looking for two things: 
1. integration with VS file system, so that I double click the file it opens, I save the notebook by clicking save etc. Canopy does that, so there must be some way to get this to work 
2. automate (and hide) the whole idea of starting up a IPython notebook server process. Again, Canopy does that already. If I open a file, it starts the server in the background, automatically connects to it etc. I don't even see/know anything about the whole architecture, as an end user it just looks as if I opened the file in the IDE. 

I think what you have in mind might be something a bit different... Really all I want is the level of support that you find in the Canopy editor...

---

PTVS IDE on top of IPython notebook should be of benefit to the users in the following:
- code navigation, refactoring, completion (in the order of complexity :) ) 
- better highlight of syntax and possible code errors 
- DEBUGGING 

(Migrated from http://pytools.codeplex.com/workitem/1901)

**Comment by denfromufa** [comment]
https://github.com/Microsoft/PTVS/issues/88

**Comment by willyd** [comment]
+1 for this.

**Comment by zooba** [comment]
Thinking about the final point 2 in the description (which is something that I'd like to be able to do), the advantage Canopy has over us is that they will launch their own IPython server. We let you have multiple ones from different sources (distros, venvs, etc.), so it's far more difficult for us to make it completely transparent, and if we did then it'd likely be too transparent for many people.

We already have an extensible environments UI, and it would be fairly easy to add controls to that for installing/starting/stopping a notebook server. If you have an ipynb file in a project, then we have enough information to reliably start the server transparently, but things get complicated quickly outside of a project (yes, we have a global default environment, but what directory do we start in? What happens with two notebooks from different directories? Ten notebooks? Do we have ten notebook servers? How do we tell users that? How do we stop them? Can we keep changing the working/root directory for a single server? Projects let users handle their own scale and environment, but it's not clear to me how that works when we have to figure it out for them.)

I'm also not convinced that editing the notebooks within VS will be beneficial. @DinoV has speculated that we might be able to embed the VS editor into a notebook when editing a cell, but until I see a working prototype I don't think it's feasible. We'd also then probably have to restrict users to a particular version of IPython (at least for a particular PTVS version). I prototyped a "raw" editor a while back that didn't attempt to render the notebook at all but made it easier to do edits that the HTML view doesn't support, but I'm not sure that anyone really needs that either.

Double-clicking a notebook file, maybe starting a server (if we have enough information to do so reliably) and opening it in the user's default browser seems like a good feature for us to provide. It looks like Canopy is simply embedding a browser, and probably relying on the HTML not changing for whatever extra commands they expose (but since they also control all the updates, they can do this more safely than we can). We could open it in a browser in VS, but I think people would rather use their default browser than whatever version of Internet Explorer is embedded in VS.

**Comment by denfromufa** [comment]
It may be worth looking at design of workbench + mathematica notebook, where workbench is customized eclipse environment. Although it is not very comfortable workflow however it seemed to me that it contains some nice ideas.

**Comment by willyd** [comment]
Another thing I would love, is to be able to use the VS graphical debugger to debug code in a IPython notebook. How hard would that be?

**Comment by zooba** [comment]
@denfromufa Thanks for the tip, I'll take a look.

@willyd There are a few different ways of approaching this, with varying degrees of difficulty. I've just started #774 with my vision of how it could look, and I've called in the IPython team to help us figure out how we can make it work. Feel free to comment/discuss over there.

**Comment by denfromufa** [comment]
One way to support jupyter notebooks would be to use the custom source format instead json based .ipynb. This is done ipymd project by @rossant:

https://github.com/rossant/ipymd

So both jupyter notebooks and PTVS would share the same "backend" file on disk (e.g. .py file with commented cell blocks) and both IDEs can edit the file interactively. The output of the code cells in the notebook would have to be separated into a different storage format.

**Comment by zooba** [comment]
@denfromufa That's been my working idea for a while (and I even prototyped it a while back). But I'm still not sure exactly how it would be used - the actual workflow question is still highest importance in my mind.

**Comment by denfromufa** [comment]
The workflow is that jupyter notebook is mainly used as a "frontend" to prototype and visualize using figures, tables, widgets, and any other rich output. PTVS can be used as a "backend" for intellisense, linting, debugging, version control, variable explorer, navigation (references) and refactoring. Basically just steal main features from JupyterLab, VS Code, Hydrogen, Rodeo IDE, Spyder, PyCharm. Did I miss anything?

**Comment by zooba** [comment]
It doesn't translate into a story as nicely as we'd like, that's all. What problem has someone encountered that makes them decide to open the file in Visual Studio? What is it about Visual Studio's support for .ipynb that makes it better than a plain text editor? How do we help them resolve their issue faster, or with less effort? Those are the kind of questions we need to answer to justify the scenario.

**Comment by Anapo14** [comment]
Hey there. If you still need native Jupyter notebook integration, you should use python in VS Code. We are not currently planning on integrating Jupyter notebook support for Python in Visual Studio.
