### ISSUE TITLE
Perf issue in PTVS 2.2 while debugging

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/PTVS#947]
I'm using PTVS 2.2 for VS 2013 and I'm seeing terrible performance while debugging my python code. It takes forever to step over each statement.

Environment: Python 64-bit 2.7

Can anyone suggest what may be wrong with my project/solution?

Let me know if you need any more info.

Regards,
Rajesh

**Comment by zooba** [comment]
Chances are you have a local variable with a very slow `repr()`.

In order to display locals in the Locals and Autos windows, we will call `repr()` for most objects in the current function. Sometimes these will do things like executing database queries that could take a long time.

Have a look in the Locals window while stepping and see if there's anything you have there that could be taking a long time to generate.

**Comment by rnagpal** [comment]
Thanks Steve for the quick response!

Yes, I did noticed that if I clear everything from my Watch window, things are much better.

Follow up question: I was having items like self.iterable.has_started where iterable was a parent class of this(self) class and I was trying to access the has_started field.

Can expressions like self.iterable.has_started load the entire "iterable" class everytime I access any property on them?

**Comment by zooba** [comment]
It depends how `iterable` is implemented. If it is a property that generates a collection on access, then yes, that is likely to be pretty slow.

We've contemplated adding very short timeouts here so that anything that is slow once is not evaluated again unless you manually request it, but nobody's had time to do that yet. It's probably the best way to help people avoid these problems - we can't really solve it without changing the offending code.

**Comment by rnagpal** [comment]
Related query:
I've a custom Iterable class(QueryIterable) that implements __iter__ as follows:
def __iter__(self):
        return self.Iterator(self)

I've also this Iterator class implemented which implements next method and I wanted to have breakpoint there so that I can debug.

I noticed that on the line:
databases = list(client.ReadDatabases())

ReadDatabases() returns QueryIterable. I wanted to debug from the point when ReadDatabases has returned and when the list() calls the next method on the Iterator. I have breakpoint set on the next method but somehow that whole code runs without hitting the breakpoint and the cursor comes to return self.Iterator(self) shown below at which point the next method has already been executed.

def __iter__(self):
        return self.Iterator(self)

Has someone faced this issue earlier and any way to workaround it?

Regards,
Rajesh

**Comment by zooba** [comment]
Seems like Python is suppressing tracing within the `list` constructor. It might be a bug in CPython, but otherwise I doubt we can do much.

If you still want to investigate this issue, please file a new bug and include complete source code to reproduce the issue.
