### ISSUE TITLE
Completion won't automatically pop up

### ISSUE THREAD

**Issue by mateuszlewko** [Microsoft/PTVS#980]
Complettion doesn't pop up until I press Ctrl-j or type '.' 
For example, in Pycharm whenever you start writing something, it automatically gives you a list of possible keywords.
It's really annoying in visual studio.

I hope you fix this :)

screenshot of pycharm:
http://i61.tinypic.com/20960wn.png

screenshot of visual studio:
http://i62.tinypic.com/2qtilg1.png

**Comment by zooba** [comment]
We deliberately don't pop up the completions at the start of a line, since it's so common to be typing a new name that having it auto-complete all the time is very annoying (yes, we tested this :) ). After the first equals symbol it will start popping up automatically.

But since we keep seeing a lot of confusion around this, we should make *something* pop up, even if it's going to require the extra character press anyway, as then it will look less like a bug.

**Comment by mateuszlewko** [comment]
What do you think about an option to turn on/off 'auto-complete all the time'?
I'm used to ignore auto-complete pop up when I type new name.

**Comment by zooba** [comment]
That option is already there, the problem is that once the popup is shown it's going to default to selecting something. So if you type `i` followed by a space, it will complete to `if` automatically. You need to type `i<escape><space>`, which gets very annoying very quickly.

The closest thing to a middle-ground is to have it pop up but not select anything, so you need to use the mouse or arrow keys to select a name if you want to use it. We already do this at the start of lists (type `[a` and see the popup there), and while it avoids interrupting people who know what they're typing, we don't think it's actually that helpful. But maybe it is? We don't normally get much feedback on things that are easy to work around :)

**Comment by zooba** [comment]
This is already implemented.
