### ISSUE TITLE
Large file performance issue

### ISSUE THREAD

**Issue by pyuser00** [Microsoft/PTVS#984]
VS2013 is continually freezing and crashing while working on a module that is about 6500 lines. Is intellisense or the continual syntax checking causing the issue? I am assuming it is the file size; but could it be something else?

(Eventually I plan to split the module to make it more manageable, but I need to work with it as is for now...)

**Comment by zooba** [comment]
It's typically not the file size - our processing is split up by function, so the more functions you have the more memory/time required. This multiplies substantially if you are nesting functions within functions (or classes within functions), so that may be the cause. 6500 lines is not a problem in itself.
