### ISSUE TITLE
Intellisense missing builtins

### ISSUE THREAD

**Issue by ajmarks** [Microsoft/PTVS#987]
Running VS2015, Anaconda 3.4 64bit

Intellisense seems to be missing builtins unless the file explicitly has a `from builtins import *`.  I've tried  refreshing the DB, but that did not help.

**Comment by zooba** [comment]
Which builtins are you expecting to see that aren't there?

**Comment by ajmarks** [comment]
Almost all of them.  On my screen right now, I have super(), KeyError, classmethod, and property:
![image](https://cloud.githubusercontent.com/assets/5182431/11191391/09ffdcec-8c69-11e5-9ff2-7b65402b4a48.png)

**Comment by zooba** [comment]
Do you mean the coloring?

**Comment by ajmarks** [comment]
Not just the coloring, that's a symptom.  Check out the tooltip: KeyError is an unknown type.

**Comment by zooba** [comment]
Can you grab the contents of Tools, Python Tools, Diagnostic Info (make sure you don't have any DB refresh running in the background) and post it as a [gist](https://gist.github.com)? There should be something in the logs about that. At the very least, I should be able to ask for one or two specific files to inspect after checking the logs.

**Comment by ajmarks** [comment]
I probably shouldn't have done this, but I deleted the corresponding subdir in CompletionDB, and when it rebuilt the db, it worked.  [Here is the log though](https://gist.github.com/ajmarks/425a0cbca1920a6178dc).

**Comment by zooba** [comment]
Unfortunately when you grabbed that log, there was a DB refresh running and so none of the info I needed made it in. And now that log is gone :)

Glad you got it working though. My guess is that there was some transient error but we survived, and so saved an incorrect result. Since we only check file existence and date/time, everything looked good and we didn't re-run. Currently deleting the folder is the only way to fix that.

Since there's nothing more to do here I'll close this issue. But we are working on changes for the next major release that will improve this.
